### ISSUE TITLE
Nonbinary Options

### ISSUE THREAD

**Issue by LilyOfTheFlame** [Luke100000/minecraft-comes-alive#1000]
Currently, all villagers and players are either seen as male or female, with no in between.  I propose that there should be an option for nonbinary villagers/players.

**Comment by Luke100000** [comment]
You are mixing gender/sexual orientation with sex. There are traits for that, as well as config options to turn gender off all together.

**Comment by LilyOfTheFlame** [comment]
I can't find a nonbinary trait in any menu.  Where is it?

**Comment by Luke100000** [comment]
nonbinary would not have an effect ingame, thus there is no separate trait. Only bisexual.
