### ISSUE TITLE
Gender-based Naming

### ISSUE THREAD

**Issue by disky00** [Luke100000/minecraft-comes-alive#1007]
It doesn't appear that names are following gender. I see that this was previously a reported issue but the report was closed after an update. I have female characters that use female voices with names like Samuel and James, and female names on male characters.

I love this mod, by the way! Thank you for your hard work!

**Version**
Architectury is installed, and the version I'm running is 7.5.19. 
MC 1.20.1, Fabric 0.15.11

**Comment by disky00** [comment]
I've also confirmed that I have the latest version of Architectury installed for 1.20.1 Fabric, 9.2.14.

**Comment by Luke100000** [comment]
So far it always was a villager naming mod, check your modlist.

**Comment by disky00** [comment]
Indeed, this was it. I guess the modpack already had one installed. Thanks very much!
