### ISSUE TITLE
Can't login to utilize saved skins

### ISSUE THREAD

**Issue by WinterWisteria** [Luke100000/minecraft-comes-alive#1008]
**Describe the bug**
Suddenly can't login to utilize saved player made skins "You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy for keeping apps secure."

**To Reproduce**
1. Click Login when choosing to see saved skins
2. Click your account to login when it opens in your browser.
3. Error.

**Screenshots**

**Version**
MCA Up to date, 1.20.1, Forge

![image](https://github.com/user-attachments/assets/6190d332-7a32-435d-9195-3b8b8ff1f11e)

**Comment by Luke100000** [comment]
Yes, a recent change seems to block some people. Need to fix that.

**Comment by SmoothCatTobii** [comment]
same for me i just made a new modpack and can't login anymore but im still logged in inside my old modpack is there any file i could copy to transfer it to my new modpack so im logged in there aswell?

**Comment by Luke100000** [comment]
It's fixed now, please let me know if it works as expected now (7.5.20 for 1.20.1, 1.19.2 will follow once I know it works)
