### ISSUE TITLE
Optifine on 1.18

### ISSUE THREAD

**Issue by Luke100000** [Luke100000/minecraft-comes-alive#101]
Mipmapping enabled confuses things.
![image](https://user-images.githubusercontent.com/7905977/155997406-cc75d427-b694-49aa-a903-dd31c81c63f0.png)
May only affect guards.
Also OpenGL errors are thrown

**Comment by chronosacaria** [comment]
I am not the mod author, but as a fellow mod author who has had to contest with the absolute nightmare that is Optifine's code, it can be extremely troublesome as the code is not open source and is extremely invasive. 

If you are on a newer version of Minecraft, have you considered using, for Forge, Oculus (https://www.curseforge.com/minecraft/mc-mods/oculus) and Rubidium (https://www.curseforge.com/minecraft/mc-mods/rubidium) or, for Fabric, Iris (https://www.curseforge.com/minecraft/mc-mods/irisshaders) and Sodium (https://www.curseforge.com/minecraft/mc-mods/sodium)? These combination of mods allow you to use shaders in Minecraft as well as get the performance boosts that one would see from Optifine. As a matter of fact, many people see better improvements using the combination of mods than the do with just Optifine.

Just thought I'd throw it out there. I apologise for my English :)
