### ISSUE TITLE
Add a API for use local (local PC/LAN/WAN Public) LLM API(Like Text-generation-WebUI, Llama.CPP, ChatGLM WebUI etc.)

### ISSUE THREAD

**Issue by SakuraRK** [Luke100000/minecraft-comes-alive#1010]
**Is your feature request related to a problem? Please describe.**
I'm living on China mainland, As your know the OpenAI proactive blocked the China mainland and Hongkong SAR., Macau SAR's connect and API request. So they can't use official ChatGPT...instead Local API or more expensive's 3rd Party API. :(

**Describe the solution you'd like**
Add a function to use the Local API for any can't use the official ChatGPT service's region. *_*
*If possible please deploy it to every version that supports the LLM villager chat.*

**Describe alternatives you've considered**
It's seem so clearly so I make it more short to read. <3 
So...nothing here and have a good night/day.

**Additional context**
None. ^_^

**Comment by Luke100000** [comment]
I (or more specifically my server) use OpenAI (among other providers), not the end user. The ban should therefore not affect the user.

If you do not want or cannot use my server, you can connect any OpenAI endpoint compatible endpoint. I personally recommend Ollama, very easy to set up.

Check out details here: https://github.com/Luke100000/minecraft-comes-alive/wiki/GPT3-based-conversations#custom-endpoints
