### ISSUE TITLE
Save villager just in case

### ISSUE THREAD

**Issue by MightyDolph** [Luke100000/minecraft-comes-alive#1011]
**Is your feature request related to a problem? Please describe.**
some times when villagers die. graves don't spawn (so no reviving). this is very annoying and got me to stop using the mod on multipool worlds (i didn't uninstall just stopped interacting with villagers)

**Describe the solution you'd like**
I think there should be a camera item or something of the like to save a villager data and put it into a grave later

**Describe alternatives you've considered**
An alternative is to make the grave system better but if that was to happened it would have bean fixed already.

**Additional context**
This happened a 2 years ago on 1.16.5, I stopped using the mod and wanted to return; but it will be annoying to lose all the progress again. so mauby the problem is fixed (with the graves).

**Comment by Luke100000** [comment]
This problem is too generic to be an MCA feature and should be a separate mod. For example, ledger does that tho it might be a bit overkill for your case: https://modrinth.com/mod/ledger
