### ISSUE TITLE
Login in to upload outfits, found this

### ISSUE THREAD

**Issue by McSlayMcFierce** [Luke100000/minecraft-comes-alive#1012]
My google account won't let me sign in because it violates Google's OAuth 2.0 policy.

**To Reproduce**
1. Go to 'the outfit library'
2. Click on 'login'
3. Scroll down to 'sign in with google'

![Screenshot_26-10-2024_20218_accounts google com](https://github.com/user-attachments/assets/c96d3e26-1ae5-441f-8cab-341b1a5915ef)

**Version**
recent version, 1.20.1, forge

**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.

**Comment by Luke100000** [comment]
Merged with #1008 :)
