### ISSUE TITLE
Skin Library Is Not Authenticating Me

### ISSUE THREAD

**Issue by CherryPuppet** [Luke100000/minecraft-comes-alive#1017]
**Describe the bug**
I loaded up the latest update of MCA Reborn and tried to take a look at the skin library when the messages "Failed to check authentication" and "Failed to fetch list" pop up and no skins were shown. Trying to log in kept giving me the message "Failed to check authentication". Only the global skins are displayed.

**To Reproduce**
1. Launch Minecraft with MCA Reborn - 7.5.20
2. Get into the skin library by pressing the keybind or using the /mca editor command and navigating to the library button
4. It will say "Authenticating..." and then display the error message
5. Press the login button
6. It will display the same error message

**Screenshots**
![2024-10-30_17 02 25](https://github.com/user-attachments/assets/e206d2dc-88cd-47ff-93ab-ddd360716fb1)
![2024-10-30_17 02 38](https://github.com/user-attachments/assets/f64a0f7f-16d3-486a-8b24-41f656ba1759)

**Version**
MCA Reborn - 7.5.20
Minecraft - 1.20.1
Forge - 47.3.6

**Latest.log**
[latest.log](https://github.com/user-attachments/files/17580312/latest.log)

**Comment by Luke100000** [comment]
Old auth no longer works, this is intended. But what happens exactly when you re-login? Did you get past google? What was the content of the final page in the browser?

**Comment by CherryPuppet** [comment]
Is there an alternative login method that I'm missing? The only way I know how is with the button inside the skin library. I tested it again, it didn't bring me to google at all, unfortunately. No browser opened up or anything like that. It just stayed on the authentication screen inside Minecraft and said "Failed to check authentication".

If it helps, I know that there's some weird stuff going on with my Microsoft account.

**Comment by Luke100000** [comment]
No, the button is correct. It should open a login using your default internet explorer, check if one is selected.
Theoretically, you can manually open the file; it is in the temp folder (%TEMP% on windows) prefixed with immersive_library.

**Comment by CherryPuppet** [comment]
When I open the file, it has nothing inside.

**Comment by Luke100000** [comment]
Drop it here please

**Comment by CherryPuppet** [comment]
Sorry, I forgot to mention that it is a folder, not a file. GitHub isn't letting me attach it.

**Comment by Luke100000** [comment]
Hmm then I ran out of ideas, the combination of error and log should not be technically possible.

**Comment by CherryPuppet** [comment]
Would my launcher of choice be getting in the way by any chance? I'm using Prism Launcher 8.4

**Comment by Luke100000** [comment]
Possible, but unlikely. I cannot explain why the file isn't written to disk, yet the directory is. IF something fails, it would crash your game, or at the very least say something in the log. Were you able to log in in the past?

**Comment by CherryPuppet** [comment]
Yes, right up until the newest update of the mod.

**Comment by Luke100000** [comment]
Fixed in new build, or you can delete the file "immersiveLibraryToken" in your save dir.
