### ISSUE TITLE
My buildings aren't recognized!

### ISSUE THREAD

**Issue by mmocha3** [Luke100000/minecraft-comes-alive#1018]
When I built a big house it got recognized.

I built an INN and a storage room but NONE of them is recognized! they're just considered homes, as for the storage room I didn't even add any beds I added 9 chests and a lectern and it's still isn't recognized as a storage room..

its not letting me progress in my village PLEASE help!

**Comment by Luke100000** [comment]
Look what blocks the blueprint sees and make sure all blocks are accessible by blocks of air
