### ISSUE TITLE
Configuración

### ISSUE THREAD

**Issue by Peli93ESP** [Luke100000/minecraft-comes-alive#1021]
He visto que no hay mucha explicación sobre cada función de la configuración.
Me gustaría saber si la temporada de impuestos que en la configuración viene por defecto 168000 ¿eso como lo calculan? ¿Son segundos?

**Comment by Luke100000** [comment]
Time values are usually in ticks, see https://github.com/Luke100000/minecraft-comes-alive/wiki/Config
