### ISSUE TITLE
Villagers Attacking Each Other

### ISSUE THREAD

**Issue by s3alampr3y** [Luke100000/minecraft-comes-alive#1027]
**Describe the bug**
My villagers will be all fine and dandy for a while until one villager attacks another. Sometimes multiple villagers attack each other. It doesn't matter if they're family or not, married or not. This isn't limited to archers only either unlike the other similar bug report I saw.

**Version**
MCA 7.5.21, 1.20.1 (with 47.3.0 Forge), ATLauncher

**Latest.log**
[latest.log](https://github.com/user-attachments/files/17782532/latest.log)

**Comment by Luke100000** [comment]
> until one villager attacks another

This is not MCA behavior, villagers cannot attack each other, nor will they cause revenge behavior. Does it happen without any other mods? If not, please find the conflict. Start with AI and villager mods like VillagerVenture.
