### ISSUE TITLE
Can't Complete Authentication

### ISSUE THREAD

**Issue by CherryPuppet** [Luke100000/minecraft-comes-alive#1028]
**Describe the bug**
Sorry to bother again, but whenever I try to go login to use the skin library, while going through the authentication process, it takes me to a page where it says "Access blocked: This app's request is invalid".

**To Reproduce**
1. Launch Minecraft with MCA Reborn - 7.5.21
2. Open up the skin library and press the login button
3. Click the sign in button
4. It will say "Access Blocked"

**Screenshots**
![Screenshot 2024-11-15 171819](https://github.com/user-attachments/assets/902bc8c5-82bf-4cae-8cc5-51a1cba01293)
![Screenshot 2024-11-15 171049](https://github.com/user-attachments/assets/39dac44d-3762-487d-8501-dd69d5905149)

**Version**
MCA Reborn - 7.5.21
Minecraft - 1.20.1
Forge - 47.3.6

**Latest.log**
[latest.log](https://github.com/user-attachments/files/17782914/latest.log)

**Comment by Luke100000** [comment]
Huh. Press see error details and send the little popup as well please.

**Comment by CherryPuppet** [comment]
![Screenshot 2024-11-16 041358](https://github.com/user-attachments/assets/635475e5-b031-4dcc-9c50-d542f778ff98)

**Comment by Luke100000** [comment]
ahhh you have a very old config. Please try again now, I added the old urls.

**Comment by CherryPuppet** [comment]
It works!
