### ISSUE TITLE
Make the editor more accessible regardless of permission status

### ISSUE THREAD

**Issue by antimockingjay** [Luke100000/minecraft-comes-alive#1029]
**Is your feature request related to a problem? Please describe.**
There is no way to access the editor screen for those without OP permissions; the only option is to use the in-game items, which is an inelegant solution for servers who wish to allow players to use the editor freely without giving upgraded permissions.

**Describe the solution you'd like**
Turn "/mca editor" into a targeted command, i.e. "/mca editor [@ a, @ p, username, etc]" so that an operator can bring the full editor up for users and/or set up a command block that opens the full editor for the nearest player.

**Describe alternatives you've considered**
Instead of changing the current command, it could just be a new command, i.e. "/mca fulleditor [target]" if that is easier; I don't know much about coding mods so I have little way of knowing which option is better.

**Comment by Luke100000** [comment]
Enable full editor in the config
