### ISSUE TITLE
Cribs don't show up in Forge 1.20.1

### ISSUE THREAD

**Issue by MegShaw414** [Luke100000/minecraft-comes-alive#1030]
**Describe the bug**
The cribs don't show up at all in forge 1.20.1

**To Reproduce**
1. Go to 'Crafting table'
2. Try to craft a spruce crib
3. Nothing shows up

**Screenshots**

**Version**
MCA Version, Minecraft version, Modloader

**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.
![2024-11-18_17 08 27](https://github.com/user-attachments/assets/f0ecb3cf-f5f1-4a8a-a96d-db9af652bc20)
![2024-11-18_17 09 30](https://github.com/user-attachments/assets/edc333ca-7061-4cc2-874a-cfb76371be0b)
![2024-11-18_17 09 42](https://github.com/user-attachments/assets/efef87e0-b0be-4ee2-86e1-97d28e726b17)

**Comment by Luke100000** [comment]
Because cribs are not released yet :)
There are technical problems preventing the update atm.

**Comment by MegShaw414** [comment]
I see. Thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
