### ISSUE TITLE
ai chat turn off wont work

### ISSUE THREAD

**Issue by BloodRoseDiamond** [Luke100000/minecraft-comes-alive#1033]
hi 

I'm having some trouble with the AI voice chat thing messing around turn it on but now it wont go away type in commands nothing and clear files still nothing don't want to uninstall the mod and re install due to gameplay, I'm hoping it just a different command what i couldn't find online

**Comment by Luke100000** [comment]
`/mca chatAI disable` or via the config: https://github.com/Luke100000/minecraft-comes-alive/wiki/GPT3-based-conversations

**Comment by BloodRoseDiamond** [comment]
ive done that one but the then i click to interact they still talk they say there lines what appear in chat

**Comment by Luke100000** [comment]
The lines which appear when right clicking are not part of the chat AI?

**Comment by Luke100000** [comment]
Ah you mean the text to speach, `/mca tts enable false`, or via the config

**Comment by BloodRoseDiamond** [comment]
o yes it work thanks u also be noted if i want mess around with it turn it off thanks u
