### ISSUE TITLE
TTS blocks personality-specific dialogue

### ISSUE THREAD

**Issue by Mornaistare** [Luke100000/minecraft-comes-alive#1034]
**Describe the bug**
 When Text to Speech is enabled, villagers won't say any personality-specific dialogue, they will just pull lines from the "main" list of dialogues instead of the one for their personality. I noticed this after my husband (flirty personality) suddenly stopped acting flirty after I enabled TTS. I played a couple of days like this and the behavior was persistent, so I can confirm it wasn't just a coincidence. Disabling TTS in the config returned his personality.
 I then did some tests on a fresh new world, and confirmed it wasn't just my husband:

**To Reproduce**
1. Turn TTS on in the config.
2. Start the game and talk to a villager a few times.
3. Notice the lack of personality-specific dialogue.
4. Disable TTS using commands
5. Talk to the villager again.
6. They will now use personality-specific dialogue.
7. Enable TTS using commands.
8. Talk to the villager again.
9. They will now stop using personality-specific dialogue.

**Version**
MCA 7.5.21, Minecraft 1.20.1, Fabric

**Comment by Luke100000** [comment]
This is intended for now as personality specific dialogues are a massive mid quality spam with unknown future. It is excluded from non-english, the datapack TTS, and at least for now from the online TTS.
