### ISSUE TITLE
Cant Assign Jobs

### ISSUE THREAD

**Issue by GODLYexe** [Luke100000/minecraft-comes-alive#104]
I understand this may have been solved already but I am having trouble assigning jobs to my villagers. I don't know if the jobs are already added, but from what is happening on my end i can not assign a work location. When I press the button to I get a message in chat from the villager about how that will do, but then when i look on the villager's little description on the left hand side it says they are still jobless.

**Comment by Luke100000** [comment]
A misleading WIP right here; the button makes them jobless. The villager should then accept the nearest workstation within the near future. Should be fixed in 7.1.2.

**Comment by GODLYexe** [comment]
> A misleading WIP right here; the button makes them jobless. The villager should then accept the nearest workstation within the near future. Should be fixed in 7.1.2.

Thank you for telling me this! I was so dang confused on this situation- I felt like i was going crazy but thank you so much my dude!

**Comment by CDAGaming** [comment]
Closed as assumed resolved
