### ISSUE TITLE
Command Issues

### ISSUE THREAD

**Issue by MerlinWither** [Luke100000/minecraft-comes-alive#106]
When i try to use the commands:
/mca-admin forceFullHerts and /mca-admin forceChildGrowth 
In chat appears the message: An unexpected error occured trying to executa that command
Why does this message appear? and How can i fix this?

PS: I'm sorry for grammatical error but english isn't my native language.
Thanks for any reply and help

**Comment by Luke100000** [comment]
Can you execute it, and then append the log at `%appdata%/.minecraft/logs/latest.log` here please? You may only paste the chunk containing the crash.

**Comment by MerlinWither** [comment]
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/8170677/latest.log)

**Comment by Luke100000** [comment]
Thanks!
