### ISSUE TITLE
MCA villagers should be counted as vanilla villagers for tag purposes

### ISSUE THREAD

**Issue by MoriyaShiine** [Luke100000/minecraft-comes-alive#109]
This is potentially invasive, but if you have no objections then I can make a PR in the morning (with a config, would you like it defaulted to true or false?). This is to avoid issues such as https://github.com/MoriyaShiine/bewitchment/issues/262 and any other mod that checks for villagers in tags.

Of course I also understand if this is rejected due to the nature of the solution.

**Comment by CDAGaming** [comment]
I wouldnt really see this as "invasive", more so just would require extreme testing to make sure it doesn't cause any incompatibilities or weird behavior. Seeing as though we extend off the base class already, I see no reason this shouldnt work, so I'm looking forward to your PR. No objections here.
