### ISSUE TITLE
GUI Positioning on Ultrawide monitors is off

### ISSUE THREAD

**Issue by zachsai** [Luke100000/minecraft-comes-alive#117]
![image](https://user-images.githubusercontent.com/63996164/157325711-7546ec16-eece-4a9f-a434-2cdcf9b2038a.png)

please make it reactive x value, that way it will adjust to all sizes of screens

**Comment by WelpSTudent** [comment]
![image](https://user-images.githubusercontent.com/63996164/157325448-96823bc4-e00b-452b-bd6d-08f53102a7dc.png)
