### ISSUE TITLE
1.18.2 Issue: don't Load

### ISSUE THREAD

**Issue by MerlinWither** [Luke100000/minecraft-comes-alive#120]
When i try to run Minecraft 1.18.2 with mca give me this message
Minecraft Comes Alive (mca) has failed to load correctly
java.lang.reflect.InvocationTargetException: null

I give the crash report and lastest log:

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/8240214/latest.log)

[crash-2022-03-13_18.02.37-fml.txt](https://github.com/Luke100000/minecraft-comes-alive/files/8240216/crash-2022-03-13_18.02.37-fml.txt)

Thanks for help and I'm sorry for grammatical error but english isn't my native language

**Comment by CDAGaming** [comment]
@MerlinWither Should work fine in the next round of betas, if not let me know 👍

**Comment by MerlinWither** [comment]
> @MerlinWither Should work fine in the next round of betas, if not let me know 👍

Unfortunately, the error persists

**Comment by Luke100000** [comment]
Don't open new issues :)

**Comment by MerlinWither** [comment]
> Don't open new issues :)

i'm sorry

**Comment by CDAGaming** [comment]
@MerlinWither Does this occur with just Architectury + MCA Forge 1.18.2? If so, send that log here.

**Comment by MerlinWither** [comment]
> @MerlinWither Does this occur with just Architectury + MCA Forge 1.18.2? If so, send that log here.

Doesn't give me the error with fabric version or with forge 1.16.5
Only in Forge 1.18.2

**Comment by MerlinWither** [comment]
The error was fixed, there was a problem with Archituctery
