### ISSUE TITLE
Czech lang dont work

### ISSUE THREAD

**Issue by zanecek** [Luke100000/minecraft-comes-alive#121]
Minecraft is set to czech.
MCA works in english.
Maybe cs_cz instead of cs_cs?
(f.e. here:
https://github.com/Luke100000/minecraft-comes-alive/blob/1.18.2/common/src/main/resources/assets/mca/lang/cs_cs.json
)

**Comment by zanecek** [comment]
Sorry I play 1.16.5
https://github.com/Luke100000/minecraft-comes-alive/blob/1.16/common/src/main/resources/assets/mca/lang/cs_cs.json

**Comment by Luke100000** [comment]
Thanks! The mapping was wrong for a few languages.

**Comment by zanecek** [comment]
Please, when will be fixed this bug in 1.16.5 as well?
My privat modpack works in 1.16.5, because a lot of important mods are not yet available in 1.18.x...

**Comment by Luke100000** [comment]
Next release

**Comment by zanecek** [comment]
Thank you, I'm glad to hear that there will be next version for 1.16.5...
