### ISSUE TITLE
All spawn eggs are pigs

### ISSUE THREAD

**Issue by Vermin404** [Luke100000/minecraft-comes-alive#127]
in creative if i try to spawn a villager or grim reaper, anything from the mod. it just comes out as a pig. before maybe two updates earlier ( i have the forge 1.18.2 beta 18 now) i could spawn villagers but the grim reaper was a pig. the update just one before this, all of them were pigs and thats still the problem in the current one.

**Comment by ImDoingThisForMyWife** [comment]
Am having the same issues

**Comment by Kierstal** [comment]
Also having this same issue. 
Forge beta 1.18.2  40.0.18 (newer forge versions don't load half my other mods correctly).

**Comment by Vermin404** [comment]
this was fixed with the new architectury update recently!
