### ISSUE TITLE
7.2.0 beta 21 crashes (Fabric 0.13.3, 1.18.2)

### ISSUE THREAD

**Issue by ZaneFlynt01** [Luke100000/minecraft-comes-alive#128]
My game keeps crashing before it loads whenever I load it with beta 21, but beta 20 worked fine. The crash report that it gives me every time I try to open it is:

The game crashed while initializing game
Error:java.long.RuntimeException: Could not execute
entrypoint stage 'main' due to errors, provided by 'mca'!
Exit Code: -1

**Comment by CDAGaming** [comment]
@DarkBoi1987 Please attach a full log (.minecraft/logs/latest.log)

**Comment by CDAGaming** [comment]
closing, use beta 22 for 1.18.2
