### ISSUE TITLE
Suggestion: Have armor on guards last indefinitely.

### ISSUE THREAD

**Issue by pantsguyapp** [Luke100000/minecraft-comes-alive#131]
I love to give diamond armor for my guards, but it may be danger if the armor got depleted without my knowledge.
Maybe useful to make it so that the armors to never break on the villagers.

**Comment by WildBamaBoy** [comment]
No to this one. If armor didn't deplete, MCA's core gameplay behavior would deviate from Minecraft's.

**Comment by Luke100000** [comment]
Alternatively I can offer some sort of armory building where you provide armor in case it breaks.
