### ISSUE TITLE
MCA fails to load correctly

### ISSUE THREAD

**Issue by ImDoingThisForMyWife** [Luke100000/minecraft-comes-alive#132]
jang.lang.reflect.InvocationTargetException: null

I'm fairly new to modding minecraft and I want to get this mod for my wife because she really enjoyed it back in the earlier days of minecraft, I went into the Mod TOML and changed the load order to both before, and later after, it has not worked either time, I do have the latest version of Architectury installed, I don't know the issue and I was hoping for some help. Apologies if this is just a waste of time

[Crash Report 3-20-2022.txt](https://github.com/Luke100000/minecraft-comes-alive/files/8310702/Crash.Report.3-20-2022.txt)

**Comment by CDAGaming** [comment]
B21 is for 1.18.1, please use beta 22
