### ISSUE TITLE
Villager says I’m already married to her this is in 1.18.1

### ISSUE THREAD

**Issue by wingbroman** [Luke100000/minecraft-comes-alive#133]
She’s not married to me yet but she keeps saying she is and every time I try to gift her the diamond ring I have her at 73 hearts she keeps saying “it’s a nice ring dear but we’re already married is their a fix for this

**Comment by Luke100000** [comment]
Villager Editor, make the spouse field empty. Any idea how you may have caused this bug?

**Comment by wingbroman** [comment]
I'm playing this on questcraft vr so I don't know how to make the spouse field empty

**Comment by wingbroman** [comment]
And I don't know how it happened it just happened when I started flirting with her too much maybe

**Comment by Luke100000** [comment]
I'll close that for now since I lack the information to track that issue down
