### ISSUE TITLE
World unable to load

### ISSUE THREAD

**Issue by Gavin456b** [Luke100000/minecraft-comes-alive#137]
With MCA installed (currently 7.2.0-beta.25-forge) my world with fail to start, and sends me back to the main menu. There's no crash report but the error is visible in the latest.log. Upon removing mca the game functions again.
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/8337013/latest.log)

**Comment by T0X1CW17HUK3** [comment]
I have the same problem but in 1.16.5

**Comment by Luke100000** [comment]
Does this also happen if you only install mca?

**Comment by CDAGaming** [comment]
Closed due to this being an older MCA beta, when 7.2.0 wasn't in as stable of a condition.

If this issue still persists in 7.2.0, on a world that didn't use this specific beta, please re-open with a new crash log with just MCA (And related dependencies, if any).
