### ISSUE TITLE
Guards and Archers are teleporting like crazy and killing themselves [1.18.2] [7.2.0-Beta.40]

### ISSUE THREAD

**Issue by Art1xs** [Luke100000/minecraft-comes-alive#144]
what. the. heck.

**Comment by Vermin404** [comment]
i have this problem too. (forge version) all my villagers are teleporting around the village like crazy. a big amount of the population has died to this issue. not just guards or archers all of them. they either teleports up on roofs and gets stuck. or they teleport until they die. you cant really talk to anyone either, as soon as you try and talk to them they teleport away

**Comment by CDAGaming** [comment]
Resolved in newer betas. Please reset your config if you used betas effected by this, or manually increase the teleport limit
