### ISSUE TITLE
Crash when launching (1.16.5 fabric)

### ISSUE THREAD

**Issue by votalspectre** [Luke100000/minecraft-comes-alive#147]
Like the title says , it crashes when launching in 1.16.5 fab.
Other versions such as 1.18.2 works but not 1.16.5.
Does not matter which fabric 1.16.5 version , it crashes.

Here is the error message (if that helps):

The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'mca'!
exit code : -1

Also if anyone got the same issue , how did you fix it?

**Comment by Luke100000** [comment]
Please add the full log!

**Comment by CDAGaming** [comment]
Closing due to non-response, feel free to reopen with a full log when able!
