### ISSUE TITLE
[Suggestion] Poly Marriage

### ISSUE THREAD

**Issue by druidicmage** [Luke100000/minecraft-comes-alive#148]
i don't really have much else to say; can there be a poly marriage function? 

for SP;
some sort of trait villagers can have that allow or disallow it, and maybe a talk mechanic to talk about it and gain the trait perhaps

for MP;
being able to set marriage type to mono or poly? making you able to marry multiple people

**Comment by Luke100000** [comment]
We decided to not add this, we already have enough bugs with single marriage.
