### ISSUE TITLE
Feature: Family history for spawned/SpawnQueue villagers

### ISSUE THREAD

**Issue by KennaKilla** [Luke100000/minecraft-comes-alive#149]
When I come across a village there are baby villagers but they don't have parents like they should when I bring up the family tree. Is there a fix for this? 1.16.5

**Comment by Luke100000** [comment]
not a bug, just not implemented yet. Freshly spawned villagers are all orphans

**Comment by KennaKilla** [comment]
okay was making sure! thank you!

**Comment by Luke100000** [comment]
added
