### ISSUE TITLE
missing sounds?

### ISSUE THREAD

**Issue by WanabeNecro** [Luke100000/minecraft-comes-alive#150]
I'm trying to join a server but it gives me the error "Registry remapping failed: Received ID map for Minecraft:sound_event contains IDs unknown to the reciever" and then lists a bunch of names that looks like mca:villager_male_suprise or mca:working.saw, does this mean i should downgrade the mod?

**Comment by WanabeNecro** [comment]
also is this the correct place to put it or should i see if the server has its own github? just made an account to ask this stuff

**Comment by Luke100000** [comment]
Make sure both versions are the same, and if yes this is the right place to ask :)

**Comment by WanabeNecro** [comment]
yup that was it. got it working now, i didnt read what version of mca i needed i just grabbed the latest
