### ISSUE TITLE
Pehkui does not work on MCA Villagers

### ISSUE THREAD

**Issue by mcwoodcraft** [Luke100000/minecraft-comes-alive#151]
The scaling mod Pehkui does not work on MCA Villagers. The reason I guess is because MCA have their own scaling system for Villagers, well the model scales but not the hitbox.
Command used:
**_/execute run scale set 2 @e[type=mca:female_villager]_**

**Comment by Luke100000** [comment]
To avoid at least some of the million bugs in relation to the MC pathfinder the scale is limited to 1.99. Not sure how I can provide compatibility while avoiding villagers getting stuck at literally everything.

**Comment by CDAGaming** [comment]
Solution: Configurable : )

*Note: We are not liable if we make it configurable. You are on your own from there :)*

**Comment by mcwoodcraft** [comment]
Yeah makes sense
