### ISSUE TITLE
Villager teleports back to home village in multiplayer

### ISSUE THREAD

**Issue by j-rasberry** [Luke100000/minecraft-comes-alive#159]
If one player tells a villager to follow them from one village and brings it to a new village. Then commands them to stay. If another player comes along and tells them to follow them then the villager will just teleport back to where it came from.

**Comment by CDAGaming** [comment]
Resolved in 7.2.0 due to teleportation being configurable as well as teleporting itself being rewritten to avoid this type of situation.
