### ISSUE TITLE
Only allowing one job for each type of workstation

### ISSUE THREAD

**Issue by j-rasberry** [Luke100000/minecraft-comes-alive#162]
When placing down more than one workstation of the same type only one villager will accept the job. When moving to another village the same applies. I have ranked up my village but, you can't have more than one fletcher as an example. Not sure if this is a bug or a feature. I assumed these villagers still work similar to the vanilla villagers but, that doesn't seem to be the case.

**Comment by Luke100000** [comment]
can't confirm, which version? Doe sit work on a minimal example? (Flat world, 3 villagers, 3 brewing stands)
