### ISSUE TITLE
WhyI can't press the right mouse button to open book or interacting with villager？

### ISSUE THREAD

**Issue by Sakuraron** [Luke100000/minecraft-comes-alive#165]
I can't press the right mouse button to open book or interacting with villager.(version is 1.18.2)
Why?(I am a Chinese, I am poor at English)

**Comment by MithMax** [comment]
Same on 1.18.1 for me. Removed all my other mods, and only loaded MCA and Architectury (latest versions of both),  and I have no interaction menus, as well as the books not opening.

**Comment by Sakuraron** [comment]
I hope the author can repair

**Comment by CDAGaming** [comment]
Fixed in rc3

**Comment by MithMax** [comment]
Ahh just tested it, Thank you for the quick repair, and great job with this mod! Thank you.

**Comment by Sakuraron** [comment]
Thanks
