### ISSUE TITLE
[1.16.5] [v7.0.10] Please fix server console spam.

### ISSUE THREAD

**Issue by Cixon** [Luke100000/minecraft-comes-alive#168]
https://i.imgur.com/drFKzMi.png

**Comment by CDAGaming** [comment]
Will be fixed in 7.2.0, but won't be backported to prevent breaking changes and since this isnt an issue that can cause crashes

**Comment by CDAGaming** [comment]
Edit: Aforementioned response was for something different. These logger warnings are due to how our TrackedData works, so it being called from another class is just how it works unfortunatly.
