### ISSUE TITLE
Headstones do not allow writing 

### ISSUE THREAD

**Issue by Lebyo** [Luke100000/minecraft-comes-alive#169]
I have not figured out how to put a name on a headstone. Is there a tool needed, like a chisel or something?

**Comment by Luke100000** [comment]
This is done automatically once a villager dies

**Comment by Lebyo** [comment]
Ok, so I understand now. Place a headstone, and when a villager dies, the writing will show up on a headstone rather than the player receiving mail (only if the villager is related to you). And the headstones work regardless of a villager's relation to the player.

**Comment by Lebyo** [comment]
I wonder though, is there a way to transfer letters to headstones, or to revive a villager via a letter?

**Comment by CDAGaming** [comment]
@Lebyo to revive a villager, youd either need the scythe or staff of life

**Comment by CDAGaming** [comment]
Closed as resolved, at this time there are no plans to have custom tombstone writings as well.
