### ISSUE TITLE
ReaperSpawner crashma server

### ISSUE THREAD

**Issue by TheButterbrotMan** [Luke100000/minecraft-comes-alive#171]
Fabric: 0.13.3
Minecraft: 1.18.2
Modpack: https://www.curseforge.com/minecraft/modpacks/deathdusk
https://bytebin.lucko.me/i9hQNZaMGN

**Comment by CDAGaming** [comment]
@TheButterbrotMan Can you generate the crash without NotEnoughCrashes?

**Comment by TheButterbrotMan** [comment]
I dont know, because i dont know how to replicate.

**Comment by TheButterbrotMan** [comment]
Is there anyway i can tempfix this? keeps crashing my server.

**Comment by Luke100000** [comment]
You can disabled the grim reaper spawner in the config (`allowGrimReaper`) for now until I finally find the issue.

**Comment by CDAGaming** [comment]
Closed as presumed resolved / STALE. If this is still occuring, please re-open with a new log without NotEnoughCrashes.
