### ISSUE TITLE
you cant interact with villagers

### ISSUE THREAD

**Issue by Vermin404** [Luke100000/minecraft-comes-alive#172]
i cant give a gift to a villager. i go to interact like normal and the "right click to gift" thing and its just like always in that regard. but when you press on the gift nothing happens. i have tried this on multiple saves and i cant gift to anyone.

when finding this bug i found out that nothing but "talk" and "family tree" works. you cant trade or any kind of interaction. they are just empty buttons.

version mca : [[Forge 1.18.2] MCA Reborn - 7.2.0-rc.5+1.18.2]
Architectury: v4.1.44 for 1.18.2
forge: 1.18.2 - 40.0.44

<img width="421" alt="mcainteract" src="https://user-images.githubusercontent.com/101948309/162659954-3d2238f7-a49b-4231-ae9a-ef4fc7959ccf.PNG">
<img width="421" alt="mcaoptionbar" src="https://user-images.githubusercontent.com/101948309/162659955-b26a9f92-96fc-4504-ad1a-cc36496ea6d2.PNG">
<img width="421" alt="mcagift" src="https://user-images.githubusercontent.com/101948309/162659956-181abca5-4856-4be1-8985-83ab9b43b6a8.PNG">

**Comment by atecrayons** [comment]
same with me :(

**Comment by Luke100000** [comment]
Version and type of server please

**Comment by AlexProGear** [comment]
Same issue in forge 1.18.1, mod version 7.2.0
