### ISSUE TITLE
Suggestion: The ability to gift villager with meats to heal them

### ISSUE THREAD

**Issue by pantsguyapp** [Luke100000/minecraft-comes-alive#173]
When the villager following you, they might get themself in critical condition. The only valid solution atm would be to just wait for the villager to naturally heal themself. For this, player should be able to gift villagers with meat, specifically steak, for them to heal some health on the instant, similar to wolves.

**Comment by CDAGaming** [comment]
Eh, It wouldnt be instantly, more so it would be that at certain health levels it can choose a food item to eat and heal from (Both food priority and the health level would probably be configurable)

**Comment by Luke100000** [comment]
They will start eating when low on health if they have food.
