### ISSUE TITLE
issue with ores and villagers

### ISSUE THREAD

**Issue by atecrayons** [Luke100000/minecraft-comes-alive#175]
i've spend like two hours looking for rose gold, still can't find it and even went in spectator. It didn't spawn in anywhere :( please someone help if there's a place i'm supposed to look for it. Also none of the interactions work. this was all on the newest one on 1.18.1 forge. Gifting doesn't work either and won't let me give them the gold ring i made them or anything lol. I also cannot Trade button does nothing when I click it. I downloaded this all on to my apex server fyi. I even downloaded arch api and didn't make a difference. Anyways great mod been wanting an update forever and i feel so happy that it's back :)

**Comment by Luke100000** [comment]
Rose gold is not yet added due to the lack of use cases, it's only available as a creative item :)

**Comment by atecrayons** [comment]
i understand thank you for telling me about the ores. will village interactions be fixed?

> Rose gold is not yet added due to the lack of use cases, it's only available as a creative item :)

**Comment by Luke100000** [comment]
Once I find the bug, sure :) That's why I asked you to include more information, it doesn't happen for me.

**Comment by atecrayons** [comment]
> Once I find the bug, sure :) That's why I asked you to include more information, it doesn't happen for me.

sorry. so, when i click interact all of the choices don’t work, like follow, stay, ride horse, gift, ect. when you click any of those buttons nothing happens and they just stare at you lol. same thing with trade. I’m using the 1.18.1 forge version. I’m using other mods with it as well. here are the list of mods in a dropbox link

https://www.dropbox.com/sh/86ngt4kkkrza6ub/AACbvXf2fJO9AGC5a9oLuUUva?dl=0

**Comment by Luke100000** [comment]
Can you please provide the exact filename of mca and the type of server you are playing on?

**Comment by atecrayons** [comment]
> Can you please provide the exact filename of mca and the type of server you are playing on?

yes. i’m on my server and it’s apex hosting

**Comment by atecrayons** [comment]
the file name is “minecraft-comes-alive-7.2.0+1.18.1-forge.jar”
