### ISSUE TITLE
Not information of the rules

### ISSUE THREAD

**Issue by BedMan333** [Luke100000/minecraft-comes-alive#177]
There is not any way to know for what and how exacty do the rules tab works.

It says that taxes get in the chests, but does not. I don't know if was something missing from my part, or is a not designed as today.

The same for marry and birth limits. I don't know what they stand for, as, for example, a cannot still marry two people even when I got the King Rank, and I am still being able to procreate as much as a want. Maybe is just for the villagers, but it seems weird the way is blind explained.

**Comment by Luke100000** [comment]
I added tooltips, I hope that helps. Regarding taxes, if you get a message "Village paid their taxes", are all chests in the storage still empty? Marriage limit has nothing to do with the matchmaker rings required to marry two villagers.
