### ISSUE TITLE
Lags my single player world

### ISSUE THREAD

**Issue by lSherozl** [Luke100000/minecraft-comes-alive#181]
This mod seems to lag my world more than any other mod, mind seeing the spark results and seeing whats wrong https://spark.lucko.me/X6dV4ZxJ8x

**Comment by Luke100000** [comment]
Thanks. Some of the things are indeed buggy and can be fixed.

**Comment by lSherozl** [comment]
> Thanks. Some of the things are indeed buggy and can be fixed.

I would also see how your mod interacts with these mods which have similar functions:
https://www.curseforge.com/minecraft/mc-mods/villagers-respawn
https://www.curseforge.com/minecraft/mc-mods/regrowth
https://www.curseforge.com/minecraft/mc-mods/villager-names

**Comment by Luke100000** [comment]
I did a 30 min profiling report, 1.16.5 seems unaffected by the performance issue.

**Comment by lSherozl** [comment]
![image](https://user-images.githubusercontent.com/65663746/163681925-48cd9b99-b282-4da5-8459-db88537469fa.png)
It seems to be the heaviest mod, so its either there is something needed in the code to make it run smoothly, it conflicts with some mods we don't know about, or my computer is slow

**Comment by lSherozl** [comment]
You can try running it in the better minecraft plus modpack and see how well it is for you

**Comment by Luke100000** [comment]
Minecraft AI. There isn't really anything I can do from my side (except the bug I mentioned, it will remove 20% of mcas impact).  If you place an equal amount of vanilla villagers you should see a similar result. There are mods out there which party fixes the AI performance impact.

I also see that forge is drunk and causes another 20%, can't really influence that part.

The mods you mentioned all have far less complex entities and are not affected by this issue.

Try decreasing the entity update distance, if available. It's by far the slowest thing on a server and you often wont even notice if its decreased.

**Comment by Luke100000** [comment]
Ok, I finished the analysis and tracked this issue down to 2 problems, both caused by synchronicity and therefore wait times until e.g. chunks are loaded. First issue has been improved for now and will be pushed in the next version and will be fully fixed for 1.18.2 sometimes later.
Second issue is weird and requires more time in order to not introduce more bugs.
