### ISSUE TITLE
Mixin compatibility issue with other mods that mix into reloadPlayerRenderers

### ISSUE THREAD

**Issue by parzivail** [Luke100000/minecraft-comes-alive#182]
https://github.com/Luke100000/minecraft-comes-alive/blob/1.18.2/common/src/main/java/mca/mixin/MixingEntityRenderers.java#L27

This mixin overwrites the target method, which removes any chance of compatibility with other mods which simply inject into the target method, for example:

https://github.com/Parzivail-Modding-Team/GalaxiesParzisStarWarsMod/blob/master/src/main/java/com/parzivail/pswg/mixin/EntityRenderersMixin.java#L25

Related crash (reported to me by TheRanker#3348): https://pastebin.ubuntu.com/p/5BH8jXKBXJ/

**Comment by Luke100000** [comment]
Thanks for pointing that out, not sure why I used an Overwrite at all
