### ISSUE TITLE
Female and male possibly all npc's not loading in properly

### ISSUE THREAD

**Issue by SnoopisPoopis** [Luke100000/minecraft-comes-alive#187]
all npc's are 1ft tall and white entitys 
![image](https://user-images.githubusercontent.com/103967589/163884802-2282c526-8afc-4538-a762-c776d3ffb36b.png)

**Comment by Luke100000** [comment]
**[HOW TO WRITE ISSUES](https://github.com/Luke100000/minecraft-comes-alive/issues/114)**

**Comment by CDAGaming** [comment]
Closed via #114 and the fact that in most cases this is due to outdated mods.
