### ISSUE TITLE
Ticking Entity Error

### ISSUE THREAD

**Issue by JoanLona** [Luke100000/minecraft-comes-alive#189]
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 19/04/2022, 4:28 pm
Description: Ticking entity

java.lang.ArithmeticException: / by zero
	at mca.entity.VillagerEntityMCA.method_6007(VillagerEntityMCA.java:580)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1308.method_5773(class_1308.java:346)
	at net.minecraft.class_1646.method_5773(class_1646.java:318)
	at mca.entity.VillagerEntityMCA.method_5773(VillagerEntityMCA.java:603)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mca.entity.VillagerEntityMCA.method_6007(VillagerEntityMCA.java:580)
	at net.minecraft.class_1309.method_5773(class_1309.java:2354)
	at net.minecraft.class_1308.method_5773(class_1308.java:346)
	at net.minecraft.class_1646.method_5773(class_1646.java:318)
	at mca.entity.VillagerEntityMCA.method_5773(VillagerEntityMCA.java:603)
	at net.minecraft.class_3218.method_18762(class_3218.java:702)
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)

-- Entity being ticked --
Details:
	Entity Type: mca:female_villager (mca.entity.VillagerEntityMCA)
	Entity ID: 769
	Entity Name: Emilia
	Entity's Exact location: 88.63, 67.00, -1322.72
	Entity's Block location: World: (88,67,-1323), Section: (at 8,3,5 in 5,4,-83; chunk contains blocks 80,-64,-1328 to 95,319,-1313), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,-64,-1536 to 511,319,-1025)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:485)
	at net.minecraft.class_3218.method_31420(class_3218.java:363)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:331)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Valbahutog'/527, l='ServerLevel[New World]', x=80.50, y=66.00, z=-1330.50]]
	Chunk stats: 3292
	Level dimension: minecraft:overworld
	Level spawn location: World: (80,384,-1328), Section: (at 0,0,0 in 5,24,-83; chunk contains blocks 80,-64,-1328 to 95,319,-1313), Region: (0,-3; contains chunks 0,-96 to 31,-65, blocks 0,-64,-1536 to 511,319,-1025)
	Level time: 13 game time, 13 day time
	Level name: New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 108462 (now: false), thunder time: 76831 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:907)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 473826128 bytes (451 MiB) / 2147483648 bytes (2048 MiB) up to 2147483648 bytes (2048 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: Intel(R) UHD Graphics
	Graphics card #0 vendor: Intel Corporation (0x8086)
	Graphics card #0 VRAM (MB): 1024.00
	Graphics card #0 deviceId: 0x9bc4
	Graphics card #0 versionInfo: DriverVersion=27.20.100.8280
	Graphics card #1 name: NVIDIA GeForce GTX 1650 Ti
	Graphics card #1 vendor: NVIDIA (0x10de)
	Graphics card #1 VRAM (MB): 4095.00
	Graphics card #1 deviceId: 0x1f95
	Graphics card #1 versionInfo: DriverVersion=30.0.14.7168
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 3.20
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 18263.05
	Virtual memory used (MB): 12258.74
	Swap memory total (MB): 10240.00
	Swap memory used (MB): 754.33
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		additionalstructures: Additional Structures 3.0.3
		advanced_runtime_resource_pack: Runtime Resource Pack 0.5.5
		arcanus: Arcanus 1.29
		architectury: Architectury 4.2.50
		armor-stand-editor: Armor Stand Editor 1.3.2+1.18.2
		artifacts: Artifacts 7.0.3+fabric
		awesomedungeon: Awesome Dungeon 2.0.8
		awesomedungeonend: Awesome Dungeon Edition end 1.0.1
		awesomedungeonnether: Awesome Dungeon Edition Nether 1.0.1
		awesomedungeonocean: Awesome Dungeon Edition Ocean 2.0.6
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.6-1.18.2
		cardinal-components: Cardinal Components API 4.1.4
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-block: Cardinal Components API (blocks) 4.1.4
		cardinal-components-chunk: Cardinal Components API (chunks) 4.1.4
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		cardinal-components-item: Cardinal Components API (items) 4.1.4
		cardinal-components-level: Cardinal Components API (world saves) 4.1.4
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.1.4
		cardinal-components-world: Cardinal Components API (worlds) 4.1.4
		chunky: Chunky 1.2.164
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config: Cloth Config v6 6.2.57
		collective-fabric: Collective (Fabric) 4.26
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_llamalad7_mixinextras: MixinExtras 0.0.7
		com_github_luben_zstd-jni: zstd-jni 1.5.2-2
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		comforts: Comforts 1.1.2-1.18.2
		configurablemobpotioneffects-fabric: Configurable Mob Potion Effects (Fabric) 1.4
		convenient-mobgriefing: Convenient mobGriefing 2.0.2
		crawl: Crawl 0.10.6
		dashloader: DashLoader 3.1.1+1.18
		dehydration: Dehydration 1.2.7
		despawningeggshatch-fabric: Despawning Eggs Hatch (Fabric) 2.3
		dev_quantumfusion_dashloader_dashloader-core: dashloader-core 1.4.0
		dev_quantumfusion_hyphen: hyphen 0.2.0
		disable_custom_worlds_advice: Disable Custom Worlds Advice 2.0
		dismountentity-fabric: Dismount Entity (Fabric) 1.5
		dragondropselytra-fabric: Dragon Drops Elytra (Fabric) 1.4
		dualwielding: Dual Wielding 1.0.8
		dynamicfps: Dynamic FPS 2.1.0
		earthtojavamobs: Earth2Java 1.8.0+1.18.2
		easyelytratakeoff-fabric: Easy Elytra Takeoff (Fabric) 2.2
		elytratrinket: Elytra Trinket 3.0.0-1.18.1
		enchant_giver: Enchant Giver 1.1.0
		enchantingcommands-fabric: Enchanting Commands (Fabric) 1.7
		enhancedblockentities: Enhanced Block Entities 0.6+1.18.2
		environmentz: EnvironmentZ 1.2.2
		expandability: ExpandAbility 6.0.0
		fabric: Fabric API 0.51.0+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.3+d82b939260
		fabric-convention-tags-v1: Fabric Convention Tags 1.0.0+bd8a4a1860
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.14+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.4.0+4457765560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.11+91896a4960
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-language-kotlin: Fabric Language Kotlin 1.7.3+kotlin.1.6.20
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.3+2d83e92c60
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.0+81ea5b3c60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.0+fe4ddef060
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.0+2373a54560
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabricloader: Fabric Loader 0.13.3
		farsighted-mobs: Farsighted Mobs 1.1-1.18
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		fiber: fiber 0.23.0-2
		forgetmechunk: Forget Me Chunk 1.18.X-1.0.3
		freecam: Freecam 1.0.4
		geckolib3: Geckolib 3.0.38
		horsebuff: HorseBuff 1.2.3
		improvedmobs: Improved Mobs 1.18.2-1.10.7
		incendium: Incendium + Seed Fix 5.0.3
		indypets: Independent Pets 0.8.1
		infinitetrading-fabric: Infinite Trading (Fabric) 2.1
		invmove: InvMove 0.7.0
		iris: Iris 1.2.2-build.32
		java: OpenJDK 64-Bit Server VM 17
		lazydfu: LazyDFU 0.1.2
		libraryferret: Library Ferret 1.0.3
		lithium: Lithium 0.7.9
		logical_zoom: Logical Zoom 0.0.14
		maelstrom_library: Maelstrom Library 1.2.4-1.18.2
		mca: Minecraft Comes Alive 7.2.1+1.18.2
		mcda: MC Dungeons Armors 2.0.5
		mcdar: MC Dungeons Artifacts 1.4.5
		mcdw: MC Dungeons Weapons 4.2.5
		medievalweapons: Medieval Weapons 1.1.9
		minecraft: Minecraft 1.18.2
		mm: Manningham Mills 2.3
		modmenu: Mod Menu 3.1.1
		mostructures: Mo' Structures 1.4.1+1.18.2
		multipart_entities: MultipartEntities 1.1.5-1.18.2
		mythicmounts: Mythic Mounts 1.18.2-6.0
		omega-config: OmegaConfig 1.2.3-1.18.1
		org_anarres_jcpp: jcpp 1.4.14
		org_aperlambda_lambdajcommon: lambdajcommon 1.8.1
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.20
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.20
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.20
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_joml_joml: joml 1.10.2
		packet_tweaker: Packet Tweaker 0.2.0+1.18-pre1
		patchouli: Patchouli 1.18.2-67-FABRIC
		prefab: Prefab 3.1.3
		reach-entity-attributes: Reach Entity Attributes 2.1.1
		repurposed_structures: Repurposed Structures 4.1.5+1.18.2
		seedfix: Seed Fix 1.0.2
		server_translations_api: Server Translations API 1.4.9+1.18.2-rc1
		sgui: sgui 1.0.1+1.18.2
		sit: Sit 1.18.2-18
		skiptransitions: Skip Transitions 1.3.2+1.18.x
		sodium: Sodium 0.4.1+build.15
		spruceui: SpruceUI 3.3.0+1.17
		starlight: Starlight 1.0.2+fabric.89b8d9f
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		tenshilib: TenshiLib 1.18.2-1.6.6
		treeharvester-fabric: Tree Harvester (Fabric) 5.1
		trinketofundying: Trinket of Undying 2.0.1-1.18
		trinkets: Trinkets 3.3.0
		villagespawnpoint-fabric: Village Spawn Point (Fabric) 1.8
		waystones: Waystones 2.5.0
		worldedit: WorldEdit 7.2.10+1742f98
		worldeditcui: WorldEditCUI 1.18.2+01
	Loaded Shaderpack: ComplementaryShaders_v4.3.3.zip
		Profile: Custom (+7 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['Valbahutog'/527, l='ServerLevel[New World]', x=80.50, y=66.00, z=-1330.50]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

**Comment by Luke100000** [comment]
Did you set `giftDesaturationReset` to 0?
