### ISSUE TITLE
The interaction system doesn't make any sense

### ISSUE THREAD

**Issue by KayshiAri** [Luke100000/minecraft-comes-alive#190]
Any interaction is pretty much pure RNG no matter how many hearts you have with a villager. 
Sometimes they start hating you out of nowhere despite you gifting them stuff and overall trying pretty much anything
Is this the intended behavior because it seems like something's not working properly. 

Mod version: minecraft-comes-alive-7.2.0+1.18.2-fabric.jar

**Comment by Luke100000** [comment]
After interaction, what does the magnifier icon tell you?
