### ISSUE TITLE
Suggestion to add more visual traits

### ISSUE THREAD

**Issue by Jpex8** [Luke100000/minecraft-comes-alive#191]
More traits that changes the villager's physical appearance like gigantism as a counterpart to dwarfism, villagers being left handed and ambidextrous, and possibly being amputees.

**Comment by Luke100000** [comment]
since everything above 2m would break stuff gigantism would be only visual and therefore slightly weird.

**Comment by CDAGaming** [comment]
Closed as technically resolved, as I added a few traits on this list that technically makes this done.
Amputees and Gigantism would likely break things, but Left Handed was added in recent updates alongside other traits.
