### ISSUE TITLE
VillagerFactory

### ISSUE THREAD

**Issue by TheButterbrotMan** [Luke100000/minecraft-comes-alive#192]
Cannot really say anything about this crash, found it in my crash-reports folder.

https://bytebin.lucko.me/Do35zYe6oT

**Comment by Luke100000** [comment]
Thanks. I want to offload the villager spawner to a thread, this should solve this issue too.

**Comment by CDAGaming** [comment]
Should be fine now, re-open if this is still problematic in recent MCA updates.
