### ISSUE TITLE
Back Item Support

### ISSUE THREAD

**Issue by slave2midna** [Luke100000/minecraft-comes-alive#193]
Love the Destiny Feature! It's just such a wonderful addition to this mod, and I thank you for the work - However, using MC. 1.18.2, and the Alpha Build- in combination with Curios and Mr.Crayfish Backpack - the visual backpack doesn't appear on the back of MCA's models.

I've seen this before with mods that modified player models, and I can't remember what part of the mode needed to be changed for them to make it work for them - but I wanted to point it out in case there were plans to add support for mods using items that appear on the back of player models when using destiny.

Still using it! Love this mod, love this update! Keep up the great work!

**Comment by Luke100000** [comment]
In upcoming alpha 3 it should work
