### ISSUE TITLE
VillagerEditorSyncRequest

### ISSUE THREAD

**Issue by TheButterbrotMan** [Luke100000/minecraft-comes-alive#194]
Crashing in my modpack on server, when clicking on next. Client do not crash.
https://bytebin.lucko.me/UYxKpW9Lcu

**Comment by TheButterbrotMan** [comment]
https://www.curseforge.com/minecraft/modpacks/deathdusk

**Comment by TheButterbrotMan** [comment]
How can i disable the choose gender and name gui temporaily to temp fix this?

**Comment by Luke100000** [comment]
In the config there should be a flag, something with `destiny`.

**Comment by TheButterbrotMan** [comment]
Is there any progress on this? Anything I can do to speed up process?

**Comment by Luke100000** [comment]
Sorry, I'm lacking behind with the issues lately. I can not reproduce this error, but maybe it got fixed when I cleaned related issues. I try to push alpha 3 today, if you want please tell me if it's indeed fixed

**Comment by TheButterbrotMan** [comment]
I will. If you want to reproduce, just use my modpack.

**Comment by TheButterbrotMan** [comment]
Fixed!
