### ISSUE TITLE
Villagers won't breed, imported villagers wander off, Minecraft incest

### ISSUE THREAD

**Issue by killercow37** [Luke100000/minecraft-comes-alive#195]
I had, for a while, a bustling city of 24 villagers. Of those 24, one was my wife, and 13 were my children, leaving a total of 10 villagers. Of those 10 villagers, 2 were second generation. I've put the birth rate at 0%, I've put it at 100%, I've put it at 50%, and nobody is having any kids except me. I have no idea why. This brings me to my second bug.

I located a nearby village and kidnapped all 7 males of the village since I had 10 daughters (don't know if the large disparity between sons and daughters is a bug but it could be) and brought them to my village. I rehomed them all so they were citizens of my village, and yet every single one of them appeared dedicated to walking back to their old village. They never got far because I brought them home every time but it got bad enough that I ended up corralling them and leaving them in a fenced off area for a while because I was sick of finding them. One is still lost to this day. 

After the new villagers became accustomed to their new home, I began marrying them off. During the village gathering at the town square, I was giving rings to my daughters so that they'd marry whoever was nearby and one of the daughters married one of my sons. Not sure if that's a bug but it definitely weirded me out. If it's not a bug, there should be repercussions for incest like dwarfism or other deformities. I wouldn't know if there are or not, since they didn't have kids either. 

I have no idea why nobody is breeding except me. If possible, could a small side note be added when you hover over the rules in the blueprint that tell you what the percentages are? For example, when you hover over Birth Rate, it could say "Dictates how many babies are born in your village. A higher percentage means more babies" or whatever it is, since it isn't mentioned.

Other than those 3 things, I'm loving the mod. I played the old MCA and I'm happy with how this reborn is going. Excited for the return of monarchies and excited to see what changes could be made. Keep up the good work :)

**Comment by CDAGaming** [comment]
Closed as resolved, recent updates have ensured that incenstual circumstances cannot happen whatsoever.
Wandering off should also be less frequent.
