### ISSUE TITLE
Crash When Launching; Java Error Exit Code 1 (Forge 1.18.2)

### ISSUE THREAD

**Issue by HxneyLin** [Luke100000/minecraft-comes-alive#200]
I've tried downloading the different versions of mca on the forge website, and reinstalling java 17, even downloading java 18. It launches just fine when I remove the mod out of the mods folder, but when I place it back in and launch it, it gives me the Java Error Exit Code 1.

**Comment by den002** [comment]
same but for my issues a little bit different and my issues is: error loading mods
                                                                                      1 error has occurred during loading
                                                                                     MCA reborn has failed to load correctly
                                                                                    Java.lang.InvocationTargetException: Null
, and how do you fix it? Do you know how to fix thats Problems? please answer me

**Comment by Luke100000** [comment]
[HOW TO WRITE ISSUES](https://github.com/Luke100000/minecraft-comes-alive/issues/114)
