### ISSUE TITLE
I Cant Marry Anyone 1.18.2

### ISSUE THREAD

**Issue by ECFOX** [Luke100000/minecraft-comes-alive#201]
I have an engagement ring and no prior spouse and no matter who I get to 100 hearts they all will say I have a spouse and refuse marriage on those grounds, when I try and find them using the whistle no one shows up and it says loading never pulling up anything. Ive checked if its a conflict and have loaded only the mod to the same result. I have no clue what I can do to fix it

**Comment by Luke100000** [comment]
`/mca-admin resetMarriage` fixes that, but sadly I do not have enough information to fix the actual cause.
