### ISSUE TITLE
Skin Compatibility Issue with Epic Fight custom player model

### ISSUE THREAD

**Issue by user12312333** [Luke100000/minecraft-comes-alive#203]
When running MCA(7.3.0-alpha.2) with EpicFight(1.8.1.8) the skin is bug as shown below. This was on Forge v40.0.54. I know you spent a lot of time working on the skin customization and the detail (especially the eye blinking every some interval cause that's a very neat detail to the animation), so is there a way to make these 2 mods compatible? I remember Dr Who regen mod also has lots of skins but they apply it directly onto the vanilla skin so epic fight does not have compatibility issue. 

Worst case scenario, can a config option be added to temporary disable MCA skin until finding a way to make both of them work? 

![Screenshot from 2022-05-05 21-57-25](https://user-images.githubusercontent.com/83680483/167060436-eded0934-d526-4db7-ac24-07cf8af21928.png)

Thank you,

**Comment by Luke100000** [comment]
Epic Fight mod uses it's own models (stumbled across this issue with another mod already), a compatibility is theoretically possible but would take too much time and add a lot of more code to maintain. If anyone is interested, it would be a perfect chance for a plugin.

**Comment by Kurochimaru1** [comment]
It would be great if a guide to remove the function of MCA player skins from the new mod file, would just be posted... A compatibility mod is not required to do this, is it?

**Comment by Luke100000** [comment]
No, the player model can be disabled in the config, sry for missing that question :)
Where would you personally look for such a guide? I understand that the destiny screen is very aggressive and configuration is important. How would you like to resolve this personally?

**Comment by Kurochimaru1** [comment]
hmmm... So there is actually a config... And this function that gives mca player model is called "Destiny", correct?

**Comment by Luke100000** [comment]
`launchIntoDestiny` opens destiny
`allowDestinyCommandOnce` and optionally `allowDestinyCommandMoreThanOnce` allow to open destiny whenever you like
`allowDestinyTeleportation` toggles the start location feature
`letPlayerCustomize` only disabled mca models on players
`allowPlayerEditor` allows `/mca editor`

**Comment by Kurochimaru1** [comment]
I thank you from the depths of my heart for this quick response! I couldn't ask for more... May you be successful with all your goals... Thanks again!

**Comment by Kurochimaru1** [comment]
Sorry to bother you again. I've tried checking the MCA's config in the Mods menu, but it's greyed out, and I tried these commands on console in-game, but it seems they were not meant for the game console... Where exactly should I look for that config?

**Comment by Luke100000** [comment]
In the config directory :) `%appdata%/.minecraft/config/mca.json`
We can't really use the config screen because we use more complex entries and should stay modloader independent.

**Comment by Kurochimaru1** [comment]
Thanks again! This saved me for real this time! :3

**Comment by CDAGaming** [comment]
Resolved via 7.3.21's `playerRendererBlacklist`
