### ISSUE TITLE
Villager`s run away from me

### ISSUE THREAD

**Issue by zerorra** [Luke100000/minecraft-comes-alive#207]
after destroying the cobblestone, they avoid me and particles appeared on me
![2022-05-09_18 10 08](https://user-images.githubusercontent.com/49894501/167440606-0178b17f-5d82-46cd-8540-516de122d695.png)

**Comment by Luke100000** [comment]
Looks like another mod does this. We neither have this particles nor any interaction with blocks being destroyed.
