### ISSUE TITLE
HELP ASAP

### ISSUE THREAD

**Issue by irusV4** [Luke100000/minecraft-comes-alive#211]
**okay, so earlier today, 5/11/22 my Minecraft was working fine and better than ever, then hours later I try to get back onto Minecraft and it keeps saying that the mod "isn't loading correctly" and I've made sure it was updated and my architectury was updated and it made it even worse!! I'm using the 1.18.2 beta version of the mod so please help I really enjoy this mod and I also really enjoy Minecraft!**ALSO before it started being weird when i went to spawn some villagers IT SPAWNED PIGS!!!!

**Comment by Luke100000** [comment]
Please append the log!
