### ISSUE TITLE
Spouse or child when working just punches the air

### ISSUE THREAD

**Issue by GoldieGamingYT** [Luke100000/minecraft-comes-alive#214]
I'm playing Minecraft 1.18.2 with the latest release of the mod. Whenever I order my spouse or child to work, they will just punch the air (given that they have the right tools) and I have to push them to the nearest tree for them to chop but after that they'll just keep punching the air after the wood is gone and will do this till night fall. Is this a bug or feature?

Other mods installed:
Better Villages Mod

**Comment by Luke100000** [comment]
Punching the air was a sign that no trees have been found. It's fixed now and will get improved later.
