### ISSUE TITLE
Please Allow Disabling of MCA Players Skins - We want to use our own MC skins

### ISSUE THREAD

**Issue by MokahTGS** [Luke100000/minecraft-comes-alive#216]
Why do you force the MCA skins on players?  Please let us turn that option off in the configs.

**Comment by JahxSenpoopie** [comment]
> Why do you force the MCA skins on players? Please let us turn that option off in the configs.

We've already said we were making the destiny skins optional, had you actually looked on the discord, you wouldn't be here. Please look in the discord server for updates if you haven't already! Thanks!

Dom

**Comment by Luke100000** [comment]
Also, you CAN turn it off in the config

**Comment by MokahTGS** [comment]
Where?
