### ISSUE TITLE
comes alive reborn doesn't work

### ISSUE THREAD

**Issue by anonime21** [Luke100000/minecraft-comes-alive#218]
when I try to open minecraft it crashes and it tells me ''the game stopped working, this error could have been generated by a generation of invalid java runtime, check the custom settings''

**Comment by anonime21** [comment]
i only have this mod in the next forge version if this is a compatibilitie issue: 40.1.20 for 1.18.2

**Comment by anonime21** [comment]
comes alive reborn: 7.3.0-alpha3

**Comment by CHINGCHONG2012** [comment]
same, I'm using the 1.16.5 latest version and the game crashes every single time I use MCA, but when I remove MCA my Minecraft runs just fine, I then tried to test using MCA only and no other mod but the game still crashed

**Comment by Luke100000** [comment]
[HOW TO WRITE ISSUES](https://github.com/Luke100000/minecraft-comes-alive/issues/114)

**Comment by Luke100000** [comment]
for 1.18 you also need architectury
