### ISSUE TITLE
Please update lang 

### ISSUE THREAD

**Issue by Sakuraron** [Luke100000/minecraft-comes-alive#219]
![}VV JK~CWW8(9A3 JWVRL_0](https://user-images.githubusercontent.com/103231535/168967450-c1f4a21a-22b1-4bb0-aa8a-4d1cacd79118.png)
![1VXT~{TQTP_BEN8OW}D%N9M](https://user-images.githubusercontent.com/103231535/168967459-a320aa36-f239-4057-b1e9-e95fb74e344b.png)
![5 U`USJNG @7QU223@V~PBA](https://user-images.githubusercontent.com/103231535/168967460-e25b5cff-0485-4fe4-bf71-d686237772ce.png)
![9I@$UKF2GU75ISLT5`O2 TM](https://user-images.githubusercontent.com/103231535/168967461-90e47183-8da7-4afc-be91-2922ce301b20.png)
![9X0HMLVDQ7P2MTH`B)J3)DL](https://user-images.githubusercontent.com/103231535/168967464-30d6d51e-7d1c-4160-a3c4-4fc73e14f1bc.png)
![D5EB)5QVA9OE_D ~HQ6}~@8](https://user-images.githubusercontent.com/103231535/168967472-36dd4899-f616-479b-ab92-9aa5bb487912.png)
![OT{%8L03LC@VZPAV834F1VF](https://user-images.githubusercontent.com/103231535/168967476-59ffd75b-97c1-4210-9fb3-d040b299161f.png)
![X7)O@I3F9TB1IV%9JAG~551](https://user-images.githubusercontent.com/103231535/168967477-1635a609-dd87-4e1d-9b59-a30a000a388a.png)
![XE1W$I02TQ$(335PY12(HIH](https://user-images.githubusercontent.com/103231535/168967480-c4fddae8-f3b0-4225-a34a-037cc7321d65.png)
![ZK{2KE4HI8_UR4YDLEMTZD6](https://user-images.githubusercontent.com/103231535/168967482-577ac54d-1dae-4223-a2ef-e67cc4d3c5f5.png)

**Comment by Sakuraron** [comment]
Please update lang 7.3

**Comment by Luke100000** [comment]
https://crowdin.com/project/minecraft-comes-alive-2
