### ISSUE TITLE
Feature: Add a config to disable player model in destiny menu

### ISSUE THREAD

**Issue by TheButterbrotMan** [Luke100000/minecraft-comes-alive#221]
I would like a config, that disables the possibility for players to use their current skin.

**Comment by TheButterbrotMan** [comment]
= forcing mca skins

**Comment by Luke100000** [comment]
Done, if the config flag is set, the destiny won't allow you to choose. You can still enforce the player model in the editor, but in your case the editor should be disabled anyways. Clothing and Hair will be dedicated items soon.
