### ISSUE TITLE
Update Chinese Simplified！It done.

### ISSUE THREAD

**Issue by Sakuraron** [Luke100000/minecraft-comes-alive#222]
Update Chinese Simplified！It done.

![image](https://user-images.githubusercontent.com/103231535/169480678-a52e75c3-14d5-4820-ab6c-90ad56b313c1.png)

**Comment by Luke100000** [comment]
Awesome work, thanks!

**Comment by Sakuraron** [comment]
Sorry.Please Update again,have error




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Luke100000/minecraft-comes-alive"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月20日(星期五) 下午4:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Luke100000/minecraft-comes-alive] Update Chinese Simplified！It done. (Issue #222)





 
Awesome work, thanks!
