### ISSUE TITLE
3D-Skin mod compatibility

### ISSUE THREAD

**Issue by Dr-WeiAL** [Luke100000/minecraft-comes-alive#224]
It is recommended to remove some unused options after selecting a player in General
In addition, after selecting the player, it is best not to display the preview on the left as a villager. It is recommended to display it as the player skin.
Also suggested to add Slim model
![image](https://user-images.githubusercontent.com/47446553/169668663-b2543275-89a5-4387-a78f-d3974d62fbf1.png)
In addition, it has some compatibility issues with 3d Skin Layers. For example, the Slim arm is judged to be a Classic arm, resulting in abnormal double skin.
![image](https://user-images.githubusercontent.com/47446553/169668861-1486e1f2-6db6-478e-a1b0-884e41ba6bfa.png)

**Comment by Luke100000** [comment]
None of the settings are unused, they are still used for genetics, and therefore the preview is required too.

Slim models for players work, slim models for villagers do not because we have no interest in porting over 300 skins to slim format.

Not sure why 3D could break but I will take a look at this.

**Comment by Sarelth** [comment]
I would think that the 3D skins mod just does not get enough info from MCA. Do the villager skins have a outer layer? The 3D skins mod uses that to make it appear 3D. Just thought I would put that here as an observation though.

**Comment by OposDev** [comment]
Is this issue still being reviewed? I'm experiencing the same issue on my server :c 

Version 1.18.2

In addition, in F5 mode, when other players crouch, it makes your player model crouch as well. ( Probably from the Better Third Person mod? ))

**Comment by CDAGaming** [comment]
Will be resolved in 7.3.21, but I'll have to take a deeper look into Better third Person and 3D-Skin Mod

**Comment by CDAGaming** [comment]
Resolved via 7.3.21's `playerRendererBlacklist`
