### ISSUE TITLE
mod doors

### ISSUE THREAD

**Issue by Leonardox87** [Luke100000/minecraft-comes-alive#226]
Before I start, thanks for the mod and I apologize for my English.

I'm using the MrCrayfish's Furniture Mod, since the doors allow several heights and open all at once, but the MCAR does not consider them doors. Another possible alternative to manage the types of buildings and what they need could be through configuration.
Minecraft version: 1.16.5

![image](https://user-images.githubusercontent.com/84313013/170000741-0430297c-3fa8-4ebb-80e8-80bedcdfb0eb.png)

**Comment by Luke100000** [comment]
Sadly, MrCrayfish's doors are not considered doors in code, and tags don't exist either.
While it won't help you, the upcoming 1.18 versions won't require doors anymore. I therefore close this issue.
For your specific issue, just slam a door somewhere, it doesn't need to be an actual exit.

Building types will become manageable soon.
