### ISSUE TITLE
Villagers cannot use trading blocks from other mods

### ISSUE THREAD

**Issue by Dr-WeiAL** [Luke100000/minecraft-comes-alive#233]
Just like the title says, he won't get the occupation of other mods
![image](https://user-images.githubusercontent.com/47446553/171028336-a62bf53e-642c-4121-bee5-8494a2d3cde0.png)

**Comment by CrystalRiver998** [comment]
![2022-06-02_16 53 54](https://user-images.githubusercontent.com/106496807/171658103-6a04f6be-5e7a-40dd-9796-9b353aa858fb.png)
Same mod, worked for me... They just dont get a uniform, they can still be traded with

**Comment by Dr-WeiAL** [comment]
I can use vanilla work blocks here, but not mod work blocks

**Comment by CrystalRiver998** [comment]
Im using more Villagers as well. the MCA villagers can use the modded job blocks. do you have the most recent version of the mod?

**Comment by CrystalRiver998** [comment]
they should get green particals around them when they walk near the forest work block. then when you interact with them they have the job title. they just dont LOOK like they have the job

**Comment by Dr-WeiAL** [comment]
![image](https://user-images.githubusercontent.com/47446553/171686267-873b679a-ae2e-4517-a920-9da6ee7da75f.png)
I'm sure I'm using the latest version, but they still won't interact

**Comment by CrystalRiver998** [comment]
ohhh. i see now, im using 1.16.5. must be an issue with 1.18

**Comment by Dr-WeiAL** [comment]
Well, I forgot to tell you that I'm using version 1.18.2

**Comment by RogerVir** [comment]
Hmm.. Try assigning a building as a workplace and then add a modded block. The only issue I have is that they don't have a specific outfit for a job (as already mentioned by others). (1.18.1).

**Comment by CrystalRiver998** [comment]
Now using 1.18.2, no problem with them using job blocks from More villagers

**Comment by GeminiMarshdevil** [comment]
i am getting this issue on my 1.18.2 modpack, confirmed on server with 10 other players all experiencing the same issue. 
modpack in question:
https://www.curseforge.com/minecraft/modpacks/shaped-aion-cubes/files

this affects all extra jobs from all mods. pneumatic craft job is blocked, lightman's currency job is blocked, oh the biome's you'll go job is blocked.

**Comment by CDAGaming** [comment]
This issue is now closed as non-us. Under further investigation, some of Rubidium/Sodium's settings tend to interfere with villager's ai (The entity and AI mixins, which are disableable).
