### ISSUE TITLE
Feature Request: Mod Integrations with Currency Mods.

### ISSUE THREAD

**Issue by GeminiMarshdevil** [Luke100000/minecraft-comes-alive#234]
Howdy!
I'm the team lead on a group of modpack authors, making modpacks for a few server communities and I really wanna include Minecraft Comes Alive Reborn in all my future modpacks. To ensure that future outcome comes to pass, I'd love for MCAr to have currency integration configs with Lightman's Currency or Calemis Economy, on forge. (preferably Lightman's as that seems to be the one most folks are finding easiest to use, also the creator is just a swell guy)

Essentially the same sort of replacement Numismatic Overhaul has for villager trades, but on the Forge mods.  

preempting a question:
Our group has decided against using fabric due to a multitude of issues, chiefly among them being the head creator of fabric being vocally hateful towards certain groups of peoples.  We're equally not using Quilt due to a lack of mods support, currently.

**Comment by Luke100000** [comment]
Since MCA does not modify trades it should work fine, did you tested it?
