### ISSUE TITLE
Timeout while in Destiny Screen

### ISSUE THREAD

**Issue by TheButterbrotMan** [Luke100000/minecraft-comes-alive#237]
When i try to join my server, it connects i get dirt screen, then after some time i see the mca logo some seconds and time out

https://bytebin.lucko.me/tc7eNUxHnA

When i disable LaunchIntoDestiny it works.

**Comment by TheButterbrotMan** [comment]
When i enter /mca destiny everything works without problems. But when i stay to long in it i get timed out again.

**Comment by Luke100000** [comment]
Is this the complete log? Does this also happens on a server? Destiny pauses the game, but this should not cause a timeout.

**Comment by TheButterbrotMan** [comment]
It is the server log, client log looks nearly same.

**Comment by TheButterbrotMan** [comment]
Oh forgot to say, it only happens on the server. Client world runs fine.

**Comment by Luke100000** [comment]
Can you please try without REI? Because it throws a lot of errors, just to see if its related. Do I understand that the server does NOT crash? Can you send me the server log too, please?

**Comment by Luke100000** [comment]
Newest version (not recommended, buggy, but maybe upcoming 7.3.5) features a different way how destiny is handled. Maybe it fixed the issue, maybe not. It should at least handle interference with other GUI mods like origin better.

**Comment by CDAGaming** [comment]
Closing as assumed resolved, since it's been a month without any response, and we have yet to receive any similar issue relating to this.
