### ISSUE TITLE
No player skin Minercaft [1.16.5] (only steve skin)

### ISSUE THREAD

**Issue by MAGGen-hub** [Luke100000/minecraft-comes-alive#238]
I tried this mod with all my mods and without. Player allways have standart steve skin. Is it even posible to get vliager skin from [/mca editor] in this game version or not? I also don't have standart mca start screen... Please answer. Thank you for your attention.
Minecraft 1.16.5
Forge 36.2.35

**Comment by Luke100000** [comment]
Playing as the villager is added in 7.3.0 (1.18.2) and above, no backport is planned

**Comment by MAGGen-hub** [comment]
Thanks for answer.
