### ISSUE TITLE
Dialogues are broken with Spectrum mod

### ISSUE THREAD

**Issue by Kardane** [Luke100000/minecraft-comes-alive#239]
![image](https://user-images.githubusercontent.com/64183602/172129300-84ff8b2b-9edf-4d14-96ce-9a84a9119060.png)
7.2.0v

![image](https://user-images.githubusercontent.com/64183602/172130263-f3e32159-06b3-4519-9ab8-1bf139c73d72.png)
7.3.0v

Spectrum's version : spectrum-1.4.0-1.18.2-chaos-and-exploration
But previous Spectrum version works well (spectrum-1.3.3-1.18.2-midgame18-trinkets-brewing)

**Comment by TheButterbrotMan** [comment]
It seems Like Iris Shaders also had a problem connected to langfiles in combination with Spectrum. Maybe their bugfix helps you also to fix it?

https://github.com/IrisShaders/Iris/blob/trunk/docs/changelogs/1.2.6/full.md

**Comment by DaFuqs** [comment]
I adressed the issue with https://github.com/devs-immortal/Incubus-Core 👌

**Comment by CDAGaming** [comment]
Closed as resolved, thanks DaFuqs
