### ISSUE TITLE
A loading crash

### ISSUE THREAD

**Issue by PurpleRose44** [Luke100000/minecraft-comes-alive#240]
So ive got both mca reborn and the library thing in my mods folder (32 mods) and it says that mca has crashed during the loading, my minecraft doesnt crashed i can still play it.

I am just concerned on why it is happening because it doesnt do it all the time.

**Comment by Luke100000** [comment]
Can you please append affected logs and/or crash reports?

**Comment by PurpleRose44** [comment]
> Can you please append affected logs and/or crash reports?

Ah very sorry for not adding them in, im not very good with tech when it comes to logs but i have fixed it i just had an out of date config, i had to delete it then replay the mod.

I had the same problem with byg where someone said they deleted the byg config, again very sorry for not adding the logs,

**Comment by Luke100000** [comment]
No problem, glad its resolved!
