### ISSUE TITLE
Exit code 1 for MCA reborn forge 1.18.2

### ISSUE THREAD

**Issue by SheenieTheCat** [Luke100000/minecraft-comes-alive#241]
Hello yall, I am modding minecraft 1.18.2 but MCA reborn for 1.18.2 always gives me the "an unexpected issue occured and the game has crashed. We're sorry for the inconvinience. This crash may be caused by an invalid java runtime configuration. check any custom configuration settings exit code: 1

but the thing is my minecraft runs well with other mods, it's just minecraft comes alive reborn for 1.18.2 (yes i've triple checked the version) for my correct installer which is forge, that isn't working.

**Comment by Luke100000** [comment]
Please check and append the logs, and check if the correct architectury version is installed

**Comment by Regnak85** [comment]
Get this Error too, if i forget to install Architectury. So you should check if this is installed too.
