### ISSUE TITLE
Suggestion: Ability to disable notifications/local notifications

### ISSUE THREAD

**Issue by SupItzGray** [Luke100000/minecraft-comes-alive#242]
Hello, I love this mod a lot, I play with it on a multiplayer server. but.

The notifications for other villagers getting married seem to not be in a local area in the 7.2.1 1.18.2 Forge version. Users on this server find the constant notifications annoying.

My suggestion: a config to disable notifications serverwide, or these notifications only being in a radius around the notification event (Such as marriage)

**Comment by Luke100000** [comment]
Events will now only show when you are within the village or are good friends with this villager, and if its not explicitly disabled in the config.
