### ISSUE TITLE
Villagers not restocking their trade

### ISSUE THREAD

**Issue by Cheeky0wl** [Luke100000/minecraft-comes-alive#243]
So i got a villager librarian that i saved from being a zombie, unfortunately I've used up a certain trade option and she hasn't restocked that option for a long time now. She has a bed to sleep on; but on the village map she has no home. Do villagers need to be assigned to a home for them to restock?

**Comment by CrystalRiver998** [comment]
they just need to be able to interact with their block. Ive found that sometimes you have to reset them because someone else stole their block while  they were away from it-from playiing 1.16.5 and 1.18.2

**Comment by Luke100000** [comment]
I will close this because I never touched trades and was not able to find a reason for it not to work.
