### ISSUE TITLE
Small Chat Heads incompatibility

### ISSUE THREAD

**Issue by Fourmisain** [Luke100000/minecraft-comes-alive#247]
When using [Chat Heads](https://www.curseforge.com/minecraft/mc-mods/chat-heads), some villager messages get the player's chat head, for example:

![receiver_uuid](https://user-images.githubusercontent.com/8464472/173176427-5991b3db-a1e1-4f20-8757-284f93238ffa.png)

Fix is extremely simple:
https://github.com/Luke100000/minecraft-comes-alive/blob/70a69dbdc406dd7d4b9e691baffe6b933c0bca0c/common/src/main/java/mca/entity/ai/Messenger.java#L90
Instead of using `receiver.getUuid()` as the sender UUID, `Util.NIL_UUID` should be used.

(Btw, the reason why the other messages don't get a chat head is because they were sent using `player.sendMessage()`, which internally uses `Util.NIL_UUID`.)

**Comment by Fourmisain** [comment]
P.S.
Technically it'd be even better if the Villager's UUID would be used as the sender's UUID.
Chat Heads could then theoretically match the entity and show the Villager head in chat - but I can't expect you to rewrite your chat system just for a theoretical possibility.
(Also I'm not sure if the sender UUID is even allowed to be from a non-player.)

**Comment by Luke100000** [comment]
Yes, thats definitely a typo, thanks :)
It is not allowed to use a non player, since its not implemented for other entities. I could implement it, but that might break mods again. Since Chat Heads probably won't work on villagers anyways I will fix that with NIL_UUID.

**Comment by Luke100000** [comment]
Yes, that's definitely a typo, thanks :)
It works from non players.
