### ISSUE TITLE
Compatibility Issue

### ISSUE THREAD

**Issue by Jinx-Calem** [Luke100000/minecraft-comes-alive#249]
So I have a bunch of fabric mods, including Origins, and MCAR. I saw that there's the menu when you play a new world to create your character/profile for MCAR.... However when I started a new world, I got the origins select first, then it just threw me into the game. Is the profile selector for all worlds, or world-specific? And if it's world-specific, I'm fairly sure the origins menu glitches it out, and the profile menu doesn't appear.

**Comment by Luke100000** [comment]
fixed
