### ISSUE TITLE
1.18.2-server, Tired of Villagers stealing my bed :(

### ISSUE THREAD

**Issue by CrystalRiver998** [Luke100000/minecraft-comes-alive#250]
Attempted to use the restricted Access on my house to prevent villagers from coming in, doesnt work... does prevent them from making my house their home.... untill i log out, then my house is fair game again and i log in with all the beds in my house claimed.

Can we gave a way for players to "claim" a bed so villagers cant?

**Comment by Luke100000** [comment]
Added in 7.4.0, beds are now claimed and blocked buildings are not used by villagers
