### ISSUE TITLE
1.18.2 MCA and FirstPersonModel incompatibility

### ISSUE THREAD

**Issue by Orgamorsh** [Luke100000/minecraft-comes-alive#253]
MCA 7.3.1 villager model conflicts with FirstPersonModel 2.1.0. Firstperson has a feature that culls the arms from your playermodel in first person so you can use the vanilla arms. But when using the villager playermodel, the arms remain, resulting in double the arms.
![Screenshot_622](https://user-images.githubusercontent.com/58994640/174231208-679867b2-7ad8-4301-a069-bbe94b8f823a.png)

**Comment by OkinawaGaijin** [comment]
There is also a weird issue with the villager player model when used with the firstpersonmodel mod as well as Daedalus combat mod.

1. Daedalus adds neat combat animations like a three swing combo with a sword. If you use the firstpersonmodel mod you can see the swing animation in first person with no issues.
2. But if you also use a custom MCA villager skin, during the animation the arm swings right into the camera and blocks the view.

I tried different height and width settings to see if I can find a model size that works with no issues, but to no avail.

I actually thought about opening an issue about it, but I wasn't sure whether the fault lies within MCA, Daedalus, or the firstpersonmodel and I didn't want to bother all those devs with that problem, opening issues on each of their githubs.

**Comment by CDAGaming** [comment]
Closed as resolved in v7.3.21 via the `playerRendererBlacklist` (Where by default, when first Person Mod is active, it'll disable our arms so they can take over)
