### ISSUE TITLE
1.18.2 MCA: Game Crash Before Starting Up

### ISSUE THREAD

**Issue by YunanStratus** [Luke100000/minecraft-comes-alive#254]
When I start up either version of 1.18.2 MCA Reborn, my game crashes and I'm not sure why. I start up the game and it doesn't even get to the loading red screen before it crashes. I've made sure that its none of my other mods, it's only this one but I'm not sure how to check what's wrong with it or the reason behind it.

**minecraft-comes-alive-7.3.0-forge**
![Screenshot minecraft-comes-alive-7 3 0-forge](https://user-images.githubusercontent.com/86123583/174467103-e1a0c8c9-007a-4c54-b0a2-10f151da65f8.png)
![Screenshot minecraft-comes-alive-7 3 0-forge (2)](https://user-images.githubusercontent.com/86123583/174467107-c9772784-fa21-4026-8522-28d4f308104e.png)
![Screenshot minecraft-comes-alive-7 3 0-forge (3)](https://user-images.githubusercontent.com/86123583/174467108-00fb25e9-405a-40b3-ae69-010b1a25b2f2.png)

**minecraft-comes-alive-7.3.1-forge**
![Screenshot minecraft-comes-alive-7 3 1-forge](https://user-images.githubusercontent.com/86123583/174467121-bbad7946-71c1-425e-b365-13b6bafe3fba.png)
![Screenshot minecraft-comes-alive-7 3 1-forge (2)](https://user-images.githubusercontent.com/86123583/174467127-4a18b064-7560-42a0-9fd0-0cde38be6ac5.png)
![Screenshot minecraft-comes-alive-7 3 1-forge (3)](https://user-images.githubusercontent.com/86123583/174467130-3a458b12-e122-43d9-b0bf-e08fc61b8d43.png)

Screenshots for both versions of 1.18.2 (I'm unsure if they'll show up)

**Comment by Luke100000** [comment]
You are missing a dependency: https://www.curseforge.com/minecraft/mc-mods/architectury-api/files

**Comment by YunanStratus** [comment]
> 

Thank you!
