### ISSUE TITLE
Your children dont move.

### ISSUE THREAD

**Issue by CHERRYRACHH** [Luke100000/minecraft-comes-alive#258]
I have had two kids and even when being fully grown up they will not move, at all. I will tell them to follow me and walk away but they still don't move at all. I can move them by running into them but they do not move freely or follow you. (The version I am using is minecraft-comes-alive-7.3.3+1.18.2-fabric - from curse forge)

**Comment by Luke100000** [comment]
Can you verify this without any other mods please? On a new world.

**Comment by Luke100000** [comment]
Merged with #272
