### ISSUE TITLE
None of the Villagers have jobs

### ISSUE THREAD

**Issue by Blazie4ever** [Luke100000/minecraft-comes-alive#259]
I just started a new world in the 1.19 update. I've been to three different villages and none of the villagers have jobs other than a few guard villagers. I've tried to get them to have a job by placing more of the job items around such as lecturns, furnaces, etc as well as telling them that they are to work by them but it's been a few minecraft days and still none of the villagers have jobs. I started a second world and am still having the same issue.

**Comment by animartin4000** [comment]
Same here. 

For some reason the villagers wont assign themselves any jobs. I am using [[Fabric 1.19] MCA Reborn - 7.3.3+1.19](https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn/files/3841720) and it has been roughly a week or two in game. the village has 6 villagers and the only job assigned is a guard. Village has no nitwits and started with a Stone-cutter, a Cartographer table,  multiple compost bins, and i built a lectern along with a smithing table but nobody has taken any jobs. Seed is 769384246496236499 and i was at the nearest Savanna Village at  X 165 Z 765.

has anyone else had this issue by chance?

Mods i am using are
 - AdditionalAdditions-5.0.1
 - architectury-5.7.27-fabric
 - exlinecopperequipment-fabric-1.19-v2.0.3
 - fabric-api-0.56.1+1.19
 - iris-mc1.19-1.2.5
 - minecraft-comes-alive-7.3.2+1.19-fabric
 - modmenu-4.0.0
 - sodium-fabric-mc1.19-0.4.2+build.16

**Comment by animartin4000** [comment]
made a new game removing the other mods to avoid and conflicts and i was having the same issue were the villagers wont assign themselves any jobs.

**Comment by c4ll4d0ct0r** [comment]
I can confirm I am also having this issue. 1.19, forge, none of the villagers can get jobs unless I go into the villager editor and manually assign them to guard or something. I still can't get them to become any normal villager job even though there are valid buildings and job blocks in the village. This village has a population of 11 and no nitwits. I tried things in a different, brand new world and still had the same issue. 

edit: I also can't get the "average of 20 hearts" rank upgrade even though I have 20+ hearts with every villager. I wonder if this might somehow be oddly related?

**Comment by Wilevar** [comment]
Having the same issue. Did the same as Animartin4000 and confirmed it happens with just MCA and it's requirements.
- No jobs except for the guards,
- Villagers won't take a job at a new job site or when instructed to reset their work location,
- "Average 20 hearts" doesn't seem to actually use an average of all villager's hearts level, but instead seems to check Rank, which isn't clearly defined.

**Comment by NFLD99** [comment]
same issue here, temp fix ive done is add everything i need to a wondering trader via command blocks

**Comment by KSSTEA** [comment]
I'm having that same issue too, I need emeralds for a project but I can't get any because they're not taking jobs

**Comment by Nathan22211** [comment]
Can confirm this as well. No guard villagers, but I do find the occasional nitwit.

**Comment by DARKIN0918** [comment]
please fix this issue i can't play minecraft without MCA :(

**Comment by KlaraChaos** [comment]
i can also confirm this they dont take any new jobs

**Comment by Bloodaxe95** [comment]
Yeah it seems to be the case on my end as well. I'm on Fabric 1.19 with version 7.3.4.

**Comment by Nydekore99** [comment]
Same bug on my end, just glad I'm not the only one

**Comment by CDAGaming** [comment]
Fixed for 7.3.9, Sorry it took me so long to fix this, Issue due to placeholder code that made it into the release on accident.
