### ISSUE TITLE
Scythe can be applied to the ground + Cursed Villagers + Villagers in only one house

### ISSUE THREAD

**Issue by ghost** [Luke100000/minecraft-comes-alive#26]
I'm not sure if this is a thing supposed to be like that, but you can apply the Scythe with a soul to the ground, and you get the achievement that you have revived a villager- but nothing happens, because you have to apply the soul to the graves to revive, right?

The Screenshot depicts it the best. It's not permanently like this but sometime
![Screenshot (146)](https://user-images.githubusercontent.com/67586937/139577393-692c0f41-86d7-494d-a28a-e72534b52946.png)

Also, Villagers seem to enter only one home. I didn't spawn them manually into there, I spawned a few more to watch this occasion, and also the Villagers which were here before entered this house. I didn't enter it as well because I noticed that Villagers started following me randomly.
![Screenshot (147)](https://user-images.githubusercontent.com/67586937/139577168-3912287e-91b6-4f67-b1d0-58c3e02087cf.png)

And are Kids supposed to sit on the ground like this? Because they might be slaughtered very easily by zombies then.  As well as that, revived Kids seem to brabble the whole time, lol
![Screenshot (149)](https://user-images.githubusercontent.com/67586937/139577246-94c6ae1e-65bd-4539-9d7b-cec9c55bdab6.png)

As a last little reminder, I noticed that some Graves were occupied by the same person : like two graves were used by one person, it wasn't the same name, it was the same person. But I didn't went further into it.
You can revive one and on the other one nothing happens. Also you can apply two souls on one gravestone which wastes a soul.

**Comment by Luke100000** [comment]
Please use different issues :)
Subissue 1 has been fixed, the missing skin issue is weird. Is this a vanilla zombie villager? Do you use fabric or forge?

**Comment by ghost** [comment]
> Please use different issues :) Subissue 1 has been fixed, the missing skin issue is weird. Is this a vanilla zombie villager? Do you use fabric or forge?

Yes I will next time! Sorry for the mistake. And yes it is a Vanilla Villager and the version is the Forge one.

**Comment by Luke100000** [comment]
everything should be fixed in the meantime
