### ISSUE TITLE
Villagers Cause Lag When 'Staying'

### ISSUE THREAD

**Issue by Reveter** [Luke100000/minecraft-comes-alive#262]
Villagers are causing significantly more lag when told to stay, over when allowed to move freely, as profiled with Observable. Possibly related to job blocks, per #72, as the villager in question was emitting green particles.

Staying
![2022-06-25_00 59 05](https://user-images.githubusercontent.com/8112174/175759416-c82850a1-7333-4307-9da7-ec24bd630347.png)
.

Moving Freely
![2022-06-25_01 00 27](https://user-images.githubusercontent.com/8112174/175759435-0bb98ac8-93f9-4478-9992-417cc96fd474.png)

Profile of a Staying Villager
![mca_profile](https://user-images.githubusercontent.com/8112174/175759450-dc879eb7-e0dd-4bb3-ab82-192161c7ec18.png)

**Comment by ProsperCraft** [comment]
This is on a multiplayer server running the [TownCraft ](https://www.curseforge.com/minecraft/modpacks/towncraft)for 1.18.2 pack.  
minecraft-comes-alive-7.3.3+1.18.2-forge

We won't be able to keep it in the pack if not resolved as the pack is meant for a high population server.
