### ISSUE TITLE
Archer's friendly fire and Thorns

### ISSUE THREAD

**Issue by SDPhantom** [Luke100000/minecraft-comes-alive#268]
I often help defend the villages from mobs. During which, taking friendly fire from archers is a common occurrence. When I have Thorns on me, I get hit, the archer takes thorns damage, then they get pissed at me over the damage they took.

**Comment by CDAGaming** [comment]
Closing since for the most part, there isn't much that can be done with this without significant pathfinder edits.

**Comment by Luke100000** [comment]
But we can prevent prevent passive thorn damage. I will keep that closed because friendly fire is a major topic and is on the todo already
