### ISSUE TITLE
Villagers and player villager models from older versions render with black hair

### ISSUE THREAD

**Issue by SDPhantom** [Luke100000/minecraft-comes-alive#269]
Minecraft: 1.18.2
Forge: 40.1.52
MCA: minecraft-comes-alive-7.3.4+1.18.2-forge.jar

![Untitled](https://user-images.githubusercontent.com/29202325/176713114-cb212444-bf72-4efc-b11f-9a70dd7733a2.png)

**Comment by SDPhantom** [comment]
Seems like this only happens for villagers generated by older versions of MCA Reborn. Using a villager editor on affected villagers to re-set their hair color doesn't work, nor does using _**/mca editor**_ for an affected player.

**Comment by Luke100000** [comment]
fixed in recent version
