### ISSUE TITLE
Server Players stuck in Spectator mode (1.18.2) (on first join)

### ISSUE THREAD

**Issue by gamerpotion** [Luke100000/minecraft-comes-alive#271]
Hi, on my modpack's server - [https://www.curseforge.com/minecraft/modpacks/darkrpg](https://www.curseforge.com/minecraft/modpacks/darkrpg)
players are complaining that when they join the game for the first time, they get stuck in spectator mode. We have to run an auto command on the server to switch players into survival mode, but is there a way to fix this?  I'm guessing this happens when they first make their destiny choices and combined with server lag it happens?

**Comment by SDPhantom** [comment]
There was a compatibility issue with Origin #255 that was fixed a week ago. It appears to have gone out in the 7.3.4 version.

**Comment by gamerpotion** [comment]
> 

Hey thanks, yes we are on the latest 7.3.4 version.  Shall I disable the destiny launch option in config for now?

**Comment by SDPhantom** [comment]
I'd try it.

**Comment by jiangyh91** [comment]
Hi, we are also on the latest 7.3.4 version, and we have same problem on 1.18.2 fabric server.

**Comment by Luke100000** [comment]
Upcoming 7.3.5 should fix it, please report if it has been fixed
