### ISSUE TITLE
Children dont move on a server.

### ISSUE THREAD

**Issue by CHERRYRACHH** [Luke100000/minecraft-comes-alive#272]
When playing on a server, if you place a child down, they do not move. They don't move even when you tell them to follow or do a chore. They only begin moving once they have hit the adult age.  (Mod version is: minecraft-comes-alive-7.3.4+1.18.2-fabric)

**Comment by SDPhantom** [comment]
Have you checked if they move in other age states? There are 5 of them with different speed settings, Baby, Toddler, Child, Teen, and Adult. Babies are stationary and not meant to move. They just sit in place from the moment you spawn them. They should start wandering around at the Toddler state. This should be a quarter of your _**villagerMaxAgeTime**_ setting; 40 mins or 2 Minecraft days by default. (192000 ticks / 20 ticks per sec / 4 growth stages)

**Comment by CHERRYRACHH** [comment]
Yes, I've checked. They don't move at all until they hit the Adult stage, but as I've tested they only don't move on a server. Singleplayer they are just fine.

**Comment by CHERRYRACHH** [comment]
So i figured out if you use a Villager Editor on them it'll unstick them but they are still stuck unless you use one.

**Comment by Luke100000** [comment]
Sadly I still can't verify this. Try without any other mods please

**Comment by CDAGaming** [comment]
Closed as non-reproducable, please re-open if this is present in the latest mca version.
