### ISSUE TITLE
Get In T Bucket Mod Crash

### ISSUE THREAD

**Issue by keepinitreal247** [Luke100000/minecraft-comes-alive#273]
So I've been looking like everywhere for my crash log to post here after trying to pick up a villager in a bucket but one doesn't seem to have generated Minecraft closes without reason anytime I try so here is the debug log instead :\
AND NOW I CAN'T GET THE GODDAMN DEBUG LOG TO LOAD......Sorry Just let me know if you cant recreate this and ill try my best to get the debug log........

Minecraft Version-1.18.2
Forge Version-40.1.48
Mod Versions- MCA -(7.3.4+1.18.2) GITBM(1.18.2 - 4.0.1)
Debug Log-

**Comment by Luke100000** [comment]
Can you please link this mod? I can't seem to find it.

**Comment by CDAGaming** [comment]
![image](https://user-images.githubusercontent.com/16328918/187566416-73f844d3-b7b0-48e2-9894-b34c8e812030.png)
Fixed in v7.3.21 via `villagerInteractionItemBlacklist`
