### ISSUE TITLE
Easy Villager

### ISSUE THREAD

**Issue by Luke100000** [Luke100000/minecraft-comes-alive#275]
Not gud. Need fix. Cloning and wrong villagers.

**Comment by Luke100000** [comment]
Can't fix, Easy Villagers only support Vanilla. But I fixed that planting vanilla villagers are converted to mca villagers.

**Comment by kanapuro** [comment]
unfixable !??!?! screw my stupid sigma life!!! im trying to play with Infinite Trades and that doesnt work, and Trade Cycling rarely works half the time either!!! man!!!!

**Comment by JahxSenpoopie** [comment]
womp womp
