### ISSUE TITLE
Can't marry a player because ''I'm married to a villager'' when I'm not married to any villager

### ISSUE THREAD

**Issue by KSSTEA** [Luke100000/minecraft-comes-alive#278]

**Comment by Sakurokamizenakura** [comment]
You can try open your profile (/mca editor), then check if your marry status is empty. If not, delete the name of your "spouse" and try to marry another player. If it's empty, try to write the name in that box, close the window, open your profile again and then delete the name you wrote. Hope this will work.

**Comment by Luke100000** [comment]
I broke something in recent updates, which cause relationships from older saves to be corrupted
