### ISSUE TITLE
Adventurers still won't stay.

### ISSUE THREAD

**Issue by IndolentKheper** [Luke100000/minecraft-comes-alive#282]
It wasn't fixed, now they just say something different. 100 hearts, 20 open beds in the village, still can't get any adventurers to stay. The only way is to get them turned into a zombie and cure them.

**Comment by Luke100000** [comment]
What are they saying instead? Notice that you have a 50% chance of success, increasing when you gained hearts. Not every adventurer likes to stop adventuring.

**Comment by IndolentKheper** [comment]
Ok I get it now, so it's really that only 50% of adventurers have the possibility of moving in, not that each adventurer has a 50% chance. The ones that refuse never say yes no matter how many hearts, while the ones that agree to stay will do so if you just ask once or a few times. Seems I was unlucky and a majority of my adventurers were ones who would never join, no matter how many hearts or how many times I asked. But I got one today that joined right away.

Might need to be clearer that the ones that don't want to stay will never want to stay no matter how much you ask.

**Comment by Luke100000** [comment]
I see. I will add phrases specifically appearing when you ask twice.
