### ISSUE TITLE
1.18 Baby Disappearing Bug

### ISSUE THREAD

**Issue by Reyzerbit** [Luke100000/minecraft-comes-alive#285]
I was just goofing around seeing if there is any way to drop a baby, and I found if you click outside of the inventory GUI to drop the baby, it makes the baby disappear and you get the "don't drop the baby" message, but never get the baby back in your inventory.

**Comment by KingMushroomBoy** [comment]
It is probably intentional. Babies if they get dropped in real life will probably die. That's just a guess I have never tried it so I won't know XD

**Comment by CDAGaming** [comment]
Closed as feature is intentional
