### ISSUE TITLE
Rumours make the game unresponsive in a world with no structures

### ISSUE THREAD

**Issue by alex-fantastico** [Luke100000/minecraft-comes-alive#286]
Asking for a rumour caused the game to stop working properly, and need to be closed with Task Manager. I was playing in a world with structures turned off, and this seems to be the cause. I had no issue in another world which had structures. 

Presumably the game is getting stuck in an infinite loop, searching for structures which don't exist.

**Comment by Luke100000** [comment]
Should not happen, I set a maximum search range and it should stop after a while. I will check this, thanks!

**Comment by Skeevert** [comment]
So I ran some tests and found out, that the locate stronghold command in vanilla does not fail in a world without structures: it just points to the coordinates where it's supposed to be.
Maybe that'll be helpful.
I think I can take a closer look myself.

**Comment by Luke100000** [comment]
Sadly I wasn't able to fully fix it, as I did not find a way to check if structures are present in general. I instead decreased the search distance to 128 (from 256). It should now scan for approx a minute and then stop, similar to the locate command.
