### ISSUE TITLE
Langfiles fails loading?

### ISSUE THREAD

**Issue by TheButterbrotMan** [Luke100000/minecraft-comes-alive#287]
![unknown](https://user-images.githubusercontent.com/64548098/178392105-aa2afff4-28d8-45b4-9228-60a037b94b99.png)
https://bytebin.lucko.me/GDdrGnuDc0

**Comment by TheButterbrotMan** [comment]
It looks for all destiny.story.x like this

**Comment by Luke100000** [comment]
Do you have spectrum installed by any chance?

**Comment by TheButterbrotMan** [comment]
Yes. This mod.

**Comment by Luke100000** [comment]
Yea, spectrum (or more probably, one of its libraries) does some funny stuff and neither me nor Spectrums dev found the actual problem yet.

**Comment by Luke100000** [comment]
https://github.com/Luke100000/minecraft-comes-alive/issues/239

**Comment by TheButterbrotMan** [comment]
Is this fixed in latest release? Im still experiencing it, this why i am asking.

**Comment by Luke100000** [comment]
no, not yet fixed, I merged the issue here with the one mentioned

**Comment by TheButterbrotMan** [comment]
Ops, sorry!

**Comment by TheButterbrotMan** [comment]
> no, not yet fixed, I merged the issue here with the one mentioned

Anything i can do to fix this temporarily? Without removing spectrum or mca?

**Comment by TheButterbrotMan** [comment]
@Luke100000
