### ISSUE TITLE
1.16.5 "40 average hearts" challenge won't be checked off

### ISSUE THREAD

**Issue by weevilz** [Luke100000/minecraft-comes-alive#289]
i have at least 60+ hearts on all my villagers (about 5 or 6) and it still wont check off. i reloaded the world and i closed minecraft and reopened it, none of which fixed the problem. my taxes are at 0%, does that have anything to do with it? every other challenge is completed.

**Comment by Luke100000** [comment]
To avoid being the king of a small village, average hearts are weighted towards larger villages. For 5 villages, you need an average of approx 80. Since thats confusing I'm working on a better solution.

**Comment by weevilz** [comment]
ahhh i see. thank you :)
