### ISSUE TITLE
Could not execute entrypoint stage 'main' due to errors, provided by 'mca'! Fabric 1.18.2

### ISSUE THREAD

**Issue by Gamerbolts** [Luke100000/minecraft-comes-alive#292]
Hello! I am working on a rather large fabric modpack. I updated MCA Reborn to the newest version of 7.3.6. I tried to start my server and it failed to load. No crash. But I do have this log. Any help is appreciated. Thank you!

https://pastebin.com/LejSLxu9

**Comment by Luke100000** [comment]
Yea sorry for that, I messed up the server and fixed it a hour later in 7.3.7, please try this version :)

**Comment by Luke100000** [comment]
Also I see Spectrum in the mod, there might be issues with the translations together with that mod. I'm still investigating that issue.

**Comment by Gamerbolts** [comment]
Yep the issue was fixed in 7.3.7. Thank you. I will keep on eye on Spectrum and report anything I find.
