### ISSUE TITLE
Datapack Failed Validation

### ISSUE THREAD

**Issue by ardissaps** [Luke100000/minecraft-comes-alive#293]
https://paste.atlauncher.com/view/07afd37d-5ccb-42a5-91c7-600d783e2a82
![image](https://user-images.githubusercontent.com/82106625/178639819-b9b9546c-0fed-4055-8fb8-9a27f982d8c0.png)

**Comment by erazare** [comment]
not sure if this is the same issue as i am watching it from the server side.. i havent even attempted to run it on the client, if it wont work in a server enviroment i have no interest in it. i first noticed it when updating from 7.3.5 to 7.3.7 and the error was that this mod is specifically trying to execute a function as a client and not a dedi which is an automatic irrecoverable failure. This event occurs IMMEDIATELY after the server is "ready for connections". I then backed down to 7.3.6 and had the same errors and fatality. Backed back to 7.3.5 and runs like mercury. I have tried this on 40.1.54 and 40.1.60 same exact results.

**Comment by Luke100000** [comment]
7.3.6 is confirmed to fail on server only, was a different issue. Are you using forge or fabric?

**Comment by erazare** [comment]
forge.. here's the crashlog :
[crash-2022-07-13_12.32.44-server.txt](https://github.com/Luke100000/minecraft-comes-alive/files/9104266/crash-2022-07-13_12.32.44-server.txt)

**Comment by erazare** [comment]
also i have tried this without any Epicfight mod with same result.. i only mention this because i had been using 7.3.5 with EpicFight with no issues, i just assumed that incompatibility has been fixed. but i did try it without and then same exact result ( that crashlog is without )

**Comment by Luke100000** [comment]
Awesome, found the error, will fix this later that day.

**Comment by erazare** [comment]
Thank you so much glad I could help

**Comment by erazare** [comment]
Awesome, thanks!
