### ISSUE TITLE
Keeps crashing 1.18.2

### ISSUE THREAD

**Issue by Doviie** [Luke100000/minecraft-comes-alive#296]
[crash-2022-07-13_23.02.36-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/9108051/crash-2022-07-13_23.02.36-client.txt)

**Comment by Luke100000** [comment]
Can you please send the latest.log

**Comment by CDAGaming** [comment]
Closed due to non-response, Please re-open with a valid log and we'll take a look into this
