### ISSUE TITLE
Rightclicking with Blueprint crashes game 

### ISSUE THREAD

**Issue by TwixWolf** [Luke100000/minecraft-comes-alive#297]
I have used the mod for a month on my SMP server. However, i recently discovered how to use the blueprint.  When I do the game crashes to home screen.  I am not sure what is conflicting
[crash-2022-07-13_23.02.36-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/9117534/crash-2022-07-13_23.02.36-client.txt)

**Comment by Luke100000** [comment]
Latest.log please

**Comment by TwixWolf** [comment]
Yes!  I also updated my MCA to the latest version and it still crashes.  Here are the logs and the crash repor
[crash-2022-07-17_21.31.53-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/9129006/crash-2022-07-17_21.31.53-client.txt)
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/9129007/latest.log)
t

**Comment by TwixWolf** [comment]
I have an update.  It only happens where I am building.  Using a naturally spawning village works fine.  But I am trying to make my own village

**Comment by Luke100000** [comment]
Good job, thanks. To temporarily fix it, you can use `/mca-admin removeVillage theAffectedVillagerName`. This will force the village to reevaluate, hopefully removing the broken building. In the meanwhile I try to fix it.
