### ISSUE TITLE
CRASH WHEN BOOTING bug 1.18.2

### ISSUE THREAD

**Issue by BLAZINGKAT** [Luke100000/minecraft-comes-alive#298]
when Minecraft loads with this mod installed it immediately crashes as it boots up and it constantly says java runtime configure error 1

mod version is newest release for 1.18.2
error java runtime

**Comment by 4rthr1** [comment]
try to download the architectury mod, I'd the same problem for a couple days and I finally figure it out with architectury API

**Comment by Luke100000** [comment]
latest.log please

**Comment by CDAGaming** [comment]
Closed due to non-response, please re-open if still present with a valid log file.
