### ISSUE TITLE
{Enhancement} Rose Gold

### ISSUE THREAD

**Issue by Kqmu** [Luke100000/minecraft-comes-alive#30]
Enhancement: 
Config Setting to DISABLE Rose Gold Spawns

For the Forge side May I suggest a tag on Rose gold (since Tinker's Construct adds Rose Gold)
basically maybe add the tag
"#forge:ingots/rose_gold" for more Cross Mod compatibility 
MCA Rose Gold: 
![image](https://user-images.githubusercontent.com/70139586/140012731-f8f51f76-5292-4916-acac-3fc2febc7530.png)
Tcon Rose Gold: 
![image](https://user-images.githubusercontent.com/70139586/140012747-830ac8f4-7967-467d-9cab-82f239271731.png)

**Comment by JahxSenpoopie** [comment]
We're leaving our rose gold in the mod, we will have a purpose for it in the future
