### ISSUE TITLE
Seeing my own head compatibility compatibility issues

### ISSUE THREAD

**Issue by CyberTime48** [Luke100000/minecraft-comes-alive#301]
When using First-person Model and MCA it will render the my head when looking at my roommates account. It also will un-render his head.
This does not happen with my other friend who does not share a room.
I tested this issue with just MCA, First-person Model, Not Enough Animations and Skin Layers 3D on minecraft 1.18.2. Forge 40.1.68
![Headless bro](https://user-images.githubusercontent.com/109621302/179818428-c404bfe2-e6f4-412e-a3fd-e8e140edf448.png)

**Comment by CDAGaming** [comment]
Fixed via 7.3.21's `playerRendererBlacklist` Setting, as certain RenderLayers can now be disabled with different mods if they overwrite the same things we do.
