### ISSUE TITLE
THE GAME CRASHED WHILST RENDERING OVERLAY (1.18.2)

### ISSUE THREAD

**Issue by GaelGlez** [Luke100000/minecraft-comes-alive#302]
I keep getting this error, I have already installed architectury-4.5.73 because I have the forge-40.0.24 version and thats the only that supports it, I have tried all the version of MCA and none of them works, can you help me pls? 
![Captura de pantalla (15)](https://user-images.githubusercontent.com/109765970/180315713-548451ad-5da5-477f-ad31-5c3d65668405.png)
![Captura de pantalla (17)](https://user-images.githubusercontent.com/109765970/180317526-4031eb2e-bd04-46e0-b3af-e881bf3ce95d.png)
[crash-2022-07-21_15.59.25-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/9162874/crash-2022-07-21_15.59.25-client.txt)

(This is the first time that I ask for help, so I dont know if this is all that you need or how you need it)

**Comment by Luke100000** [comment]
Can you try without optifine please?

**Comment by GaelGlez** [comment]
yes look, Its giving me the same error again
![Captura de pantalla (21)](https://user-images.githubusercontent.com/109765970/180321098-e6b5c532-53ff-43ce-b8da-9e1f6190aa12.png)
![Captura de pantalla (19)](https://user-images.githubusercontent.com/109765970/180321104-bd1291a1-cbbd-4cbf-8a59-04589a803730.png)
[crash-2022-07-21_16.48.36-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/9163000/crash-2022-07-21_16.48.36-client.txt)

**Comment by GaelGlez** [comment]
I dont know if this makes it easier but I run the game without any other mods, just those two and now this is what appears
![Captura de pantalla (23)](https://user-images.githubusercontent.com/109765970/180325316-2ef382b3-756e-4a2e-a825-7a8b47394fd5.png)
![Captura de pantalla (25)](https://user-images.githubusercontent.com/109765970/180325472-95958be1-44ac-42b0-bdd9-43f5abc6b8fb.png)
[crash-2022-07-21_17.22.48-fml.txt](https://github.com/Luke100000/minecraft-comes-alive/files/9163133/crash-2022-07-21_17.22.48-fml.txt)
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/9163135/latest.log)

**Comment by CDAGaming** [comment]
The Forge version in use here appears to be very out of date, and is likely the cause of this issue. Please use Forge 40.1.0 (Latest Recommended Build of Forge 1.18.2), and retry.

**Comment by CDAGaming** [comment]
Closed from non-response, please re-open with a valid log and up to date mods if this is still an issue.
