### ISSUE TITLE
Not starting in forge 41.0.63 for minecraft 1.19

### ISSUE THREAD

**Issue by Oxicide** [Luke100000/minecraft-comes-alive#303]
Minecraft (1.19) tries to launch in this version of forge (41.0.63) and can't start, its try to open minecraft but then goes black and close without a crash report. Any advice what to do? This happens in other mods but the solution was downgrading the version of it and sometimes it works.

**Comment by Luke100000** [comment]
send the log please

**Comment by Oxicide** [comment]
the thing is thats no crash log and dont know where to find it :(

**Comment by Luke100000** [comment]
Not the crash log, the logs/latest.log in the minecrafts save directory

**Comment by Oxicide** [comment]
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/9169218/latest.log)
here u go! thx!

**Comment by Oxicide** [comment]
oh im reading it and maybe is the forge version?

**Comment by Luke100000** [comment]
Are you sure its mca related? Balm from blay09 is crashing, mca is not related to this.

**Comment by Oxicide** [comment]
before i inserted mca it was working perfect so idk, maybe that 2 make conflict?

**Comment by CDAGaming** [comment]
Once again Forge 41.0.94 or above must be used for MCA 1.19 7.3.9
