### ISSUE TITLE
Mod not recognized

### ISSUE THREAD

**Issue by ExhileArc** [Luke100000/minecraft-comes-alive#307]
I have installed the 1.19 version and have everything that is needed installed, the game shows up and loads fine but the iteams and actual mod doesnt. its just normal minecraft for me

**Comment by Luke100000** [comment]
looks like you did not install the right version. Verify that you use Fabric/Forge accordingly and send me the log please

**Comment by ExhileArc** [comment]
> looks like you did not install the right version. Verify that you use Fabric/Forge accordingly and send me the log please

Fabric is working fine and i am able to load and play other mods using it
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/9176143/latest.log)

**Comment by Luke100000** [comment]
Can you copy and paste the whole file name of mca here please?

**Comment by CDAGaming** [comment]
Closed via #114, Please re-open with a valid log file.
