### ISSUE TITLE
1.19 MCA-7.3.11, hearing my own character make villager sounds.

### ISSUE THREAD

**Issue by Wilevar** [Luke100000/minecraft-comes-alive#308]
With default MCA settings, for some reason my own character seems to be laughing and making various male villager sounds from the mod.
I'm using the "Player" option, so my character has MCA traits but is using a custom skin, is set to male and such. But I don't think my character should be making sounds at all. Not sure why it's happening, shouldn't be a mod conflict as I don't _think_ I have anything modifying villagers in any way aside from MCA. 

For now I'm just going to disable their voices in the config and hope that stops my character as well. I'm disabling it on the server first to see if it's a client side thing.

**Comment by Luke100000** [comment]
Please try MCA without any other mods to verify that its not a mod conflict.

**Comment by Wilevar** [comment]
Running a new server with just MCA and it's requirements does seem to fix the issue. I'm going to start adding back in mods to see if I can find the culprit.

**Comment by Wilevar** [comment]
Huh... Well, I re-added every mod a few at a time to both the server and client, testing as I went, and never go the player voices to happen again.

Maybe I was being followed by an invisible villager. Possibly an adventurer I told to use the Inn as their home, then despawned. Maybe some part of them remained or they stopped rendering but were still present, since they still get stuck following each other. Dunno.

If the problem returns, I'll see what I can figure out.
