### ISSUE TITLE
1.19, MCA 7.3.11, Villager and Adventurer Issues.

### ISSUE THREAD

**Issue by Wilevar** [Luke100000/minecraft-comes-alive#309]
**Villager AI Issues:**

- Villagers seem to have no pathing preference for walking on/using paths.
- Villagers don't regularly go to their workplace during the day.
- Villagers wander to the edges of town, often getting killed.
- Villagers can't seem to navigate out of water flowing into a pool, and get stuck.
- Villagers don't seem to respond to the bell whatsoever, not returning to their homes when struck, despite the bell showing on the blueprint.

Overall I've had to fully fence-in all paths to limit the AI's options for going from place to place, and manually tell all villagers to stay at their workplace.

**Adventurer AI Issues:**

- Adventurers don't take refuge at the Inn at night.
- Adventurers get "stuck" following a villager, to the point of following them to their bed at night, or stuck talking to each other for days on end.
- Adventurers _manually told_ to use the Inn as their home will then sleep in the Inn, but also get added to the population, can end up married with a villager, then despawn some time later.

Removing the inn as a building via the Blueprint cleared up the adventurers who were counted as villagers, so not the end of the world, but something I now have to keep in mind.

**Comment by CDAGaming** [comment]
Point 1, 3 (probably), and 4 is vanilla behavior, defining set paths is not really something on the roadmap, but can be dealt with depending on what Luke wants to do for 7.4/7.5.
Point 2 and 5 I have verified personally as working in the current version of MCA

**Comment by CDAGaming** [comment]
Points 1 and 3 for adventurers, are from what I've seen, intended. 7.3.5 adjusted it to where they no longer automatically claim beds, including the inn. Whether that should be changed is up to @Luke100000 with point 2 simply being a side-effect of them not having much else to do

**Comment by CDAGaming** [comment]
Closing as technically addressed for now. Luke can feel free to re-open if this is in-fact something that needs feature adjustments for.

**Comment by Luke100000** [comment]
Yes, some of the issues are in progress, or outdated by the new system. The pathfinder overhaul might be interesting but I don't know if Minecraft has a weighted pathfinder and I don't feel like writing a custom one ^^
