### ISSUE TITLE
Crash when approaching village

### ISSUE THREAD

**Issue by RetroGamerAndre** [Luke100000/minecraft-comes-alive#31]
I have the most recent version of the forge MCA on 1.16.5, and any time i walk near a village i get a crash.
[crash-2021-11-21_19.21.16-server.txt](https://github.com/Luke100000/minecraft-comes-alive/files/7577624/crash-2021-11-21_19.21.16-server.txt)

**Comment by Luke100000** [comment]
did you set `interactionFatigueCooldown` in the config to zero?

**Comment by RetroGamerAndre** [comment]
i did, in the past it was just true false for that option, guess i shouldn't have tried to think like the older versions

**Comment by Luke100000** [comment]
Then just delete this line so it resets to default :)
