### ISSUE TITLE
Fabric 1.19 Teleportation Issue

### ISSUE THREAD

**Issue by eithli** [Luke100000/minecraft-comes-alive#311]
When villagers are set to follow the player and are teleported to that player when they are far enough, setting them to move freely causes them to disappear.

**Comment by Luke100000** [comment]
Do they disappear or do they return to their next POI, e.g. work station?
If you are familiar with an NBT editor, can you search for affected villagers?

**Comment by CDAGaming** [comment]
Closing as technically intended, as the WanderOrTeleportTask works both ways. Bring them far enough, and they will TP to their next POI if they get another WalkTarget.
