### ISSUE TITLE
Losing Progress

### ISSUE THREAD

**Issue by NingNaga** [Luke100000/minecraft-comes-alive#312]
Ever since i had this mod in the server with Sophisticated Backpacks (the only mod that changes things in the Playerdata) this mod has been resetting every progress i had everytime i shutdown my server and logged in, brought me back to spawn with my playerdata deleted and with nothing  and giving me Alex's Mobs book (given to every player when they are **NEW** to the server) overall the mod is good and improved but the new UI popup thing has broken it much maybe it is detecting were new players telling us to do the whole Char. customization over and over again 

p.s 1.18.2

**Comment by Luke100000** [comment]
Just to verify, Sophisticated Backpacks causes this issue?

In the worlds data directory, are there files called `mca_player_uuid.dat`, one for each player?

If you use `/mca editor` while being OP, does the UUID stays the same for each server restart?

**Comment by Luke100000** [comment]
Can't verify, need more info
