### ISSUE TITLE
Error on Loading

### ISSUE THREAD

**Issue by Blaster9898** [Luke100000/minecraft-comes-alive#313]
When trying to set up Minecraft Comes Alive along with Arcitectuary. I keep getting the game to load, but now I have zeroes where the text is. What do I do from there?

![IMG_0513](https://user-images.githubusercontent.com/47837140/180889718-b9bc5835-b139-4dff-9dda-5101adef6aee.jpg)

**Comment by CDAGaming** [comment]
Please attach a log file to troubleshoot this further.

**Comment by Luke100000** [comment]
This looks like resource loading crashed, without log it's impossible to tackle
