### ISSUE TITLE
Trouble loading  

### ISSUE THREAD

**Issue by Ti-girl2336** [Luke100000/minecraft-comes-alive#316]
![2022-07-28](https://user-images.githubusercontent.com/110209363/181664007-2cb90a48-6bea-4ac5-b955-882111ccbe4e.png)
I have tried multipole times but whenever I try to open forager with the mod on 1.19 this shows up. I have already deleted it an reinstalled. Does anyone have any advise? #315 #

**Comment by Malifyed** [comment]
I also have the same exact problem

**Comment by Malifyed** [comment]
do you have the architectury api dependency?

**Comment by Luke100000** [comment]
[HOW TO WRITE ISSUES](https://github.com/Luke100000/minecraft-comes-alive/issues/114) (especially the log is always important)
