### ISSUE TITLE
End portal too far away!

### ISSUE THREAD

**Issue by Aikirob** [Luke100000/minecraft-comes-alive#318]
played with this on and at the start it teleported me to a village, I was literally 1100 chunks away from the nearest end portal, this made the game unplayable, couldnt reach the end portal.

**Comment by Luke100000** [comment]
The scan for villages is limited to 128 chunks. Therefore, even in worst case scenario, the spawn village would be within the first two rings of strongholds. The furthest stronghold cant be farther than a few thousand blocks. Are you sure this issue is mca related? What is your position?

**Comment by Aikirob** [comment]
Was fixed when I disabled the destiny function in config and started a new game, so yes something went wrong with the teleport function. I am using about 170 mods though, so it might have been a compatibility issue with another mod which caused the malfunction. But you should make it check for end portal location and have it spawn a stronghold near the village if it's too far away, I wasted hours trying to find a stronghold that was unreachable. Used an online seed tool to see where it was and the nearest was 1400 chunks away from my location at the village. That's roughly 3-4 hours of real world time worth of walking. That's pretty game breaking.

**Comment by Luke100000** [comment]
I can't interfere with the stronghold spawning, and again, technically you cant be further away than about 4000 blocks.
Also, don't use seed tools on modded environments, they probably don't work properly. Use the inbuild `/locate stronghold`

Oh and don't forget about the nether travelling, 1:8 ratio :)
