### ISSUE TITLE
What is a Sirben?

### ISSUE THREAD

**Issue by kingdom84521** [Luke100000/minecraft-comes-alive#32]
Sorry for disturbing the development, I'm a translator of this mod.

This is actually NOT an issue, I'm just struggling about the answer.

As the title say, I found that there is a trait call "Sirben" now inside the en_us.lang file, but I have search all over the internet and can't even find a definition of the word Sirben, so I came here, wondering if I can get a answer from the contributors.

A link to a Wikipedia Page will be the best answer, or you can just type some explanation of the trait, that will be OK, too.

**Comment by Luke100000** [comment]
Sirben is the name of one of our Discord members :) Keep it untranslated. It is an easteregg, but I wasn't aware of the massive confusion it would cause hehe

**Comment by kingdom84521** [comment]
I see. Well, I will still translate the rest of the words in the sentence, and maybe add a bit of sarcastic intonation in it.

Hopefully the translation can match the meaning you want.
