### ISSUE TITLE
Doesn’t work

### ISSUE THREAD

**Issue by Hen8** [Luke100000/minecraft-comes-alive#320]
Even when I install architectury, my game crashes immediately. I’m using forge 1.0.105 I think on 1.19 and it doesn’t work. I’m really sad because I love this mod.

**Comment by CDAGaming** [comment]
Please attach your latest log from .minecraft/logs and ill take a peek.

**Comment by Hen8** [comment]
> Please attach your latest log from .minecraft/logs and ill take a peek.

I’ll do it when I get home

**Comment by Hen8** [comment]
> 
Hi! I'm home now. I dont know where to check that. when the game crashes, it reads: An unexpected issue has occurred and the game has crashed. We're sorry for the inconvenience. This crash may have been caused by an invalid java runtime configuration. Check any custom configuration settings. Exit code:1.

**Comment by Luke100000** [comment]
By default it's in `%appdata%/.minecraft/logs/latest.log`

**Comment by CDAGaming** [comment]
Closed via #114, please re-open with a proper log
