### ISSUE TITLE
Villager Names are Not Names

### ISSUE THREAD

**Issue by EquinoxEUW** [Luke100000/minecraft-comes-alive#322]
Short Issue, I'm not sure how to fix this but all the villagers in my villages spawn with names like this

entity.mca.female_villager_cleric

Any way to fix this?

**Comment by EquinoxEUW** [comment]
This is for 1.18.2 Forge
Latest Architectury version for 1.18.2
Using a Modified version of Better MC 1.18.2 Forge


SS Provided for Mods that we are Using

![image](https://user-images.githubusercontent.com/102207880/182010402-76ba502e-c6c6-4c3a-9369-fbea9f972dff.png)
![image](https://user-images.githubusercontent.com/102207880/182010408-ef8bc402-2829-434a-9b63-2ef467132a16.png)
![image](https://user-images.githubusercontent.com/102207880/182010414-66adcb88-6a6a-4058-8c4d-9e0830fa5b13.png)
![image](https://user-images.githubusercontent.com/102207880/182010433-498335b7-42e1-44aa-aa0a-3727f0fcc779.png)
![image](https://user-images.githubusercontent.com/102207880/182010445-3ef5cffe-4d5f-4aa0-bab8-76e4e8fad176.png)
![image](https://user-images.githubusercontent.com/102207880/182010457-5b1a5e5b-f7dc-4513-a5ac-68c60fc8de6c.png)

**Comment by Luke100000** [comment]
Can you please drop the entire modpack here: https://mega.nz/megadrop/iiXE0lz8qqU
That way I can quickly reconstruct the error

**Comment by Luke100000** [comment]
Reopen if new info is available
