### ISSUE TITLE
[1.18.2 - MCA 7.3.15] Villager won't recognize workstation from Mana and Artifice.

### ISSUE THREAD

**Issue by Corbent** [Luke100000/minecraft-comes-alive#326]
I'm using:
-MC 1.18.2
-minecraft-comes-alive-7.3.15+1.18.2-forge.jar
-Mana and Artifice 1.7.2.8

Don't know if MCA Reborn already supports mod added professions but I can't get a jobless villager to take the profession added by Mana and Artifice (which is important since it pretty much gets the mod started). If I bring a jobless villager into a home and I  put down a vanilla workstation, like a stone cutter, they take the job without issue, but the Runeforge from M&A is completely ignored in every attempt.

**Comment by Luke100000** [comment]
Can't confirm, works fine for me (Forge 1.18, mca 7.3.17). Are you sure it is not a mod conflict? Please try with only mca and mana. If it works, add more and more mods until you found the culprit. If it does not work with just those two mods, please reopen the issue.
