### ISSUE TITLE
Villagers are breaking things

### ISSUE THREAD

**Issue by inlanoche** [Luke100000/minecraft-comes-alive#327]
I have a lot of instances of villagers breaking windows and doors.  I do have Zombie Awareness mod installed (which has zombies doing this), but wondering if that is conflicting and seeing all villagers as able to do this.  I will be checking with the other mod as well, but wanted to point that out, incase others are seeing the same.
(MC 1.16.5)

**Comment by Luke100000** [comment]
I'm fairly certain that this is not an issue on MCA side, maybe report that to Zombie Awareness (if its their feature) or check the config in case there are blacklists.

**Comment by inlanoche** [comment]
Is the entity designation for mca villagers different?  the mod blacklists minecraft:villager.

**Comment by inlanoche** [comment]
never mind, got it.  mca:male_villager and mca:female_villager.  Guessed that the format would be the same as with the spawn eggs.  Working properly now.
