### ISSUE TITLE
mca reborn not loading 1.19.1

### ISSUE THREAD

**Issue by M284090** [Luke100000/minecraft-comes-alive#328]
I'm getting an error message during the common_setup event phase, 
it says: 
java.lang.NullPointerException: Registry Object not present:
mca:sirben_baby_boy

what should i do to fix this?

**Comment by kenuto7** [comment]
i'm having the same issue, did you happen to get it resolved?

**Comment by Luke100000** [comment]
https://github.com/Luke100000/minecraft-comes-alive/issues/114

**Comment by KingofJank** [comment]
I'm also having the same issue.

**Comment by CDAGaming** [comment]
Reopen as per #114
