### ISSUE TITLE
Incompatibilities with VillagerTools mod

### ISSUE THREAD

**Issue by oMiCid00** [Luke100000/minecraft-comes-alive#329]
Minecraft Version: 1.18.2
Forge Version: 40.1.68
Mod Version: 7.3.15
Private server

I can't use items like Scroll of Hubris, Rough Emerald Shard (items from VillagerTools mod v1.0.2 ) etc... on villagers.
It opens the MCA Reborn Interface on right click and doesn't apply the item's effect.

Mod link : https://www.curseforge.com/minecraft/mc-mods/villager-tools

**Comment by CDAGaming** [comment]
Intentional incompatibility, several `targetType == EntityType.VILLAGER` checks found when these should instead be `instanceof VillagerEntity` of something like that.

**Comment by Luke100000** [comment]
I will add proper support to modded items, but before that VillagerTools needs to generify their items as CDA mentioned.

**Comment by CDAGaming** [comment]
Closing as no longer an issue on our end. We've done our end to add support for modded items, but we can't overwrite their choice to not use generified references. Once they fix it on their end, things should work fine.
