### ISSUE TITLE
Setting Villager Beds

### ISSUE THREAD

**Issue by YunanStratus** [Luke100000/minecraft-comes-alive#33]
I tried to set a 'home' place for villagers in a village I already created before getting the mod. The problems is that, even when I try to delete the beds and then add them back, it says that the villager can't claim it because it's not an 'empty' bed.? Each building meets the requirements for a village, such as the bed color, blast furnace, etc. yet they won't claim it. Also, I can't figure out how to change the name of the village. I have a name for it that I've stuck to and it bothers me that it changes the name and I can't figure out how to change it back.

**Comment by Luke100000** [comment]
Villagers in 7.0.4+ do not care about beds, only whether the building has space. Doublecheck in the blueprint if the building reports the correct amount of beds vs who currently lives there.
Village renaming does not work yet, I'm on it.

**Comment by YunanStratus** [comment]
Will do thanks! And about the village naming, don't rush, take as much time as you need bub!
