### ISSUE TITLE
Invisible Villagers

### ISSUE THREAD

**Issue by JuanTaco666** [Luke100000/minecraft-comes-alive#332]
Im playing on 1.18.2 Forge - 40.1.68 (if it matters) but the latest update made villagers invisible. I reverted the update to the one before it (released on the 3rd of august) and the villagers went back to normal. Not sure whats causing it but definetely needs to be looked into

**Comment by CDAGaming** [comment]
Please send your latest.log from .minecraft/logs/latest.log

**Comment by JuanTaco666** [comment]
Upon further testing, and reinstallation of the mod, the villagers have gone back to normal, and I havent been able to reproduce the issue so it seems that it may have been some kind of corrupted or messed up file in the version that I initially downloaded. Unless it comes back, sorry to have wasted your time but it is fixed on my end for now.

**Comment by CDAGaming** [comment]
All good, closing as resolved, let us know if this returns and we'll take a look!
