### ISSUE TITLE
In villager editor, Villagers have the default steve skin below hair, eyes and clothing

### ISSUE THREAD

**Issue by Eddstews** [Luke100000/minecraft-comes-alive#333]
I am playing on 1.19.1 Fabric, And I have noticed that within the villager editor for some strange reason villagers will not render properly and will display the default steve skin with the villager's hair, eyes, and clothing still there. I have not tested if this bug is present on other versions and everything else within the mod seems to be working as intended, Did I do something wrong or is this an issue with the mod itself?

I only have some performance mods and the mod file's name is as is. This glitch can be viewed basically anytime you enter the menu that lets you edit villagers or the menu that shows up when a new world is made. Villagers outside the editor don't have this issue.

**Comment by Luke100000** [comment]
When you say villager editor, do you test this on actual villagers or the player? Does it happen for both?

**Comment by Eddstews** [comment]
![2022-08-13_00 25 54](https://user-images.githubusercontent.com/110943234/184469981-7dddc8b7-1484-4efe-ae53-85a274ddda53.png)
![2022-08-13_00 25 06](https://user-images.githubusercontent.com/110943234/184469985-c1de3e8b-4433-41e1-a725-3cc7c69b24d6.png)

In these two menus, however, outside of them the issue is not present.
![2022-08-13_00 26 06](https://user-images.githubusercontent.com/110943234/184470013-b3ded225-ee01-402e-bf44-d5d4b3ffe2df.png)

**Comment by Luke100000** [comment]
Can't verify, can you please check the log for any suppressed errors?

**Comment by Eddstews** [comment]
Didn't find anything other than this 
[23:48:46] [Render thread/ERROR]: No data fixer registered for mca:tombstone
[23:48:46] [Render thread/ERROR]: No data fixer registered for mca:male_villager
[23:48:46] [Render thread/ERROR]: No data fixer registered for mca:female_villager
[23:48:46] [Render thread/ERROR]: No data fixer registered for mca:male_zombie_villager
[23:48:46] [Render thread/ERROR]: No data fixer registered for mca:female_zombie_villager
[23:48:46] [Render thread/ERROR]: No data fixer registered for mca:grim_reaper
This might be it but i saw no other issue relating to mca

**Comment by Luke100000** [comment]
Thanks. No those are fine.

**Comment by Eddstews** [comment]
Are those errors related to this issue?

**Comment by Luke100000** [comment]
No

**Comment by Eliemi** [comment]
the problem is with iris, if you use iris with sodium and indium with quilt mod loader it renders normally

**Comment by Eliemi** [comment]
its something with 1.19 onwards in older version this doesn't happen

**Comment by Luke100000** [comment]
Fixed
