### ISSUE TITLE
missing villagers

### ISSUE THREAD

**Issue by AREX116** [Luke100000/minecraft-comes-alive#339]
Villagers disappear after a while. At first I thought they were just dying or getting stuck somewhere, but when I installed the minimap mod to look for them, I discovered that they are not anywhere in the city and their names are not on the headstones either, they just disappear and their names remain on the list of villagers and the villagers counter.

Can anyone help me find them or just delete them from the mod count?
Thank, you

**Comment by Luke100000** [comment]
You can use an nbt editor to search the entities data, they usually wandered of and are unloaded

**Comment by Luke100000** [comment]
Merged  with #266
