### ISSUE TITLE
Widow isn't a widow?

### ISSUE THREAD

**Issue by corbsies** [Luke100000/minecraft-comes-alive#34]
One of my villagers is married, but their spouse is dead. Their husband turned into a zombie and burned to death. I think that the husband dying as a zombie might be the cause of this bug. Also, the dead husband's name was on the villager list until I removed his home (which was still under his name even though he was dead.)  I submitted this bug 3 times in the discord, but no response :( . 

*neither were revived*

**Comment by Luke100000** [comment]
fixed in b8f003bd5bd9de8a0d6b556af996b3b87e85f9e6
