### ISSUE TITLE
1.18.2 7.3.19 crashes with forge 40.1.73+

### ISSUE THREAD

**Issue by Luke100000** [Luke100000/minecraft-comes-alive#348]
https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn#c907

**Comment by CDAGaming** [comment]
Er, for 1.18.2, thats just 40.1.73, as hugher then that is 1.19

**Comment by CDAGaming** [comment]
Closed via #114 
![image](https://user-images.githubusercontent.com/16328918/185764716-a0f9c09b-8c5b-4c88-9584-9148af2a4658.png)
Also works fine in a fresh instance
