### ISSUE TITLE
Armor model on players not replaced

### ISSUE THREAD

**Issue by Luke100000** [Luke100000/minecraft-comes-alive#350]
https://media.discordapp.net/attachments/879830926723534878/1010630989250302022/unknown.png?width=1214&height=683

**Comment by CDAGaming** [comment]
Yea, doing this isnt really an options unless we either do an Overwrite to the initial constructor, breaking mod compatibility
Or doing a custom entity type + a custom renderer, also breaking mod compatibility.

**Comment by Luke100000** [comment]
We need to do that anyways since the armor model reacts to the slim model, which we do not support.
I will try to snatch and replace the model given to the ArmorFeatureRenderer. Epic fight mod probably gets even more broken but that's something for later.
