### ISSUE TITLE
[1.16.5] Grim reaper spawn ritual is not working

### ISSUE THREAD

**Issue by RadonCoding** [Luke100000/minecraft-comes-alive#354]
![image](https://user-images.githubusercontent.com/86915746/186398670-01b11ee7-f6d9-4d76-9b4c-09baca1b6822.png)

**Comment by RadonCoding** [comment]
Using the latest version for 1.16.5 Forge

**Comment by CDAGaming** [comment]
Fixed! It'll be included for the 7.3.20 global release, since it's too close to its release date to do more re-deployments of 1.16.5/1.17.1 at the moment.

**Comment by RadonCoding** [comment]
Would it be possible to get a unofficial fixed release?

**Comment by CDAGaming** [comment]
https://mega.nz/file/TU5TgTKY#UMN21wB-5dlJM94FiCxGNJwMeMSFbzcKrMa5-Yeo37E

@RadonCoding Sure thing! Here you go 👍

**Comment by RadonCoding** [comment]
thank you i appreciate it
