### ISSUE TITLE
Sometimes world creation freezes at 100%, updating mca:r is the only change i've made

### ISSUE THREAD

**Issue by Jetpack-Cat** [Luke100000/minecraft-comes-alive#357]
with the new 1.16.5 forge update. If I make a world, then quit that world back to the title screen, then make a new world,  there's a chance it will freeze at 100% world creation. The only thing I've done with my modpack https://www.curseforge.com/minecraft/modpacks/jetpack-cat is updated mca. . The only option you have is to crash the game with task manager

forge 36.2.39 
minecraft-comes-alive-7.3.19+1.16.5-universal

**Comment by CDAGaming** [comment]
#114 - Please submit a log file

**Comment by Jetpack-Cat** [comment]
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/9422801/latest.log)

**Comment by CDAGaming** [comment]
See #358
