### ISSUE TITLE
Falling off the map/delayed timer

### ISSUE THREAD

**Issue by Jetpack-Cat** [Luke100000/minecraft-comes-alive#358]
Sometimes when starting a new world, with launch into destiny set to true, it will spawn you into the world but the world hasn't started loading so you begin to fall hundreds of blocks off the map. You don't fall into the void and die, but you keep falling until the game starts loading block, then you spawn in the world.

I've noticed my timers are significantly delayed. I have quests that have times set for 35 ticks that don't activate for up to 8 seconds after I spawn. If it spawns me off the map and I fall until it actually starts loading the world, then after it respawns me on the ground I have to wait 5-7 seconds for those timers to finish.

Other times it spawns me right into the world and none of that happens.

forge 36.2.39
minecraft-comes-alive-7.3.19+1.16.5-universal

**Comment by Jetpack-Cat** [comment]
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/9422810/latest.log)

**Comment by CDAGaming** [comment]
This and #357 contain numerous other issues in your logs, ranging from Concurrent exceptions, resource pack issues alongside other errors -- each of which caused from other mods.

For that reason I'm considering both of these invalid unless you can resolve those first.

**Comment by Luke100000** [comment]
The delay in timers might be connected to the (horrible single threaded and slow) way of retrieve structure positions. It's "Normal". Falling out of the world is known but I failed to reconstruct this issue myself.

**Comment by Jetpack-Cat** [comment]
Understandable. I noticed the falling out of world issue and delayed timers are only happening when I choose a biome to spawn in using destiny. If I choose to spawn "somewhere" then I don't have that issue. I'm assuming it's due to loading the world in the new location.

**Comment by CDAGaming** [comment]
This is correct, as choosing a structure in Destiny is similar to if you did `/locate structure <name>` and tp'd to the location it found. If its in entirely new chunks, it can take a bit to load.

IE That's just normal minecraft for ya xD
