### ISSUE TITLE
Launch into destiny, selecting snowy village spawns you in the taiga village

### ISSUE THREAD

**Issue by Jetpack-Cat** [Luke100000/minecraft-comes-alive#359]
Selecting snowy village spawns you into the taiga village
minecraft-comes-alive-7.3.19+1.16.5-universal
forge 36.2.39

Actually, also selecting the savannah village spawns me in the desert.
Selecting plains village spawned me in a desert village
selecting taiga spawns me in the plains
selected savannah again and it spawned me in the taiga

Would having a config option to skip the biome selection screen be an option? 
Setting  `"allowDestinyTeleportation": false,` also removes the beginning story screens, I edited the lang file text to fit my modpack story.

If the mod had compatibility with fancy menu, I could just delete all the biome buttons and leave the "somewhere" button, but for some reason when I edit the biome select screen it resets itself the next time I visit that screen.

**Comment by Jetpack-Cat** [comment]
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/9422803/latest.log)

**Comment by Jetpack-Cat** [comment]
Actually, also selecting the savannah village spawns me in the desert.
Selecting plains village spawned me in a desert village

**Comment by Jetpack-Cat** [comment]
![image](https://user-images.githubusercontent.com/100042170/186620901-f688633d-3aa4-4d3d-9159-c44b09738e79.png)
![image](https://user-images.githubusercontent.com/100042170/186620932-52b5e072-f311-4cfb-838a-c1dd791f5115.png)
![image](https://user-images.githubusercontent.com/100042170/186620989-f423ceae-74b1-40aa-aff5-f102a1ed6eec.png)

**Comment by Luke100000** [comment]
You can now define your own locations in the Config.

**Comment by Jetpack-Cat** [comment]
Will defining my own locations still trigger the 3 screens of text?(hopefully). And does it give the ability to name the button if we define our own location?

**Comment by Luke100000** [comment]
Yes, it uses the translation files as usual. If the location does not exist, you won't teleport either. The first line is `destiny.story.reason`, the second line can be specified in the map in the config and is usually `destiny.story.travelling`, the third line only depends on the location `destiny.story.location`
