### ISSUE TITLE
Graveyard just dissapears

### ISSUE THREAD

**Issue by Hunterandruff** [Luke100000/minecraft-comes-alive#361]
7.3.16 1.18.2 fabric

Whenever I define a place as a graveyard it stays fine until I refresh the blueprints or I create a new building. It demotes me down to merchant whenever it happens and is a pain to keep registering while trying to rank up.

**Comment by CDAGaming** [comment]
Blueprint changes have been made to more recent updates of MCA
Please re-produce this in 7.3.20 and re-open, as well as supply a screenshot of the blueprint screen while hovering over the area on the blueprint the graveyard is at, so we can see what its detecting.

**Comment by Luke100000** [comment]
I can reopen that because I didn't quite fixed it, but it will be fixed in 7.4 :)
The recheck of the blueprint has troubles with "grouped" buildings. A plain bug on my side.

**Comment by Hunterandruff** [comment]
![GithubGlitchScreenshot](https://user-images.githubusercontent.com/112111400/186784325-57c2f5c8-b6ba-43d5-acd6-398d9d9d4afe.png)

I'm only providing this screenshot since CDAGaming said I should post a screenshot.

**Comment by Luke100000** [comment]
Should have been fixed
