### ISSUE TITLE
Could the spawn locations be centered? and could you add this text to the lang file for translation?

### ISSUE THREAD

**Issue by Jetpack-Cat** [Luke100000/minecraft-comes-alive#362]
![image](https://user-images.githubusercontent.com/100042170/186736749-cb39fa0a-61bf-4154-96f3-b1253f2687a1.png)

If I disable all but the "somewhere" spawn destination, the button will be all the way to the left which will look bad.
I have someone translating my pack into chinese, could the "where will your journey start?" be placed into a lang file? along with the "who are you?" text that appears on the first destiny screen?

And least of all, is there a way I can change the text on the button? I tried with fancy menu but the button text resets every time. 

Or a config option to auto choose the somewhere spawn location to skip this screen but continue the destiny intro text as if I had selected the somewhere button.

minecraft-comes-alive-7.3.20+1.16.5-universal.jar

**Comment by CDAGaming** [comment]
At the moment, the feature pipeline for 7.3 has been closed. So while this is a good idea, the earliest it can be done is 7.4, unless @Luke100000 wants to interject and make a .21 release.

**Comment by Jetpack-Cat** [comment]
Luke is a very nice name :D

**Comment by Luke100000** [comment]
We might end up with a .21 version anyways if something smaller breaks. Won't promise anything ^^
The translation for the center text is `gui.destiny.journey` and I think its already translated in Chinese. Same with `gui.destiny.somewhere`
Regarding centering, I think it's best to just skip the screen for a single button, and centering the rest.
