### ISSUE TITLE
some villages dont "spawn" with houses automatically

### ISSUE THREAD

**Issue by Hunterandruff** [Luke100000/minecraft-comes-alive#364]
The issue could be with the village JUST loading in but I just wanted to confirm with the devs.  The village doesnt spawn with any houses inside of it (and I know it was registered as a village cause I used /locate) and was really confusing when I tried to add other buildings.
![image](https://user-images.githubusercontent.com/112111400/186784513-6849e5e5-ebb1-45b7-9c67-29c3836d0c39.png)

**Comment by Luke100000** [comment]
Not a bug. The blueprint needs some time to sync. If you come by a few minutes later the first buildings should be scanned. In 7.4.0 this wont be a thing anymore as buildings and villagers are no longer a required dependency, the blueprint will be a player-only thing basically.
