### ISSUE TITLE
Crash with Terraforged

### ISSUE THREAD

**Issue by Airisii** [Luke100000/minecraft-comes-alive#365]
I crash when selecting the village option in the pop-up start menu of mca with terraforged installed. I'm not sure which mod is of fault so I'll paste the crash here.

Crash Log: https://pastebin.com/mT2ymtPW

**Comment by CDAGaming** [comment]
Mod Compatibility Conflict it seems, you just wont be able to select a structure with terraforged it seems and since TerraForged likely isnt maintained for 1.16.5, this isnt really resolvable i dont think

**Comment by CDAGaming** [comment]
nvm, Fixed :)

**Comment by CDAGaming** [comment]
I'll re-deploy 1.16.5 for this as soon as possible

**Comment by Airisii** [comment]
Thanks!
