### ISSUE TITLE
Can't get clothing resource pack to load in forge 1.19

### ISSUE THREAD

**Issue by MissSweetViolet** [Luke100000/minecraft-comes-alive#366]
I've been trying to make a clothing resource pack for a world I made, and can not figure out how to get the clothing to load in. As far as I can tell everything is correct, I've checked things over a dozen times, ran my json through a json checker, checked to make sure all the folders are right, the data pack and resource packs show on my list is world and I've checked the layering order of both the data and resource packs, but none of my clothing appears. I've never made a data pack before, but have checked through many tutorials, and even had someone check for me, as far as I know, everything is correct, so I'm super confused.

**Comment by Luke100000** [comment]
Send the two packs here and I will take a look. I will also make a template soon because tbh, packs are confusing.

**Comment by MissSweetViolet** [comment]
Thank you, I was a little unsure how I should send them, I put them in a main folder and then made a folder for both the data and resource pack and uploaded to dropbox. Hopefully that works, if not, let me know and I'll try to do it another way. https://www.dropbox.com/sh/8to5zvzmju5ufi6/AAD5HzqBr4lA28Er5sf3mhKDa?dl=0

**Comment by Luke100000** [comment]
You got bamboozled by windows weird habit of hiding the file extension, you added it twice :)
You also added your namespace twice.
You also forgot to add the path to the actual skins in the json. You still used the mca textures. The paths also had "skins" twice in it.
The jsons were in subdirectories, don't do this.

**Comment by MissSweetViolet** [comment]
Ah, thank you, I had no idea that any of that was off. I'll try to fix that! :)

**Comment by Luke100000** [comment]
Wait a minute, I fixed it on the way and will upload it soon :)

**Comment by Luke100000** [comment]
[Archive.zip](https://github.com/Luke100000/minecraft-comes-alive/files/9440148/Archive.zip)
Here you go! I merged it, it now is a datapack and a resource pack at the same time (sadly you still need to add it to datapacks and resourcepacks twice)
