### ISSUE TITLE
It won't let me set up a home for my villager, even when we're married. forge 1.19.1 42.0.9

### ISSUE THREAD

**Issue by dani12344444** [Luke100000/minecraft-comes-alive#367]
It won't let me set up a home for my villager, even when we're married.

**Comment by Luke100000** [comment]
What happens if you do so? Anything in the chat?

**Comment by dani12344444** [comment]
yes, she asks me if there is another place nearby and some other things

**Comment by Luke100000** [comment]
Then the building is not valid. If you use the blueprint it tells you more detailed reasons. Or you can wait for 7.4.0 since that removed the need of valid buildings.

**Comment by dani12344444** [comment]
Can I change the version without my villagers disappearing?

**Comment by CDAGaming** [comment]
In some cases, but most of the time, no.

**Comment by Luke100000** [comment]
Upgrading should always be fine

**Comment by CDAGaming** [comment]
Closing as technically resolved, 7.4.0 will have a better system, but for now the blueprint rules us all!
