### ISSUE TITLE
Probably compatibility issue [FABRIC]

### ISSUE THREAD

**Issue by Diabolo751** [Luke100000/minecraft-comes-alive#368]
minecraft-comes-alive-7.3.20+1.19.2-universal.jar

I'm playing a decently big modpack I created and every time I talk to a villager, instead of seeing the usual text, I get this:
![issue mca](https://user-images.githubusercontent.com/112251405/187026946-0cdc0e42-fa07-4abe-a4d8-6ed4b0714762.png)
 
I suspect it might be an issue with the haema mod or the better villages mod, but I'm unsure. I couldn't take a screenshot but this issue also applies to the text when you start, such as #story_reason or something. Thanks in advance and I really enjoy the mod :)

**Comment by Luke100000** [comment]
Not again! XD Do you have spectrum in your modpack?

**Comment by Luke100000** [comment]
#239

**Comment by Diabolo751** [comment]
Yeah I have it. I guess that's the problem then.

**Comment by CDAGaming** [comment]
Seems I closed #239, without reading into it. Spectrum itself still has an issue, but Incubus Core and other mods with similar issues fixed it, so its something Spectrum needs to fix once we forward the info in 239.

**Comment by CDAGaming** [comment]
This issue was resolved in newer versions of Spectrum, but 7.3.21 will be shipping with a compatibility adjustment for older versions of Spectrum, since its a minor change.
