### ISSUE TITLE
became outlaw by accident 

### ISSUE THREAD

**Issue by wayoffnorth** [Luke100000/minecraft-comes-alive#369]
became outlaw by accident, any way i can reset my rank to 0?

**Comment by Luke100000** [comment]
Talk to villagers, gift villagers stuff, excuse to villagers after you hit them

**Comment by wayoffnorth** [comment]
its like 1500, there is no way to reset it?

**Comment by Luke100000** [comment]
Do you believe that this is an error? To reach such an score you need to murder approx 10 villagers in front of the whole village.

Resetting such a score requires complete genocide, or you need to wait until they sent a few waves of bounty hunters, as that increases your rep again.
