### ISSUE TITLE
OverwriteOriginalVillagers in configs not working  

### ISSUE THREAD

**Issue by zalfrost** [Luke100000/minecraft-comes-alive#37]
I'm not sure if this is a bug or not because, in the old version(1.12.2), there is a similar option in the config file that can overwrite the original Minecraft villagers and change them to MCA villagers instead. That makes every time the original villagers try to spawn it will immediately replace them with MCA villagers.

But in this MCA Reborn v7.0.4, the option seems like it's not working at all. I already try to set the value from _True_ to _False_ and then change it to _True_ again. When I change it to _False_ and restart Minecraft, everything looks normal (original villagers co-exist with MCA villagers). The same things happen after I change the value to _True_ and then restart Minecraft when it was supposed to overwrite the original villagers but it didn't.

I really hope it's just a small bug...

**Comment by Luke100000** [comment]
If you forcefully spawn a vanilla villager (e.g. command/spawn egg), why should we forbid this? The option only affects villagers spawned naturally

**Comment by zalfrost** [comment]
Does it also affect the villagers that already spawn in my existing world before installing this mod? I'm kinda afraid to try to open my main existing world since this mod is still in early beta. 

p/s: I test this mod in my world created for testing purposes and not my main world.

**Comment by Luke100000** [comment]
No, it should not touch villagers already present. But please backup anyways :)

**Comment by zalfrost** [comment]
I'll make sure to do a backup first. Thank you and I'm sorry for taking your time for this little matters.
Have a nice day✨👍🏻
