### ISSUE TITLE
Job Title Font Color different glitch with the rest on WTHIT 

### ISSUE THREAD

**Issue by ardissaps** [Luke100000/minecraft-comes-alive#370]
The Color changed to dark gray but only after the "(" :
![image](https://user-images.githubusercontent.com/82106625/187062536-3b63938a-6f68-4323-a239-1bc64319bb1c.png)

**Comment by Luke100000** [comment]
Which version? I checked both WTHIT and Mca, neither should add formatting

**Comment by ardissaps** [comment]
> Which version? I checked both WTHIT and Mca, neither should add formatting

It is not happening on all job, only some, I used latest mca on fabric 1.18.2, quilt 1.19.2 and forge 1.19.2.

**Comment by CDAGaming** [comment]
@ardissaps Which jobs are the ones showing this formatting. If you say "only some", we need to know that list

**Comment by ardissaps** [comment]
> @ardissaps Which jobs are the ones showing this formatting. If you say "only some", we need to know that list

From what I found, it only happen for vanilla proffesion such as armorer, farmer cartographer etc. The mca jobs and modded jobs all have correct color.

MCA (no issue) :
![image](https://user-images.githubusercontent.com/82106625/187101463-d962fe6e-7f6a-4b3c-b410-c7e2c3ea9b22.png)
![image](https://user-images.githubusercontent.com/82106625/187101477-1ac7d1ee-ff98-4950-91fb-8220e6654ad1.png)

More Villagers (no issue) :
![image](https://user-images.githubusercontent.com/82106625/187101604-333d14eb-ac76-4e85-9a0b-0d984bf06ec4.png)
![image](https://user-images.githubusercontent.com/82106625/187101538-6a0ea82b-9afd-4814-8634-4994d336cea2.png)

Vanilla (issue) : 
![image](https://user-images.githubusercontent.com/82106625/187101406-d64661d6-d310-499a-9862-ad6a6e69c2ee.png)
![image](https://user-images.githubusercontent.com/82106625/187101444-a8c37ee4-37cb-4500-98f5-070440e9ae4c.png)
![image](https://user-images.githubusercontent.com/82106625/187101575-6a57fa82-5278-4929-a6fa-8935341bcb10.png)

**Comment by CDAGaming** [comment]
[zipped_artifacts.zip](https://github.com/Luke100000/minecraft-comes-alive/files/9440796/zipped_artifacts.zip)
@ardissaps I've attached a build within this zip file, please try this build in Fabric 1.18.2 and tell me if the same issue is present
Note: Do not use this build with older worlds, as it is a test to see if an older commit also shows this issue.

**Comment by ardissaps** [comment]
> [zipped_artifacts.zip](https://github.com/Luke100000/minecraft-comes-alive/files/9440796/zipped_artifacts.zip) @ardissaps I've attached a build within this zip file, please try this build in Fabric 1.18.2 and tell me if the same issue is present Note: Do not use this build with older worlds, as it is a test to see if an older commit also shows this issue.

found it, it was resourcepack from [default dark mode](https://www.curseforge.com/minecraft/texture-packs/default-dark-mode) !
