### ISSUE TITLE
No interactions & no MCA villagers

### ISSUE THREAD

**Issue by SoftLilacSky** [Luke100000/minecraft-comes-alive#371]
I tried installing MCAR on my 1.18.2 server but it's not working properly. I managed to create my character, choose destiny, and I got transported to some random plains village, but all the villagers there are basic Minecraft villagers, and I can't interact with them except to trade.
I'm running Forge 40.1.73, Architectury 4.9.83 and [Forge 1.18.2] MCAR 7.3.17. I also tried to run [Universal 1.18.2] MCA Reborn - 7.3.20 but the problem remained.

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/9439881/latest.log)

**Comment by Luke100000** [comment]
Is this a new world or did you added the mod afterwards?

**Comment by SoftLilacSky** [comment]
> Is this a new world or did you added the mod afterwards?

I added the mod afterwards to an existing world.

**Comment by Luke100000** [comment]
Existing villagers are not replaced. Either find a newly generated village or convert zombie villagers.
