### ISSUE TITLE
Mca:r puts you into the game after the first destiny message if connected over LAN

### ISSUE THREAD

**Issue by Jetpack-Cat** [Luke100000/minecraft-comes-alive#373]
I feel like mca:r shouldn't put your character into the game until after you've finished reading the destiny screens and click the button on the last screen. Currently it puts you into the game after the first story screen, so you still have 2 more screens to read, but your character is already in game. If the overworld is hostile during the day, you could be attacked by a hostile mob. 

I personally drop the player from y=255, because they're dropped before they're done reading the last 2 destiny screens, they hit the ground and aren't able to avoid death by double jumping or dashing. Even if I give them fall resistance on spawning, they're going to miss the story element of falling from the sky.

This happens when playing on LAN to the non-server players, I'm assuming this will happen on a dedicated server as well. Essentials mod just came out for 1.16.5 so I assume a lot more people will start playing over LAN(since that's how Essentials mod works)

minecraft-comes-alive-7.3.20+1.16.5-universal.jar
Forge

**Comment by Luke100000** [comment]
The reason behind this is to give the game time to load, while the player is still reading. But I realize that it makes more sense to yeet the player there as soon as possible while in spectator, but change gamemode at the end. This will fix loading  time aswell as the falling-through-world issue from another issue. Thanks for the input.

**Comment by CDAGaming** [comment]
Resolved for 7.3.21
