### ISSUE TITLE
Add option to change eye color of player

### ISSUE THREAD

**Issue by Ryorama** [Luke100000/minecraft-comes-alive#375]
I’ve noticed that in the player editor when either starting a new world or running the command that there is no option to choose what color the players eyes are even though there is for the skin and hair. It’s not a large detail, but it's a bit annoying not being able to change it so it would be nice to have an option for it.

**Comment by Luke100000** [comment]
Eyes and faces are merged, therefore not really colorable. Nearly all common colors are covered tho, the need for a more fine tuned color slider is small.

For consistency I will put eyes into resource packs, allowing player to add custom ones.
