### ISSUE TITLE
[1.19.2 RC.2] Can't find id for 'net.minecraft.sounds.soundEvent' in map Registry

### ISSUE THREAD

**Issue by NovaAndrom3da** [Luke100000/minecraft-comes-alive#379]
I am using Mohist server, MC 1.19.2 (Forge 43.1.3 client). Occasionally, I get kicked off of the server due to an error, and I can't get back on. [Here](https://gist.github.com/Froggo8311/b6ad9b5c45829ffccd78089e95a29bbc) is the gist with the error. I also see [other people](https://curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn?page=2#c928) having the same issue.

Just for clarification, the filename is `minecraft-comes-alive-7.3.21-rc.2+1.19.2-universal.jar`, and I'm not sure how to reproduce it or what causes the issue in the first place.

**Comment by Luke100000** [comment]
Still can't reproduce but a lot of things changed, maybe its fixed now.
