### ISSUE TITLE
Lag when used with Essentials

### ISSUE THREAD

**Issue by ghost** [Luke100000/minecraft-comes-alive#382]
I'm hosting a multiplayer world for friends using Essential with a handful of mods, including MCA. Whenever I'm near and I face the direction of at least multiple MCA villagers, I experience a drop in frames that increases as there are more villagers. None of my friends experience this issue and I think it may be connected to me being the host of the world. I plan on conducting various tests to further understand this problem and I'll provide updates here when I have the information ready.

**Comment by ghost** [comment]
Update: Even in singleplayer, there is the same lag but when I take Essentials out of the mod list, there is no longer an issue. It seems there's something going on between MCA and Essentials but also exclusive to me because my friends use both mods and don't experience the same problem.

**Comment by ghost** [comment]
RESOLVED: I reinstalled Essentials and now the lag problem is completely gone. The version of Essentials was the same but I might've had a faulty copy of it.

**Comment by ghost** [comment]
UPDATE: The lag returned after playing more on the world with multiple players. It seems like reinstalling Essentials is only a temporary solution to remove the lag but it comes back after a while for an unknown reason.

**Comment by Luke100000** [comment]
Please send me a profiler report, either using Spark or https://docs.minecraftforge.net/en/1.14.x/gettingstarted/debugprofiler/

**Comment by ghost** [comment]
I downloaded Spark and also just updated MCA on my modpack. Updating MCA seems to have the same effect as reinstalling Essential, the lag disappears (I assume it is still temporary). I used the Spark profiler on 2 separate worlds, a test world with 60-80 MCA villagers I manually spawned in at a village, and the main world at a place where the most MCA villagers are at. Although I acquired these 2 profiles while experiencing minimal lag, I thought it would still be worth a look to identify if anything is unusual. Once the lag returns, I'll update you with 2 more debug profiles.
[TestWorldNoIssue.zip](https://github.com/Luke100000/minecraft-comes-alive/files/9532474/TestWorldNoIssue.zip)
[MainWorldNoIssue.zip](https://github.com/Luke100000/minecraft-comes-alive/files/9532475/MainWorldNoIssue.zip)

**Comment by ghost** [comment]
The issue has finally returned with my FPS dropping to 20-35.
[MainWorldwithIssue.zip](https://github.com/Luke100000/minecraft-comes-alive/files/9592730/MainWorldwithIssue.zip)

**Comment by ghost** [comment]
Before the issue returned, I had been to the place where many MCA villagers are several times and my FPS remained at a steady 60. I went there just earlier with no issue, then returned somewhere else, closed the world, reopened it, went back to the place with villagers and the lag came back suddenly.

**Comment by Luke100000** [comment]
Awesome, thanks! I think I located the issue and will try to fix it soon. Some villager got stuck and spammed the path finder. Interestingly the load should never cause that big of an FPS drop but its the only weird thing I see so lets hope its that issue.

**Comment by ghost** [comment]
Alright, thanks!
