### ISSUE TITLE
Hair bug?

### ISSUE THREAD

**Issue by CuriousCrew** [Luke100000/minecraft-comes-alive#386]
When I open the character changer there is a red thing like hair but it doesn't change even when I change the hair colour or style, it happens on my avatar and the villagers. I would be most grateful for help.

https://user-images.githubusercontent.com/113059418/188961622-24b53b7f-0e91-4721-b69c-1e9f829f866f.png
https://user-images.githubusercontent.com/113059418/188961670-35bab999-253b-47f4-9bad-94ef42a8b71b.png
https://user-images.githubusercontent.com/113059418/188961679-cf7d6cf8-0cd8-4c32-ba27-c08f4d1d7b4a.png
https://user-images.githubusercontent.com/113059418/188961689-d0d30edd-ba68-4ff1-8690-541106fdbbfa.png
https://user-images.githubusercontent.com/113059418/188961711-8e14d93a-8c94-4aff-aa99-74f113fd845f.png
https://user-images.githubusercontent.com/113059418/188961725-30e215f4-8fdd-4356-a50c-70cc459aa623.png
https://user-images.githubusercontent.com/113059418/188961730-dbe3c017-afc1-43f8-83da-3b04687ef014.png

**Comment by Luke100000** [comment]
Can you disable all resource packs please? A lot of packs modify villagers

**Comment by CDAGaming** [comment]
Yea, from a brief look, its classic z-fighting, which can be caused by a resource conflict.

**Comment by CuriousCrew** [comment]
Oh I took off the resource pack and it worked, does this happen with all resource packs or just some of them.

**Comment by Luke100000** [comment]
Just those which modified the model. Can you please tell me which pack does this? Since its so common I would like to tackle that issue from our side too.

**Comment by CDAGaming** [comment]
Probably doesnt happen to all your packs, simply find the one that's conflicting and remove it to resolve this.

**Comment by CuriousCrew** [comment]
I was using jehkobas fantasy resource pack, and when I looked into it some more it seems that it changes the villagers in vanilla Minecraft

**Comment by CuriousCrew** [comment]
Thank you both for the help :)
