### ISSUE TITLE
Mod Compatibility: Croptopia

### ISSUE THREAD

**Issue by smmmadden** [Luke100000/minecraft-comes-alive#391]
I'd like to request mod compatibility/interacting to [Croptopia](https://www.curseforge.com/minecraft/mc-mods/croptopia/files) where it expands on farms quite extensively.  Having villagers being able to chop down additional trees and harvest more types of crops would be great. I'm currently using the latest Forge version of 1.19.2 MCA with Croptopia 2.1.0 and not seeing either get harvested.
Thanks for considering request! :-)
Kind Regards,
Steve

**Comment by Luke100000** [comment]
Crops should now work, not tested tho

**Comment by Luke100000** [comment]
Merged with #953
