### ISSUE TITLE
Resource Pack Not Loading (1.18.2)

### ISSUE THREAD

**Issue by JustJetto** [Luke100000/minecraft-comes-alive#394]
Hey.

Tried making a resource pack to add skins I used before the layer based skin update, but despite my best effort, could not get them to load in the game. I looked at a similar issue that was solved beforehand, edited my pack in accordance, and still, nada. The best I can get when loading this in the game is bald heads and blank bodies where the custom hair and clothes are supposed to be. (With skin and eyes nothing changes)

I know it's something stupid I've missed, but it's left me stumped so if you have any pointers on what's causing the issue, it would be a big help.

Thanks in advance.

_p.s. How do I add the hair overlays? I have the files in the right folder--but do I have to mention them in the .json too?_

[Jetto_Skinpack_MCA_1.18+.zip](https://github.com/Luke100000/minecraft-comes-alive/files/9551632/Jetto_Skinpack_MCA_1.18%2B.zip)

Using Forge
mod version: 7.3.21+1.18.2-universal

**Comment by CDAGaming** [comment]
CC @Luke100000 

Previously, Luke is planning to release a sample pack soon, so i'll mark this as enhancement to signify that.

**Comment by JustJetto** [comment]
Nice, looking forward to it!

**Comment by Luke100000** [comment]
Merged with #429
