### ISSUE TITLE
Tag Modification

### ISSUE THREAD

**Issue by Aaron732** [Luke100000/minecraft-comes-alive#395]
Hello, I would like to create a modpack with MCA and I noticed that we could not modify the tags of the items.

**Comment by Luke100000** [comment]
Sorry for the late reply, what do you mean by that? Are you referring to tags, e.g. `#wood` or tags in terms of nbt tags, e.g. description/lore, title of an item?

**Comment by Aaron732** [comment]
Yes I am referring to tags like #wood.

**Comment by Luke100000** [comment]
This is not mca related, tags are always possible. What specific issue do you have?

**Comment by Aaron732** [comment]
When I try to change the tags in the modpack configs but it doesn't work.

**Comment by Luke100000** [comment]
Define doesn't work, what tag, what did you wanted to achieve and how. What confuses me the most is that you speak about config. Tags are defined in datapacks, not configs.
