### ISSUE TITLE
Can't find family with Whistle -> tracker suggestion

### ISSUE THREAD

**Issue by sunshinelover047** [Luke100000/minecraft-comes-alive#397]
When opening up the whistle, it shows only 6 total family members, although I have a total of 9 children. I'm in the village I spawned in and where they all should be, so it's not as if they are out of range. Also, looking at the family tree shows they are all alive, and when trying to set my house as a different villager home, they say the beds are all full so obviously, they are still occupants of the house (if that makes sense.) Running Minecraft Forge 1.16.5 and having no other problems, couldn't find anything about this on Google so figured I'd try here.

**Comment by Luke100000** [comment]
If the whistle can't find it, they are not here. It's an old bug that villager sometimes get lost in caves or other dimensions, for 7.4 I'm working on a tracker so it's at least possible to find them again.
