### ISSUE TITLE
Logic issue with Add/Update Building

### ISSUE THREAD

**Issue by smmmadden** [Luke100000/minecraft-comes-alive#403]
Seems like an issue with the logic for adding a new building or updating an existing building.  In both cases, "Add Building" button is present.  But sometimes, clicking on Add Building inside an existing building we get a warning that the building overlaps another (which of course it does not).  If the player is in an existing building, then the button should say "Update Building" so there isn't a false message.
If you happen to get that warning, then you try to remove it, it too will fail saying you have to be standing on the inside (which we are).  

Only option is Advanced | Add Room which seems to reset it.  Just need to fix the buttons so the right option appears (Add/Update) to avoid confusion.  We've seen this on multiple building types, so not isolated to one.
Forge: 1.19.2 43.1.25
MCA: 7.3.21

Steps: 
1. Go into an existing building and add/change some blocks to the structure.
2. Click on Add Building - it should say updating existing building, but it does not always work.  I tried on my Storage building and was able to reproduce. My wife tried on a house that was made larger and had the same messages.

**Comment by Luke100000** [comment]
Switched to "rooms" by default which should minimize that behavior
