### ISSUE TITLE
Aldeões quando morrem, não aparece o nome deles na lápide 

### ISSUE THREAD

**Issue by Zuik10** [Luke100000/minecraft-comes-alive#404]
Estou tento muito problema com isso, exemplo: minha neta no jogo morreu e não apareceu o nome dela na lápide então acabei quebrando sem querer. Favor arrumar, bug visual.

**Comment by Luke100000** [comment]
We don't have Portuguese devs ^^ I need a way to reconstruct this bug, else I can't fix it.
