### ISSUE TITLE
I can't interact with NPCs

### ISSUE THREAD

**Issue by lostopkk** [Luke100000/minecraft-comes-alive#406]
in the last version, i spawned some npcs in my city, but when i press second button to interact nothing happens and if i press shift + second button the npc keeps talking no infinitely

**Comment by Luke100000** [comment]
Log please

**Comment by lostopkk** [comment]
https://mclo.gs/89WUBlP
there was a bug in opengl but it wasn't with your mod, it was another one, but it still has the bugs in npcs

**Comment by lostopkk** [comment]
there was some mod that was conflicting and now it's back to work, sorry for the issue
