### ISSUE TITLE
People are reporting starting in spectator mode when joining a world, or that their screen is black.

### ISSUE THREAD

**Issue by Jetpack-Cat** [Luke100000/minecraft-comes-alive#407]
I suspect this has something to do with the launch into destiny feature.

Some people are reporting a black screen when they create a new world, and I just had one guy who joined the official server, and was stuck in spectator mode. I hopped online and issued a command to put him into survival but I'm not sure how else this could have happened as i've never had these reports before I enabled the launch into destiny feature.

I haven't updated the modpack to minecraft-comes-alive-7.3.21+1.16.5-universal yet, it's still on minecraft-comes-alive-7.3.21-rc.2+1.16.5-universal.

Is this something that you're aware of and is fixed in the most recent version?
They don't crash so there's no crash logs.

This is happening in my modpack: https://www.curseforge.com/minecraft/modpacks/jetpack-cat
I haven't experienced this personally, but i'm starting to get more reports of it.

The guy who got stuck in spectator mode said he clicked through the destiny screens quickly, not sure if that helps.

**Comment by JackNewell** [comment]
Same problem on our server, any fix for this without OP?

**Comment by Luke100000** [comment]
Destiny "protects" the player with spectator. It should not be possible to skip destiny without leaving that mode again. Well, seems like it is possible nevertheless. I will double check the code and may use another approach altogether.

Black screen is weird, I can't explain that one.
