### ISSUE TITLE
Procreation

### ISSUE THREAD

**Issue by Krash707** [Luke100000/minecraft-comes-alive#41]
While me and a friend are both playing Minecraft, we decided to add MCA Reborn to make it more fun. But after having one kid, the second wasn’t even labeled as my child and we can’t have a third as “you already have a baby with this player”, even though neither of us have the child nor even have a growing kid anymore as both are adults.

also, when my friend grabbed a baby from creative (because we can’t use the procreate command due to the prior problem) and tried to name it, her game crashed

**Comment by Luke100000** [comment]
Are you sure you use 7.0.6? Both issues should have been fixed already
