### ISSUE TITLE
Optifine causing issues with MCA

### ISSUE THREAD

**Issue by SupaStinger** [Luke100000/minecraft-comes-alive#418]
I've been trying to use shaders with MCA: Reborn. However, I've never been able to get it to work for some reason. I use Optifine as my main source for shaders (since that is the only one I know how to use) for all of my modded and unmodded worlds. For some reason, when I use Optifine with MCA: Reborn, it just crashes my game when I try to open or create a world. I have tried it with shaders on and off but the result is still the same. I did wait a while to see if one of the latest versions of MCA possibly had it fixed, but sadly, it didn't. Here is the crash log I get every time I use Optifine with MCA. Thank you so much.

MCA File Name: minecraft-comes-alive-7.3.21+1.18.2-universal
Optifine File Name: OptiFine_1.18.2_HD_U_H7_MOD

![image_2022-09-30_153903789](https://user-images.githubusercontent.com/114774158/193344342-d15e2a01-9b34-494e-a8a9-b6ad25d4e412.png)

**Comment by Luke100000** [comment]
Full log please! Are you sure its mca related, does it crash without mca too?

**Comment by SupaStinger** [comment]
> Full log please! Are you sure its mca related, does it crash without mca too?

I did a bit more testing and it seems that the issue is from Optifine itself, which I find really weird. Optifine has never caused issues like this before. I will look further into the matter. So sorry if I wasted your time, and thank you very much.
