### ISSUE TITLE
Hunters killing all animals?

### ISSUE THREAD

**Issue by smmmadden** [Luke100000/minecraft-comes-alive#421]
I'm trying to have all the different workers, but finding that we can't have hunters or they kill all the animals that may be fenced in like cows, pigs, chickens, etc.  I also found a great horse with nearly 4 block jumper and 11 speed and as soon as I rode into the village a hunter ran over to me and killed the horse while I was riding it. :-(  Finding a great horse is hard to do and why hunters are killing them makes no sense - they should be off limits.  If there are animals walking around and not fenced in some where, then I would say that's free food to hunt (just not those that wouldn't normally be hunted).
Forge 1.19.2 - 43.1.30
MCA 7.3.21
One suggestion would be to have a building (or fenced in area) designated as farm, barn, stable or something like that would make for a safe place to have animals.

**Comment by Luke100000** [comment]
The hunter chore is weird altogether. Hunting in Minecraft is not a thing due to missing respawn and killing farm animals is, as you said, not useful if not controlled properly.

Maybe I will rework the chore as "breeder" or whatever, keeping an acceptable population and killing accordingly. Or something like that. Any feedback on that?

**Comment by smmmadden** [comment]
I think the hunter would still work for loose mobs not in a closed structure (but not horses, donkeys, mules, striders, llamas) that might be used for transport.  

The Butcher seems more appropriate to do the breeding and killing of farm animals for meat.  They may need a structure to know where and what to butcher.  Perhaps adding new structures/buildings that has "one or more gates" registered as a barn, stable or pen, then the breeder would only kill excess of 3 or more (so there are always 2 for breeding).  They can still breed them and keep the population under control (to avoid large mob farms).  May be difficult to manage if the barn, stable or pen structure has mixed mobs in them unless there is a way to determine that?  Could identify each structure to have pigs (pork), cows (beef), sheep (mutton), chickens and rabbits bar, stables or pens so that the butcher knows which animals to get.   

What do you think?
Regards,
Steve

**Comment by Luke100000** [comment]
Merged with #953
