### ISSUE TITLE
Option of blacklisting trade-able items by the adventurers

### ISSUE THREAD

**Issue by Flyvee** [Luke100000/minecraft-comes-alive#422]
I think a config should be added where you can either whitelist/change what items can be traded or blacklist what shouldn't be able to be traded(for me an enchanted golden apple should not be traded especially for just 20 emeralds).

**Comment by Luke100000** [comment]
My concern is that this should be done by trade mods, I don't think re implementing this as part of the config makes sense. I can adapt the prices tho.

**Comment by Luke100000** [comment]
I improved the prices, but other than that it should be configurable using an trading  table configuration mod.
