### ISSUE TITLE
Skin won't render in editor while using Iris Shaders 

### ISSUE THREAD

**Issue by mogneto** [Luke100000/minecraft-comes-alive#423]
Pretty much explained. When you are in the character editor while using Iris Shaders (doesnt matter if shaders are enabled or not), the player skin won't render and will stay as default minecraft steve (print below). It works properly after you finish editing, tho. But you'll have to use the '/mca editor' command multiple times till you're satisfied with the result. 
Sadly, if you play without cheats, you'll have to know well how the colors you picked look like.
![image](https://user-images.githubusercontent.com/71944195/193910652-f4cd024b-9bf8-457d-9b3f-8dfa90be62cf.png)

**Comment by Eliemi** [comment]
if you use iris, sodium and indium with quilt mod loader this doesnt happen it renders the character normally

**Comment by Eliemi** [comment]
its something with 1.19 onwards in older version this doesn't happen

**Comment by Luke100000** [comment]
related to #483 and #333 and fixed
