### ISSUE TITLE
Villagers Keep "Disagreeing" With Me When I Try To Talk To Them

### ISSUE THREAD

**Issue by samthelizard** [Luke100000/minecraft-comes-alive#424]
I'm not sure if it's just me, but whenever I try to talk to the villagers, they just "disagree" with me and say things like "Nope", "No", "No way", etc.

**Comment by Luke100000** [comment]
Hmm, any other mods which may interfere? Did you try with an empty hand? Do you reach the interaction menu or fail to open altogether? Can you please try without any other mods (on a new world) to make sure?

**Comment by samthelizard** [comment]
After testing for any mod incompatibilities, I have determined that the cause of this problem is from the mod "Get in the bucket". I am assuming that the mod is the reason why the npcs keep disagreeing with me, perhaps it thinks that we have a bucket in our hand (even though we don't) and are trying to pick them up with it. After disabling this mod, I no longer have the problem. Here is the link to said mod if you would like to try and see for yourself. I apologize for any inconvenience / worry I may have caused. 
https://www.curseforge.com/minecraft/mc-mods/get-in-the-bucket-mod/#:~:text=Mod%20for%20Minecraft%20that%20allows,throw%20it%20into%20EntityData%20tag.
