### ISSUE TITLE
Workers show as jobless in Villager UI

### ISSUE THREAD

**Issue by smmmadden** [Luke100000/minecraft-comes-alive#426]
Looking at the Villager, you can see if they are Working, Staying, Following, etc, but if you look at the UI of the Villager, it always shows as Jobless.
![image](https://user-images.githubusercontent.com/10309346/194312268-f17d48bc-b00f-4414-b54f-6064aba3e117.png)
![image](https://user-images.githubusercontent.com/10309346/194312344-dd8cd8e8-c1a4-49a4-8be6-228c33675053.png)

Also noticed that if you have someone follow you or stay, when you tell them to move freely and they were a worker, they no longer show as working until you tell them to work again.
Forge: 1.19.2 - 43.1.33
MCA: 7.3.21

**Comment by Luke100000** [comment]
A chore is not a profession. If you interrupt the chore they will not continue working since they don't really remember their work place. Chores are still weird.
