### ISSUE TITLE
villager profession/job bug

### ISSUE THREAD

**Issue by RConTRS** [Luke100000/minecraft-comes-alive#432]
mc version : 1.16.5 (latest forge and mca mod version)

villagers cannot switch or take jobs in some cases

for example, breaking mason's stonecutter won't make him jobless, he will stay as mason.
breaking a farmer's composter will make him jobless, but when placing the composter (or any profession block) won't do anything, he will stay jobless.
i also noticed that some villagers don't restock at all, somehow when the bugs above happens

lastly, i don't know if those issues happen in other versions anyway, thanks

**Comment by Luke100000** [comment]
Profession mechanics are not affected by mca, I need more information to track this down.
