### ISSUE TITLE
Issue with launching into destiny

### ISSUE THREAD

**Issue by FullMetalMaster** [Luke100000/minecraft-comes-alive#435]
I'm having an issue where and I'm not sure if it's with bettervillage-forge-1.19.2-2.0.0 or the mod pack im in but when we have this feature on the world will either lag out or you'll fall through the world and get stuck in spectator mode I've tested this a couple times and it seems to happen every time I'm not really sure what's going on hopeful its less buggy next update here my log 
![image](https://user-images.githubusercontent.com/52523300/196703486-e52b47eb-c25c-4ce8-ba5f-fcda5d6c572d.png)
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/9820858/latest.log)

**Comment by FullMetalMaster** [comment]
![image](https://user-images.githubusercontent.com/52523300/196703572-32951bfd-62ab-406b-a611-4f5b3e36e3fa.png)
like i just fall though the world

**Comment by Luke100000** [comment]
Merged with #407
