### ISSUE TITLE
1.19.2 Fabric Ticking Entity Crash on World Load

### ISSUE THREAD

**Issue by Gamerbolts** [Luke100000/minecraft-comes-alive#437]
Hello! I loaded up my minecraft world testing my modpack. And crashed. Here is the crash log: https://pastebin.com/UXir2NB9

Any help is appreciated. Thank you!

**Comment by Luke100000** [comment]
Log please, it may contain more information

**Comment by Gamerbolts** [comment]
Sorry here is the log
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/9840675/latest.log)

**Comment by Luke100000** [comment]
Merged with #447
