### ISSUE TITLE
Request: Config option for mca villagers being targeted by all hostile mobs

### ISSUE THREAD

**Issue by pantsguyapp** [Luke100000/minecraft-comes-alive#442]
Unlike vanilla villagers, these are humans like players, who gets targeted by all hostile mobs, can we have config option for that?

Vice versa, mca villager will run away from all hostile mobs.

**Comment by Luke100000** [comment]
Would a black/whitelist and a attackedByMonsters similar as we did for guards in #74 be enough?

**Comment by pantsguyapp** [comment]
I don't see why not.

**Comment by Luke100000** [comment]
Just took a look at Mojangs code, the way aggression is implemented seems out of scope for MCA. I didn't verified https://www.curseforge.com/minecraft/mc-mods/big-brain but it should work fine for mca
