### ISSUE TITLE
( Forge 1.19.2 ) Marriage options not appearing in villager menu

### ISSUE THREAD

**Issue by MrXenoMorphG** [Luke100000/minecraft-comes-alive#444]
I married a female villager with the engagement ring and have around 150 hearts but the procreate, divorce, inventory and work options don't apear in the menu or when talking. However the family tree tab shows I am married.

I only have a couple ambient sound and combat mods installed as well as serene seasons and complementary shaders.
I also have two versions of architectury installed.

**Comment by Luke100000** [comment]
The engagement ring engages you, not marry. Do you have ideas on how to make this more clear to the player?
