### ISSUE TITLE
Character creation skin doesn't appear

### ISSUE THREAD

**Issue by ghost** [Luke100000/minecraft-comes-alive#448]
Just like in the title, the character skin I create in the beginning of the game or by using the /mca editor command will not display. What I see is my current character skin, the one I had for 4 years or so haha. I'd appreciate any help no matter how little and do apologize in advance if there's already a post I did not see about this. I am, for the record, using oculus and rubidium. Thank you in advance!
![12](https://user-images.githubusercontent.com/117318205/199606927-635abada-5429-4bf0-8a57-2ba5312cbc92.png)
![13](https://user-images.githubusercontent.com/117318205/199606933-06dc3893-6147-48bd-9150-4f07d42a4e6e.png)

**Comment by Pauu7** [comment]
Hi! Look, it happened the same thing to my game. What i did was using only the mod (comes alive reborn) at first, and then i created the world to see if it worked, and yes, it showed up the character creation skin. Later i put other mods in the folder and that's it. But i dont have a clue if it will work for you, but i hope so!

**Comment by Pauu7** [comment]
What im sayin' it's that maybe it conflicts with other mods. Maybe you just have to upload the game only with the mca first, and only then put other mods!

**Comment by ghost** [comment]
Thank you so much for your answer!

**Comment by ErPedro** [comment]
I actually want this to happen, how do I use MY skin?

**Comment by Luke100000** [comment]
@ErPedro  `/mca editor`
