### ISSUE TITLE
Mining Chore

### ISSUE THREAD

**Issue by xuqinkun** [Luke100000/minecraft-comes-alive#449]
The book Managing Your Family Vol. XI mentioned children can mine and have a peculiar ability to search for and locate ores underground. But I can't find it on work menu.
![image](https://user-images.githubusercontent.com/19572081/199638691-8edc20d6-8308-4f44-9c8f-27e5b1de32f7.png)
![image](https://user-images.githubusercontent.com/19572081/199638951-a6bfb818-5ab1-4e35-af7c-d5cff38b4819.png)

**Comment by xuqinkun** [comment]
Minecraft 1.19.2 Java
Forge 43.1.43
TmTmc-MCAReborn 1.0.20

**Comment by benniloidl** [comment]
I have the same problem

**Comment by Luke100000** [comment]
Ups, sorry @xuqinkun I completely missed that issue. MCA Reborn never reimplemented mining, the wiki you are referencing is for the old MCA.

The book is a copy paste and should get fixed, thanks.

**Comment by benniloidl** [comment]
Isn't there a plan to implement that feature? Because I'd personally love it.

**Comment by Luke100000** [comment]
Yes, not very high on the todo but eventually :)

**Comment by Luke100000** [comment]
merged with #953
