### ISSUE TITLE
Minecraft launcher closes before startup.

### ISSUE THREAD

**Issue by prodatastealer** [Luke100000/minecraft-comes-alive#450]
I am using 1.18.2 with Forge. Before the game starts up it will close out and then the launcher cannot be opened. I could  just be being impatient though.

**Comment by Luke100000** [comment]
Latest.logs please! If you can not reopen the launcher, try killing everything launcher and java related in the task manager.

**Comment by prodatastealer** [comment]
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/9946640/latest.log)

**Comment by Luke100000** [comment]
Doublecheck that the correct version of architectory is installed

**Comment by prodatastealer** [comment]
THIS FIXED IT THANK YOU!!
