### ISSUE TITLE
Lanterns not being recognised in blueprint

### ISSUE THREAD

**Issue by GhostOpsX** [Luke100000/minecraft-comes-alive#453]
im trying to start my own village but the blueprint isnt registering lanterns at all so i cannot create the storage house. It also says i need 400 hearts to progress in rank, no matter what village i go to. 
edit -  this is in 1.16.5

**Comment by Luke100000** [comment]
The storage requires lectern, not laterns :)
And yea, if you start your own village, you wont be a king automatically. You still need to earn trust first.
