### ISSUE TITLE
[1.18.2] Minecraft Comes Alive (mca) encountered an error during the sided_setup event phase

### ISSUE THREAD

**Issue by jorlopgil** [Luke100000/minecraft-comes-alive#454]
Very good, my English is not very good and I am using a translator, I hope you understand me well. Me and a friend are having a problem starting Minecraft 1.18.2 with Forge 40.1.61 (also tried 40.1.73 (my friend uses this) and 40.1.84) and Java 17. We both have 8gb of RAM allocated to the game .

Many times when entering it gives a loading error and you have to restart until it works.

I put some log that have come out.

[https://paste.ee/p/wLMpc](url)

[https://paste.ee/p/nKVIw](url)

Greetings.

**Comment by Luke100000** [comment]
I doubled checked everything on my side, I see no issues. It is either a forge problem or a mod conflict.
