### ISSUE TITLE
[Suggestion/Compatibility] Add a tag for tax

### ISSUE THREAD

**Issue by VVVHY** [Luke100000/minecraft-comes-alive#456]
Since so many mods/modpacks attended to create some new currencies, adding a tag for tax may be beneficial to the compatibility with others.

**Comment by Luke100000** [comment]
I planned to implement this as a config because I need a value for each item. A emerald for example is more worth than a copper coin. Does this work for you?

**Comment by VVVHY** [comment]
Yes, thank you for your response.

**Comment by pantsguyapp** [comment]
Can you make it so this support multiple items, along with the chance of how rare the item will be offered by the villager?

**Comment by Luke100000** [comment]
Yes, that's why I said a config might be more suitable :)

**Comment by Luke100000** [comment]
Added
