### ISSUE TITLE
Suggestion: Survival method to have villagers quit their picked job if they haven't got any experience.

### ISSUE THREAD

**Issue by pantsguyapp** [Luke100000/minecraft-comes-alive#457]
I have and still hate how the vanilla villager mechanic work of changing the job of the villager. First you have to find the designated jobsite, break it, and replace it with your desired worksite, and then there is still a chance the villager spot another one that is closer to him, or the villager is literally too far to detect the jobsite is gone and don't change its job.

A method to simply have the villager to "reset job" if it hasn't got any experience(Kind of like the recycle button from Easy Villagers mod but this time it makes the villager become unemployed and also delete its chosen jobsite), you can repeat this until the villager has picked the designated jobsite. 

If it has been traded once, then the option disappear.

**Comment by Luke100000** [comment]
Notice that there is a "set work space" which does that. In 7.4.0 I am extending this feature further. E.g. adding confirmation for villagers with experience.
