### ISSUE TITLE
Suggestion: Nitwit as a trait

### ISSUE THREAD

**Issue by pantsguyapp** [Luke100000/minecraft-comes-alive#458]
Vanilla villagers have a designated "Nitwit Villager", can MCA do the same? Especially with all the fancy traits and personalities, nitwit can settle in along with other traits like homosexuality, color blind or serbian...

Nitwit villagers have their own schedule for waking up and idling, I know its only a thing in Bedrock, but perhaps MCA couldpull this off.(https://minecraft.fandom.com/wiki/Villager#Schedules)
Nitwit villagers will NOT pick up any jobsite whatsoever and they will NEVER initialing any trading.
Nitwit villagers will have their own set of clothes, like any other villager profession, just imagine how you would detect an irl NEET. ;-)

**Comment by Luke100000** [comment]
Nitwits are a thing in Java edition too, and therefore MCA. I have to defend them from Dom as he want to remove them for whatever reason.

**Comment by Luke100000** [comment]
Will close since it is a thing already.
