### ISSUE TITLE
Rose Gold impossible to find anywhere 

### ISSUE THREAD

**Issue by farmlifefpv** [Luke100000/minecraft-comes-alive#46]
After spending 120 hours on a world already, i have yet to find a single block of Rose gold Ore... Out of curiosity i went into spectator mode and tried to look for some, spent about an hour looking, nothing. I dont find any indications that it is spawning

Any help will be appreciated

**Comment by Luke100000** [comment]
Rose gold is not implemented yet due to the lack of use cases
