### ISSUE TITLE
a translation problem 

### ISSUE THREAD

**Issue by werewolf0717** [Luke100000/minecraft-comes-alive#461]

**Comment by werewolf0717** [comment]
![스크린샷(66)](https://user-images.githubusercontent.com/118168905/201622746-fff33c5c-155a-4e79-bc8e-c202ac172c5a.png)
I'm a Korean who is playing this mode really fun. but there's a little problem, It's a translation problem. When I gave flowers to the NPC, The answer is "really pretty." says. In Korean, "정말 예쁘다." says. but in the game NPC says "정발 예쁘다." says. I want the translation to be changed due to this problem. ㅂ->ㅁ. I'd appreciate it if you could work on it at your convenience.

**Comment by Luke100000** [comment]
Thanks for the report, please log in to https://crowdin.com/project/minecraft-comes-alive-2 and change the translation, maybe the original translator made a typo. You can use a google account for convenience. This is easier for me to manage :)
