### ISSUE TITLE
Server crash on player join

### ISSUE THREAD

**Issue by MehdiPG** [Luke100000/minecraft-comes-alive#465]
Hello. I have mca installed on my minecraft server but when a player joins the server, it crashes. Reading the crash report, I saw that the problem was from mca. Also this has started to happen to me when I installed the mca mod. I don't know if you can help me, I would really appreciate it. Here is the crash report: https://pastebin.com/raw/8kYa54aC

**Comment by Luke100000** [comment]
Hi, I just wanted to try again on finding that issue but the pastebin is gone and I didn't saved it.

**Comment by MehdiPG** [comment]
> Hi, I just wanted to try again on finding that issue but the pastebin is gone and I didn't saved it.

Don't worry. I solved the problem. Thank you btw.
