### ISSUE TITLE
MCA incompatible with Mohist

### ISSUE THREAD

**Issue by SoyJetixXD** [Luke100000/minecraft-comes-alive#466]
### Hello!
Me and my friends are working on a server with mods and plugins, to achieve this we had to use _**Mohist (Mods + Plugins)**_ and everything was normal until we added the _**MCA**_ to the modpack and from then on the server wouldn't start.
We tried removing all the plugins and some mods but the problem continued. 
The problem was related to the _**MCA**_, we used the normal configuration but nothing, we changed the configuration and nothing.
The only solution was to remove the _**MCA**_ from the server but we love your mod and we want to find a solution to enjoy it.
### Some data:
**Minecraft Version: 1.16.5
MCA Version: minecraft-comes-alive-7.3.21-1.16.5-universal
Mohist Version: mohist-1.16.5-1088-server
Forge Version: 36.2.39
Modpack: https://www.mediafire.com/file/m0d6ha1bp2jt8x5/Modpack.zip/file
Logs: [2022-11-20-1.log](https://github.com/Luke100000/minecraft-comes-alive/files/10052578/2022-11-20-1.log)
Plugins: SkinsRestorer
Online-mode: False (We are no premium)**
### Thanks for reading!

**Comment by Luke100000** [comment]
Thanks for the detailed error and modpack link. It has been previously reported here #378 but it seems more people are using Plugins than expected so I will see how to fix that.
