### ISSUE TITLE
Storage Keeps turning into Bookkeeper

### ISSUE THREAD

**Issue by Himbert1** [Luke100000/minecraft-comes-alive#468]
Storage meet's the requirenment to be considered one but after adding the building it turns into a Bookkeeper
- 8 Chests, 1 Lantern, 1 Crafting Table and 1 Lectern are in the Room

**Comment by Luke100000** [comment]
Does the blueprint recognize the chests? Are they vanilla or modded?

**Comment by Luke100000** [comment]
Can't verify issue

**Comment by UplinkPhobia** [comment]
For the record, this can be indeed caused by modded chests. Quark's chests for example are not detected.
