### ISSUE TITLE
what the actual nazi hell is this?

### ISSUE THREAD

**Issue by Niitek** [Luke100000/minecraft-comes-alive#470]
>   "advancement.mca.baby_smelted": "You are a horrible person!",
>   "advancement.mca.baby_smelted.description": "Abort a baby by unconventional means.",
> 
>   "advancement.mca.baby_sirben_smelted": "Truth, Justice, and the pursuit of destruction!",
>   "advancement.mca.baby_sirben_smelted.description": "Go out of your way to eliminate those cultists (even if by unethical methods)!",elted.description": "Go out of your way to eliminate those cultists (even if by unethical methods)!",

Please tell me this was some sick dev's joke that was accidentally passed into the live version... like seriously.. what the actual fuck is this?
Babies in furnaces is just wrong on every level.

**Comment by Luke100000** [comment]
It's a reference to original mca, feel free to discuss this in more detail with CDA
