### ISSUE TITLE
Can't start or launch a single player world for the 1.19 version

### ISSUE THREAD

**Issue by Katgirl217** [Luke100000/minecraft-comes-alive#471]
Every time I try to enter an old single-player world or create a new one it keeps saying, "Connection Lost Invalid Player Data" I've tried everything I could think of to fix it, including restarting Minecraft, logging out and logging back into Minecraft, and uninstalling the launcher and re-downloading it. The only way I can enter a world is by deleting the mod. It's weird since every version of the mod except the 1.19 version works fine.

**Comment by Luke100000** [comment]
Please append the latest.log
