### ISSUE TITLE
After trying to procreate for another kid, I am given a copy of my toddler as a baby by my wife

### ISSUE THREAD

**Issue by StrangeHermit** [Luke100000/minecraft-comes-alive#48]
So, I want a second kid after my first daughter Julibee(who is a toddler). I go up to my wife, Reyna, go to talk and click "Procreate." Instead of a dance, I have my wife telling me something along the lines of "You lost our baby?!? Oh, here he is!" and get handed a copy of Julibee as a reset baby in the pink blanket, with the actual Julibee is still being around. When the baby grows, they are actually different in looks, personality and traits, but they still have the same name and I have to manually change it. Do I just have to wait for Julibee to reach an older age and then try again for another kid, is this actually an issue or something else?

**Comment by Luke100000** [comment]
Theoretically, if you place the baby it's removed from the tracker. Which obviously failed somehow, I will investigate this

**Comment by Luke100000** [comment]
Baby retrieval temporary disabled in 7.0.7 and therefore fixed
