### ISSUE TITLE
Hair visual Glitch

### ISSUE THREAD

**Issue by DungeonMtr** [Luke100000/minecraft-comes-alive#483]
Hi im having some trouble with the mod. Im having a visual glitch that for some reason it overlays the outer layer of my player skin's head into the villagers head. Picture for reference:
![image](https://user-images.githubusercontent.com/64873468/208239513-59701a32-a504-4aa7-8920-b66e84adae71.png)

This also happens in the character creation menu but it fixes itself when i create the character. Problem is that the other villagers have it and idk how to fix it.

**Comment by Luke100000** [comment]
Can you try disabling all resource packs?

**Comment by DungeonMtr** [comment]
That seems to be the problem indeed. Is there a way to fix it? Or do i have to play without resourcepacks?

**Comment by Luke100000** [comment]
You can manually fix the resourcepack and delete everything villager related until I figure out why it's affecting mca villagers. Can you send me the resourcepack here please?

**Comment by DungeonMtr** [comment]
I think i found the issue, the resourcepack added layers to the steve skin and for some reason its hair was clipping through

**Comment by DungeonMtr** [comment]
Indeed that was the problem, its now fixed, thanks for the tip on it!

**Comment by Luke100000** [comment]
I will keep that open since the steve texture shouldn't appear in the first case ^^ Can you link me the resource pack please?

**Comment by DungeonMtr** [comment]
Sure. The resourcepack im using is the following:
https://www.curseforge.com/minecraft/texture-packs/pixagraph-by-amzahr
