### ISSUE TITLE
zombie ai taking over

### ISSUE THREAD

**Issue by TellurianTech50** [Luke100000/minecraft-comes-alive#485]
with better mobs, the zombie ai takes over with some villagers making them break windows and doors, as well as emptying chests and furnaces and causing the guards and archers to attack the villagers and each other

**Comment by Luke100000** [comment]
https://github.com/Flemmli97/ImprovedMobs/blob/26f6b2855fda99e6b7079f4428241987d56fbafb/common/src/main/java/io/github/flemmli97/improvedmobs/events/EventCalls.java#L190

I assume you mean ImprovedMobs? It assigns the stealing goals to every pathfinding entity. You can blacklist or ask the mod author to add mca as a default blacklist, but other than that I'm not sure how it is mca related.
