### ISSUE TITLE
Error code 1 when I try to sart the game.

### ISSUE THREAD

**Issue by Thekingundertheshade** [Luke100000/minecraft-comes-alive#486]
Hello, I try to play the 7.3.21 version of this mod on minecraft 1.19.2. I'm using forge 1.19.2-43.2.0. But with all of this I get the error code 1 when I click play on the launcher, before the game even starts. What I have to change to keep using minecraft 1.19,2?
I don't know what I'm doin wrong.

**Comment by Phoenix5089** [comment]
I had the same issue! I even tried witching back to 1.19 or trying later version and switching to forge. To no avail, I kept encountering this error, perhaps there's something wrong with the files?

**Comment by Luke100000** [comment]
I really need the latest.log. Error code 1 literally means "it crashed". It's not helpful without the log.

**Comment by Thekingundertheshade** [comment]
Sorry, now here I saw Architectury, and now seems to be working
