### ISSUE TITLE
Underground/inside a mountain Village

### ISSUE THREAD

**Issue by LuckySkye13** [Luke100000/minecraft-comes-alive#488]
Version:
minecraft-comes-alive-7.3.21+1.19.2-universal.jar

Hello, I'm trying to make a village inside a mountain, basically hollowing it out and making a cavern-like area to make a village in. However, villagers refuse to recognize "homes" inside, and when I try to use the blueprint item, it gives "Building has too large volume!" message above my hotbar... Is there any way to make an underground village work? They work with vanilla villagers since all they do is check for a valid bed.

**Comment by Luke100000** [comment]
Press add room instead. Since you need a village first, make some sort of dummy building outside.
I'll merge this with that here: #484
