### ISSUE TITLE
JER (Just Enough Resources) stops functioning when MCA Reborn is active.

### ISSUE THREAD

**Issue by StokkanTV** [Luke100000/minecraft-comes-alive#49]
Did some testing, had 400+ mods installing, narrowed it down to find out what made my JER not work or even show up.
MCA Reborn ended up being the cause, and I can't put my finger on why, as those two mods have no correlation with one another.

**Comment by Luke100000** [comment]
Can you append the log file, please?

**Comment by StokkanTV** [comment]
> 

Why yes ofc, the moment I figure out what you mean by 'append the log file' cuz honestly this is the first time I make a github post like this bro.
Give me a Youtube link or an explanation how to do so and I'll help 100% givin' you what you need!

**Comment by Luke100000** [comment]
enter `%appdata%/.minecraft/logs` in your file explorer and send me the debug.log (but only if your broken version is the last version launched)

**Comment by StokkanTV** [comment]
[debug.log](https://github.com/Luke100000/minecraft-comes-alive/files/7841618/debug.log)
Here we go, hope this helps.

**Comment by Luke100000** [comment]
Ok I read your log, it's not an issue directly caused by mca, but a general incompatibility. I tried JER 1.16.5-0.12.1.133 with JEI 1.16.5-7.7.0.106 and it works fine, tho it crashes while Farmers Delight is also installed. Try updating JER and see if the error is gone.

**Comment by StokkanTV** [comment]
I proceeded to do some tests. 
- I got the .133 version of JER, reinstalled MCA, and removed farmer delight and any mod related to farmer delight. 
This led to only show item (example, gunpowder) could be traded by a villager, but not able to show what mob is able to drop the item, which is the main use of JER's feature.
- I then proceeded to remove MCA again, and JER functioned as normal.
- Knowing only having JEI and JER active in the mod-folder with MCA alongside for me still doesn't work, I proceeded to refresh the whole Minecraft folder, config and other stuff to see if a fresh re-install fixed it.
Nope, still no JER working with MCA. Testing with gunpowder if it let me see which mob drops it (And it is supposed to show a creeper) but nothing, not even the JER menu show for me.

**Comment by Luke100000** [comment]
My bad; didn't notice JER wasn't working properly, the gunpowder experiment is a good hint. I'll investigate this issue.

**Comment by StokkanTV** [comment]
I'll stay updated to hear from you!

**Comment by Luke100000** [comment]
Found the issue, 7.0.7 will work with JER
