### ISSUE TITLE
head part of the villager model doesn't work well with First-person Model and Better Combat 

### ISSUE THREAD

**Issue by Red-TF2-Sniper** [Luke100000/minecraft-comes-alive#493]
the head part of the villager model blocks the first person camera when attacking with melee weapons when using with first-person model mod and better combat. its the same thing with sneaking too
![2022-12-26_15 11 01](https://user-images.githubusercontent.com/91907457/209583739-f1fe7ada-9ef6-4da7-b24c-2cb65a53e971.png)

FPM mod https://www.curseforge.com/minecraft/mc-mods/first-person-model/files/4089361

Better Combat mod https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus/files/4211954

**Comment by Luke100000** [comment]
related to #469, technically first person mod should bee supported. What version?

**Comment by Red-TF2-Sniper** [comment]
1.18.2 Forge-40.1.85

**Comment by ZsoltMolnarrr** [comment]
Hello!
This happens when setting body part visibility to `true`. This forces the body part to be rendered, even if Better Combat wants the hide it.
The solution is to just avoid setting it to true, since every render cycle starts with this state.
