### ISSUE TITLE
Suggestion: A command to tell the village ai that i live in the village

### ISSUE THREAD

**Issue by SteelTigerV2** [Luke100000/minecraft-comes-alive#495]
A command to tell the ai that i live in the village so it doesn't give my bed away when living with a spouse vilager

what's happening is i have a house for me and my family with beds for me, my spouse and children. but the ai keeps giving my bed away to some stranger

so my idea is away to tell the ai that "Hey i live here too"

**Comment by Luke100000** [comment]
Party implemented in the new version. No more bed stealing :)

**Comment by Luke100000** [comment]
"Restricted" now does that properly. Or at least it should.
