### ISSUE TITLE
Crashing Upon 1.19.2

### ISSUE THREAD

**Issue by kacegotmace** [Luke100000/minecraft-comes-alive#497]
For some reason, every time I try to play the game with MCA Reborn, Forge, it crashes. It says "Exit Code: 1", every time it crashes. Other people on Forge have complained about this, but I'm not sure what their exit codes are. I also don't know how to provide a log or crash report

**Comment by Luke100000** [comment]
I need the latest.log

**Comment by TerrisaChurchill** [comment]
Having same issue

**Comment by Luke100000** [comment]
Please check 7.4.0, to be released soon
