### ISSUE TITLE
Crash: Game crashes when starting a world because of "color blind" trait

### ISSUE THREAD

**Issue by User3624** [Luke100000/minecraft-comes-alive#499]
Basically, whenever you load into an existing or new world, the game freezes and crashes after "Loading terrain..." screen
![image](https://user-images.githubusercontent.com/108425476/209851386-90cc040a-9bf2-48dd-9beb-39f3dd738237.png)

**Comment by Luke100000** [comment]
Fixed in upcoming version, classic Turkish system locale issue :)

**Comment by User3624** [comment]
A little note: the game and the launcher WEREN'T in Turkish. Only the computer that Minecraft was running in was Turkish
