### ISSUE TITLE
Localisation problem [RU_RU]

### ISSUE THREAD

**Issue by SilverInfinite** [Luke100000/minecraft-comes-alive#50]
Hi, im player from Russia and found problem, what changeable names broked: Feeling, names of marriage and abilities

Upd: I must say what im playing on 1.16.5

**Comment by Luke100000** [comment]
With broke, do you mean some phrases are not yet translated? You can check the status and help translate here: https://crowdin.com/project/minecraft-comes-alive-2

**Comment by SilverInfinite** [comment]
> With broke, do you mean some phrases are not yet translated? You can check the status and help translate here: https://crowdin.com/project/minecraft-comes-alive-2

I mean, what scripts alittle broke and for example instead of Personality: Naughty its making Peronality: %v1#

**Comment by Luke100000** [comment]
Thanks. will be fixed in 7.0.7

**Comment by SilverInfinite** [comment]
> Thanks. will be fixed in 7.0.7

Ok thanks. And one more thing: Can i use and change skin if im using downloaded skin, for example from Ely.by (if you log in from that site in Minecraft you using skin what choose) im just dont know how it work

**Comment by Luke100000** [comment]
For the player? The player is not changed right now. For the villager? Theoretically yes, by naming the villager like the player using a nametag, but it's not recommended. Doesn't work with genetics and stuff.

**Comment by SilverInfinite** [comment]
> For the player? The player is not changed right now. For the villager? Theoretically yes, by naming the villager like the player using a nametag, but it's not recommended. Doesn't work with genetics and stuff.

Oh, you mean what for now its unavailable change player, got it

**Comment by Luke100000** [comment]
fixed in recent commits
