### ISSUE TITLE
1.19.2{server} Villagers are all small and named jobless

### ISSUE THREAD

**Issue by itstaajaae** [Luke100000/minecraft-comes-alive#509]
For some reason MCA villagers are all loading in small and have the name jobless. it pops up their name in chat but not when interacting with them. This only happens on a server and doesn't happen in single player. 
![2023-01-05_18 07 26](https://user-images.githubusercontent.com/114267704/210902622-6950e46b-f98e-4ac4-ae9d-d4b25507cfb7.png)
![2023-01-05_18 07 35](https://user-images.githubusercontent.com/114267704/210902626-bd887aeb-005a-4e0e-a6e3-32350bbda94b.png)
![2023-01-05_18 07 36](https://user-images.githubusercontent.com/114267704/210902631-55f33eee-d6e8-49ab-8110-13a6109276c5.png)

**Comment by itstaajaae** [comment]
IK it looks like kids, but they are all adults I'm playing ATM8 if that helps

**Comment by Luke100000** [comment]
I changed something which may affect that
