### ISSUE TITLE
When choosing player in character creation, Armor overlay is broken

### ISSUE THREAD

**Issue by BoyManDuck** [Luke100000/minecraft-comes-alive#510]
When choosing player option for the character creation and then putting on armor, the whole overlay seems to be all mismatched

[Universal 1.19.2] MCA Reborn - 7.4.0

forge

![2023-01-06_02 35 27](https://user-images.githubusercontent.com/122084221/210964393-91364574-51f0-46cd-905b-2b71369146ce.png)
![2023-01-06_02 23 21](https://user-images.githubusercontent.com/122084221/210964463-20876278-8489-45dc-acc5-6ac0b5dbda00.png)
![2023-01-06_02 23 14](https://user-images.githubusercontent.com/122084221/210964465-a5403a2c-d538-4789-862a-2e3d5fa09f3e.png)
![2023-01-06_02 35 22](https://user-images.githubusercontent.com/122084221/210964468-778c22a3-2901-46d9-9dcd-df3481e9aba3.png)
![2023-01-06_02 23 46](https://user-images.githubusercontent.com/122084221/210964456-c1fcf798-bf51-4df8-9124-9daebc7c8d87.png)
![2023-01-06_02 23 31](https://user-images.githubusercontent.com/122084221/210964459-81da95cf-c036-448e-8e24-b2ee0ad1c7d7.png)
![2023-01-06_02 23 25](https://user-images.githubusercontent.com/122084221/210964462-26c33e99-888f-4fce-a9cc-9bd09eccfe50.png)

**Comment by Luke100000** [comment]
Screenshot, modloader and version please

**Comment by Luke100000** [comment]
Does it also does this when only using mca? Especially graphics mods like optifine are know to be funky.

**Comment by BoyManDuck** [comment]
let me go check

**Comment by BoyManDuck** [comment]
when removing all other mods except its required dependency (Archtitectury) the bug still shows

**Comment by Luke100000** [comment]
Perfect, thanks!

**Comment by TheRibbuns** [comment]
Yeah this is happening to me too, modded armors are bugged the same way and for some reason the villagers aren't effected
