### ISSUE TITLE
Minectaft wont load after mod installed

### ISSUE THREAD

**Issue by ehhut1** [Luke100000/minecraft-comes-alive#519]
Minecraft crashes when trying to open when this mod is installed. Says, "unexpected issue occurred ant the game has crashed. Exit Code: 1"

Version: 1.19.3-forge-44.1.0

Mod Version: minecraft-comes-alive-7.4.0+1.19.3-universal

**Comment by Luke100000** [comment]
Did you install architectury? Please append the log
