### ISSUE TITLE
Can't set home

### ISSUE THREAD

**Issue by emmad04** [Luke100000/minecraft-comes-alive#52]
Hi, whenever I try to set home for my family nothing comes up in chat, so I try 'go home' and get 'we move too much, I don't know where home is'. I've also tried using the whistle and my husband stopped appearing but is still alive. If anyone can help it will be much appreciated. Thank you.

**Comment by Luke100000** [comment]
append log, please.
For the second issue, is the husband loaded?

**Comment by emmad04** [comment]
Sorry I'm new at this how do I access the append log? And yes my husband is there and can still interact with him but when I try to use the whistle only the daughter shows up. Thanks for the quick response.

**Comment by emmad04** [comment]
I think I have resolved the issue of not being able to set home as I think being too close to spawn was the issue, but the husband still does not appear on the whistle. (I'm on the fabric version, latest release)

**Comment by Luke100000** [comment]
The log is located at `%appdata%/.minecraft/logs/latest.log`, being close to spawn should not be a reason for failure but hopefully, the log can tell us more. Can you verify that your husband is registered as such by checking in the family tree for both you and the villager if a connection is shown?

**Comment by emmad04** [comment]
[2022-01-18-3.log.gz](https://github.com/Luke100000/minecraft-comes-alive/files/7891147/2022-01-18-3.log.gz)
(I do play with other mods installed)
![image](https://user-images.githubusercontent.com/97975118/149987845-b5317eb3-65e8-4ce1-bc9b-527c857fc449.png)

**Comment by emmad04** [comment]
[2022-01-18-3.log.gz](https://github.com/Luke100000/minecraft-comes-alive/files/7891168/2022-01-18-3.log.gz)

(I do play with other mods installed) And yes the husband is showing connected in the family tree.

**Comment by Luke100000** [comment]
Cool, the log did not help in our case but contained another crash which I can fix now, thanks!
Regarding the log, it seems like you did not try setHome in this run. To be precise, the log indicates that the game crashed directly after launch. Maybe try again, but before trying to setHome, write something in the chat, like `------------` so I can see the exact timestamp. Then send the latest.log, not the zipped one.

**Comment by emmad04** [comment]
It seems the problem is no longer happening, I took them back to space it was happening and no longer appears. If it does appear again I will make sure to get the file. But I'm glad I could at least help with something else, sorry if I wasted time with that issue. However, do you know of any fixes for the whistle?

**Comment by Luke100000** [comment]
The whistle is indeed weird. You could send me the entire world and I can a more detailed look at it, but it's some work for a small effect.

**Comment by emmad04** [comment]
I can deal with it (just keep him in a room somewhere), but thank you for the help and quick response.
