### ISSUE TITLE
Setting home location doesn't change anything.

### ISSUE THREAD

**Issue by keidakat** [Luke100000/minecraft-comes-alive#520]
Updating to the latest version swapped all the villager's homes around and they won't listen when I try to tell them which home is theirs. They just go "ok" and wander off to sleep in another random house later with no feedback on the Blueprint that their house changed.

**Comment by Luke100000** [comment]
I was able to confirm the "go home" issue, and the blueprint is sometimes delayed. But setting home worked fine.
For the sake of simplicity and compatibility, 7.4.0 is using the vanilla bed system again. They can look for a new bed if they failed to reach it.

**Comment by netcore10** [comment]
I work on the same server. It seems they detect houses, but don't stick to that house and bounce between them. They also seem to prioritise one house. There's one house with 4 beds, but 6 villager's seem to claim it, or move elsewhere at random times regardless of what house you state is their home. They'll stay there, then move elsewhere at random moments claiming a different bed.

**Comment by keidakat** [comment]
Then something is wrong with the pathing because they can claim a bed just fine and then choose to wander off and claim a bed on the other side of town.  For instance, Marko and Ivar were both set to beds in the Blacksmith but now are sleeping in the inn clear on the other side of town. An inn that has 4 beds, but is home to 8 villagers...

![2023-01-13_18 20 19](https://user-images.githubusercontent.com/27837516/212440752-5da0aa35-3121-41b1-8eb5-b1c71f34a0e6.png)

**Comment by Luke100000** [comment]
> but is home to 8 villagers

A home in 7.4.0 is a claimed bed, you can not claim a bed twice so that is definitely odd.  I guess I will be staring at villagers for a while...

**Comment by Luke100000** [comment]
Please see if the issue persists in 7.4.1
