### ISSUE TITLE
New in Town Compatibility

### ISSUE THREAD

**Issue by KatNyxion** [Luke100000/minecraft-comes-alive#523]
**Describe the bug**
MCA does not seem to save Entity tags of the "New in Town" Datapack. Specifically the main part of it is a "Town Planner" who if they die, respawns every minecraft day at noon. The issue comes up that it seems that when the villager is transformed it registers as "dead" and a new one spawns the next day at noon. I think it is an issue of MCA not saving the entity tag properly "nitEntity" as when I tried a kill nitEntity command it comes up with 0 results. I spoke to the maker of the datapack and they said they can't do anything to fix it, so was hoping there was a solution here.

**To Reproduce**
1. Install "minecraft-comes-alive-7.3.21+1.19.2-universal"
2. Install the New in Town datapack "https://www.planetminecraft.com/data-pack/new-in-town-a-settler-s-experience-data-pack/"
3. Hit a tree and get the Town Charter book
4. Place Town Charter
5. NPC spawns
6. Wait until noon next minecraft day, another NPC spawns even though the original is still alive.

**Version**
MCA Version: 7.3.21, Minecraft version: 1.19.2, Modloader: Fabric

**Comment by Luke100000** [comment]
I fixed the issue on my side by copying the tags. I will also need to readd a few nbt tags like noAI. The second issue needs to be fixed by the datapack:
In `restore_town_planner.mcfunction` it is explicitly searched for an villager, which excludes mca villagers. I see no downside in just removing that.
```
execute unless entity @e[type=villager,tag=nitKTP,distance=..2] ...
```
