### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by Rogenar** [Luke100000/minecraft-comes-alive#526]
[Universal 1.19.3] MCA Reborn - 7.4.0 verison causing crash.

**Comment by Luke100000** [comment]
latest.log

**Comment by Rogenar** [comment]
this version
![sd](https://user-images.githubusercontent.com/122460325/212480062-6b1e9bc0-2962-4ef2-ae7f-d969072d0d7f.png)

**Comment by Luke100000** [comment]
I meant the latest.log file in your logs directory

**Comment by Rogenar** [comment]
These are the last errors in the crash and log file
[rei.log](https://github.com/Luke100000/minecraft-comes-alive/files/10418140/rei.log)
[rei-issues.log](https://github.com/Luke100000/minecraft-comes-alive/files/10418141/rei-issues.log)
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/10418142/latest.log)
[crash-2023-01-14_19.10.12-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/10418143/crash-2023-01-14_19.10.12-client.txt)

**Comment by Luke100000** [comment]
Is your system language Turkish?

**Comment by Rogenar** [comment]
yeah.

**Comment by Luke100000** [comment]
Ok perfect, then please wait for 7.4.1, its fixed and will be pushed in that version.

**Comment by Rogenar** [comment]
thank you.
