### ISSUE TITLE
Armor Texture visual error when player uses MCA Model/Hybrid Model

### ISSUE THREAD

**Issue by Pearilous** [Luke100000/minecraft-comes-alive#532]
**Describe the bug**
Armor worn by a player using MCA's custom player model does not appear on the player properly.

**To Reproduce**
1. Choose any model type other than "Vanilla"
2. Equip armor in your armor slots. different colors of armor display this more vibrantly.
3. Press F5 to see your character in 3rd person.

**Screenshots**
![image](https://user-images.githubusercontent.com/123029845/213306408-3bcb4d4f-bff3-40f5-a965-65149e219f14.png)
![image](https://user-images.githubusercontent.com/123029845/213306524-c53aae34-8b52-40f0-ad61-5ea9c80c88af.png)
![image](https://user-images.githubusercontent.com/123029845/213306561-8e67ea8b-897a-4c7c-ab43-b295143f3554.png)

**Version**
7.4.0, 1.18.2, Curseforge

**Comment by Luke100000** [comment]
Fixed in 7.4.1, related to #510
