### ISSUE TITLE
Even with 300+ hearts villagers won't accept bouquet/ring

### ISSUE THREAD

**Issue by Belial-alt** [Luke100000/minecraft-comes-alive#534]
**Describe the bug**
I tried finding similar issues on the Issues page first and didn't see anything, so sorry if you have solved this and I just couldn't find it.

I had a couple different villagers that I liked and got them up to over 100+ hearts and they still didn't accept the bouquet. I kept trying to get them to like me, giving gold blocks, trying good interactions, I would hug them to get a good interaction chance and then they would accept romantic interactions. I even realized I got better responses when no other villagers were around, so I would go somewhere private, get positive interactions with romantic interactions before attempting to gift bouquet/ ring and they still won't accept it. Tried with male and female villagers, more than just the two shown below.

**Screenshots**
![image_2023-01-19_132226532](https://user-images.githubusercontent.com/90856610/213564750-441582dd-e592-4668-990a-600d173eda05.png)
![image_2023-01-19_132438407](https://user-images.githubusercontent.com/90856610/213565312-374280ac-0489-47f2-8413-379a0956298d.png)

**Version**
MCA Version: 7.4.0
Minecraft version: 1.19.2 
Modloader: CurseForge v. 0.217.3.7928

**Latest.log**
[2022-12-20-1.log.gz](https://github.com/Luke100000/minecraft-comes-alive/files/10461279/2022-12-20-1.log.gz)

**Comment by Luke100000** [comment]
What are your traits?

**Comment by Belial-alt** [comment]
> What are your traits?
If i remember right
heterochromia
homosexual
bisexual

**Comment by Luke100000** [comment]
Thanks. The combination of homosexual and bisexual definitely sounds potential buggy and from past reports it seems like either of those two also causes issues

**Comment by Belial-alt** [comment]
> Thanks. The combination of homosexual and bisexual definitely sounds potential buggy and from past reports it seems like either of those two also causes issues

I had a feeling they might mess with each other, but in the moment I was like "I'll do both lol"

Is there anyway I can reset my traits to try and fix this?

**Comment by Belial-alt** [comment]
It took me a while to figure out, but I was able to enable fulleditor in the config. I took off the homosexual trait and just had bisexual. Albert turned me down, so I gave the bouquet to Harmanda and it worked! Thank you for all your help and your quick response! <3

**Comment by Luke100000** [comment]
Let's merge with  #576
