### ISSUE TITLE
Please remove the weird discombobulated male voice that does a demented laugh

### ISSUE THREAD

**Issue by ncottrill** [Luke100000/minecraft-comes-alive#535]
**Is your feature request related to a problem? Please describe.**
I am really troubled by this loud male demented sing-songy laugh that echoes loudly in the village. I cannot track down the villager making the sound and its truly annoying.

**Describe the solution you'd like**
Please remove that sound track or turn it down or tell the player what to do to make the villager stop the noise.

**Describe alternatives you've considered**
I've looked all over trying to find the sound. It seems to emanate from nowhere in particular.

**Additional context**

**Comment by Cal-Is-Burning** [comment]
The villager trait that you're referring to is called a "Sirben." Having read through the config, it doesn't look like there is any way to remove them. They are incredibly rare, but they will occasionally say "random sirben noises" in the chat, which could help you identify them. While I personally find this villager trait to be sort of charming if potentially a bit insensitive, I also think it would be a good idea to be able to disable certain traits in the config if you don't like them.
