### ISSUE TITLE
7. 3. 21&22&23 teleport bug ?

### ISSUE THREAD

**Issue by Sokraa** [Luke100000/minecraft-comes-alive#539]
When on a start, I choose start in some Village and I get teleported somewhere where is no village, mby missunderstanding ?

**Comment by Luke100000** [comment]
Are you sure you got teleported? If no village has been found, you will stay on the spot

**Comment by Sokraa** [comment]
Well when I start completely new game, and choose that I want to be for start teleportet for example in taiga village or plains village, no mather what I choose, I still start new world on the same exact place.

**Comment by Luke100000** [comment]
Wait. You are on 1.16.5? That version does not have biome specific village tags

**Comment by Sokraa** [comment]
oh yeah.. that didnt came to my mind

**Comment by Luke100000** [comment]
No wait, that doesnt solve the issue XD Where did you find the buttons in the first place? You should only be able to select "village", "shipwreck" etc

**Comment by Sokraa** [comment]
its the buttons what you choose before spawn

**Comment by Luke100000** [comment]
How many do you see, and do you indeed use 1.16.5? Are the buttons translated correctly? Did you ever install any other version of mca?

**Comment by Sokraa** [comment]
I see 7 buttons, I'm using mc 1.16.5, I have mc in english so i suppose that they are correct, yes I have installed 7. 3. 21-23, but on this world I am and I was running just 7. 3. 23

**Comment by Luke100000** [comment]
But did you ever install a version 1.18.2 or above?

**Comment by Sokraa** [comment]
I think that i didnt

**Comment by Luke100000** [comment]
Ok this is very cursed, and in any case, thanks for reporting. 7.3.24, no ETA, should fix that issue. For now don't click any other button than shipwreck or somewhere ^^

Alternatively you can delete the config at `config/mca.json` to fix
