### ISSUE TITLE
Armor buggy

### ISSUE THREAD

**Issue by Bugster1970** [Luke100000/minecraft-comes-alive#542]
https://cdn.discordapp.com/attachments/838815543326408775/1066444494876196864/Screenshot_413.png

https://cdn.discordapp.com/attachments/838815543326408775/1066444495161401374/Screenshot_414.png

it fixes when i uninstall the mod

and also another thing to note i cant place babys even in the latest 1.19.2 rc4 versions

**Comment by Luke100000** [comment]
Thanks. already fixed, see #532

**Comment by Bugster1970** [comment]
> Thanks. already fixed, see #532

thanks it was really annoying and i least expected it to be mca
