### ISSUE TITLE
Server crashes periodically during interactions with villagers with chatbot AI enabled

### ISSUE THREAD

**Issue by ncottrill** [Luke100000/minecraft-comes-alive#543]
**Describe the bug**
When interacting with MCA villagers (with the chatbot AI enabled), sometimes the server freezes ... and then crashes.

**To Reproduce**

The issue seems to be random, but it does happen about 3-4 times per real life server day.

**Screenshots**
NA

**Version**
MCA Version, Minecraft version, Modloader
MCA Reborn:  minecraft-comes-alive-7.4.0+1.19.2-universal
Minecraft version 1.19.2
Fabric 

**Latest.log**
This is the crash report from the server

[crash-report.txt](https://github.com/Luke100000/minecraft-comes-alive/files/10477479/crash-report.txt)
[latest-server-log.log](https://github.com/Luke100000/minecraft-comes-alive/files/10477491/latest-server-log.log)

**Comment by Luke100000** [comment]
Should be unrelated to chat, this is the rumors button trying to look for a structure. I still wasn't able to figure out why its not working, especially since this is basically a vanilla function. Thanks for the report.

**Comment by Luke100000** [comment]
Merged with #438
