### ISSUE TITLE
game freezes when talking with villagers

### ISSUE THREAD

**Issue by cha1r** [Luke100000/minecraft-comes-alive#544]
**Describe the bug**
when i speak to a villager, and they prompt me with "how did you find this village" or something along those lines, the text box freezes and i can no longer interact with anything in the world. the game doesn't crash but nothing can be interacted with.

**Version**
1.19.2, fabric, optifabric

**Latest.log**
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/10487182/latest.log)

**Comment by Luke100000** [comment]
merged with #438
