### ISSUE TITLE
Request: Convert vanilla villager command should retain the trades and discount.

### ISSUE THREAD

**Issue by pantsguyapp** [Luke100000/minecraft-comes-alive#546]
**Is your feature request related to a problem? Please describe.**
When I use the converting radius command, the newly converted mca villager had their trades reset.

**Describe the solution you'd like**
Upon executing the command, the trades are kept.

**Describe alternatives you've considered**
Nope.

**Additional context**

**Comment by Luke100000** [comment]
There would be too much stuff to convert and copy. Converting villagers is lossy.
Villagers keep their trades and level if they are at least level 2.
