### ISSUE TITLE
Suddenly an Outlaw

### ISSUE THREAD

**Issue by solanum-tea** [Luke100000/minecraft-comes-alive#55]
I had and still have a reputation of 83 average hearts and I have mayor status. I just fulfilled the requirements to reach the next rank and when I checked, it said I was an outlaw. Unlike the requirements to rank up that were previously there, there is nothing telling me what to do next. I don't want to be an outlaw and I don't know what I did. The only thing I can think of is killing a villager in another town very far away from my hometown. The thing is the outlaw rank didn't show up until later when I fulfilled the requirements to rank up. What should I do?

**Comment by Luke100000** [comment]
fixed in the upcoming version.
For now, mark a required building as blocked to fix.
