### ISSUE TITLE
Armor Not Rendering Properly

### ISSUE THREAD

**Issue by Cubepixelzzz** [Luke100000/minecraft-comes-alive#550]
Hey! I really love your mod however I noticed a bug that, well isn't too important, but I should add. The armor appears on the character in a weird way. I tried using modded armor and some render properly while other renders in the same manner as the leather armor below. I just wanted to bring it to your attention.
![2023-02-01_03 12 12](https://user-images.githubusercontent.com/109840522/215987822-2a3f3a13-f249-4262-bad4-0ced725d552c.png)
![2023-02-01_03 11 57](https://user-images.githubusercontent.com/109840522/215987828-02ebe756-19b2-49cb-9f7b-d1fe2fc9828c.png)
![2023-02-01_03 12 06](https://user-images.githubusercontent.com/109840522/215987833-d550569d-1e82-4294-be97-c83130568709.png)

**Comment by Luke100000** [comment]
Thanks for the nice screenshots, it has been fixed and I try to push a new versions once I have time :)
See #542
