### ISSUE TITLE
Armor Rendering issue

### ISSUE THREAD

**Issue by Amarthanor** [Luke100000/minecraft-comes-alive#551]
**Describe the bug**
Armor Rendering incorrectly with MCA and no other mods.

Note I tested it out with just Architectury and not MCA attempting to get the same result, and the armor rendered correctly.

**To Reproduce**
1. Install Architectury (architectury-7.0.66-forge)
2. Install either MCA (minecraft-comes-alive-7.4.0-rc.4+1.19.3-universal) or (minecraft-comes-alive-7.4.0+1.19.3-universal)
3. Equip any vanilla armor
4. Armor renders across player in strange ways.

**Screenshots**
![2023-02-01_08 34 52](https://user-images.githubusercontent.com/124171534/216072420-d27f1005-5a2d-4e08-8585-60342912b342.png)

**Version**
MCA Version - 7.4.0
Minecraft version - 1.19.3
Modloader - Forge - 1.19.3-forge-44.1.8

**Latest.log**
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/10558062/latest.log)

**Comment by Luke100000** [comment]
Thanks for the good issue, it has been fixed and I try to push a new versions once I have time :)
See #542
