### ISSUE TITLE
So everytime I try to run my own modpack with MCA Reborn it crashes but when I run it without it runs just fine.

### ISSUE THREAD

**Issue by AsteriaLive** [Luke100000/minecraft-comes-alive#553]
So, I have tried this mulitple times. I don't know if something is interfering or what but it is annoying. I am using curseforge to make the modpack and it doesnt show a crash report. All it says is: **An unexpected issue occurred and the game has crashed. We're sorry for the inconvenience. Exit code: 1**

Here are the mod folder I used: https://drive.google.com/file/d/1h9owlmmgY6YPyK3BIhSRLxSQj5fEHFaB/view?usp=sharing

If anyone can help me thank you so much. I am trying to do make this modpack for a small streamer server.

EDIT: I fixed it :) It just took a long time

**Comment by Luke100000** [comment]
Log please
