### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by Rogenar** [Luke100000/minecraft-comes-alive#555]
minecraft-comes-alive-7.4.0+1.19.3 versiyon.
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/10574657/latest.log)
[rei.log](https://github.com/Luke100000/minecraft-comes-alive/files/10574658/rei.log)
[rei-issues.log](https://github.com/Luke100000/minecraft-comes-alive/files/10574659/rei-issues.log)
[crash-2023-02-03_04.08.33-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/10574660/crash-2023-02-03_04.08.33-client.txt)
what is the reason of this?

**Comment by Luke100000** [comment]
Fixed in 7.4.1
