### ISSUE TITLE
Armor texture error

### ISSUE THREAD

**Issue by ghost** [Luke100000/minecraft-comes-alive#556]
**Describe the bug**
Armor texture error
**To Reproduce**

**Screenshots**
![QQ截图20230203130413](https://user-images.githubusercontent.com/83486178/216517691-16483eaf-75cf-4058-bb97-a06635c54715.png)
![QQ截图20230203130347](https://user-images.githubusercontent.com/83486178/216517697-b6ae11db-fc01-4fac-aeaa-eb4c9a3dfe42.png)
![QQ截图20230203130340](https://user-images.githubusercontent.com/83486178/216517699-5fe28c09-275b-4b07-bc3d-8a81a6474c55.png)
![QQ截图20230203130334](https://user-images.githubusercontent.com/83486178/216517700-7df6d347-cdc4-4610-aa88-8a18696cebaa.png)

**Version**
MCA Version, Minecraft version, Modloader
minecraft-comes-alive-7.4.0+1.19.2-universal
1.19.2 forge43.2.4

**Comment by Luke100000** [comment]
Thanks, fixed, see #542
