### ISSUE TITLE
Nametags aren't hideable, can't interact with villagers unless mca villager model is used

### ISSUE THREAD

**Issue by JetpackRescue** [Luke100000/minecraft-comes-alive#56]
for my modpack I place villagers on a team to hide their nametags, I have a personal mod that adds a box over entities with their names that you can see at all times when within 30 blocks of them. MCA is doing something weird so that when I use your villagers, they not only have the name box from my mod, but they also get their minecraft nametags back. I'm using a datapack to hide minecraft nametags.

```
team add HiddenVillager

team join HiddenVillager @e[type=villager]
team join HiddenVillager @e[type=mca:female_villager]
team join HiddenVillager @e[type=mca:male_villager]

team modify HiddenVillager nametagVisibility never
```

if in the mca config I set  `"overwriteOriginalVillagers": true` then it shows minecraft nametags when I've set them to never be visible. If I set `"overwriteOriginalVillagers"` to false, the nametags are hidden like they should be, but I don't get the neat looking mca villagers.

also, if i set `"overwriteOriginalVillagers"` to false, i can't interact with any villager like I can if I use mca villagers.
The only other mob I've had issues hiding nametags with is lycanites mobs and he does something weird with his mobs that break compatibility with in control mod as well.

**Comment by Luke100000** [comment]
`overwriteOriginalVillagers` has nothing to do with villagers itself, it just replaces vanilla with modded.
In 7.0.7 I changed something related to names, maybe it fixed this.
Please drop the entire data pack here so I can test this quickly.

**Comment by Luke100000** [comment]
Can you please verify if the nametag behaves weirdly in 7.0.7?

**Comment by Luke100000** [comment]
Added manual config flag too
