### ISSUE TITLE
Unable to chat with baby.

### ISSUE THREAD

**Issue by ncottrill** [Luke100000/minecraft-comes-alive#564]
**Describe the bug**
Baby is sad. We used to be able to play rock paper scissors or hug baby to help baby feel better. But, now, if we push TALK interaction button, nothing happens. We have to push ESC to get out of the interaction GUI. 

**To Reproduce**
1. Have a baby
2. Try to TALK to baby
3. There are no options for things we can say to the baby. We can no longer play rock paper scissors, etc.
4. Baby remains sad.

**Screenshots**
![baby](https://user-images.githubusercontent.com/14022160/216802897-0c8479fe-cd15-4fc9-a28e-dc09b8f99b05.png)

**Version**
MCA Version 7.4.4, 
Minecraft version 1.19.2, 
Modloader Fabric

**Latest.log**

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/10610269/latest.log)

**Comment by Luke100000** [comment]
I changed that babies now babble in the title too. It does apparently only work on singleplayer ouf, will fix that

**Comment by Luke100000** [comment]
Fixed in 7.4.5!
