### ISSUE TITLE
Guard Villagers mod guards attack mca villagers.

### ISSUE THREAD

**Issue by JetpackRescue** [Luke100000/minecraft-comes-alive#57]
I suspect this is connected to the last issue I posted a bit ago. Guard villagers mod guards are seen by minecraft as villagers, but mca villagers are not seen as villagers, so the guards attack them. I would suspect this also means that iron golems wont attack enemy mobs that attack mca villagers, because mca villagers aren't seen as villagers by minecraft.

I realize mca has it's own guards, but I think this issue might cause more issues with other mods since the mca villagers aren't seen as villagers by minecraft, so any other mod that also does something regarding villagers won't work.

EDIT: the villagers are now flying around on parrots, which is a feature from improved mobs mod where hostile entities have a chance of spawning a parrot to fly on when they're trying to get somewhere they can't normally get to, like if they're chasing the player.

**Comment by Luke100000** [comment]
Please provide a minimal example, I tested both mca and the guards mod, they work fine for me.
