### ISSUE TITLE
blueprint doesnt show all vanilla job buildings

### ISSUE THREAD

**Issue by CharCharthemonkey** [Luke100000/minecraft-comes-alive#571]
if using the blueprint to assign villagers to jobs the blueprint is missing atleast half if not more then alot of the vanilla job houses

**Comment by Luke100000** [comment]
To clarify, do you mean "missing" in terms of not even there or just not marked accordingly? Can you manually add them? Is there a job block INSIDE the building? Can you name examples?

**Comment by CharCharthemonkey** [comment]
library farm grindstone loom and potentially others are just not even showing  which is odd also for the grindstone one its actually there yes BUT its with another which is confusing since its using the smithing table to make not the grindstone

**Comment by Luke100000** [comment]
farm is no building, but the rest is indeed weird. But can you manually add it?

**Comment by CharCharthemonkey** [comment]
if u mean "add a generic building" then yes but one specfically for any of the ones i mentioned above no also the farm would be the greenhouse technically

**Comment by Luke100000** [comment]
And if you add such generic building, what blocks did it recognize? Did it recognize the job site?

**Comment by CharCharthemonkey** [comment]
it does not sadly which is y i originally looked for job specfic buildings but then found none for the ones i mentioned

**Comment by Luke100000** [comment]
Then please send me a screenshot of one example building, with especially good view on the job site

**Comment by CharCharthemonkey** [comment]
if i had any sure but atleast for the farm one its not that difficult to do

**Comment by Luke100000** [comment]
Except the farm, because again, farms don't have roofs and without roof its not a building

**Comment by CharCharthemonkey** [comment]
farms can techncially have roofs cause its called a greenhouse which has many farms inside of it

**Comment by CharCharthemonkey** [comment]
btw i joined the discord but cant figure out how to actually chat there

**Comment by Luke100000** [comment]
Read the rules and press the verify button ^^
