### ISSUE TITLE
player and villagers skin not showing

### ISSUE THREAD

**Issue by FahadDC** [Luke100000/minecraft-comes-alive#573]
Hello, thanks for the great mod in minecraft. when i play it in single player it works fine.

but when i played it in multiplayer i can't choose skin for myself.
picture .. https://media.discordapp.net/attachments/829796006953877566/1072993558535086150/image.png?width=900&height=670

when i pick Player skin it show my own skin fine
 
the villagers also missing their skins 
picture .. https://media.discordapp.net/attachments/829796006953877566/1072993808637239336/image.png?width=902&height=670

Logs for Server ..
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/10690198/latest.log)

Logs for my client ..
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/10690200/latest.log)

i had this issue for both 1.19.2 and 1.19.3 
@Luke100000

**Comment by Luke100000** [comment]
```
[00:32:12] [Netty Client IO #0/ERROR]: Channels [vanillaplustools:net-channel,mca:main,toolleveling:main] rejected vanilla connections
```
Can you share more details about your server? It seems to block some connections.
