### ISSUE TITLE
Villagers skin and personality not showing

### ISSUE THREAD

**Issue by Deserto0** [Luke100000/minecraft-comes-alive#577]
When in enter in multiplayer the villagers are missing their skin and they are all dwarfs. And they don't have any personality

![image](https://user-images.githubusercontent.com/124760126/218292165-8a5c7e1c-59ef-47a1-a930-acae19880822.png)
![image](https://user-images.githubusercontent.com/124760126/218292193-41d9878f-3026-4c7a-a1e0-23d694ff6d6b.png)

Version 1.19.2

**Comment by Luke100000** [comment]
I fixed something related, maybe it's gone
