### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by zinsser901224** [Luke100000/minecraft-comes-alive#578]
Crash at Game-Startup
1.18.2 and forge 40.2.1
[crash-2023-02-13_11.21.38-fml.txt](https://github.com/Luke100000/minecraft-comes-alive/files/10718386/crash-2023-02-13_11.21.38-fml.txt)

**Comment by Luke100000** [comment]
Looks like a version mismatch between archiitectury and forge, make sure both are up to date, or if architectury specifies a forge version, use that
