### ISSUE TITLE
Conflict with Iguana Tweaks Reborn

### ISSUE THREAD

**Issue by zonicraft** [Luke100000/minecraft-comes-alive#58]
I found that when with the Iguana Tweaks Reborn mod is installed all the npcs that are nor adults have their models flickring between an adult form and a smaller one, even when they are still babys

**Comment by Luke100000** [comment]
Finally, a way to reconstruct this error. Once I have time I'll try to track that issue down, thanks.

**Comment by Luke100000** [comment]
In the iguanatweaks toml config file, set `"Childs Growth Villagers" = false`. This will fix the issue while I look for a more convenient solution. They did some magic to slow down aging, which conflicts with MCA.
