### ISSUE TITLE
'PercentageOfVanillaVillages' doesn't work

### ISSUE THREAD

**Issue by riesaexe** [Luke100000/minecraft-comes-alive#581]
In the latest version ([Universal 1.18.2] MCA Reborn-7.4.5),
'PercentageOfVanillaVillages' doesn't work.
The default generated mca.json does not contain this option.
I tried to edit mca.json and add this option, but it will be cleared after starting the server.
I don't know if this is a bug or a new feature. If it is a new feature, please tell me how to start the generation of the original village.

My mother tongue is not English, and I express it through software translation. I hope I don't have any reading difficulties for you. Thank you.

**Comment by Luke100000** [comment]
Yes, thanks, the documentation is outdated here, `fractionOfVanillaVillages` is the value.
