### ISSUE TITLE
Possible Compatibility Error, not sure with what.

### ISSUE THREAD

**Issue by APrimevalWorld** [Luke100000/minecraft-comes-alive#582]
**Describe the bug**
Game spawn area loads up to 96% via launcher logs and 100% in game; does not load any further. It's defo MCA as I disabled it and it worked fine. I'm going to do some test runs with earlier versions of forge to see if I can help at all.

**Note: Strangely, upon opening the world you can actually fix the error by loading the game without the mod, opening the world and then doing the same WITH the mod enabled. I'm a curseforge user, just for clarification.

**To Reproduce**
1. Launch Minecraft
2. Create A New World (I'm using OTG generator with Terraforged landscapes and BOP + Lost Cities)
3. Open World
4. See Error

**Screenshots**
The only screenshots I can provide are of the launcher logs, which is pretty much exactly the same as the latest.log from what I understand.

**Version**
7.3.21, 1.16.5, Forge 36.2.39

**Latest.log**
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/10730858/latest.log)

**Comment by Luke100000** [comment]
Probably related to #436 tho it should crash after ~30 or 60 seconds, I will soon try another approach which may or may not end up in a Catastrophe

**Comment by APrimevalWorld** [comment]
> Probably related to #436 tho it should crash after ~30 or 60 seconds, I will soon try another approach which may or may not end up in a Catastrophe

It didn't actually crash after that time. It just infinitely ran until I task manager closed the whole app since it wasn't going to let me do anything. I might try and run an experiment, but I waited about 10 - 20 minutes and it did nothing at all. No new lines of code were generated in all the times I was trying to play, but I am going to try a couple of things to see if I can help you out at all with the process of fixing this. Partially because I loved MCA for 1.12.2, so the sooner this gets fixed the better it is for many people.

**Comment by Luke100000** [comment]
No 10+ minute is definitely past a timeout, but I still think both issues are related and I hope my attempt will fix the issue. I will notify you once done!

**Comment by APrimevalWorld** [comment]
> No 10+ minute is definitely past a timeout, but I still think both issues are related and I hope my attempt will fix the issue. I will notify you once done!

Alright! I wish you the best of luck, btw. Apologies if I sound a little passive aggressive rn - truly not the intention. I will also let you know about what I find once I do a couple of experiments - it might help you a little.

**Comment by APrimevalWorld** [comment]
> No 10+ minute is definitely past a timeout, but I still think both issues are related and I hope my attempt will fix the issue. I will notify you once done!

Alright, I think this is a compat issue. I'm unsure with what - I have about 250 mods on that file, but it runs fine on its own. I will see if I can work on replicating the issue with certain mods to help you fix this - assuming you can - so others don't experience the same problem.

**Comment by Luke100000** [comment]
Merged with #842
