### ISSUE TITLE
Texture dislocation  about leggings&boots

### ISSUE THREAD

**Issue by InkSsskeleton** [Luke100000/minecraft-comes-alive#587]
If players choose to be "Villager" on the beginning menu,textures of leggings and boots will be dislocated when player wears.but this doesn't happens on Villager the mobs.
![2023-02-18_15 42 02](https://user-images.githubusercontent.com/78021392/219852775-97c454b5-f0ad-443b-9cc7-4bae3ecdcb44.png)
(when wearing leggings)

![2023-02-18_17 43 42](https://user-images.githubusercontent.com/78021392/219853552-70e366da-5dda-43b1-9252-c04289a79d1c.png)
(when wearing boots)

Mod version:minecraft-comes-alive-7.4.0+1.19.2-universal    (Forge version)

**Comment by Luke100000** [comment]
fixed a while ago, please upgrade :)

**Comment by InkSsskeleton** [comment]
> fixed a while ago, please upgrade :)

oh sorry
