### ISSUE TITLE
After the update, villagers will not spawn in villages

### ISSUE THREAD

**Issue by AxeDark13** [Luke100000/minecraft-comes-alive#594]
Hello,
I used to play on version 7.3.21 1.19.2 universal. I decided to update MCA to the latest (7.4.6) and the villagers stopped spawning in villages. But egg working good. I tried to demolish minecraft and put it on "clean minecraft" - it didn't work. They won't compare anyway. I put back the old version - they started to spawn again .-. 
I play on Minecraft 1.19.2 with Fabric(don't know it's verion, but Fabric API is 0.73.2).

**Comment by Luke100000** [comment]
latest.log please

**Comment by SimplyTadpole** [comment]
I can confirm I'm having the exact same issue. [Here's](https://github.com/Luke100000/minecraft-comes-alive/files/10832182/latest.log) my log if it helps any.

**Comment by Luke100000** [comment]
Thanks, log confirms the issue.

**Comment by AxeDark13** [comment]
> latest.log please

Sorry, there was no way to send the log 
Here

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/10833502/latest.log)
