### ISSUE TITLE
Texture Map/Generator

### ISSUE THREAD

**Issue by firemaster1294** [Luke100000/minecraft-comes-alive#595]
I'm a modpack developer, and I haven't found any texture mappings for ease of generating textures within MCA.

It would be nice to have either an in-game texture editor with an export to pack option (although this is a lot of work, I know), or at the very least it would be nice for you guys to publish a map of which textures go where in the .png files.

In the meantime, I've taken to drawing multicoloured checker patterns to try and figure out what goes where 🙃

**Comment by Luke100000** [comment]
Just to clarify, do you mean skins? All skins are 64x64 steve format :)
There is a converter included to generate burned and zombie clothing.
I'm working on an example pack, but first I want to fully add temperature (and thus biome) based clothing.

**Comment by firemaster1294** [comment]
Oh! That's awesome! I'm curious why I wasn't able to just add in the More Villagers styles - unless the Villager format is different from the Steve format. I'm not familiar with it. How does the converter work?

**Comment by Luke100000** [comment]
You also need some skin descriptor files: https://github.com/Luke100000/minecraft-comes-alive/wiki/Custom-Skins

The converter is a python script which creates the (optional) clothing variants, it's not properly documented anyways and not relevant for now :)
