### ISSUE TITLE
Config for mca villager spawns + vanilla villager spawns?

### ISSUE THREAD

**Issue by n0valey** [Luke100000/minecraft-comes-alive#596]
**Is your feature request related to a problem? Please describe.**
Me and my friends like the mca villagers, but also miss certain mechanics that are reliant on the vanilla testificate villagers, I tried to disable zombie villagers being overwritten so that there could be a lore implication (the normal villagers arent able to defend themselves, and thus eventually got wiped out by the zombie virus, but can still spawn as zombie villagers)

**Describe the solution you'd like**
A config option that lets you tweak the spawn rates, like 50% mca zombie villagers to 50% vanilla zombie villagers, and vanilla zombie villagers won't turn into glitched mca villagers when you heal them. Maybe a similar spawn tweak for mca villagers and villages versus normal vanilla villagers and villages

**Describe alternatives you've considered**
I already tried to disable mca zombie villagers overwriting vanilla zombie villagers, but when I healed them, the vanilla zombie villager turned into a glitched mca villager with a glitched texture and bugged dialogue. I would try to write it myself but I'm only a modpack maker, not a mod developer haha

**Additional context**
The ability to do iron farms and villager farms for trading is being missed, id like a natural way to get normal zombie villagers and villagers without having to spawn them in manually, Thank you so much!

**Comment by Luke100000** [comment]
I added `fractionOfVanillaZombies`, which is what you need I think. For villagers, use `fractionOfVanillaVillages` as replacing entire villages is more immersive than a mix.
