### ISSUE TITLE
java.lang.NullPointerException: Cannot read field "" because "e" is null & field_6002

### ISSUE THREAD

**Issue by RealxRancor** [Luke100000/minecraft-comes-alive#601]
https://pastebin.com/aLQWGY8k

**Comment by RealxRancor** [comment]
newst release of mca

**Comment by Luke100000** [comment]
How did that happen XD Does this happen frequently?

**Comment by RealxRancor** [comment]
> How did that happen XD Does this happen frequently?

all the time..

**Comment by Luke100000** [comment]
[minecraft-comes-alive-7.5.0-beta.0.2+20230226T214358Z-fabric.zip](https://github.com/Luke100000/minecraft-comes-alive/files/10834797/minecraft-comes-alive-7.5.0-beta.0.2%2B20230226T214358Z-fabric.zip)
In this zip is a dev build for fabric 1.19.2, can you try if that one works please?

**Comment by RealxRancor** [comment]
on my way

**Comment by RealxRancor** [comment]
https://pastebin.com/dl/QGN1Cvf0

cant even create a new world

**Comment by Luke100000** [comment]
I mean that's not an mca crash anymore, looks like carpetfixes/wearblackallday doesn't like to live.

**Comment by RealxRancor** [comment]
oh my bad imma test it rn

**Comment by RealxRancor** [comment]
im sorry
