### ISSUE TITLE
bug with zombies

### ISSUE THREAD

**Issue by robtbs** [Luke100000/minecraft-comes-alive#602]
**Describe the bug**
im getting this error in the console

27.02 23:40:27 [Server] Server thread/WARN defineId called for: class forge.net.mca.entity.ZombieVillagerEntityMCA from class forge.net.mca.util.network.datasync.CDataParameter
27.02 23:40:27 [Server] Server thread/WARN defineId called for: class forge.net.mca.entity.ZombieVillagerEntityMCA from class forge.net.mca.util.network.datasync.CDataParameter
27.02 23:40:27 [Server] Server thread/WARN defineId called for: class forge.net.mca.entity.ZombieVillagerEntityMCA from class forge.net.mca.util.network.datasync.CDataParameter
27.02 23:40:27 [Server] Server thread/WARN defineId called for: class forge.net.mca.entity.ZombieVillagerEntityMCA from class forge.net.mca.util.network.datasync.CDataParameter
27.02 23:40:27 [Server] Server thread/WARN defineId called for: class forge.net.mca.entity.ZombieVillagerEntityMCA from class forge.net.mca.util.network.datasync.CDataParameter
27.02 23:40:27 [Server] Server thread/WARN defineId called for: class forge.net.mca.entity.ZombieVillagerEntityMCA from class forge.net.mca.util.network.datasync.CDataParameter
27.02 23:40:27 [Server] Server thread/WARN defineId called for: class forge.net.mca.entity.ZombieVillagerEntityMCA from class forge.net.mca.util.network.datasync.CDataParameter
27.02 23:40:27 [Server] Server thread/WARN defineId called for: class forge.net.mca.entity.ZombieVillagerEntityMCA from class forge.net.mca.util.network.datasync.CDataParameter

**To Reproduce**
This happen just when i start the server

**Screenshots**

**Version**
minecraft-comes-alive-7.3.23+1.16.5-universal.jar , 1.16.5, forge-1.16.5-36.2.39

**Latest.log**
https://paste.gg/p/anonymous/7f1b8e78b3684f9ea770c08399796d3a

**Comment by Luke100000** [comment]
Those a warnings, not errors. It's just Minecraft being confused :)
