### ISSUE TITLE
Player Genetics Fail

### ISSUE THREAD

**Issue by VeriaArt** [Luke100000/minecraft-comes-alive#603]
When starting the game, I created my own representation of what I'd like to be (ex. 1). Unfortunately, it switched to something random (ex. 2). I'm just trying to figure out why and how to fix it. I went through all the steps of creating my player genetics and clicked done afterwards and it still randomized my genetics.

Ex. 1
![image](https://user-images.githubusercontent.com/126529919/221720105-6de65d91-7567-4fc8-97b2-df21c3ed3743.png)
Ex. 2
![image](https://user-images.githubusercontent.com/126529919/221720184-954172c4-54be-44f2-8d66-65d6d250d4dc.png)

**Comment by Luke100000** [comment]
Version, modloader, server type please

**Comment by Luke100000** [comment]
Wait, that's a 1.19.3 default skin, did you select "player"?

**Comment by VeriaArt** [comment]
Yes I did! It's 1.19.3 with Forge. I was in a single player world??

**Comment by Luke100000** [comment]
Player uses the player skin, if you want the villager skin, keep villager selected :) you can change that later using "/MCA editor"
