### ISSUE TITLE
Villagers don't use Handcrafted's fancy beds

### ISSUE THREAD

**Issue by TheSnugget** [Luke100000/minecraft-comes-alive#605]
**Describe the bug**
Villagers do not recognize Handcrafted fancy beds as beds, and do not use them.

**To Reproduce**
1. Find a village
2. Replace beds with Handcrafted fancy beds
3. Wait until night
4. Watch the villagers not sleep, I guess

**Version**
7.4.7 1.19.2 Fabric

**Comment by Luke100000** [comment]
Do vanilla villagers sleep?

**Comment by Luke100000** [comment]
Merged with #655
