### ISSUE TITLE
Beds not being read

### ISSUE THREAD

**Issue by whosmaelo** [Luke100000/minecraft-comes-alive#606]
Every time i try to make a building like an inn or big house the beds are not registered, I'm sure it's not the bed I'm using because I am using the vanilla beds, but I am wondering I missed an attachment or something.

**Comment by Luke100000** [comment]
https://github.com/Luke100000/minecraft-comes-alive/blob/1.18.2/.github/ISSUE_TEMPLATE/bug_report.md

**Comment by whosmaelo** [comment]
i will inform you when my minecraft chooses to start working again, sorry for this inconvenience

**Comment by whosmaelo** [comment]
sorry for the waste of time, i figured out why it didn’t work, it was because i use doors which made the mod think it was a separate building. ty.
