### ISSUE TITLE
Can't Create a World

### ISSUE THREAD

**Issue by PixelYalak** [Luke100000/minecraft-comes-alive#61]
When i tried to create a world It says "Errors in currently selected datapacks prevented the world from loading. You can either try to load it with only vanilla data pack ("safe mode"), or go back to the title screen and fix it manually.
![Adsız](https://user-images.githubusercontent.com/98321816/150779891-d375ab3e-ef02-4196-a3d9-f29b73a4a981.png)

**Comment by Luke100000** [comment]
append the log please

**Comment by shyzeq** [comment]
same problem

**Comment by Luke100000** [comment]
> same problem

What language has your windows and please append the log

**Comment by shyzeq** [comment]
> > same problem
> 
> What language has your windows and please append the log

[2022-01-29-1.log](https://github.com/Luke100000/minecraft-comes-alive/files/7963893/2022-01-29-1.log)
My Windows Language is Turkish.

**Comment by Luke100000** [comment]
Thank you very much, issue will be resolved in 7.0.7
