### ISSUE TITLE
Not a Bug Really - A villager accidentally got killed.

### ISSUE THREAD

**Issue by tevrenos** [Luke100000/minecraft-comes-alive#610]
I use an OP armor and an archer villager shot me and got killed.

Now I'm down -500 in relationships.

is there a quick way to regain 500 or a command to use for this case? (Blocks of emeralds don't work :P)

**Comment by Luke100000** [comment]
The villager editor

**Comment by tevrenos** [comment]
Thank you.. and also thank you very much for the great mod.
