### ISSUE TITLE
IllegalStateException: Accessing LegacyRandomSource from multiple threads

### ISSUE THREAD

**Issue by ereese99** [Luke100000/minecraft-comes-alive#612]
**Describe the bug**
Upon exploring new chunks, server crashes.

**To Reproduce**
Explore a little faster than normal, eventually this is bound to happen.
[crash-2023-03-15_06.53.10-server.txt](https://github.com/Luke100000/minecraft-comes-alive/files/10980156/crash-2023-03-15_06.53.10-server.txt)

**Version**
MCA 7.4.7, Minecraft 1.19.2, Fabric 0.14.17

**Comment by Luke100000** [comment]
I suspect another mod here, the crash in mention is caused by `tickMovement`, which is vanilla.

https://bugs.mojang.com/browse/MC-249933
Especially that report looks familiar: https://bugs.mojang.com/secure/attachment/477828/crash-2022-04-08_04.51.21-server.txt
