### ISSUE TITLE
[Fabric 1.19.2] Server timeout Crash

### ISSUE THREAD

**Issue by DPZSoul1** [Luke100000/minecraft-comes-alive#616]
Okay, I'm trying to make a modded Minecraft server using Fabric. Every time I connect to the server, it gets stuck on the "Minecraft Reborn" page and eventually times out without loading the page. I've tried again multiple times, but it still doesn't work. However, it works fine in single player. How can I fix this?

**Comment by Luke100000** [comment]
I need logs, but I think it already got reported by any of those 30 timeout reports ^^
