### ISSUE TITLE
[Fabric 1.19.2] Zombies look like player

### ISSUE THREAD

**Issue by EnterUsernameHereNow** [Luke100000/minecraft-comes-alive#618]
So i'm not sure if this is an easter egg or a bug
but for some reason all the zombies... look like me?
It wasn't like this at first it just happened and never stopped.

I've tried getting turning off all texture packs
I've also restarted mc, but more zombies (that look like me) keep spawning

**Version**
Fabric 1.19.2, 7.3.21

**Comment by Luke100000** [comment]
Definitely not MCA related, Zombies remain untouched

**Comment by EnterUsernameHereNow** [comment]
Ah i see, my bad I assumed it was MCA reborn because it has custom villager zombies, my apologies
