### ISSUE TITLE
Error in data pack

### ISSUE THREAD

**Issue by Taoscar** [Luke100000/minecraft-comes-alive#62]
![safemode](https://user-images.githubusercontent.com/98332875/150817709-d6bc31d5-007e-42fc-a350-3ed002092817.png)
[tlauncher_01_24_2022_14_27_52.log](https://github.com/Luke100000/minecraft-comes-alive/files/7926909/tlauncher_01_24_2022_14_27_52.log)

**Comment by PixelYalak** [comment]
I have same problem too. I installed only MCA. :/

**Comment by Luke100000** [comment]
please always append the log

**Comment by Taoscar** [comment]
tlauncher_01_24_2022_14_27_52.log

**Comment by Taoscar** [comment]
[tlauncher_01_24_2022_14_27_52.log](https://github.com/Luke100000/minecraft-comes-alive/files/7928589/tlauncher_01_24_2022_14_27_52.log)

**Comment by Taoscar** [comment]
> please always append the log
[tlauncher_01_24_2022_14_27_52.log](https://github.com/Luke100000/minecraft-comes-alive/files/7946072/tlauncher_01_24_2022_14_27_52.log)

**Comment by Luke100000** [comment]
> > please always append the log
> > [tlauncher_01_24_2022_14_27_52.log](https://github.com/Luke100000/minecraft-comes-alive/files/7946072/tlauncher_01_24_2022_14_27_52.log)

Thank you! You found an interesting error

**Comment by Luke100000** [comment]
> I have same problem too. I installed only MCA. :/

Please also append the log in case it's not the same error :)

**Comment by Taoscar** [comment]
> > > please always append the log
> > > [tlauncher_01_24_2022_14_27_52.log](https://github.com/Luke100000/minecraft-comes-alive/files/7946072/tlauncher_01_24_2022_14_27_52.log)
> 
> Thank you! You found an interesting error

you're welcome, thank you to for care about it.

**Comment by Luke100000** [comment]
> > > > please always append the log
> > > > [tlauncher_01_24_2022_14_27_52.log](https://github.com/Luke100000/minecraft-comes-alive/files/7946072/tlauncher_01_24_2022_14_27_52.log)
> > 
> > 
> > Thank you! You found an interesting error
> 
> you're welcome, thank you to for care about it.

Ok think I tracked down the error, it will be fixed in 7.0.7. Just so I can make sure it's definitely the cause, what is your system language (the language windows uses)?

**Comment by Taoscar** [comment]
> > > > > please always append the log
> > > > > [tlauncher_01_24_2022_14_27_52.log](https://github.com/Luke100000/minecraft-comes-alive/files/7946072/tlauncher_01_24_2022_14_27_52.log)
> > > 
> > > 
> > > Thank you! You found an interesting error
> > 
> > 
> > you're welcome, thank you to for care about it.
> 
> Ok think I tracked down the error, it will be fixed in 7.0.7. Just so I can make sure it's definitely the cause, what is your system language (the language windows uses)?

My windows language is Turkish
