### ISSUE TITLE
I can't reach the rank of king (edit)

### ISSUE THREAD

**Issue by ghost** [Luke100000/minecraft-comes-alive#623]
I'm sorry for making another post but they closed the previous one and I couldn't reply.
I was wrong to explain.
When trying to do the Blacksmith, for some reason it doesn't count on the map and it doesn't mark it as complete even putting everything necessary, and it doesn't mark it on the list either. I know I still need more hearts, but shouldn't the blacksmith mark it anyway?
![Captura de pantalla (8090)](https://user-images.githubusercontent.com/93065025/227930961-f89acbf4-50c1-48e5-9120-7f7213b68566.png)
![Captura de pantalla (8091)](https://user-images.githubusercontent.com/93065025/227930968-cbdb9f14-bbde-40ab-89e1-3c982d4838a4.png)
![Captura de pantalla (8092)](https://user-images.githubusercontent.com/93065025/227930974-8e9ce098-08ff-459d-82ed-659c03474df1.png)
![Captura de pantalla (8093)](https://user-images.githubusercontent.com/93065025/227930979-fb8d41d4-69db-4750-9cd6-e7d1c715e6f8.png)

**Comment by Luke100000** [comment]
2x blast furnace

**Comment by ghost** [comment]
Ohhhhhh

**Comment by ghost** [comment]
Ohhhhhh
