### ISSUE TITLE
Villagers not detecting beds past Y=200

### ISSUE THREAD

**Issue by Azu124** [Luke100000/minecraft-comes-alive#624]
**Describe the bug**
Villagers stop detecting beds using the 1.18+ building height limit, tested it on the release 7.4.7

**To Reproduce**
1. Create any kind of world
2. Go over the old height limit (I tested it on Y= 244 specifically) and place a suitable villager house on there.
3. Spawn a Villager and try to assign them a bed there

**Version**
MCA 7.4.7 & _MCA 7.4.8_, Minecraft 1.19.2, Forge

Edit: Tested on the most recent MCA version too just in case.

**Comment by Luke100000** [comment]
Can't confirm, 1.19.2 Fabric villagers will both naturally select beds as well as use the nearest one at set home.
