### ISSUE TITLE
Spawning thousands of explorers in unloaded tavern?

### ISSUE THREAD

**Issue by mcjojo3** [Luke100000/minecraft-comes-alive#626]
**Describe the bug**
Soo I returned to a server I hadn't been on for quite some time and there are thousands of explorers everywhere filling the tavern to the brim crashing my client. They seem to slowly despawn if you stay there for long enough.

**To Reproduce**
1. Create a Tavern in a Town
2. Leave for a few months
3. And return to this?
As I'm not 100% sure why this happens I don't know how to fully reproduce this issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/38841486/229585049-c1309e99-e193-4a3a-864c-1d0ef1aa27fa.png)

**Version**
Started at 7.3.21 and updated to 7.4.8 during the issue, Java 1.18.2, Forge 40.2.1

**Latest.log**
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/11140964/latest.log)

**Comment by mcjojo3** [comment]
It would be nice to have a command that despawns all travelers

**Comment by Luke100000** [comment]
I still wasn't able to reconstruct this myself. Do you mind sending me the server world?

**Comment by mcjojo3** [comment]
Sadly they've all despawned now. And as the issue is pretty hard to reproduce I'm not sure how to tackle this. As it seems to be a pretty rare issue as it only seems to happen once I've been inactive for some time. I could see if it will happen again after updating but one thing that could be a temporary fix could be adding a command that despawns all adventurers which would fix it if it were to happen again.

**Comment by Luke100000** [comment]
I assume it will happen again, that's why I would like the map. My test maps don't spawn villagers when deloaded. My suspect is the spawn area but people deconfirmed that.

**Comment by mcjojo3** [comment]
The worldfile is pretty big but I'll see if I'm able to send it

**Comment by mcjojo3** [comment]
Hmm the world is too big to be uploaded I think as it won't allow me to but yeah it's definitely outside of the spawn area. As it's hard to reproduce I'll see if I can get it to happen on another world too if it could be something related to the modpack perhaps?

**Comment by Luke100000** [comment]
Merged with #842
