### ISSUE TITLE
My minecraft looks all white and black.

### ISSUE THREAD

**Issue by Blu3B3rri** [Luke100000/minecraft-comes-alive#627]
This only happens with minecraft come's alive mod active .I tried to play without shaders and without texture packs and nothing works ,for some reason the problem only appears on default worlds and not on extraplain. Thanks in advantaje

![imagen_2023-04-03_210613235](https://user-images.githubusercontent.com/129790489/229603213-9e14f75d-2546-447b-951e-3919b4c42291.png)
**Describe the bug**

**To Reproduce**

**Screenshots**

**Version**
MCA Version, Minecraft version, Modloader
![2023-04-03_21 07 08](https://user-images.githubusercontent.com/129790489/229603733-d44fb911-a830-4baa-a009-0bd03e6f5ba0.png)

**Latest.log**
![2023-04-03_21 08 00](https://user-images.githubusercontent.com/129790489/229603711-daab9373-1f36-4964-b09d-5f3abf189a48.png)

Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.

**Comment by Luke100000** [comment]
You are colorblind, choose your traits more carefully ^^
When you are an opyou can change that using `/mca editor`

**Comment by Blu3B3rri** [comment]
Omg I didn't think about it ,I choose colourblind because in real life I am
colourblind ,but I can see colors XD (my type of colorblindess makes me not
able to see many shades of colours ,but still see them).
Thank you so much I feel so stupid hahshsj
