### ISSUE TITLE
Request: Config option to disable MCA villagers to spawn golems

### ISSUE THREAD

**Issue by pantsguyapp** [Luke100000/minecraft-comes-alive#628]
I am not a fan of golem spawning in villages, since they will destroy you once you hit them even without evil intents, so may I ask for a config to have golems to only be spawned by vanilla villagers.

**Comment by Luke100000** [comment]
Golem spawning is vanilla and thus I declare it as out of scope. Any mod changing golem spawn behavior should be compatible.
