### ISSUE TITLE
The conflict before the mod crashes

### ISSUE THREAD

**Issue by yuankun1** [Luke100000/minecraft-comes-alive#629]
I added crafting dead immerse-1.16.5-10.11-alpha when they crashed halfway

[crash-2023-04-10_21.27.24-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/11190756/crash-2023-04-10_21.27.24-client.txt)

**Comment by Luke100000** [comment]
It looks like it render the player in the loading or main screen, is this correct?

**Comment by yuankun1** [comment]
> It looks like it render the player in the loading or main screen, is this correct?

Just putting crafting-dead-immerse-1.16.5-1.0.11-alpha and doing minecraft-comes-alive-7.3.23+1.16.5-universal together will cause me to crash at the end of the boot
Removing crafting-dead-immerse-1.16.5-1.0.11-alpha does not cause a crash when startup is complete
