### ISSUE TITLE
Incompatibility with No Hostiles Around Campfire

### ISSUE THREAD

**Issue by SimplyTadpole** [Luke100000/minecraft-comes-alive#639]
**Describe the bug**
Using this mod alongside No Hostiles Around Campfire creates a crash. Removing either of those and nothing else fixes the crash.

**To Reproduce**

1. Install MCA Reborn and No Hostiles Around Campfire
2. Attempt to load Minecraft

**Screenshots**
Screenshots not really applicable.

**Version**
• MCA Version: 7.4.8
• Minecraft version: 1.19.2
• Modloader: Quilt

**Latest.log**
https://mclo.gs/fLstVxJ

**Comment by Luke100000** [comment]
```
Critical injection failure: LVT in net/minecraft/class_634::method_11112(Lnet/minecraft/class_2604;)V has incompatible changes at opcode 62 in callback #charm:charm.mixins.json:event.ClientSpawnEntityMixin from mod charm->@Inject::hookOnEntitySpawn(Lnet/minecraft/class_2604;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;Lnet/minecraft/class_1299;)V.
--
869 | Expected: [Lnet/minecraft/class_1299;]
870 | Found: []
871 | Available: []
```

It's a passive error, Charm crashes, but I can't spot an error on either side.

https://github.com/svenhjol/Charm/blob/2c73cf726dd5d33bf01b7241418304666465de21/src/main/java/svenhjol/charm/mixin/event/ClientSpawnEntityMixin.java

https://github.com/Luke100000/minecraft-comes-alive/blob/1.19.2/quilt/src/main/java/net/mca/quilt/cobalt/network/NetworkHandlerImpl.java#L50
