### ISSUE TITLE
[Suggestion] [1.18.2] Limited Player Setup

### ISSUE THREAD

**Issue by slave2midna** [Luke100000/minecraft-comes-alive#645]
Something I'd love to see, is a bit more control over the Destiny screen during initial setup. The limited player setup option doesn't appear to actually limit the player at all - and even with turning many other options to false-there is still a lot of availability to customize.

In this case, I'd like to see the option to limit player customization to simply non-visual traits like:
- Name
- Masculine | Femine
- Non-Visual Traits

In the instance where I use MCA, I've had to turn off Destiny entirely because the model and customizations conflicts with other mods - and therefore even if players change skin, eyes, hair, clothes, and size - it is not reflected in their gameplay. However, we'd still love for players to be able to change their Name, set their gender settings, and possibly even set traits to inherit of further customize the game. **However, we'd be happy with just simply name and gender if traits was too much.**

Ideally, just a means of limiting more options for character creation would prevent the need for us to turn it off entirely due to conflicts with the model and other mods - we have methods of players changing skin on the fly so most visual change comes from that.

Also would like to see a feature like this back ported to 1.18.2 - simply due to not being able to play the latest version at the current moment.

**Comment by Luke100000** [comment]
Since the model conflicts anyways, it sounds like you want `enableVillagerPlayerModel` set to false.

**Comment by slave2midna** [comment]
The model conflict in this case only applies to players, and doesn't apply to villagers. When a new player joins a world with Destiny - they can create their appearance using skins, hairs, eyes etc. However, after spending time adjusting these setting and then joining the world - none of those customizations show up on their character other than Name/Gender and non-visual traits.  

This is not a problem with MCA I feel, as this is in relation to an entirely different issue with an entirely different mod that isn't a huge deal to fix. Since Villagers aren't affected by it, simply turning off destiny preserves the functionality of villagers with the vanilla player and things are fine-because the conflict is only affecting players when using destiny to tailor their own character.

Would turning **enableVillagerPlayerModel** to **false** while still using Destiny keep MCA villagers the way they were intended? I don't want to change how villagers work - just allow players to get the benefit of 'gender' and 'names' for the purpose of them interacting with villagers.

**Comment by slave2midna** [comment]
Deleted my original response, because I hadn't really understood it. But as it stands - we do actually have `enableVillagerPlayerModel` set to `false`. Below is a list of the settings we are currently using in an attempt to limit player customization.

`"launchIntoDestiny": true,`
  `"allowDestinyCommandOnce": false,`
  `"allowDestinyCommandMoreThanOnce": false,`
  `"allowDestinyTeleportation": false,`
  `"enablePlayerShaders": true,`
  `"enableVillagerPlayerModel": false,`
  `"forceVillagerPlayerModel": false,`
  `"allowLimitedPlayerEditor": true,`
  `"allowFullPlayerEditor": false,`
  `"allowPlayerSizeAdjustment": false,`
  `"useModernUSANamesOnly": false,`

This problem currently is that we don't want players to see [THIS](https://i.imgur.com/QACe6VV.png) screen.

What we would prefer to happen, is that when a player joins in - they only see [THIS](https://i.imgur.com/xLslkuD.png) screen. Which doesn't seem to be an option in the current configuration setup.

**Comment by Luke100000** [comment]
Ohhh I see. Why tho? The genes will become relevant when they have offspring and other than that won't affect anything

**Comment by slave2midna** [comment]
Don't get me wrong, I'd LOVE to include traits as well - I just felt like it would be easier to implement an option to remove the second screen for this suggestion. But hey! It it's possible to just disable skin/model customization and keep traits, I'd be all for that as well! I was just wanting to make my suggestion reasonable.

**Comment by Luke100000** [comment]
I'm still not sure about the actual issue. Of course I can hide that options, and filter traits. But why do they bother? And is it fine that your offspring will be randomized instead? I'm especially unsure what traits you plan on keeping, since they are barely implemented player sided yet.

**Comment by slave2midna** [comment]
I'm so sorry, I promise I am not trying to make it complicated at all. The suggestion aims simply to help with compatibility. It's merely a suggestion, and would be a nice feature - but it's not an actual issue. I'm sorry if I'm not explaining it correctly. 

THE PROBLEM
When a player joins our server/world for the first time with the above settings, that player is asked to set the following:
- Name
- Gender
- Face
- Hair
- Skin
- Clothes
- Breasts
- Size
- Traits

This is cool! And I love it - However, **_due to a compatibility issue with an existing mod we use_** that modifies player models, **Face, Skin, Hair, Clothes, Size, and Breasts** - do NOT show up. No matter what options the player chooses, it will reset back to their default skin.

Therefore, on our server/world - we simply disable destiny, and just let the player spawn is as their vanilla skin/model. This is simply because we don't want to remove the mod that changes the player model, and we respect that it's not an issue with MCA itself,

THE SUGGESTION
this suggestion is simply to have the option of removing *Face, Skin, Hair, Clothes, Size, and Breasts** from destiny, so that when a new player joins our server/world they are only prompted for their Name, and Gender. Traits can be randomized still, or set, I don't mind either. This would just avoid them getting excited about customizing their character's face, skin, hair, eyes etc. - only to spawn into the world with their default skin and model and being sad because they can't use the MCA customization options.

We can simply continue to just not use destiny, I just thought it would be cool to still give players a name and gender for roleplay purposes and still use the mod that is overriding MCA's model. But turning off Destiny entirely allows us to use both mods without any conflicts. We just don't get name, gender, or trait customization when we do this.

**Comment by Luke100000** [comment]
Ok now I get it, I think ^^ Sure, I can do that. I won't filter traits for now, you can either disable or enable that page.

**Comment by slave2midna** [comment]
WONDERFUL! Totally ok! Looking forward to that update. Thank you for the patience!

**Comment by Luke100000** [comment]
`allowBodyCustomizationInDestiny`, `allowTraitCustomizationInDestiny` do the trick now

**Comment by slave2midna** [comment]
Oh wow! Nice! Thank you! Will this be coming in the next 1.18.2 update?

**Comment by Luke100000** [comment]
Unlikely, 1.18.2 has been retired. Maybe if I have too much time :)

**Comment by slave2midna** [comment]
Daaang. _Well, here's to hoping it might slip in some day!_ - sadly our pack/server can't move to 1.19 just yet. But I'm sure SOMEDAY we'll make the change - when more things update. I look forward to the new option if and when our server and playerbase gets to see it!
