### ISSUE TITLE
[Suggestion(s)]: Curios Compatibility/MCA Cosmetics

### ISSUE THREAD

**Issue by BedMan333** [Luke100000/minecraft-comes-alive#647]
Hi! My request is based on my need to put cosmetic and helping curios to the mca villagers. May it for roleplay, or for other mods needs, I beg for this to be added.

I do not know how it may be possible. I just have the idea of putting the curios item in their inventory, or gifting it to the villager directly.

Another way to resolve this problem is by creating cosmetics especially for the mca villagers, that helps to give them extra depth to the villagers, in the same fashion of coloring their hair, or changing their clothing (good work on that, btw! It feels so natural!).

All this maybe is a bit stupid, I know. But I know a lot of people who wants to create immersive multi-raced (elves, orcs, demons, angels, beastfolk, etc) fantasy worlds, with Mca in the middle of all, and having to rely in other mods to provide for the cosmetics for ears, tails and other miscelaneous stuff met with the obligation to use curios cosmetics to achieve it.

Please, would you like to consider one of my two suggestions? Thanks for your efforts and time! You are awesome!!!

**Comment by Luke100000** [comment]
Merged with #446
