### ISSUE TITLE
hi i would like to report a bug when i play the mod the face's of the villgers are invisible how can i fix it ?

### ISSUE THREAD

**Issue by dark-demon619** [Luke100000/minecraft-comes-alive#651]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Version**
MCA Version, Minecraft version, Modloader

**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.

**Comment by dark-demon619** [comment]
![2023-05-11_23 03 50](https://github.com/Luke100000/minecraft-comes-alive/assets/81345067/8e931870-0119-4938-93b4-a02079e42f9a)

**Comment by dark-demon619** [comment]
and sometimes even the hands are invisible

**Comment by Luke100000** [comment]
The point of a template is that you fill in the required information
