### ISSUE TITLE
MC 1.19.2 Fabric 0.14.19 - Crash on Picking Destiny 

### ISSUE THREAD

**Issue by Cal-Is-Burning** [Luke100000/minecraft-comes-alive#656]
On creating a new world using MCA Reborn 7.5.0-rc.3 and Numismatic Overhaul and loading the destiny screen, the game crashes upon clicking any option button.

Removing Numismatic Overhaul resolves the issue, however the two mods go well together and it would be nice to see this issue fixed :)

**Comment by Luke100000** [comment]
https://github.com/wisp-forest/numismatic-overhaul/issues/78
