### ISSUE TITLE
The villagers' material has a purple black error on the server, or it is a white child

### ISSUE THREAD

**Issue by Mangopill** [Luke100000/minecraft-comes-alive#658]
Describe the bug
The villagers' materials on the server are all purple and black lost materials, sometimes white colored children
Version
minecraft-comes-alive-7.4.8+1.18.2-universal forge40.2.1
Logs

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/11473442/latest.log)

[debug.log](https://github.com/Luke100000/minecraft-comes-alive/files/11473446/debug.log)
![2023-05-15_08 59 11](https://github.com/Luke100000/minecraft-comes-alive/assets/132248671/3a99723f-0be7-4bc7-a09d-c824bf4a7e83)
![2023-05-15_08 22 53](https://github.com/Luke100000/minecraft-comes-alive/assets/132248671/aa0bbc01-f9ed-4b8f-a277-e5796a018159)
![2023-05-15_08 25 58](https://github.com/Luke100000/minecraft-comes-alive/assets/132248671/1760df32-694a-4532-bd47-4922873f9368)
At the same time, the wild cats also have this problem

**Comment by Luke100000** [comment]
Looks like your shaders crashed, try without to confirm
