### ISSUE TITLE
more clothes and translation

### ISSUE THREAD

**Issue by Thecobrax052** [Luke100000/minecraft-comes-alive#659]
**Describe the bug**
More clothes

*We can no longer choose more clothes? In the online library it only allows you to have one tab? I want to add more clothes, but when I edit the file and add the skins for clothes they do not appear, in fact only a certain number of clothes from the many of the mod don't come out either.

**Version**
7.5.0

By the way, I just made the translation a bit bad, but understandable into Mexican Spanish, I did the best, since my English is not that good, but I would like it to be included in future updates, it's on the page where the translated mod files

**Comment by Luke100000** [comment]
What file do you edit? What is the tab you mentioned? Does a screenshot help here?
