### ISSUE TITLE
villagers don't wear hats from hats mod

### ISSUE THREAD

**Issue by JetpackRescue** [Luke100000/minecraft-comes-alive#66]
However your rendering your villager entities or putting them into the game, is unlike every other mod. Hats mod puts hats on all entities, except mca villagers. I think you should change how you're rendering them so they're grabbed by other mods that adjust or alter entities, otherwise it's not very compatible.

**Comment by Luke100000** [comment]
Link the repo of your mod and I will see why it doesn't work. We are not doing any special stuff regarding rendering, so it sounds more like an incompatibility from the hats mod tbh.

**Comment by JetpackRescue** [comment]
https://www.curseforge.com/minecraft/mc-mods/hats

https://github.com/iChun/Hats

it's not my mod, i'm trying to use mca and hats in a modpack i've been working on.

**Comment by Luke100000** [comment]
Thanks, I checked the source code, both mods should be perfectly compatible. I'll investigate this further once I have time.

**Comment by Luke100000** [comment]
Sadly I was not able to find the issue and do not have more time. Since it only affects the villager and we are currently finishing 1.16.5 I'll close this issue and we'll see if 1.18 fixes it.
