### ISSUE TITLE
skin library report

### ISSUE THREAD

**Issue by guyfingerguy** [Luke100000/minecraft-comes-alive#664]
i think it would be a good idea to have a report feature for the skin library, as it's existed for what, two weeks now? and there's already a hitler skin uploaded. people are gonna upload more and more awful skins, and right now there's nothing anyone can do about it. that's all

**Comment by Luke100000** [comment]
Sounds like it's time to gather some moderators, thanks for the report.

**Comment by Bipbip2109** [comment]
Oh no, I'm playing videogames and I just saw a HITLER SKIN online, so traumatizing
