### ISSUE TITLE
Custom player models optional

### ISSUE THREAD

**Issue by festro** [Luke100000/minecraft-comes-alive#668]
**Is your feature request related to a problem? Please describe.**
Not necessarily just a peeve when starting a new world as having to fine tune the models to resemble my default skin takes a lot of time.

**Describe the solution you'd like**
Would like MCA to default to Minecraft player skin and add an item\command to customize or change appearance\traits if the player so chooses.

**Describe alternatives you've considered**
I'm not sure of any workarounds.

**Additional context**
This isn't a deal breaker for me, this mod just add too much value to the game to be so petty, it's just something that takes up time when starting a new game and would just like to suggest a solution.

**Comment by Luke100000** [comment]
There are many flags to customize that, keywords are destiny and editor: https://github.com/Luke100000/minecraft-comes-alive/wiki/Config

**Comment by festro** [comment]
Ok, thanks for the clarification.
