### ISSUE TITLE
Wont allow gifting

### ISSUE THREAD

**Issue by JessikaTyler** [Luke100000/minecraft-comes-alive#670]
It will not allow me to gift at all. I tried to see if it was a part of the update but i am assuming not since i can not find anything on it. 

**Screenshots**
I dont know how to ss but in there is no option to gift, only to talk. 
**Version**
MCA Version, Minecraft version, Modloader
1.19.4
**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.

**Comment by Luke100000** [comment]
Press interact, and send me a screenshot of the screen.
