### ISSUE TITLE
Need help with custom skins in Aternos server.

### ISSUE THREAD

**Issue by gaelealm** [Luke100000/minecraft-comes-alive#672]
I´m having an issue with custom skins in my Aternos server.

I deleted all the folders in the clothing folder for male, female and neutral, leaving only "guard" as it is where I added all the custom skins.

When I try to change skins in a regular world, I have no problems at all, I can change a villager´s skin to the one I want. The problem is when I try to do this in an Aternos server, I can only use like 6 skins of the 30-40 I added, this happens with both male and female villagers, and I can´t understand why. 

I would appreciate any help with this, thanks in advance!

**Comment by Luke100000** [comment]
Did you apply the datapack to the server world?
