### ISSUE TITLE
IT DOESN'T WORK.

### ISSUE THREAD

**Issue by bbbb3** [Luke100000/minecraft-comes-alive#676]
**Describe the bug**

Since 1sth of june,I have tried to make the mod work. Now that the new version arrived, 1.20 i have updated everything & downloaded the latest version of the mod, And all the files that are attached. It still doesnt work. When the game launches theres a note that says the game has failed to load, so i really dont know what to do. Now that 1.20 is here, i have download forge & optifine im still exited exited to play the game although it crashes. Any type of help will be appreciated. 
Best regards.

Berta.

**To Reproduce**

**Screenshots**

**Version**
MCA Version, Minecraft version, Modloader

**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.

**Comment by Luke100000** [comment]
We don't support 1.20 yet, and neither do our dependencies so we can't port either

**Comment by bbbb3** [comment]
It dosen't work for me I get in and when i start a new world I get a The game crashed whilst unexpected error  Error: java.lang.NoSuchMethodError: 'boolean net.minecraftforge.client.extensions.common.IClientMobEffectExtensions.renderGuiIcon(net.minecraft.world.effect.MobEffectInstance, net.minecraft.client.gui.Gui, com.mojang.blaze3d.vertex.PoseStack, int, int, float, float)' I dont know why can someone  help me?

**Comment by Luke100000** [comment]
The template is not for decoration purposes, fill it out.
