### ISSUE TITLE
Grieving points update to graveyard when removed

### ISSUE THREAD

**Issue by Shibva** [Luke100000/minecraft-comes-alive#677]
I am not sure whether this is a feature that is not considered or is a bug

currently in the mod my villagers are grieving in spots where a grave no longer exists and becomes quite annoying. Why not they head to the graveyard to grieve?

(also a method to move graves into your graveyard without forgetting a soul would be a nice thing to have as well; only managed to move one with the create mod

(sorry if this is a bit lacking, not much to recommend and am drowzy af rn as im typing thing)

**Comment by Luke100000** [comment]
The Grieving spot IS the graveyard, however, graveyards with less than 3 tombstones are hidden from the map. I suspect that an empty graveyard remains somewhere...

**Comment by Shibva** [comment]
Well, the graves have been broken or relocates so idk why they are not breathing at the actual graveyard if the graveyard, they are no longer exists

According to the schematics system, there are no graveyards except for I constructed. Yet they're still grieving around the plaza where there were a bunch of graves initially, but are no longer there after I remove them/relocated them.

**Comment by Shibva** [comment]
I will know that some of them did die before the graveyard initially was constructed if that means anything

**Comment by Shibva** [comment]
might wanna put this under bug as well

**Comment by Shibva** [comment]
Is there a way that I can tell but there may be a Hidden grave spot?

Could you explain to me how it works so I can possibly try and fix it in my world because it seems like whatever is happening is not working properly or it's still thinking that it's there

**Comment by Shibva** [comment]
Also… I'm not sure if this is correlated with, but it seems like when I bring some entities back, but some of the family tree still recognize them as dead. Not sure if this is any correlation to the bug that I'm experiencing.


I'm also using quilt which should be using the fabric API

**Comment by Shibva** [comment]
I switch to the fabric instead of quilt, using the same world, and I think the issue may be still occurring.

Is there a way that I can remove all grieving points including the ones that might not show up? If so, please let me know; I'm willing to cooperate.

Also; do they also have the ability to grieve at town center?
