### ISSUE TITLE
Zombie Villager Crashes Server

### ISSUE THREAD

**Issue by BoyFromFlanders** [Luke100000/minecraft-comes-alive#678]
**After a certain amount of time the server will spam the same error like twenty times and will crash.**

**To Reproduce**
It occurs after a certain amount of time which does vary.

**Screenshots**
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/136155235/d93d070f-b79b-472e-a71f-3881603b09c2)

**Version**

MCA: 7.5.2
MC version 1.19.2
Curse Forge 43.2.14

**Latest.log**
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/11711860/latest.log)

**Comment by Luke100000** [comment]
This is not an error, just Minecraft having a stroke. The log doesn't mentioned a crash either, maybe the crash log has more luck here.

**Comment by BoyFromFlanders** [comment]
Yeah I thought so, the server has 6 gb of ram and an Intel Xeon E5-1630v3 @ 3.7Ghz / Intel i7-7700k @ 4.5GHz, and there is no crash log at all. Do you recommend more ram or a better cpu?

**Comment by Luke100000** [comment]
Without the error I can't recommend anything. If your dedicated server has 6 GB RAM assign no more than 3 GB to Minecraft. CPU is never good enough, this is Minecraft :(

**Comment by BoyFromFlanders** [comment]
Alright thanks mate, appreciated!
