### ISSUE TITLE
Conflict with Morph mod

### ISSUE THREAD

**Issue by Natedogwoooof** [Luke100000/minecraft-comes-alive#683]
**Describe the bug**
I don't know if this bug is on your guy's side or morphs side but I'll post it here too so basically one year zombie or any more in the mod called morph mod that has a custom hand it shows Minecraft Comes Alive reborn villager hand

**To Reproduce**
1. Go to install morph and Minecraft Comes Alive reborn on 1.16.5
2. Click the villager type on the destiny screen
3. Scroll down to the zombie morph or any morph that has hand over ride
4. The air is it will use the Minecraft Comes Alive villager hand aka the hand of whatever villager clothing you chose for your player character instead of the zombie hand or whatever other hand is for that morphs hand

**Screenshots**

**Version** Minecraft Comes Alive version is 7.3.35 and 1.16.5 the mod loader is Forge 36.2.39 and Tabula and morph and ichunuti are latest

**Latest.log** will add once I hop on my PC in a second sorry if this was on morph's side not yours IDK if you still update 1.16.5 if there are bugs

**Comment by Luke100000** [comment]
Any two mods with custom models will conflict, not sure how I could add compat specifically for morph.

**Comment by Natedogwoooof** [comment]
> Any two mods with custom models will conflict, not sure how I could add compat specifically for morph.

is there any way i can stop it from using the villager hand in the config and make it use the player hand without using the player skin sorry if I'm late.

**Comment by Luke100000** [comment]
In `playerRendererBlacklist` in the config, add `"morph", "arms",` to disable arm rendering when morph is installed

**Comment by Natedogwoooof** [comment]
> In `playerRendererBlacklist` in the config, add `"morph", "arms",` to disable arm rendering when morph is installed

and i dont think i formatted it correctkly and im getting this crash
[crash-2023-07-30_15.56.56-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/12210153/crash-2023-07-30_15.56.56-client.txt)

and this is what my config is im  sorry if this isnt what u ment
[mca.txt](https://github.com/Luke100000/minecraft-comes-alive/files/12210157/mca.txt)

**Comment by Natedogwoooof** [comment]
i had to copy and rename to .txt to upload
