### ISSUE TITLE
Teleport Lost Villagers

### ISSUE THREAD

**Issue by AnonymousWolfGirl** [Luke100000/minecraft-comes-alive#684]
I keep getting frustrated when I can't find any of my villagers. They just disappear and I can't find them anywhere. I think a good solution for this problem would be to either have an item like the whistle that can call your family but for the rest of the town, or be able to go into the blueprint and call a town meeting and have all villagers teleported to the town square.

**Comment by kristibektashi** [comment]
If the town hall meeting thing is implemented then you should be at least mayor in order to be able to use it

**Comment by Luke100000** [comment]
Notice that it is impossible to teleport unloaded villagers. And your lost villagers are in most cases deloaded. The villager tracker is the only way to track them, aside from scanning save files.
