### ISSUE TITLE
[Suggestion and bugfix] Bed-registry for players towards village population

### ISSUE THREAD

**Issue by Shibva** [Luke100000/minecraft-comes-alive#687]
**Is your feature request related to a problem? Please describe.**
Whenever I place a personal bed; I have an extra spot in my village for one more villager to be populated into the world. This is quite annoying at it leaves me with a bed that I don't have for my own

**Describe the solution you'd like**
A method to detect if the valid bed is set by a player and if it is to blacklist it towards the population count
OR
count any players whos bed is set in the village as their respawn point as part of the villages populations (considering the fact that it doesn't count players that live there)

**Describe alternatives you've considered**
Maybe a means for a custom bed that won't be registered as a bed to increase the village cap or maybe a means to prevent beds from contributing to the population unless the bed is a part of a valid building in the village

**Additional context**
I feel its well explained enough; though if more is needed feel free to ask

**Comment by Luke100000** [comment]
Merged with #687
