### ISSUE TITLE
Waystones don't spawn in villages

### ISSUE THREAD

**Issue by JetpackRescue** [Luke100000/minecraft-comes-alive#69]
https://www.curseforge.com/minecraft/mc-mods/waystones

Waystones mod adds teleportation waystones to villages, you can have it put waystones in some villages or force them into all villages. Could you implement compatibility with waystones mods?

**Comment by Luke100000** [comment]
Why should they use them? Villagers rn do not visit other villages.

**Comment by JahxSenpoopie** [comment]
lol nice. Anyways, we do not plan to have villages visit other villages like Luke said above. However, if you are trying to move villagers into other villages, you can always use the follow command and make sure to set their home in the new village using the set home command.

**Comment by Kasualix** [comment]
But players don't mean to let the villagers visit other villages, what player want is to obtain the waystone itself!

**Comment by Luke100000** [comment]
> But players don't mean to let the villagers visit other villages, what player want is to obtain the waystone itself!

That's not an mca issue anymore :)
