### ISSUE TITLE
it still doesnt work 

### ISSUE THREAD

**Issue by bbbb3** [Luke100000/minecraft-comes-alive#690]
**Describe the bug**
It dosen't work for me I get in and when i start a new world I get a The game crashed whilst unexpected error  Error: java.lang.NoSuchMethodError: 'boolean net.minecraftforge.client.extensions.common.IClientMobEffectExtensions.renderGuiIcon(net.minecraft.world.effect.MobEffectInstance, net.minecraft.client.gui.Gui, com.mojang.blaze3d.vertex.PoseStack, int, int, float, float)' I dont know why can someone  help me?

**Comment by Luke100000** [comment]
The template is still not for decoration purposes, fill it out.

**Comment by bbbb3** [comment]
let´s do that then. could you be so kind & explain how to fill out the template

**Comment by Luke100000** [comment]
Its the one you deleted when creating the issue. It tells you exactly what is required and where to find it. In #676 its still there, for reference.

**Comment by bbbb3** [comment]
Describe the bug

It dosen't work for me I get in and when i start a new world I get a The game crashed whilst unexpected error Error: java.lang.NoSuchMethodError: 'boolean net.minecraftforge.client.extensions.common.IClientMobEffectExtensions.renderGuiIcon(net.minecraft.world.effect.MobEffectInstance, net.minecraft.client.gui.Gui, com.mojang.blaze3d.vertex.PoseStack, int, int, float, float)' I dont know why can someone help me?

Berta.

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See error
Screenshots
If applicable, add screenshots to help explain your problem.

Version
MCA Version, Minecraft version, Modloader

Latest.log
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called latest.log. On Windows by default %appdata%/.minecraft/logs/latest.log.
