### ISSUE TITLE
Still doesn't work

### ISSUE THREAD

**Issue by bbbb3** [Luke100000/minecraft-comes-alive#691]
**Describe the bug**
It dosen't work for me I get in and when i start a new world I get a The game crashed whilst unexpected error Error: java.lang.NoSuchMethodError: 'boolean net.minecraftforge.client.extensions.common.IClientMobEffectExtensions.renderGuiIcon(net.minecraft.world.effect.MobEffectInstance, net.minecraft.client.gui.Gui, com.mojang.blaze3d.vertex.PoseStack, int, int, float, float)' I dont know why can someone help me?

**To Reproduce**

**Screenshots**

**Version**
MCA Version, Minecraft version, Modloader

**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.

**Comment by Luke100000** [comment]
If you send one more not filled-in template I will block you. And use edit, don't create new issues.
