### ISSUE TITLE
MCA Crashes with Aged Modpack

### ISSUE THREAD

**Issue by ZeroX15** [Luke100000/minecraft-comes-alive#693]
**Describe the bug**
Well, when i try to start with Aged Modpack, it crashes but don't shows the crash message.
https://modrinth.com/modpack/aged

**Version**
7.5.3*, 1.19.2, Fabric

**Comment by Luke100000** [comment]
Please also append the latest.log, it may help

**Comment by ZeroX15** [comment]
It was the Numismatic Overhaul/Claim mods causing the conflict

**Comment by Luke100000** [comment]
Here is the thread regarding Numismatic: #675
