### ISSUE TITLE
1.19.2 blur every time I install mca reborn

### ISSUE THREAD

**Issue by robohavier32** [Luke100000/minecraft-comes-alive#697]
When I join my world, it has a blur effect with pink saturation.

I don't know why this happens, so I don't know the steps to reproduce except for installing the mod.

**Screenshots**
https://github.com/Luke100000/minecraft-comes-alive/assets/136960980/8a92f0d1-c762-4120-b212-5a7644446445

**Version**

minecraft-comes-alive-7.5.3+1.19.2-universal.jar, (1.19.2) 43.2.14, forge

**Latest.log**
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/11894155/latest.log)

**Comment by Luke100000** [comment]
Watch your traits when you spawn, sadly, you are now a sirben ^^
`/mca editor` if you have cheats on.

**Comment by robohavier32** [comment]
thank you so much for responding so quickly!!!
