### ISSUE TITLE
no config option to turn off bones after breaking a headstone

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [Luke100000/minecraft-comes-alive#699]
**Describe the bug**
Lack of a config option to turn off bones dropping from headstones!!

**To Reproduce**

**Screenshots**

**Version**
MCA Version:, 7.5.3 + 1.19.4  Minecraft version: 1.19.4 Modloader: Forge 45.1.0

**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.
This is just too morbid for me. There needs to be an config with an option in the config to turn them off!

**Comment by Luke100000** [comment]
This appears to be oddly specific to me, why would there be a config for that? Notice that you find remains all over minecraft in various places.

**Comment by SonicTheHedgehog58987276** [comment]
villager bones from breaking a headstone are too morbid, but vanilla minecraft remains are different.

**Comment by SonicTheHedgehog58987276** [comment]
how about instead make the graves hold items?

**Comment by SonicTheHedgehog58987276** [comment]
I Also Have Another Issue https://github.com/Luke100000/minecraft-comes-alive/issues/698

**Comment by Luke100000** [comment]
Don't link unrelated issues :)
As with every block, the drops are specified in their lootables. The way to configure this is to overwrite the loot tables.
