### ISSUE TITLE
Villager fatigue bugged

### ISSUE THREAD

**Issue by JahxSenpoopie** [Luke100000/minecraft-comes-alive#70]
If you have 15% fatigue and go to another villager to speak with them they have the same fatigue, I just thought this was a visual bug and thought nothing of it, but I would get 20-25% fatigue on 1 villager then the next villager I would talk to would be a low chance successful.

Please fix or I'm calling corportate!11

**Comment by Luke100000** [comment]
Can't confirm, does it happen on a minimal example, e.g. 2 new fresh villagers?

**Comment by JahxSenpoopie** [comment]
You interact with one villager for a while then when you talk to another villager, whatever fatigue you had from the previous villager gets carried over to the new one you're interacting with

**Comment by Luke100000** [comment]
Local or dedicated server? Did you try the minimal example?

**Comment by JahxSenpoopie** [comment]
Yes I tried the example. I'm pretty sure it happens both locally and on a server. Like I said, it will carry whatever fatigue you had with the previous villager you interacted with

**Comment by CDAGaming** [comment]
This afaik shouldn't be present anymore in 7.2.0, but if so, please re-open
