### ISSUE TITLE
Fence Gates Pathfinding

### ISSUE THREAD

**Issue by nimbXnumb** [Luke100000/minecraft-comes-alive#700]
**Describe the bug**
Villagers do pathfind through fence gates but can't open them. They just jump in front of them. Btw vanilla villagers ignore fence gates unless they are open.

**To Reproduce**
1. Build a plot surrounded by fence with fence gate.
2. Spawn villager inside

**Screenshots**
![2023-06-30_17 53 57](https://github.com/Luke100000/minecraft-comes-alive/assets/117385950/c53cec59-157d-41d0-9a7c-69c08db70636)

**Version**
MCA Version - 7.5.3, Minecraft version - 1.19.2, Modloader - Fabric

**Latest.log**
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/11916458/latest.log)

**Comment by SwayMinin** [comment]
And also trapdoors

**Comment by nimbXnumb** [comment]
And also trapdoors (closed by mistake)
