### ISSUE TITLE
Error code: -1

### ISSUE THREAD

**Issue by Shisui593** [Luke100000/minecraft-comes-alive#702]
**Describe the bug**
Error when trying to start the game with several mods, we are 3 people with the same mod pack but 1 of us gets an error.Error when trying to start the game

**To Reproduce**
1. our friend gets an error when he starts to play (we are all using the official launcher)

**Screenshots**
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/91435459/1e0437c0-75b9-4538-9927-fd786b57edfe)

**Version**
Minecraft version: 1.19.2 , Modloader: Fabric (+Fabric API)

**Latest.log**
 
[crash-2023-07-01_00.59.00-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/11927132/crash-2023-07-01_00.59.00-client.txt)

**Comment by Luke100000** [comment]
Update mca, this version is 10 months old
