### ISSUE TITLE
[Suggestion] Strengthen the grim reaper

### ISSUE THREAD

**Issue by ghost** [Luke100000/minecraft-comes-alive#71]
When I was trying to strengthen the grim reaper by In Control! ( https://github.com/McJtyMods/InControl ) mod (used damagemultiply function), I found it doesn't work. But when I used other functions (like healthmultiply, healthadd), it works successfully. Then I realized that the attack of the grim reaper just applies a wither effect to the player. So I wonder whether or not you can make the grim reaper attack with straight damage. It is important to modpackers.

**Comment by Luke100000** [comment]
It should do both damage and effect. I will rework the grim reaper anyways and consider your request, I think I did not use attributes properly, causing Control to fail.
