### ISSUE TITLE
Farmer's Delight Stove

### ISSUE THREAD

**Issue by prunes-git** [Luke100000/minecraft-comes-alive#710]
**Describe the bug**
Villagers pathfind onto the stove ( farmersdelight:stove ) and burn to death. (R.I.P my son)

**To Reproduce**
1. Place stove.
2. Let villager walk onto it.
3. Panic as you try to get them off the stove.
4. Shed a tear and remember the good times.
5. Console all the other villagers.

**Version**
minecraft-comes-alive-7.5.3+1.20.1-universal

**Comment by Luke100000** [comment]
This sounds like a general problem, isn't it? It should also affect vanilla villagers and Sirbens cat. True story.

**Comment by Luke100000** [comment]
Let's merge with #710

**Comment by prunes-git** [comment]
Perhaps a general issue but I did notice the villager pathfinding blacklist in the configuration.

**Comment by Luke100000** [comment]
Its a heavily misleading flag used for something different. But instead of tags a config list may also work, I will consider this
