### ISSUE TITLE
User Interface requires useless input

### ISSUE THREAD

**Issue by AngleWyrm10** [Luke100000/minecraft-comes-alive#715]
**Is your feature request related to a problem? Please describe.**
During character creation, a backstory is presented that requires three mouse clicks to step through, but no decision or choice by the player.

**Describe the solution you'd like**
Consolidate the story into three paragraphs presented on a single page, which requires only one click to move on

**Describe alternatives you've considered**
A checkbox/setting to disable the backstory page(s) for those who've played this mod more than once.

**Additional context**
Best use of user input is when the mod requires a user decision, otherwise the less clicks the better.

**Comment by Luke100000** [comment]
Community voted for 3 pages, and I feel like the config is already too clustered with destiny related flags.
