### ISSUE TITLE
Catalog bug

### ISSUE THREAD

**Issue by Pookkkk** [Luke100000/minecraft-comes-alive#719]
When you build a prison with 1 iron door,The Blueprint says you build 2 iron doors.Then i try to figure out what is the problem so i try to place 2 iron doors and match with the Blueprint.Blueprint says i placed 4 iron doors.It's a bug Blueprint count 1 iron door for 2 iron doors so build a prison is impossible.Sorry my english is not very well :D
![2023-07-26_16 11 06](https://github.com/Luke100000/minecraft-comes-alive/assets/140620705/4b1e4a58-35d2-4018-88c4-ec4f3267c7d7)
![2023-07-26_16 15 30](https://github.com/Luke100000/minecraft-comes-alive/assets/140620705/ee86af9a-3200-4fd8-82c6-01448e70f0b8)

**Comment by Pookkkk** [comment]
its 1.20.1 version btw.

**Comment by Luke100000** [comment]
Probably a change in 1.20, since doors are technically two blocks. Its not gamebreaking tho, after all you need at least 1 door.

What is the issue is that your prison is a bit too small, 64 is the minimum here.

I will rework that, its quite a user unfriendly thing.

**Comment by Pookkkk** [comment]
thank you.
