### ISSUE TITLE
Standing villagers lag the server

### ISSUE THREAD

**Issue by pantsguyapp** [Luke100000/minecraft-comes-alive#72]
- Set a villager to stand still and it will proceed to lag the whole server, causing massive tick lag.

**Comment by Luke100000** [comment]
I can not reproduce that issue, how do you measure tick lag? Does it always happen? Do you have mods? Dedicated Server or Integrated Server?

**Comment by pantsguyapp** [comment]
Comes to think of it, all these villagers are laggy as hell when used along with the Minecolonies mod since they follow the vanilla villagers claiming beds and workstation mechanic, they constantly emit green particles around them, indicating that they just had claimed something.

**Comment by Luke100000** [comment]
MCA Villagers do not claim beds, therefore the green particles refer to workstations. This is a good hint on what might be going on, I will investigate that somewhere in the future.

**Comment by pantsguyapp** [comment]
Oh yeah, that does indicates what might be happening, not sure at all tho, on other notes, I quit playing Minecraft so you're on your own to figure this out from now on.
