### ISSUE TITLE
Invincible and annoying villagers

### ISSUE THREAD

**Issue by deserto-1** [Luke100000/minecraft-comes-alive#723]
**Describe the bug**
I was playing in a 1.18.2 server and the villagers seem to be invincible, they have like some weird regen. Also, they seem to not have a cooldown when spamming scared/hurt/fleeing messages.

**Version**
1.18.2

(https://cdn.discordapp.com/attachments/940831657722806293/1134717427511472189/latest.log)

**Comment by Luke100000** [comment]
message spam received a cooldown
