### ISSUE TITLE
Library Issue

### ISSUE THREAD

**Issue by Simons123** [Luke100000/minecraft-comes-alive#724]
**Describe the bug**
So when I was trying to edit a villager back to the original skin that they had it would pull up an authentication option which had never been asked before, so when I did it and authenticated it it prompted an error on the website that it brought me too. Now when I try to pull up the library that the skins were on all it gives me is a Failed to Check Authentication.

**To Reproduce**
1. Use the Villager Editor
2. Click on Body to select Clothes
3. Pick Library

**Screenshots**

**Version**
1.20.1, 7.5.3, Forge
![image_2023-07-30_122812805](https://github.com/Luke100000/minecraft-comes-alive/assets/26693874/35ce85f8-5d5c-42b1-a88e-78dd27076597)

**Comment by Luke100000** [comment]
Server maintenance, please wait

**Comment by Simons123** [comment]
How long should this take?

**Comment by Luke100000** [comment]
Until I'm done

**Comment by IsaacFred** [comment]
Hi. I know this was closed, however I'm still getting the server error. Are the servers still down and if so, is there an ET of when you think they'll be back up?

**Comment by Luke100000** [comment]
Until I'm done ^^
I can't convince Java to connect, technically the server is back online but Java (and Java only) rejects connection.

**Comment by Luke100000** [comment]
Ok fixed, it will still occasionally restart while I connect the last few wires but should otherwise work.
