### ISSUE TITLE
**ONLINE LIBRARY FAILS TO AUTHETICATE AND CONNECT TO THE INTERNET**

### ISSUE THREAD

**Issue by IsaacFred** [Luke100000/minecraft-comes-alive#725]
Description of the bug
When I would try to access the online Skin Library for this mod, it would say "Failed to authenticate" and I would be unable to login or access anything in the library. This has been an ongoing problem all day. I don't know if the servers are down or something, but it's not working now when it was working perfectly two days ago. I've tried everything to fix it, but nothing has worked.

Use the Villager Editor Book
Click on Body and hit "select Clothes or hair"
Pick "Library"
Try to login or do anything with the online library
See error message "Failed to authenticate"

If this is a problem with server maintenance, when can I expect the servers to be back up? Thanks for taking the time to read this. I know you're probably busy, so it means a lot.
Version
1.20.1, Fabric Mod loader

**Comment by Luke100000** [comment]
#724
