### ISSUE TITLE
Crash server

### ISSUE THREAD

**Issue by manu1978** [Luke100000/minecraft-comes-alive#726]
Crash server

**Version**
minecraft-comes-alive-7.5.4+1.20.1-universal

[crash-2023-08-01_02.27.56-server.txt](https://github.com/Luke100000/minecraft-comes-alive/files/12223264/crash-2023-08-01_02.27.56-server.txt)

**Comment by Taleuxss** [comment]
SAME

**Comment by xllifi** [comment]
Same problem. Running Fabric 0.14.21+1.20.1
Logs: https://mclo.gs/UQrPgfV

Downgrading to 7.5.3 fixed the issue

**Comment by Luke100000** [comment]
> Same problem. Running Fabric 0.14.21+1.20.1 Logs: https://mclo.gs/UQrPgfV
> 
> Downgrading to 7.5.3 fixed the issue

That one is unrelated, and it looks like a permission issue as it cant find the mod file? `java.nio.file.NoSuchFileException: /home/********/mods/minecraft-comes-alive-7.5.4+1.20.1-universal.jar`

**Comment by xllifi** [comment]
> That one is unrelated, and it looks like a permission issue as it cant find the mod file? `java.nio.file.NoSuchFileException: /home/********/mods/minecraft-comes-alive-7.5.4+1.20.1-universal.jar`

Oops. That was wrong log. Server has auto-restarts on crash and that was right when I removed 7.5.4
This one is correct: https://mclo.gs/cVffhaY
Crash report: https://mclo.gs/qDnDu1V

**Comment by Luke100000** [comment]
Yep that one looks right. I fixed it in 7.5.5!
