### ISSUE TITLE
Player's MCA skin won't load/show up

### ISSUE THREAD

**Issue by AyZeppelin** [Luke100000/minecraft-comes-alive#730]
First things first: The character creation works fine. However, after I finish it and start the game, the player skin will still be the default Alex/Steve one or any normal skin they're using.

MCA Version: 7.3.23, Minecraft version: 1.16.5, Forge.

%appdata%/.min
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/12254472/latest.log)
ecraft/logs/latest.log`.

**Comment by Luke100000** [comment]
When epicfight is installed, this feature will be disabled because it is not compatible anyways. You can enforce it by deleteing the epicfight lines in the config.
