### ISSUE TITLE
Improperly chopping some trees

### ISSUE THREAD

**Issue by xllifi** [Luke100000/minecraft-comes-alive#736]
**Describe the bug**
Cherry tree (mangrove too, probably) is non-standart and can't be cut down by an NPC

**To Reproduce**
1. Make a cherry tree
2. Have an NPC cut it down

**Screenshots**
![cherry tree](https://github.com/Luke100000/minecraft-comes-alive/assets/70767436/ae6ff05b-debc-4da0-9a07-d6a3aefc4f36)

**Version**
Fabric v7.5.5+1.20.1

**Latest.log**
Logic error, no logs

**Comment by xllifi** [comment]
+acacia
![acacia chopped down](https://github.com/Luke100000/minecraft-comes-alive/assets/70767436/a5e4c597-4cbf-48e8-a384-733f96f5ed28)

**Comment by Luke100000** [comment]
Merged with #953
