### ISSUE TITLE
1.19.2 visual bug

### ISSUE THREAD

**Issue by Monster-Cookee** [Luke100000/minecraft-comes-alive#740]
i got a visual bug in modded 1.19.2 that made no sense as ive never gotten something like this before after narrowing it down which mod caused it it was MCA reborn not sure how to fix the issue tried different versions tried updating nothing works 

![2023-08-09_18 32 10](https://github.com/Luke100000/minecraft-comes-alive/assets/142042903/9f4d0d90-f75e-42ca-92c5-b669bcdb0546)
![2023-08-09_18 32 02](https://github.com/Luke100000/minecraft-comes-alive/assets/142042903/bf13ee8b-a09b-4622-a2a0-54635b3ab76b)
![2023-08-06_21 14 44](https://github.com/Luke100000/minecraft-comes-alive/assets/142042903/003a0dfc-625f-46c4-9373-5201f7020e46)

im on the latest forge version and the latest version of MCA no optifine or anythin

**Comment by Luke100000** [comment]
My condolence, you are now a Sirben...

Tho `/mca editor` can edit traits, and F4 temporarily disables shaders too :)
