### ISSUE TITLE
[Bug] Duplicate graves of same villager at graveyards

### ISSUE THREAD

**Issue by Shibva** [Luke100000/minecraft-comes-alive#742]
**Describe the bug**
When a villager undergoes death, a second slot in a graveyard can be filled with the same villager. At first I was not sure whats causing it but a running theory I have is that it might have todo to the lack of secondary grave creation if a villager dies from a zombie and turns into a zombified version of it. The first time and the second time being them killed as a zombified villager

**To Reproduce**
1. goto a village and create a small graveyard
2. Set your gamemode to HARD (this dasticaly increases the odds of a villager when killed transmuting into a zombified one)
3. three, spawn a zombie and have it kill a villager in a controlled area
4. notice if a grave if filled once it dies and it becomes a zombified version
5. to recreate the scinerio's have the zombified villager be killed by you, a golem, or a guard
6. observe and see that a second grave in the yard is taken and it being the same.

**Screenshots**

**Version**
19.2 - 7.5.5+

**Latest.log**
n/A

**Comment by AeXiaohu** [comment]
This is also a bug that repeatedly drops items and can resurrect duplicate villagers.

Steps:
1. First, give the villagers 8 emeralds
2. Letting zombies kill villagers will turn them into zombies and drop 8 emeralds, as well as generate a tombstone
3. Then kill the zombie villagers, they will repeatedly drop 8 emeralds and generate duplicate tombstones again

Screenshots:
![CN9MY_E H4~07YNWFVTIXP3](https://github.com/Luke100000/minecraft-comes-alive/assets/30280708/d3225ad0-8036-44e3-a174-9aff4df44294)
![0GG5EN5~I6FJHM3~KY`CGL6](https://github.com/Luke100000/minecraft-comes-alive/assets/30280708/2704a733-3f52-498a-9f69-8b2758e43eae)
![L)164( 27QP31AZ} X6WO}V](https://github.com/Luke100000/minecraft-comes-alive/assets/30280708/e1a6d34b-5a1e-49c8-b67f-d3f0289f4f8b)
