### ISSUE TITLE
unable to edit config?

### ISSUE THREAD

**Issue by guyfingerguy** [Luke100000/minecraft-comes-alive#744]
sorry if this is a really stupid problem, but when i open the config json file, i'm unable to change or edit any of the options. is this an actual problem or am i doing something wrong?

**Comment by Luke100000** [comment]
As in you can not modify? Make sure to open it with a text editor. If they just reset, it means you made the config invalid, use for help: https://jsonlint.com/

**Comment by guyfingerguy** [comment]
thank you! this helped a lot
