### ISSUE TITLE
Marriage Doesn't Work With Diamond Ring

### ISSUE THREAD

**Issue by AymenAbb** [Luke100000/minecraft-comes-alive#745]
If you marry a villager with a diamond wedding ring, it wont count. You can notice this because the achievement till death do us part doesn't trigger. Marriages work properly with a normal gold ring.

1. Marry a villager using a diamond wedding ring
2. You get a marriage acceptance reaction
3. You can't use any features that require marriage like working or checking inventory

mca 7.5.5, game version 1.19.2, fabric 0.11.2

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/12364745/latest.log)

**Comment by Luke100000** [comment]
Because that's an [engagement ring](https://en.wikipedia.org/wiki/Engagement_ring), not a wedding ring.
