### ISSUE TITLE
Minor Text Bug

### ISSUE THREAD

**Issue by AymenAbb** [Luke100000/minecraft-comes-alive#746]
**Describe the bug**
See image.

1. Talk to married villager
2. Click on Interact > Follow Me
3. Go to house
4. Interact > Locations > Home
5. See error

![Screenshot 2023-08-16 211054](https://github.com/Luke100000/minecraft-comes-alive/assets/123590232/f7c46d44-527d-4ed0-bfb8-c926831bec87)

mca 7.5.5, game version 1.19.2, fabric 0.11.2

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/12364775/latest.log)

**Comment by Luke100000** [comment]
fixed
