### ISSUE TITLE
TLauncher bug 

### ISSUE THREAD

**Issue by alyr4** [Luke100000/minecraft-comes-alive#747]
When im start tlauncher with MCA it says a bug about:

Minecraft did not start due to an unknown error! Probably it happened for your mods, try to delete it or read below  You have installed mods. We advise you to assemble your assembly using our mod-pack system 

idk why is it

**Comment by Luke100000** [comment]
me neither, that's why you should have filled out the template

**Comment by alyr4** [comment]
wdym

**Comment by Luke100000** [comment]
When creating an issue it asked you a bunch of questions. You are supposed to answer them.

**Comment by alyr4** [comment]
do you have discord ?

**Comment by Luke100000** [comment]
https://discord.com/invite/EjYwZUJbpf
