### ISSUE TITLE
[Question] Prevent villagers (non guards) from fighting back?

### ISSUE THREAD

**Issue by EnderGirl1500** [Luke100000/minecraft-comes-alive#748]
Hi, I've got some other mods and it's almost impossible for the villagers to die, which makes my game too easy. I've been looking for posts, yt videos and configs but I can't find if there's a way to stop villagers from hitting zombies, leaving that job to the guards and golems to add a bit more difficulty. Basically vanilla behaviour: just run away.

If there's no such option, I'd like this to be taken as a suggestion to add it as an option to the config file.

**Comment by Luke100000** [comment]
Deconfirmed, imo villagers are dying too easy even with that little self defence slaps.

**Comment by EnderGirl1500** [comment]
That's why I said "I've got some other mods..."; it wasn't due to MCA itself, it was because of the other mods I had installed. That's why I suggested a setting to turn fighting on or off, instead of just asking for that feature to be removed.
