### ISSUE TITLE
none of the villager skins show up

### ISSUE THREAD

**Issue by crimmycram** [Luke100000/minecraft-comes-alive#749]
I start a world, none of the skins for the villagers show up in any way, not in game nor in the options menu, I'm not even quite sure if this is an actual bug or a problem on my end? I'm using tlauncher.

1. Just open minecraft and start a world

![44](https://github.com/Luke100000/minecraft-comes-alive/assets/142730129/5254862c-f6ae-48d2-b6b1-7f3263786f88)
![45](https://github.com/Luke100000/minecraft-comes-alive/assets/142730129/46f1255a-ff7c-48f6-924e-9501bd5583e2)

7.4.8, 1.18.2, forge with tlauncher

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/12388264/latest.log)

**Comment by Luke100000** [comment]
Please test without any other mods, and if that worked, find the mod doing that
