### ISSUE TITLE
Where are the playful children???

### ISSUE THREAD

**Issue by pantsguyapp** [Luke100000/minecraft-comes-alive#752]
**Is your feature request related to a problem? Please describe.**
MCA villagers are very dull, they wander aimlessly around town, like nitwits, unlike villager children who can play tags and jump on beds.

**Describe the solution you'd like**
Make children more playful once they are old enough to walk.

**Describe alternatives you've considered**

**Additional context**

**Comment by Luke100000** [comment]
Can't confirm
