### ISSUE TITLE
[Mod Incompatibility / Crash] MCA crashes at world creation

### ISSUE THREAD

**Issue by EnderGirl1500** [Luke100000/minecraft-comes-alive#758]
**Describe the bug**
I added a lot of mods and created a new world, then my game crashed and the logs pointed out mca could be the issue. After deleting it, no more crashes.

**Version**
_All are latest versions_
MCA: 7.5.5
Minecraft: 1.20.1
Modloader: Fabric 0.14.22

**Latest.log**
[2023-09-01-2.log](https://github.com/Luke100000/minecraft-comes-alive/files/12491632/2023-09-01-2.log)

**Comment by EnderGirl1500** [comment]
I'm looking further into this, trying to discover the incompatibility, just wanted to notify about it in advance

**Comment by EnderGirl1500** [comment]
Looks like the incompatibility is with Galosphere mod

**Comment by Luke100000** [comment]
The error is a concurrent exception error, which means it should only occur rarely. Does it always happen? I don't know why exactly it happens but I should be able to fix it.
