### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Nucho8** [Luke100000/minecraft-comes-alive#759]
The game crash when it starts start

I had several mods but I removed them and left only the MCA to see if it worked but it keeps crashing.

version:
MCA 7.5.5
minecrat 1.20.1
forge for minecraft 1.20.1

![Captura de pantalla 2023-09-03 150639](https://github.com/Luke100000/minecraft-comes-alive/assets/143943529/da776ba8-7060-4060-9536-87b8ad4dac74)

I dont have a log, it doesn't make me one.

**Comment by Luke100000** [comment]
Did you install architectury?

**Comment by Nucho8** [comment]
> Did you install architectury?

When I removed the other mods I forgot to put the architecture. but how strange that it did not give me the notice that the mod required another mod as it happens with others.

Thanks.
 I'll keep looking for the mod that crashes
