### ISSUE TITLE
[1.20.1 Forge] Crash with Origins mod (conflict)

### ISSUE THREAD

**Issue by MrKashew** [Luke100000/minecraft-comes-alive#763]
**Describe the bug**
Crash upon joining server, likely due to initial screen conflict between the mods, works upon removing MCA mod

**To Reproduce**
- Run with https://www.curseforge.com/minecraft/mc-mods/minecraft-comes-alive-reborn/files?version=1.20.1
- Join server
- Crash

**Version**
MCA Version, Minecraft version, Modloader
minecraft-comes-alive-7.5.3+1.20.1-universal
1.20.1 Forge 47.1.3

Crash log:
[crash-2023-09-12_21.27.31-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/12593952/crash-2023-09-12_21.27.31-client.txt)

**Comment by Luke100000** [comment]
Doesn't look very MCA too me, Radium is crashing at a (vanilla) villager task.

```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Redirect annotation on useFasterPOILookup could not find any targets matching 'method_46979' in net.minecraft.world.entity.ai.behavior.LocateHidingPlace.
```

Try with vanilla villagers and report to Radium instead if it happens as well.

**Comment by MrKashew** [comment]
closed - issue was with a third mod as you suspected, thanks!
