### ISSUE TITLE
Workplace, hangout and home register eventually got reset

### ISSUE THREAD

**Issue by pantsguyapp** [Luke100000/minecraft-comes-alive#77]
Also happens with vanilla villagers. For MCA, the places that you registered will eventually be reset and the villager will wander and swap beds, change profession, etc...

**Comment by Luke100000** [comment]
Workplace have vanilla behavior, they should only reset if you destroy the working block.
Hangout is not implemented yet.
Regarding home: do they also swap buildings? (For the mca villagers, vanilla do not have a really permanent concept of a home) If you do not explicitly define a bed they may swap beds within the same building whoever comes first.

**Comment by Luke100000** [comment]
Do the blueprints home assignment match the location they sleep?

**Comment by pantsguyapp** [comment]
Havent mess with the blueprint that much, i will double check this.

**Comment by pantsguyapp** [comment]
Yeah, quick update from last time, I checked out the blueprint but it said that their house was switched from the original one, maybe because of chunk reset or something? I don't know, my villagers had always sleep all over what beds they can see in my town.

**Comment by Luke100000** [comment]
Will become irrelevant in upcoming versions
