### ISSUE TITLE
Villager duplication: A grave spawn when a villager got turned into a zombie villager, then another spawn once the converted zombie villager died.

### ISSUE THREAD

**Issue by pantsguyapp** [Luke100000/minecraft-comes-alive#770]
**Describe the bug**
Titled, now you can use the staff of life to resurrect the fallen villager while curing/resurrecting the zombie villager.

**To Reproduce**
provided above

**Screenshots**

**Version**
MCA Version, Minecraft version, Modloader

**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.

**Comment by Luke100000** [comment]
merged with #742
