### ISSUE TITLE
Villager death notifications

### ISSUE THREAD

**Issue by MissAlexandrina** [Luke100000/minecraft-comes-alive#771]
There are config settings for birth/marriage notifications and travellers at the inn, which either show in chat or above the hotbar depending on settings. It would be great to have an option for the same for villagers' deaths. These are tracked in the log files but it's a pain to have to dig into these files.

It almost seems as though this functionality is half-there (the logs record both the death and a 'message: xx died') but unless I'm missing something there's no config option for it.

**Comment by Luke100000** [comment]
The village registry item does that.

**Comment by MissAlexandrina** [comment]
Oh fab!
