### ISSUE TITLE
Severe Learning Deficiencies 

### ISSUE THREAD

**Issue by wvaughn409** [Luke100000/minecraft-comes-alive#775]
**Describe the bug**
The AI refuses to learn from past mistakes.

**To Reproduce**
1. Make friends with an NPC and box them in/tell them to stay so you can start a conversation. Pick a farmer.
2. Ask questions: what is your role? how do you feel? did you get enough sleep last night?
3. Observe the AI annoyingly explains technical stuff about its limitations (inability to experience emotion, npc's don't actually sleep, etc)
4. Attempt to coach the AI on concepts of staying in character, and simulating normal behavior and thought/emotion for the betterment of enhanced player immersion
5. At this point, you may see some improvement, although the AI will still obsessively begin statements with "As a famer in this digital world, etc" 
6. keep coaching the responses and repeating the three questions and you may get a perfect three with no breaking character, mentions about technical limitations, or erroneous declarations of identity which harm player immersion, however.....
7. go away for a while, go sleep overnight, fly away from loaded chunks, etc.
8. return and repeat the same three questions.
9. Observe the AI will forget everything you taught it about staying in character and simulating emotion based on the identify and life of the minecraft farmer.  It will have returned robotically to its canned nonsense about being an AI language model, incapable of feeling or expressing, and asserting that npc's don't sleep the way humans do.
10. keep trying, for like four hours.
11. get angry, start being very short with Liudovika, the humble farmer/stubborn AI language model, and observe them apologizing profusely, assuring you they will correct the behavior, but repeating the same mistakes over and over as if to torture you
12. rage quit
13. file a bug report.

**Screenshots**
n/a

**Version**
MCA Version: [Universal 1.20.1] MCA Reborn - 7.5.8
, Minecraft version: 1.20.1, Modloader: Fabric

**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/12766145/latest.log)
[2023-09-28-7.log.gz](https://github.com/Luke100000/minecraft-comes-alive/files/12766146/2023-09-28-7.log.gz)

***Note: this integration is absolutely incredible, revolutionary, and I'm a huge fan. Please continue with this outstanding work.

**Comment by Luke100000** [comment]
The AI is prompt based, they do not have real memory atm, and the new model (OpenAI's decision) is very censored and tend to ignore the task to NOT know that they are AI ^^

I am currently experimenting with  finetuned models and how to afford them, as well as with proper support for custom models if players want to use their own solutions.

I can also try to add long term memory but no idea how well that works.

**Comment by wvaughn409** [comment]
@Luke100000  Thanks for your quick response. I understand now that some of this is by-design. I will consider my issue a feature request and close the bug.

**Comment by wvaughn409** [comment]
@Luke100000 I am very curious about your development of this mod and would like to get involved to any extent you are willing to collaborate. I'm an experienced programmer and have dabbled in all things machine learning. Would you be willing to chat offline about the potential for opportunity to become part of the work? I have some resources at my disposal which may prove useful to your efforts.

**Comment by Luke100000** [comment]
> @Luke100000 I am very curious about your development of this mod and would like to get involved to any extent you are willing to collaborate. I'm an experienced programmer and have dabbled in all things machine learning. Would you be willing to chat offline about the potential for opportunity to become part of the work? I have some resources at my disposal which may prove useful to your efforts.

That would be cool, feel free to DM me on Discord (conczin), or ping me in the MCA Discord to be added as a Collaborator. A second opinion before I rework the AI endpoint can never hurt :)

**Comment by wvaughn409** [comment]
> > @Luke100000 I am very curious about your development of this mod and would like to get involved to any extent you are willing to collaborate. I'm an experienced programmer and have dabbled in all things machine learning. Would you be willing to chat offline about the potential for opportunity to become part of the work? I have some resources at my disposal which may prove useful to your efforts.
> 
> That would be cool, feel free to DM me on Discord (conczin), or ping me in the MCA Discord to be added as a Collaborator. A second opinion before I rework the AI endpoint can never hurt :)

Although we are both members of the Official MCA Reborn Server, Discord is giving me an error when attempting to reach you via DM:
_"Your message could not be delivered. This is usually because you don't share a server with the recipient or the recipient is only accepting direct messages from friends. "_

**Comment by Luke100000** [comment]
Merged with #798
