### ISSUE TITLE
How do I make a villager a Baker? It is not in the villager editor.

### ISSUE THREAD

**Issue by prezeke** [Luke100000/minecraft-comes-alive#776]
**Describe the bug**
I'm unable to change a villagers profession to be a baker. Also, blueprint does not recognize bakery as a building even though it recognizes other profession buildings unlisted in the catalog such as a butcher.

**To Reproduce**
1. Click on villager with editor
2. Go to professions

Or

1. Try to change villager job like vanilla jobs 
2. *don't know how*

![2023-10-01_00 24 08](https://github.com/Luke100000/minecraft-comes-alive/assets/132619970/01230874-5ce8-4f6f-92c1-d973d5c9e4c7)

**Version**
MCA 7.7.5, Minecraft 1.20.1, Forge 47.0.3

**Latest.log**
Append the log, just drag and drop the file here.

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/12776114/latest.log)

You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.

**Comment by Luke100000** [comment]
Baker is no valid profession yet.
