### ISSUE TITLE
[ForgeOptifine 1.16.5] cant add buildings. "too small" 

### ISSUE THREAD

**Issue by fex3760** [Luke100000/minecraft-comes-alive#778]
So i was building a "big house", when i was done obv i clicked the add building option, and then the text "building too small" pops up. Thought i misread it so i rebuilt it, still didn't work. I made it smaller, bigger, wider, moved around objects, nothing worked.

Sometimes when it doesn't show that error it shows "requires atleast one door" when im literally standing right infront of it. Its the recent 1.16.5 mod, 7.3.23.
Would downloading prev vers like 7.3.22 help?

Edit: it didn't help. Now im just pissed off.

**Comment by Luke100000** [comment]
Check that your roof is solid. A building without a proper roof is too small as it has technically 0 blocks.

**Comment by fex3760** [comment]
> Check that your roof is solid. A building without a proper roof is too small as it has technically 0 blocks.

Oh, its working now. Sorry for the minor inconvenience, it wasn't stated anywhere that i needed to also add the roof so i thought i could just add it straight away. Thank you sm tho :3
