### ISSUE TITLE
[1.20.1] Broken Xaero Minimap texture for Minecraft Comes Alive Villagers

### ISSUE THREAD

**Issue by CGMejia2001** [Luke100000/minecraft-comes-alive#780]
**Describe the bug**
Minecraft comes alive villagers have broken textures, they appear as purple in the minimap. it is also affecting what they look like inside spawners, and even outputs the same exact error about a missing texture. if this helps, I also have SinytraConnector installed, which makes fabric mods run on forge

**To Reproduce**
1. Download and install Xaero Minimap [https://modrinth.com/mod/xaeros-minimap/version/23.8.2_Forge_1.20]
2. Download and install MCA Reborn 7.5.8
3. Run Minecraft 1.20.1
4. Load up a world, go to a village
5. Minimap textures for MCA Reborn villagers should appear purple(on 1.19.2 they appear as steves)

**Screenshots**
https://pasteboard.co/fUSvFbrU2Pxz.png

**Version**
MCA Version 7.5.8, Minecraft version 1.20.1, Forge 47.1.3

**Latest.log**

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/12795193/latest.log)

**Comment by Luke100000** [comment]
Merged with #374
