### ISSUE TITLE
[Fabric 1.20.1] Rumors pointing to custom locations spitting out unexpected data

### ISSUE THREAD

**Issue by ArmandVestibule** [Luke100000/minecraft-comes-alive#782]
### Discussed in https://github.com/Luke100000/minecraft-comes-alive/discussions/781

<div type='discussions-op-text'>

<sup>Originally posted by **ArmandVestibule** October  4, 2023</sup>
Consider this scenario:

Fabric 1.20.1, latest MCA available at time of writing.

I have added an array of custom structures to the rumors list in the mod config, as per https://github.com/Luke100000/minecraft-comes-alive/wiki/Custom-Rumors-and-Destiny-Structures.

I have also created a datapack and placed an updated en_us.json file in the path:  PACK>Assets>NAMESPACE>lang

Pack has been applied (there are custom recipes in there that are showing up in NEI) and server has been rebooted, yet I get some bonkers output.

Samples:
```
Config:
  "structuresInRumors": [
"minecraft:ancient_city",
    "minecells:overworld_portal"
  ],
```
en_us.json:

`  "dialogue.location.overworld_portal/1": "Rumors circulate about an overworld portal hidden within %2$s, a gateway to otherworldly realms.",`

Ask for rumors from a villager.  Output:
` [System] [CHAT] Annabelle: #Gmale.#EFRAGILE.#Pleatherworker.#TADULT.dialogue.location.overworld_portal`

I am clearly doing something wrong, and I have a feeling it's fundamental.  Any advice?</div>

**Comment by Luke100000** [comment]
The language files are client sided, thus should be part of a resource pack. If you did that, please share it so I can take a look at this.
