### ISSUE TITLE
I KNOW THIS ISNT A BUG REPORT BUUTTT....

### ISSUE THREAD

**Issue by hoagieenjoyer** [Luke100000/minecraft-comes-alive#784]
HOW IN THE HECK DO YOU ACCESS SKIN CUSTOMIZATION AFTER SPAWNING SO YOU CAN PUT ON YOUR VANILLA SKIN?!?!?!?!?!??!?????!?!?!?? I AM FREAKING OUT OVER THIS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by hoagieenjoyer** [comment]
answer me please

**Comment by hoagieenjoyer** [comment]
THERE ISNT EVEN A CLEAR INDICATION ON HOW TO CHANGE IT!!!!!!!

**Comment by Luke100000** [comment]
`/mca editor`
