### ISSUE TITLE
Trait does not work correctly

### ISSUE THREAD

**Issue by Whataheckisasonic** [Luke100000/minecraft-comes-alive#786]
**Describe the bug**
Homosexual trait does not work at all, when i use the female potion to turn into a woman, homosexual traits female villagers does not accept my bouquets or rings, i already tested it without any other mods and it still doesnt work, even with males using male potion it does not work

**To Reproduce**
1. Go to 'gift'
2. Click on 'bouquet'
3. See error

**Screenshots**
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/90728127/b072aa5a-0eb3-4f93-b53f-b7caf7f9cd27)
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/90728127/693b6fca-c1cf-4424-9a4e-ac1e3663d6a9)

**Version**
MCA 7.5.8, Minecraft version 1.19.2, forge

**Comment by Luke100000** [comment]
What are your traits?
