### ISSUE TITLE
Nanism still works while disabled

### ISSUE THREAD

**Issue by Nicolol1234** [Luke100000/minecraft-comes-alive#787]
**Describe the bug**
On my server config, i've disabled nanism, but players are still able to choose it

**To Reproduce**
1. Install mca on server
2. Disable nanism ln config
3. Restart 
4. Connect, and choose nanism

**Screenshots**

**Version**
MCA 7.5.8+1.20.1-universal, with fabric 1.20.1 loader.0.14.22-launcher.0.11.2

**Latest.log**
Nothing is logged

**Comment by Luke100000** [comment]
Can you share the config please to reconstruct?

**Comment by Nicolol1234** [comment]
https://pastebin.com/kPxaq7y7
Here it is

**Comment by Nicolol1234** [comment]
Any news?

**Comment by Nicolol1234** [comment]
I'm bumping, because it's a real problem for me and i rly need your help 😅

**Comment by Luke100000** [comment]
Trait config did not use server config, fixed now. You would have to disable traits on the player side for now.
