### ISSUE TITLE
Red Screen Tint Bug

### ISSUE THREAD

**Issue by F0lkish** [Luke100000/minecraft-comes-alive#788]
**Describe the bug**
Red Screen Tint when i Load My world or any other world

I want to play Better MC with MCA

**To Reproduce**
1. install MCA
2. open Minecraft
3. open ur world
4. see error
5. close Minecraft
6. uninstall MCA
7. open Minecraft
8. open ur world
9. see how the bug is fixed 
**Screenshots**
![Captura de pantalla 2023-10-14 135343](https://github.com/Luke100000/minecraft-comes-alive/assets/109989641/c0f68f78-ca1b-40e7-acda-4ea3a06af155)
**Version**
minecraft-comes-alive-7.5.8+1.20.1-universal.jar / Forge 47.2.0 / Minecraft 1.20.1
Better MC BMC4
Shaders Off / ocurs the same with the Saders tuned On

¡Sorry For My English But Its Not My Main Language!
I Speak With the letter "Ñ"

**Comment by Luke100000** [comment]
You are a Sirben, chose your traits more carefully :)

/mca editor to modify your traits later on.
