### ISSUE TITLE
Increase guard's default health to be 40 more than the default villager's health pool

### ISSUE THREAD

**Issue by pantsguyapp** [Luke100000/minecraft-comes-alive#790]
**Is your feature request related to a problem? Please describe.**
When fully leveled up, a villager will gain an additional 20 more health, and guards/archers are exempt to it because they can't be traded with so they are stuck with less health than normal villagers.

**Describe the solution you'd like**
Guards/Archers should have 40 more health than whatever the set health in the config, to make them more durable against enemies and still have more health than villagers.

**Describe alternatives you've considered**
I've considered for them to only have 20 more health instead but I want guards to be stronger than villagers.

**Additional context**

**Comment by Luke100000** [comment]
To avoid a mess when changing professions, guards have higher armor rather than health. With their current 50% armor they effectively have 40 hearts.
