### ISSUE TITLE
Change gender preferences in survival

### ISSUE THREAD

**Issue by Whataheckisasonic** [Luke100000/minecraft-comes-alive#796]
Something that doesn't make much sense is not beeing able to change our sexual preferences, in the /mca editor in survival mode. i would like if you could be able to add or remove the traits "homosexual" and "bissexual" without the need of using creative mode, it would give more freedom for players that want to relate to woman beeing a woman, or a man beeing a man. Or just make the player straight up Pansexual.

**Comment by zeid0ne** [comment]
Maybe that could be done by adding a love potion (with variant for each gender) ?
And maybe you could give it to other villagers under some conditions ?

**Comment by Luke100000** [comment]
`enableGenderCheckForPlayers` in the config, I don't think adding items for such details is necessary
