### ISSUE TITLE
Enhance GPT AI

### ISSUE THREAD

**Issue by WT000** [Luke100000/minecraft-comes-alive#798]
**Is your feature request related to a problem? Please describe.**
Related to the way ChatGPT is used by villagers, is it possible to use another GPT API or use a rule-bypassing prompt (e.g. DAN) to get around the issue of villagers calling themselves an AI model. This is because it's currently difficult to communicate with them without them breaking character, at least for myself and my friend.

![image](https://github.com/Luke100000/minecraft-comes-alive/assets/55751558/5ff59241-f9ac-4377-94d7-8f9da26210a7)

**Describe the solution you'd like**
As mentioned above, I wonder if another API could be used, especially if it's on an older version of ChatGPT that is not as restricted as the present API. Furthermore, the [DAN prompt](https://github.com/0xk1h0/ChatGPT_DAN) could be used before instructing the AI, which may also get around this issue?

**Potential other solutions**
You could potentially use something like [character.ai](https://beta.character.ai/), as this does not seem to be as censored? But I'm not sure on how their API works.

**Comment by Luke100000** [comment]
OpenAI (will) turn of the older, less censored models soon which I used in the past with much greater success. I had to switch early because some users violated the TOS.

DAN would be too expensive due to the token overhead, and also a potential reason to terminate access ^^

Character AI has no API.

I am currently considering alternatives as well, especially dedicated hardware but the price and quality of results are currently a bit of a problem. My current experiments evolve around a finetuned Mistral with mixed success.

**Comment by juaps** [comment]
i would like to extend the enhancement Proposal for GPT AI with MCA Reborn Mod:

with this Integrating personalized mob profiles and enhancing interaction capabilities:

Recording Personalities:
Implement a feature where the mod records and associates personalities with individual mobs. This could involve creating a personalized profile for each mob that includes traits, preferences, and behaviors.

Contextual Understanding:
Enable the AI to comprehend player input, allowing for more nuanced interactions. For instance, mobs should understand and respond appropriately when players ask them to perform specific in-game actions like attacking, marrying, jumping, changing professions, etc.

Actionable Conversations:
Develop a system where verbal commands given to the mob translate into corresponding in-game actions. For example, instructing a mob to "attack" prompts it to engage in combat, or suggesting "marriage" initiates a process where the mob seeks a partner.

Mission Suggestions:
Introduce a dialogue system that allows players to engage mobs in conversations where they can suggest or receive mission ideas. Mobs could offer quests, accompany players on missions, or provide assistance based on the context of the conversation.

Comprehensive Interaction:
Enable mobs to respond dynamically to player-initiated discussions, fostering a more immersive and engaging gameplay experience. This could involve recognizing emotions, preferences, and contextual cues to enhance the overall interaction.

By implementing these features, the GPT AI with the MCA Reborn Mod can offer a more sophisticated and personalized interaction with mobs, enriching the gameplay and expanding the possibilities for engaging with the virtual world.

**Comment by WT000** [comment]
> OpenAI (will) turn of the older, less censored models soon which I used in the past with much greater success. I had to switch early because some users violated the TOS.
> 
> DAN would be too expensive due to the token overhead, and also a potential reason to terminate access ^^
> 
> Character AI has no API.
> 
> I am currently considering alternatives as well, especially dedicated hardware but the price and quality of results are currently a bit of a problem. My current experiments evolve around a finetuned Mistral with mixed success.

I've had a play with a few of OpenAI's models with your code (thanks for including your Python server code) and the "davinci-002" model seems to be able to hold some proper conversations! Here's a few examples: 
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/55751558/53993f35-95db-4998-9c16-8d0fdd14ed03)

![image](https://github.com/Luke100000/minecraft-comes-alive/assets/55751558/ce638209-b796-4c65-84dd-848bac6f801a)

I haven't seen it break character (yet, maybe I've been lucky), have you tried this model? If you have, how were your results?

**Comment by Luke100000** [comment]
> > OpenAI (will) turn of the older, less censored models soon which I used in the past with much greater success. I had to switch early because some users violated the TOS.
> > DAN would be too expensive due to the token overhead, and also a potential reason to terminate access ^^
> > Character AI has no API.
> > I am currently considering alternatives as well, especially dedicated hardware but the price and quality of results are currently a bit of a problem. My current experiments evolve around a finetuned Mistral with mixed success.
> 
> I've had a play with a few of OpenAI's models with your code (thanks for including your Python server code) and the "davinci-002" model seems to be able to hold some proper conversations! Here's a few examples: ![image](https://private-user-images.githubusercontent.com/55751558/298308808-53993f35-95db-4998-9c16-8d0fdd14ed03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MjQ4NzMsIm5iZiI6MTcwNTgyNDU3MywicGF0aCI6Ii81NTc1MTU1OC8yOTgzMDg4MDgtNTM5OTNmMzUtOTVkYi00OTk4LTljMTYtOGQwZmRkMTRlZDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDA4MDkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMDE1MTBlMDhjY2MyNTgyODU1M2E3NmI3YTgxNjAxN2EzYWFjYzhjNWMyODMwMDM4ZDhkZmQ3OGIwMGU3NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CGVzuaqwUICt4cugWpLTlsB_OjJy7FfWqUsbLrEE-vg)
> 
> ![image](https://private-user-images.githubusercontent.com/55751558/298308942-ce638209-b796-4c65-84dd-848bac6f801a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MjQ4NzMsIm5iZiI6MTcwNTgyNDU3MywicGF0aCI6Ii81NTc1MTU1OC8yOTgzMDg5NDItY2U2MzgyMDktYjc5Ni00YzY1LTg0ZGQtODQ4YmFjNmY4MDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDA4MDkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZDhmMzU0ZWE3YzYyZGI4YTUwYmRkOTFiOGExMTg4NWE4MDg2MWI3NDJiMmQ3MjQzYzJlNWNjYTQ5YjZkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Alk3gBrf3X0ISzUO82r8LJnw1PxRXRQo46NNHDJwUyk)
> 
> I haven't seen it break character (yet, maybe I've been lucky), have you tried this model? If you have, how were your results?

Interesting! Originally the davinci models were way to expensive, but davinci-002 today would work. It would be roughly twice as expensive than turbo. Its also labeled as the replacement model for curie, which I used previously with better results than 3.5 turbo. Will try.

In addition I am currently experimenting with Mistral (both 7B and the MoE model), I expect better results than turbo there as well.

**Comment by WT000** [comment]
> > > OpenAI (will) turn of the older, less censored models soon which I used in the past with much greater success. I had to switch early because some users violated the TOS.
> > > DAN would be too expensive due to the token overhead, and also a potential reason to terminate access ^^
> > > Character AI has no API.
> > > I am currently considering alternatives as well, especially dedicated hardware but the price and quality of results are currently a bit of a problem. My current experiments evolve around a finetuned Mistral with mixed success.
> > 
> > 
> > I've had a play with a few of OpenAI's models with your code (thanks for including your Python server code) and the "davinci-002" model seems to be able to hold some proper conversations! Here's a few examples: ![image](https://private-user-images.githubusercontent.com/55751558/298308808-53993f35-95db-4998-9c16-8d0fdd14ed03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MjQ4NzMsIm5iZiI6MTcwNTgyNDU3MywicGF0aCI6Ii81NTc1MTU1OC8yOTgzMDg4MDgtNTM5OTNmMzUtOTVkYi00OTk4LTljMTYtOGQwZmRkMTRlZDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDA4MDkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMDE1MTBlMDhjY2MyNTgyODU1M2E3NmI3YTgxNjAxN2EzYWFjYzhjNWMyODMwMDM4ZDhkZmQ3OGIwMGU3NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CGVzuaqwUICt4cugWpLTlsB_OjJy7FfWqUsbLrEE-vg)
> > ![image](https://private-user-images.githubusercontent.com/55751558/298308942-ce638209-b796-4c65-84dd-848bac6f801a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU4MjQ4NzMsIm5iZiI6MTcwNTgyNDU3MywicGF0aCI6Ii81NTc1MTU1OC8yOTgzMDg5NDItY2U2MzgyMDktYjc5Ni00YzY1LTg0ZGQtODQ4YmFjNmY4MDFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIxVDA4MDkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5ZDhmMzU0ZWE3YzYyZGI4YTUwYmRkOTFiOGExMTg4NWE4MDg2MWI3NDJiMmQ3MjQzYzJlNWNjYTQ5YjZkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Alk3gBrf3X0ISzUO82r8LJnw1PxRXRQo46NNHDJwUyk)
> > I haven't seen it break character (yet, maybe I've been lucky), have you tried this model? If you have, how were your results?
> 
> Interesting! Originally the davinci models were way to expensive, but davinci-002 today would work. It would be roughly twice as expensive than turbo. Its also labeled as the replacement model for curie, which I used previously with better results than 3.5 turbo. Will try.
> 
> In addition I am currently experimenting with Mistral (both 7B and the MoE model), I expect better results than turbo there as well.

Ah I actually tried 7B (v0.2) recently too, I Personally I used Mistral's own API (particularly using **mistral-tiny**) and got more fantasy-esc responses, here's a few examples I got from it: 
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/55751558/0a88f63a-c899-49dd-9e40-a74003834971)

![image](https://github.com/Luke100000/minecraft-comes-alive/assets/55751558/3f119d94-aa71-4a27-843c-7f1433188358)

The responses can sometimes be a bit mixed, but with some prompt tweaking I believe it could also work fairly well (especially because it's not censored and regulated like OpenAI from what I can tell, which should hopefully prevent any of those angry TOS emails)

**Comment by juaps** [comment]
Hey, question, AI is not longer avaiable? i cant manage to configurate in the updated mod

**Comment by Luke100000** [comment]
No, works fine for me, no changes made at all yet. Please share versions

**Comment by Jonah-Thomas** [comment]
I am using version 7.4.11 on 1.18.2 and the AI dont speak to me. if i was to speak i would need to use /say right? After I enable them?

**Comment by Luke100000** [comment]
> I am using version 7.4.11 on 1.18.2 and the AI dont speak to me. if i was to speak i would need to use /say right? After I enable them?

No, just mention their name directly in the chat. Its not a command. Check out https://github.com/Luke100000/minecraft-comes-alive/wiki/GPT3-based-conversations for more details.

**Comment by Luke100000** [comment]
Llama and mistral are available, custom system prompts since a while now, long-term memory in testing phase, and per-villager personality system prompts in progress.
