### ISSUE TITLE
Transform villagers in existing worlds?

### ISSUE THREAD

**Issue by AdeleHorn** [Luke100000/minecraft-comes-alive#801]
Maybe this isn't even a bug, but I found that villagers in my old worlds still look and act the same as before the installation of MCA, even when I deliberately make a new villager spawn. But villagers in worlds that were created after I installed MCA do exactly what they're supposed to do, so the mod seems to work fine in general. Has anyone else had and maybe solved this issue? I'd love to use MCA in my largest world without having to start from scratch. :/

**Comment by AdeleHorn** [comment]
Never mind, I've figured it out. :)

**Comment by EchoEllet** [comment]
> Never mind, I've figured it out. :)

Hi, can you mention how?

**Comment by AdeleHorn** [comment]
Sure. Just kill the existing villagers, and use the corresponding MCA eggs to let new ones spawn.

**Comment by EchoEllet** [comment]
> Sure. Just kill the existing villagers, and use the corresponding MCA eggs to let new ones spawn.

There is built in command for that
