### ISSUE TITLE
backport to 1.12.2 due to it being a poppular version

### ISSUE THREAD

**Issue by nekohacker591** [Luke100000/minecraft-comes-alive#802]
**Is your feature request related to a problem? Please describe.**
n/a
**Describe the solution you'd like**
a backport for 1.12.2 

**Describe alternatives you've considered**
normal MCA if my request is declined

**Additional context**
would be great for older versions such as 1.12.2 to have moderan features

**Comment by Luke100000** [comment]
A jump over 8 major versions is no longer a port, its a separate mod. The switch from 1.12.2 to 1.16.5 alone already required a rewrite. I do not have the time for another mod, especially because there is already the original MCA.
