### ISSUE TITLE
add an option to leave regular minecraft skin

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [Luke100000/minecraft-comes-alive#803]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Luke100000** [comment]
Thats the button you skipped at the very beginning, or `/mca editor` later on.

**Comment by SonicTheHedgehog58987276** [comment]
it gives me a different skin than my tl skin cape!

**Comment by Luke100000** [comment]
TLauncher is not open source, thus its impossible to provide compatibility or support.

**Comment by SonicTheHedgehog58987276** [comment]
i want regular steve skin

**Comment by cheesehead5835853853** [comment]
my mistake, im back as cheesehead, and i found out it was tlauncher that gave me those skins
