### ISSUE TITLE
Resident villagers sleeping into the inn

### ISSUE THREAD

**Issue by oMiCid00** [Luke100000/minecraft-comes-alive#805]
**Describe the bug**
Is that normal that the villagers sleep into my inn ?
I made an inn with 9 beds, and since some villagers have babies, those are sleeping into the inn's beds when they have grown.
On my blueprint, my inn turned as butcher by itself, so I supposed my new villagers slept in those beds. 

Is there a way to exclude the inn's beds from the available beds for breeding ?

Thanks for your responses :)

**Version**
MCA Version 7.5.11, Minecraft version 1.20, Forge

**Comment by Luke100000** [comment]
Thats already a thing and I assume those villagers already snacced the bed before it became an inn. Just provide them new homes. There is no kick button (yet). Well except breaking the bed.
