### ISSUE TITLE
Option for everyone to be functionally be bisexual

### ISSUE THREAD

**Issue by AnonymousLightbulb** [Luke100000/minecraft-comes-alive#806]
**Is your feature request related to a problem? Please describe.**
It's near impossible to be in a same sex relationship because of the rarity of villagers being homo/bi.

**Describe the solution you'd like**
An option in the config to make all villagers be treated as bi.

**Describe alternatives you've considered**
The option to adjust the chance of villagers having a trait.

**Comment by Luke100000** [comment]
`enableGenderCheckForPlayers` in the config :)

**Comment by AnonymousLightbulb** [comment]
Thank you!

**Comment by AnonymousLightbulb** [comment]
I once tried to get two female villagers married using matchmaker’s rings, it failed because they weren’t gay. Would I be able to do that successfully if I turn this option on?

**Comment by Luke100000** [comment]
> I once tried to get two female villagers married using matchmaker’s rings, it failed because they weren’t gay. Would I be able to do that successfully if I turn this option on?

No, for this we would need an even stronger config flag, but then it also makes sense to disable sexuality traits etc so I skipped that for now.
