### ISSUE TITLE
crash when trying to use skin library

### ISSUE THREAD

**Issue by sigmaminecrafter** [Luke100000/minecraft-comes-alive#809]
**Describe the bug**
Crashing whenever go past page 1 in the skin library

**To Reproduce**
1. Go to 'Start new world and begin to create character...'
2. Click on 'select clothing, library ... the page will look broken and when pressing page 2 it will crash....'

**Screenshots**

https://github.com/Luke100000/minecraft-comes-alive/assets/152237294/5a67079a-62e6-497f-9312-e49a85c00756

**Version**

mca reborn 7.5.11  , 1.20.1 , fabric

**Latest.log**

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/13482723/latest.log)

**Comment by Luke100000** [comment]
merged with #807
