### ISSUE TITLE
can you add a config option to turn off bounty hunter spawning?

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [Luke100000/minecraft-comes-alive#810]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when vindicators would kill minecolonies citizens 

**Describe the solution you'd like**
add a config option to disable bounty hunter illagers.

**Describe alternatives you've considered**

**Additional context**

**Comment by Luke100000** [comment]
https://github.com/Luke100000/minecraft-comes-alive/wiki/Config

`bountyHunterHeartsInterval`, set to very low value.

**Comment by SonicTheHedgehog58987276** [comment]
why not they not spawn at all?

**Comment by Luke100000** [comment]
well, stop slaughtering villagers ^^

**Comment by SonicTheHedgehog58987276** [comment]
i want to obliterate them. they steal beds from colonists

**Comment by SonicTheHedgehog58987276** [comment]
and also, it raises my knowledge of death on corail tombstone

**Comment by SonicTheHedgehog58987276** [comment]
too low reputation crashes game
