### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by SonicTheHedgehog58987276** [Luke100000/minecraft-comes-alive#812]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Version**
mca: latest i think, Minecraft version:1.20.1, Modloader: forge
**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profi
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/13530636/latest.log)
le specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.

**Comment by Luke100000** [comment]
```
[12:50:23] [main/ERROR]: Missing or unsupported mandatory dependencies:
	Mod ID: 'architectury', Requested by: 'mca', Expected range: '[9.0.8,)', Actual version: '[MISSING]'
```

**Comment by SonicTheHedgehog58987276** [comment]
i already found out, i forgot architectury.
