### ISSUE TITLE
Player head's internal position can be bugged

### ISSUE THREAD

**Issue by Tetro48** [Luke100000/minecraft-comes-alive#814]
**Describe the bug**
Player head's position isn't correctly reset, causing players to potentially suffocate unexpectedly when just half-submerged in water from the client's perspective. This also makes using water buckets rather annoying

**To Reproduce**
1. Start a new world, preferrably in Creative mode
2. Get elytra, and wear it
3. Glide using elytra
4. See client-server mismatch error

**Screenshots**
After using elytra
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/76738929/d48fcd5a-a025-4999-9860-f9c3870aed2a)
This usually shouldn't happen
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/76738929/3de70793-9639-4d30-a682-cd7d87fcc039)
Suffocation?
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/76738929/71e9b8b8-c419-4fe8-9f92-9f81674891ca)

**Version**
MCA 7.5.11, Minecraft 1.20.1, Forge 47.2.16

**Latest.log**
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/13600004/latest.log)

**Comment by Tetro48** [comment]
This issue also occurs server-side when you sprint swim in water for a bit.

**Comment by Tetro48** [comment]
Closed this issue, since it's a likely duplicate of #765.

**Comment by Luke100000** [comment]
What mca version do you use?
