### ISSUE TITLE
can a villager become an outlaw naturally or only through the debug menu ?

### ISSUE THREAD

**Issue by chandlerdawg** [Luke100000/minecraft-comes-alive#825]
hi ! hope im posting this in the right place. basically, i've been playing w the mod for a good while and noticed the "outlaw" profession in the debug menu for the villager editor. i know players can become an outlaw by killing 10 villagers or something like that, but how do the villagers get to that point on their own? is it even possible? for a while i figured it was, bc in the description of the prison it mentions locking away thieves and traitors. i waited but no villagers went out of their way to wrong me and cause drama so my prison remained empty. so, do outlaws/thieves/traitors occur naturally ? if not already that would be a v cool feature 8) thanks !! love ur work man

**Comment by Luke100000** [comment]
As a king you can outlaw a villager, which then gets executed by guards on sight. There is no other use case for prisons yet.
