### ISSUE TITLE
Race Addon

### ISSUE THREAD

**Issue by sssHpion007** [Luke100000/minecraft-comes-alive#826]
I would like the inhabitants to have different races. Something like elder scrolls. This would be an analog of the Origins mod. For example, you can start survival in hell by playing for the Piglin race. A certain race would have more interactions with its people.

There is one small mod. Mythic Mobs. He adds some more humanoids to trade with. It would be interesting to see villages of such inhabitants.
https://modrinth.com/mod/mythic-mobs/gallery

**Comment by Luke100000** [comment]
I think required traits registration etc is public to allow addons and races, if not ping on Discord.
