### ISSUE TITLE
Villagers trying to jump over closed fence gates

### ISSUE THREAD

**Issue by cohfe** [Luke100000/minecraft-comes-alive#836]
Villagers see closed fence gates as open, and they try to go through them. This causes them to be stuck trying to jump over them instead of finding a different path.

https://github.com/Luke100000/minecraft-comes-alive/assets/155850308/571602c4-e296-4fa8-a59d-1b7e288e23f6

**Comment by Luke100000** [comment]
Head to the config and check that smart door ai is disabled

**Comment by cohfe** [comment]
Which config file?

**Comment by Luke100000** [comment]
config/mca.json

**Comment by cohfe** [comment]
It says  "useSmarterDoorAI" is false

**Comment by Luke100000** [comment]
Then there isn't really anything I can do as this is vanilla behavior

**Comment by cohfe** [comment]
Ohh okay, thanks for trying to help anyways !
