### ISSUE TITLE
No signs of building size. I don't know how many blocks should I use to build.

### ISSUE THREAD

**Issue by Jiyakes** [Luke100000/minecraft-comes-alive#841]
I downloaded MCA REBORN 1.20.1, but when I opened the blueprints. There are no signs of building size. I don't know how many blocks should I use to build. Any solutions

**Comment by Luke100000** [comment]
Since a while now there is no minimum size.

**Comment by Jiyakes** [comment]
> Since a while now there is no minimum size.

Ohhh, because i watch the other people playing comes alive there's a minimum size (old version). So i thought there's a bug in my mod. Ok, thank you 😄😄😄
