### ISSUE TITLE
Clothes

### ISSUE THREAD

**Issue by jameel1222** [Luke100000/minecraft-comes-alive#848]
**Describe the bug**
the vilagers doesnt have clothes 
**To Reproduce**

**Screenshots**

**Version**
MCA Version, Minecraft version, Modloader
1.19.4 7.5.11
![٢٠٢٤-٠١-٢١_١٨ ٠٩ ٢٢](https://github.com/Luke100000/minecraft-comes-alive/assets/157297698/8f5adc53-b869-4b47-b680-6fecfb6aa7be)
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/14001764/latest.log)

**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.

**Comment by Luke100000** [comment]
Please recheck your exact installed mca version, the log does not match up.
