### ISSUE TITLE
Accidently killed villager, bounty hunters

### ISSUE THREAD

**Issue by Gamerbolts** [Luke100000/minecraft-comes-alive#850]
Hello,

I created my own modpack and was playing with my wife, we have simply swords and a villager got in the way and died almost immediately. Now bounty hunters are constantly coming. I checked the config and can't find anyway to stop them. I checked the NBT file for my playdata and world but nothing, I checked commands for mca-admin but nothing there, please help. I am not sure where the village was that caused this so going back is out of the question. Any help please, thanks!

**Comment by Luke100000** [comment]
They will stop spawning after a while. And there is config, check again :)
https://github.com/Luke100000/minecraft-comes-alive/wiki/Config

**Comment by Gamerbolts** [comment]
This one?
// Bounty hunters Attack you once a day if you have a bad reputation
"bountyHunterInterval": 24000,
"bountyHunterHeartsInterval": -150,

That's what worried me because I thought it would happen once a day every day. Thankfully that is not the case. I don't see a way to stop the bounties outright, just increase the number so it's rare. Or does "-1" work?

**Comment by Luke100000** [comment]
I would set `bountyHunterHeartsInterval` to a very low number

**Comment by Gamerbolts** [comment]
ok will do. thanks
