### ISSUE TITLE
Comes Alive and Epic Fights

### ISSUE THREAD

**Issue by Zoraior** [Luke100000/minecraft-comes-alive#851]
**Is your feature request related to a problem? Please describe.**
hey guys, its some how to make the mod comes alive use the epic mod combat?
because I try to add the mobs on the epic fight
but for some reason the mobs get stuck

**Describe the solution you'd like**
problably creating a option to disable the default render of characters make then compat with epic

https://github.com/Luke100000/minecraft-comes-alive/assets/76544300/7ebd6e61-2707-48a2-a262-7edbab6c8613

**Comment by Luke100000** [comment]
Someone would need to make Epic Fight models.

Yes you can turn them into Squidwards via config but that kinda misses the point of mca.

merged with #575

**Comment by EchoEllet** [comment]
I somehow managed to get it working by modifying both Epic fight and MCA reborn but it's not quite functional.

https://github.com/user-attachments/assets/bd0e9aa7-fdcd-4705-97a9-6f4cafe7fa13
