### ISSUE TITLE
send kids mining as a chore

### ISSUE THREAD

**Issue by urfavbxnny** [Luke100000/minecraft-comes-alive#853]
**Is your feature request related to a problem? Please describe.**
in the old version you used to be able to send your kids mining and I really like to have it back because I like to marry off my kids to create my own village and it takes a lot of iron

**Describe the solution you'd like**
a chore to send them mining and they will look for nearby caves or start digging their own mine

**Describe alternatives you've considered**
I have tried just giving them a pickaxe and see if they'll go mining freely but they don't

**Additional context**

**Comment by Luke100000** [comment]
We deconfirmed it, too much work to maintain.
