### ISSUE TITLE
Downloaded the newest version but minecraft wont let me open it telling me theres an issue with minecraft comes alive reborn, telling me its failed to load properly minecraft version 1:20:4 mca reborn version 1:20:4 curseforge 49.0.26

### ISSUE THREAD

**Issue by icyicyicyic** [Luke100000/minecraft-comes-alive#856]
**Describe the bug**

**To Reproduce**

**Screenshots**

**Version**
MCA Version, Minecraft version, Modloader

**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.

**Comment by Luke100000** [comment]
Fill in the template
