### ISSUE TITLE
MCA Reborn Voice Pack failed in 7.5.12

### ISSUE THREAD

**Issue by Sovina1991** [Luke100000/minecraft-comes-alive#857]
https://modrinth.com/resourcepack/mca-reborn-voice-pack
Previously, this voice pack matched the conversation of the villagers, but this update of the villagers' dialogue caused the language file and resource pack to become invalid

**Comment by Luke100000** [comment]
How do you notice that, what are the issues? It is expected to have some missing phrases where they remain silent until I regenerate voices.

**Comment by Sovina1991** [comment]
> 你是怎么注意到的，有什么问题？预计会有一些缺失的短语，它们会保持沉默，直到我重新生成声音。

I noticed it during normal interaction with the villagers.The current situation is that all translation files for voice and other languages (such as Chinese) have become invalid, even if there have been previous conversations between translation and voice. Thank you very much for your work. If we can restore the previous voice, the game will definitely be more immersive.

**Comment by Sovina1991** [comment]
> 你是怎么注意到的，有什么问题？预计会有一些缺失的短语，它们会保持沉默，直到我重新生成声音。

I noticed it during normal interaction with the villagers.The current situation is that all translation files for voice and other languages (such as Chinese) have become invalid, even if there have been previous conversations between translation and voice. Thank you very much for your work. If we can restore the previous voice, the game will definitely be more immersive.

**Comment by Luke100000** [comment]
Alright so, I need your feedback:

Currently I pregenerate the TTS using Google and Amazons TTS models. However, this will become out of date (Like right now), costs me a bit of money and is tedious to maintain. Also, users have to download 1GB packs. I can update the pack, sure, but it will eventually become out of date again.

Alternatives I can offer a cloud solution running on my own hardware. This is "free", always up to date, supports 17 languages and even more speakers, and the user does not have to install anything. Either a flag in the config or a command to turn it on and that's it. The user requires an internet connection tho.

So please review those samples here and tell me whether you would accept them in replacement of the current voices in the pack :)

[wavs.zip](https://github.com/Luke100000/minecraft-comes-alive/files/14130956/wavs.zip)

**Comment by Sovina1991** [comment]
> 好的，我需要你的反馈：
> 
> 目前，我使用 Google 和 Amazon 的 TTS 模型预生成 TTS。但是，这将变得过时（就像现在一样），花费我一点钱并且维护起来很乏味。此外，用户必须下载 1GB 包。当然，我可以更新包，但它最终会再次过时。
> 
> 备选方案：我可以提供在自己的硬件上运行的云解决方案。这是“免费”的，始终是最新的，支持 17 种语言甚至更多扬声器，用户无需安装任何东西。要么是配置中的标志，要么是打开它的命令，仅此而已。用户需要互联网连接。
> 
> 因此，请在此处查看这些样本，并告诉我您是否愿意接受它们来替换包中的当前声音:)
> 
> [wavs.zip](https://github.com/Luke100000/minecraft-comes-alive/files/14130956/wavs.zip)

Thank you for your dedication to this project! I have listened to all the sounds in this example and I think it is very appropriate. Looking forward to seeing the new voice system implemented, thank you again for your excellent work.

**Comment by Luke100000** [comment]
Done, take a look at https://github.com/Luke100000/minecraft-comes-alive/wiki/TTS on how to enable.
Theoretically you can select another language other than "en", however, I only pre-generated English. If you use another language, the first time a new phrase is used it will be silent and generates the voices in the background. Please notify me of any issues. Known issues are rare "hallucinations", where the speaker adds random noise to the end.

Never versions are also compatible with the old TTS pack again, in case you hate the new voices.

**Comment by Sovina1991** [comment]
Thank you for your hard work! I tested it in the latest release version of 1.20.1 and found that English can be pronounced normally, but Chinese has never had any sound. Although the game prompt says there will be no sound the first time, I have been unable to make any sound even after exiting the game, re entering the save, or opening the VPN. Do voice models need to be downloaded from the internet every time? How do I know if the voice model has been successfully downloaded?

**Comment by Sovina1991** [comment]
By the way, it seems that the villagers' AI chat has also failed. Even in the latest version of pure English environment

**Comment by Luke100000** [comment]
> Chinese has never had any sound

 As it tells you in chat, it first needs to get generated. Since MCA has 2000 phrases its unlikely you hit the same phrase again. (+ there are still 300 in the queue) Also, you still have English selected in the tts settings, thus your generated phrases sound very cursed. Something I should automate asap ^^
 
 Realistically, a new language is only available when a) I pre-generate it or b) several players use it for a longer time
 
 > villagers' AI chat has also failed

 In what sense?

**Comment by Sovina1991** [comment]
Thank you for your answer! So all I need to do now is switch the language to Chinese, chat with a villager, and wait for the Chinese language model to be generated? By the way, the manifestation of AI chat failure is that I follow the previous operation method to talk to the villagers (enter the villagers' names and greet them in the chat bar). Previously, the villagers would run up to me and answer me, but now the villagers seem to have no interest in me and will not answer my questions. I seem to have seen similar situations in other issues as well.

**Comment by Luke100000** [comment]
For the TTS, I will add this for you in a way that it automatically detects the language. I will let you know once the update is there. I also pre-generate your language but this usually takes around 4 days.

Regarding chat ai I do not see connection attempts. Did you enable it via `/mca chatAI`? Maybe this one did not work, can you manually enable it in the config via `enableVillagerChatAI`?

**Comment by Luke100000** [comment]
Done, 7.5.14+1.20.1 and 7.5.14+1.19.2 (currently uploading) now detects the language automatic. IF it is supported. For example, zh_cn works, zh_tw will not etc.

EDIT: I see that some phrases went through, so it technically works, especially once all phrases have been generated.
Just to explain why I don't just generated everything right away: Each language is around 60 hours of speech. That's quite some data to generate ^^ But one day we will have all of it.

I also saw that chatAI now responds, does it work as expected, and what was the fix? Any issues?

**Comment by Sovina1991** [comment]
I found out why AI chat failed - the default AI model seems to be incorrect. Now we need to change the model to gpt-3.5-turbo in order to have normal conversations. Then I downloaded the latest version, so it should still take about four days to have a new Chinese voice model, right?

**Comment by Luke100000** [comment]
Exactly, roughly 4 days. But now you don't have to download a GB of data and after updates it updates itself automatically.

You can check how many phrases are in the queue here btw http://rk.conczin.net:30005/v1/tts/xtts-v2/queue

Hmm, the model is weird. GPT is fine, its the old model, but mistral-small should work as well.
