### ISSUE TITLE
"AI broke, please send latest.log to dev!" AI chat doesn't seem to be working anymore 

### ISSUE THREAD

**Issue by jellydeni** [Luke100000/minecraft-comes-alive#864]
**Describe the bug**
Anytime I try to talk to one of the villagers it just responds with "AI broke, please send latest.log to dev!" it was working perfectly fine just yesterday, I did download some new mods so I'm not sure if maybe those did something. (i did remove them one by one and removing them didn't help)

**To Reproduce**
Just typing in the chat with the villager name resulted in the "AI broke, please send latest.log to dev!" message

**Screenshots**
![Capture](https://github.com/Luke100000/minecraft-comes-alive/assets/159218840/dba4216d-83bd-4c24-ade2-bc75e257304d)

**Version**
Minecraft Version: 1.20.1
MCA Reborn Version: minecraft-comes-alive-7.5.12+1.20.1-universal
Forge-1.20.1-47.2.20

**Latest.log**
[latest.txt](https://github.com/Luke100000/minecraft-comes-alive/files/14188606/latest.txt)

**Comment by MevixKH** [comment]
same problem with me..

**Comment by jellydeni** [comment]
@MevixKH i joined the MCA Reborn discord and someone else had the issue too, Luke responded with “issues with the domain, will be back online soon and I will transition to another one soon anyways”

**Comment by MevixKH** [comment]
alright thank you very much for your kindness, i hope it gets fixed as fast as possible i can't wait to show that feature to my friends :)

**Comment by ruesei-koseki** [comment]
Hello, I have same problem.

**Comment by Luke100000** [comment]
Fixed in 7.5.13, please check https://github.com/Luke100000/minecraft-comes-alive/wiki/GPT3-based-conversations for new features.
