### ISSUE TITLE
Forge 1.20.4 is not supported

### ISSUE THREAD

**Issue by Carolrg10** [Luke100000/minecraft-comes-alive#867]
Good afternoon, I just downloaded the mod and when I open the game it says this

![Captura de tela 2024-02-09 120753](https://github.com/Luke100000/minecraft-comes-alive/assets/159557600/96e6f3f1-d413-4012-a66e-ec299e8f7dda)

the mca version is minecraft-comes-alive-7.5.12+1.20.4-universal, minecraft is 1.20.4, moadloader??

[crash-2024-02-09_12.25.22-fml.txt](https://github.com/Luke100000/minecraft-comes-alive/files/14223651/crash-2024-02-09_12.25.22-fml.txt)

[latest log.txt](https://github.com/Luke100000/minecraft-comes-alive/files/14223654/latest.log.txt)

**Comment by Luke100000** [comment]
Forge 1.20.4 is not supported
