### ISSUE TITLE
How avoid them to look in my direction

### ISSUE THREAD

**Issue by Yuuzinhozi** [Luke100000/minecraft-comes-alive#869]
In my multiplayer server the TPS be really bad when im with a lot of villagers around me, idk how fix it, but I have one idea, maybe disable the option of the villagers go in we direction to say ''welcome'' avoid it, how I disable that option?

![3213213123123213](https://github.com/Luke100000/minecraft-comes-alive/assets/145175473/c391b0cd-ba20-4597-b052-6b69c4ca5dca)

**Comment by Luke100000** [comment]
in the config, there is a welcome day counter, increase it. But I would be happy if you can provide a spark profiling report because 7 TPS is beyond reasonable ^^

**Comment by Yuuzinhozi** [comment]
i was alone at the server, but it was what showed, i will try do another one when the players are online.

https://spark.lucko.me/XgPonOQx3C

**Comment by Luke100000** [comment]
Alright so, MCA vilagers are slow as always but there isnt anything we can do. Its Minecraft being Minecraft.

However, around 6 times as much time is spent on an obvious, most likely non mca related bug:
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/7905977/b51e74fa-4a3f-46df-87db-1c8da137952c)

So the player entity triggers an recipe advancement and saves the recipe book, 20 ticks per second, probably every entity.
Sadly I lack the information to further track that down, but I am certain that this is a bug.

What you can try is to give you every advancement and see if this issue stops. Make a backup first.

**Comment by Yuuzinhozi** [comment]
Im using some others mods, and that mods have some advancement, including the mca, u think getting every advancement can maybe solve? there's some command for i do it more fast, or just getting in creative and that's all.

**Comment by Luke100000** [comment]
> Im using some others mods, and that mods have some advancement, including the mca, u think getting every advancement can maybe solve? there's some command for i do it more fast, or just getting in creative and that's all.

Yes the advancement command has a grant all.
