### ISSUE TITLE
Problems with creating an Inn

### ISSUE THREAD

**Issue by SharkyLyn** [Luke100000/minecraft-comes-alive#870]
So I have been building up a village for a bit now and I have been trying to construct an Inn for my villagers but no matter how big I make it. no matter how many blocks I place. no matter how many beds it has... it is always classified as a "Big House" and it is stopping my progression with the village.

I have tried so many things, and I have tried to look up somethings on this, but nothing has helped me...

I don't know if I am building it wrong, or if I am missing something, but it just wont work and its really getting on my nerves.
So, someone please help...

**Comment by Luke100000** [comment]
Something is missing, hover over the building to see what it recognizes.
