### ISSUE TITLE
Baby got dropped & now is just gone. No more children can be made either.

### ISSUE THREAD

**Issue by ItzASecretBoi** [Luke100000/minecraft-comes-alive#872]
I dropped my baby and now when I attempt to make another one I just get the. "Maybe later..." text, I'm guessing the game is waiting for me to place down the first child, that I don't have.

1. Obtain female CHILD through procreation.
2. Go in inventory & drop CHILD
3. Poof, gone.

There is no way to reset the child status or anything so I guess I just can't have children now?

I'm using a 200 mod modpack so i'm not sure if other mods would be responsible, but they are all QOL mods so i'm not sure they are the issue.

Using version 7.5.14+1.20.1 on modrinth.

**Comment by Luke100000** [comment]
No you just have a ~3 days cooldown.

**Comment by ItzASecretBoi** [comment]
> No you just have a ~3 days cooldown.

Yeah I've noticed that now, thanks!
