### ISSUE TITLE
Villagers only appear as textureless children without jobs.

### ISSUE THREAD

**Issue by Savien-Inu** [Luke100000/minecraft-comes-alive#876]
**Describe the bug**
Upon joining a server with MCA installed and all its dependencies, villagers change their appearance to children without textures and are jobless.

**To Reproduce**
1.) Only happens when joining a server, mod works in singleplayer.

**Screenshots**
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/85548285/598f3f77-8a72-45a5-999b-f3928114c83b)

**Version**
MCA 7.5.14, Minecraft 1.20.1, Modloader Fabric 0.15.7

**Latest.log**

[latest - Copy.log](https://github.com/Luke100000/minecraft-comes-alive/files/14341113/latest.-.Copy.log)

**Comment by Luke100000** [comment]
please track down the mod conflict for me to reconstruct

**Comment by Luke100000** [comment]
Merged with #874

**Comment by Savien-Inu** [comment]
After so many attempts, I found out that deleting the [MineCells](https://www.curseforge.com/minecraft/mc-mods/minecells) seems to fix the issue. I'm not sure why this mod conflicts with MCA but [here's the log](https://mclo.gs/hsDNo0u) from the server if it's relevant (before minecells was deleted).
