### ISSUE TITLE
java.lang.NullPointerException I Cannot invoke "net.minecraft.class_2960.toString()" because the return value of "net.minecraft.class_2378.method_10221(Object)" is null

### ISSUE THREAD

**Issue by TheButterbrotMan** [Luke100000/minecraft-comes-alive#88]
I am having a massive modpack, and when i add your mod, its crashing.

[crash-2022-02-22_21.21.34-server.txt](https://github.com/Luke100000/minecraft-comes-alive/files/8120155/crash-2022-02-22_21.21.34-server.txt)

**Comment by Luke100000** [comment]
Is this modpack public?

**Comment by ghost** [comment]
yes public
https://www.curseforge.com/minecraft/modpacks/deathdusk

**Comment by Princikkk** [comment]
Its just incompatible with eldritch-mobs mod!

**Comment by TheRanker** [comment]
this isnt caused by eldritch mobs.. tested and still fails.
