### ISSUE TITLE
Feature Request: Villager revive without tombstone.

### ISSUE THREAD

**Issue by juaps** [Luke100000/minecraft-comes-alive#880]
Is your feature request related to a problem? Please describe:
Yes, the feature request is related to a problem where it's imposible to revive villagers in the game when they die without leaving a grave, causing frustration and emotional distress as my girlfriend has told me.

Describe the solution you'd like:
I would like to have a feature implemented that allows for the registration of all villagers in a village with their name and unique identification, so they can be recovered in case of death, even if they don't leave a grave.

Describe alternatives you've considered:
One alternative could be manually keeping track of villagers' names and unique identifiers outside of the game, but this can be cumbersome and prone to errors.

Additional context:
This feature is important to prevent frustration and emotional distress caused by the inability to revive villagers in the game, she cry because she lost lots of his villages friends, and i dont know how to recover, without tumbstone seems imposible, rollback is not an alternative.

**Comment by Luke100000** [comment]
A villager with small amount of hearts spawn a tombstone on death. I will not store every villager ever existed as this will clutter the world save with thousands of files. If you want something like this use dedicated tools like ledger.
