### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by EmbershadeSC** [Luke100000/minecraft-comes-alive#881]
**Describe the bug**
Game crash when MCA villager loaded

**To Reproduce**
1. Load Minecraft
2. Open world
3. Approach village
4. Crash

**Screenshots**

**Version**
7.5.14, 1.20.1, Neoforge 47.1.96

**Latest.log**
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/14394513/latest.log)
[crash-2024-02-24_15.30.16-server.txt](https://github.com/Luke100000/minecraft-comes-alive/files/14394610/crash-2024-02-24_15.30.16-server.txt)

**Comment by Luke100000** [comment]
Since this happens in vanilla Minecraft methods with no relation to MCA I have no idea how to fix it.
