### ISSUE TITLE
AIchat require me to send my lastet.log to dev

### ISSUE THREAD

**Issue by Crisaki09** [Luke100000/minecraft-comes-alive#882]
**Describe the bug**
When I try to talk with a villager in the default minecraft chat, the AI says "AI broke, please send latest.log to dev!"

**To Reproduce**
Go to a villager. 
Say "hey (villager_name) in minecraft chat". 
And  the issue appears.

**Screenshots**
![2024-02-24_19 55 29](https://github.com/Luke100000/minecraft-comes-alive/assets/161170631/cf0fb294-7ce3-4b43-96c1-3123d319bd8d)

**Version**
MCA Version: minecraft-comes-alive-7.5.14+1.20.1-universal
Minecraft version: 1.20.1
Modloader: forge 47.2.0

**Latest.log**
File is too big (432MB). What I do?

**Comment by Luke100000** [comment]
I bonked the server on the head, does it work now?

Btw, look into your latest.log, 400 mb indicates something is wrong and spams your log, decreasing performance as well.

**Comment by luizaoxx** [comment]
same, still showing this error
![Captura de tela 2024-02-26 160954](https://github.com/Luke100000/minecraft-comes-alive/assets/161372731/54595cf8-c440-4c62-97ef-6829be9fabf8)

**Comment by luizaoxx** [comment]
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/14409781/latest.log)

here's my file

**Comment by Luke100000** [comment]
I did not receive any requests in the timestamps you provided. It looks like you can not call the chatAI config command, how did you turn the AI on? Could you share the server sided mca.json please.

**Comment by luizaoxx** [comment]
i turned on inside the config file, "EnableVillagerAIChat true" as your page ask to do

**Comment by Luke100000** [comment]
please also share the config to verify

**Comment by luizaoxx** [comment]
im not on pc now, send you later fella! :)

**Comment by luizaoxx** [comment]
sorry, not sure if is this what u meant
[mca.json](https://github.com/Luke100000/minecraft-comes-alive/files/14413998/mca.json)

**Comment by Luke100000** [comment]
The config indicates that this is NOT 7.5.14

**Comment by luizaoxx** [comment]
about that, im playing 1.20 version.. is AiChat still work on it? cause im playing the latest version of mod for 1.20

**Comment by Luke100000** [comment]
No, 7.5.14 is required

**Comment by luizaoxx** [comment]
got it.. simpler than i tought, thanks budy!
