### ISSUE TITLE
Crash when making new world after enabling chat AI feature

### ISSUE THREAD

**Issue by ghost** [Luke100000/minecraft-comes-alive#891]
**Describe the bug**
Game crashes when making a new world, only started when testing "Chat AI" feature.

**To Reproduce**
Install MCA
Make new world
Enable chat AI via console command
Exit world
Delete World
Crash
Further crashing when pressing the "Singleplayer" button to make new world
Uninstall/move jar
Crashing ceases
Deletion of Config.json does not fix the problem
**Screenshots**
N/A

**Version**
minecraft-comes-alive-7.5.14+1.20.1-universal, Minecraft 1.20.1, Forge 47.2.20

**Latest.log**

[crash-2024-03-17_15.52.30-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/14628748/crash-2024-03-17_15.52.30-client.txt)

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/14628699/latest.log)
15.52.30-client.txt)

Might update report to see if removing all mods except MCA fixes issue, making it a compatibility issue...

**Comment by Luke100000** [comment]
You have 2,800 errors in your log, please clean that up a bit, data loading failed very early on.

**Comment by ghost** [comment]
> You have 2,800 errors in your log, please clean that up a bit, data loading failed very early on.

Hm, will do. Any advice? I've used this setup for a while now and haven't run into any issues, but I rather fix these errors before something goes horribly wrong. Where exactly does it point out how data loading failed? What's the most efficient fix for that? Never really hunkered down and attempted to make my own modpack before so I'm still noobish in the process, only "guides" I've found were looking into other people's modpacks, which is like looking into an advanced Trigonometry book just to learn the basics of multiplication and division.

**Comment by mgomezdev1** [comment]
I get the same error from mca when clicking on "Create World", immediately, with no need for the Chat AI feature.
I do have a fairly extensive list of mods which I assume is causing an issue somewhere. Another suspected mod is ModernFix, but testing with modernfix without mca worked just fine.

Crash Report: [crash-2024-05-12_10.19.48-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/15285589/crash-2024-05-12_10.19.48-client.txt)

**Comment by mgomezdev1** [comment]
UPDATE:
I managed to reproduce the error with only one extra mod: Cobblemon v1.5, which released less than a day ago. I'll be referencing this in their issues page as well, but mca is indeed the mod that shows up in the crash log, might be related to #913 . I've been having that issue too, and both mods use highly configurable mobs extensively.

I'll attach the logs and the crash report in case it's useful:
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/15285719/latest.log)
[crash-2024-05-12_11.36.58-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/15285720/crash-2024-05-12_11.36.58-client.txt)

**Comment by Luke100000** [comment]
Cobblemon fixed in next release
