### ISSUE TITLE
Can't read MCA books placed on the lectern

### ISSUE THREAD

**Issue by davidmoremad** [Luke100000/minecraft-comes-alive#894]
**Describe the bug**
Can't read any MCA books when they are placed on the lectern. Just readable in your hand. 
I can read every other book on the lectern, it's happening just with MCA books.

This is what happens:
https://www.youtube.com/watch?v=BLqnPDGUr2Y

**Version**
MCA Version: 7.5.14
Minecraft: 1.20.1
Modloader: 47.2.20

**Latest.log**
There's no error or info in logs (latest or debug)

**Comment by Luke100000** [comment]
Sadly not fixable, Minecraft hardcoded that for some reason.
