### ISSUE TITLE
skin library causing crash

### ISSUE THREAD

**Issue by MarioFan4039** [Luke100000/minecraft-comes-alive#896]
When I try to use the skin library feature, I only have access to the first page and when I try to go to the next page my client crashes

Steps to reproduce the behavior
1. open mca version minecraft-comes-alive-7.5.14+1.19.2-universal.jar on forge 47.2.xx
2. open any version of the villager editor
3. go to library
4. attempt to scroll through the pages of the community creations
5. crash

**Screenshots**

**Version**
MCA Version, Minecraft version, Modloader

**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.

not sure what you are talking about but here's the crash report 

The game crashed whilst mouseclicked event handler
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.network.chat.Component.m_214077_()" because the return value of "net.minecraft.client.gui.components.AbstractWidget.m_6035_()" is null

**Comment by Luke100000** [comment]
merged with #895
