### ISSUE TITLE
Unable to Trade with Villagers

### ISSUE THREAD

**Issue by EquinoxEUW** [Luke100000/minecraft-comes-alive#899]
**Describe the bug**
When approaching a villager and talking to them, they give all the interactable options apart from trading.

**To Reproduce**
1. Go to a Villager
2. Click on interact
3. No Trade option apart from Gift, Pick up, locations, follow me, stay here, ride horse, armor

**Screenshots**
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/102207880/10c5158b-2d79-450f-9873-fe0aa9ee4d16)

**Version**
7.5.14, Minecraft 1.20.1, Curseforge

**Latest.log**

[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/14897262/latest.log)

**Comment by Luke100000** [comment]
That's a guard, guards don't trade. Do you have a suggestion on how to remove this confusion?

**Comment by EquinoxEUW** [comment]
Yeah I just noticed when trading I've been trying to trade with Jobless Villagers... My apologies. A way to possibly remove the confusion though is to still add the trade option but gray it out like this

![image](https://github.com/Luke100000/minecraft-comes-alive/assets/102207880/be52f6b8-17f2-4ced-8b36-a4000f5716c8)

Adding a text pop up if hovering over it saying you cant trade with a Guard/Jobless villager. But showing unable to trade with xyzType of villager would most likely resolve potential confusion! Thank you for your speedy reply!
