### ISSUE TITLE
Game crashes with TTS service

### ISSUE THREAD

**Issue by SageAbyssal** [Luke100000/minecraft-comes-alive#903]
The game crashes when I interact with the villagers, having the tts service activated takes me out of the game for "several attempts when speaking" (According to chatgpt)

This is because when interacting with villagers, with the tts service active, it tries to speak all the phrases that are generated at the same time.

**To Reproduce**

**Screenshots**

**Version**
MCA Version (Last) , Minecraft version 1.19.2, Modloader

**Latest.log**

**Comment by Luke100000** [comment]
I need the log

**Comment by SageAbyssal** [comment]
> I need the log

Sorry, this is my first time making a report on github.

[crash-2024-04-14_15.31.25-client.txt](https://github.com/Luke100000/minecraft-comes-alive/files/14984401/crash-2024-04-14_15.31.25-client.txt)
