### ISSUE TITLE
This mod turns off automatic translation mode.

### ISSUE THREAD

**Issue by neighborsbear** [Luke100000/minecraft-comes-alive#911]
**Describe the bug**
https://www.curseforge.com/minecraft/mc-mods/autotranslation/files/4993676
When used together with automatic translation mode, automatic translation mode will not work.

**To Reproduce**

**Screenshots**

**Version**
MCA Version, Minecraft version, Modloader
[Universal 1.20.1] MCA Reborn - 7.5.14, 1.20.1, forge

**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile speci
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/15210582/latest.log)
fic) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.

**Comment by Luke100000** [comment]
Most likely fixed but I can't fully test, see: https://github.com/LangYueMc/AutoTranslation/issues/11
