### ISSUE TITLE
Entity Model Features incompatible when curing Zombie Villagers

### ISSUE THREAD

**Issue by mortal-immortal** [Luke100000/minecraft-comes-alive#920]
**Describe the bug**
[EMF] Entity Model Features When using the [Fabric & Forge] mod and healing a zombie villager, the game crashes.
https://www.curseforge.com/minecraft/mc-mods/entity-model-features

**To Reproduce**
It does not crash during treatment, but it crashes the moment treatment is completed.
1.Summon zombie villagers (vanilla or mca)
2.Throws a weak potion.
3.Use golden apples.
4.Wait for treatment to complete.

**Screenshots**

**Version**
MCA Version, Minecraft version, Modloader, bug mod
minecraft-comes-alive-7.5.14+1.20.1-universal
minecraft 1.20.1
forge
entity_model_features_forge_1.20.1-2.0.2, entity_texture_features_forge_1.20.1-6.0.1

**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/15313119/latest.log)

**Comment by Luke100000** [comment]
The log does not mention the crash, can you please check if there is a crash log as well?

**Comment by mortal-immortal** [comment]
> The log does not mention the crash, can you please check if there is a crash log as well?

It seems that the crash log is not displayed because the bug causes the screen to freeze due to a memory leak.
https://bugs.mojang.com/browse/MC-23484
Only this link appears.

**Comment by mortal-immortal** [comment]
https://www.curseforge.com/minecraft/texture-packs/fresh-animations
I also used this resource pack.

**Comment by mortal-immortal** [comment]
![crash](https://github.com/Luke100000/minecraft-comes-alive/assets/169844862/b0e0dfa6-656c-4069-b1cc-aebfedd5104f)
I checked again and it crashed even without the resource pack...

**Comment by frqnny** [comment]
![2024-06-24_20 59 45](https://github.com/Luke100000/minecraft-comes-alive/assets/45723631/0a5122d8-f2d7-4217-9849-150812018c59)
I couldn't replicate the bug. 
edit: i was on fabric, i'll test later on forge...
