### ISSUE TITLE
Game crashes after a certain amount of time (Possibly memory related..??) [1.20.1] [Fabric]

### ISSUE THREAD

**Issue by eternalbluepetya** [Luke100000/minecraft-comes-alive#922]
**Describe the bug**
When I join a world and wait a minute or so, I crash under the same error. Increasing my memory didn't seem to fix it, but I'm still riding at pretty high memory usage, so maybe it still is a memory issue.

**To Reproduce**
1. Start a new (creative) world with my mod combination
2. Simply move around, that's all I did (I picked somewhere for my location)

**Screenshots**
N/A

**Version**
7.5.14, 1.20.1, Fabric

**Latest.log**
[latest.log](https://github.com/Luke100000/minecraft-comes-alive/files/15316038/latest.log)

**Comment by Luke100000** [comment]
You have a mod `farmaddon` which performs an unsafe cast, report this to them.
