### ISSUE TITLE
custom skin show naked skin, even with the example datapack provided here

### ISSUE THREAD

**Issue by ZewenSenpai** [Luke100000/minecraft-comes-alive#924]
**Describe the bug**
I followed the exact process which the github here described for making custom skins and when generated within the game the skin shows up as naked. I tried to edit the variables a few times with no success and in the end I straight up put in the example pack provided here: https://github.com/Luke100000/minecraft-comes-alive/tree/1.19.2/example/skins

the same issue persisted

both datapacks are inputted into the save file after world creation, ran the /datapack list command and both showed up, and since it did show the naked skin it means the datapack is doing something but just not showing the actual skins themselves.

**Version**
MCA Version, Minecraft version, Modloader

MCA 7.5.14
Minecraft 1.20.1
Modrinth running Fabric

The official example file:
[Luke100000 minecraft-comes-alive 517dc8f5e29b9c9f7ac8c3225032cfa46ea00b96 example-skins.zip](https://github.com/Luke100000/minecraft-comes-alive/files/15319681/Luke100000.minecraft-comes-alive.517dc8f5e29b9c9f7ac8c3225032cfa46ea00b96.example-skins.zip)

My file:
[custom.zip](https://github.com/Luke100000/minecraft-comes-alive/files/15319685/custom.zip)

**Comment by Luke100000** [comment]
Can't confirm. 

> and both showed up

Why both, it should be one? Notice that you also have to install the resource packs and enable them to have the textures.
