### ISSUE TITLE
Adding a small classification model or doing it by Api

### ISSUE THREAD

**Issue by Abulhanan** [Luke100000/minecraft-comes-alive#925]
- The Chat Ai character positive response can increase hearts or negative can decrease heart

how can you achive this :

 1st Way
- Simply adding a small classification model that checks if response is positive or not (if possitive add a random number to heart) if not then vise versa.
- 
 2nd Way
- By sending a seperate prompt with the last message only and ask ai if it's positive or negative then taking the response as variable text and using condition and remaining maths.

Reason :
- For more Immersiveness and better Chatting

**Comment by Luke100000** [comment]
I did this a year ago with moderate results (a finetuned bert), but modern LLMs support function calling, I hope that those can be used both for heart/mood feedback but also commands. So yes, on my infinite todo :)

**Comment by Abulhanan** [comment]
i can help i'm a modder too on fiverr and i've finetunned ai models too.

**Comment by Abulhanan** [comment]
bro will you try to release this feature in next release? it's too op.
