### ISSUE TITLE
Whenever a witch spawns, it also spawns a villager who is frozen and can't die. World is full of mca villagers who just stand there like mannequins and can't be gotten rid of.

### ISSUE THREAD

**Issue by Minebrah** [Luke100000/minecraft-comes-alive#927]
[[Universal 1.19.2] MCA Reborn - 7.5.14] FORGE

So what's happening is whenever a witch spawns lightning will strike and a witch and a mca villager will both spawn in the same block/place. The witch will move and interact as normal but the mca villager will just stand there and not move. The villager can be interacted with but will not and cannot be moved. It will stand in place and be glitched there permanently. The mca villager is unable to be killed and is unable to be removed. You can hit the mca villager and they will react with the appropriate dialogue but they will not do any animations, won't move and won't take damage.

**Comment by Luke100000** [comment]
Seems like a mod conflict to me, please find if and what mod is causing this.

**Comment by totsomi** [comment]
I'm having the same issue, I presume that "Enchanced AI" is causing the issue, since it modifies the behavior of the witch, did you play with that mod ?

**Comment by totsomi** [comment]
and I'm playing on 1.20.1 so the issue persisted.
