### ISSUE TITLE
tts issue in new update

### ISSUE THREAD

**Issue by ZewenSenpai** [Luke100000/minecraft-comes-alive#933]
seems like the new update (7.5.18) had completely messed up the tts as it is not working pretty much at all now. I did not make any changes to the world I was in, only installed the new update. Checked the config the setting was still on. The command straight up does not work as it returns an error, and when I reverted the mod back to the last version the tts works again, so it is prb a version issue.

**Comment by Luke100000** [comment]
> as it returns an error

What error?

**Comment by ZewenSenpai** [comment]
> > as it returns an error
> 
> What error?

"unknown or incomplete command, see below for error", and there is nothing below

**Comment by Luke100000** [comment]
What command did you try and why don't you trust Minecrafts autocompletions?

**Comment by ZewenSenpai** [comment]
> What command did you try and why don't you trust Minecrafts autocompletions?

except I literally god damn did use the autocompletions

<img width="190" alt="image" src="https://github.com/Luke100000/minecraft-comes-alive/assets/61039687/bb7d614e-9718-4676-979f-d470d48dbcc9">

<img width="307" alt="image" src="https://github.com/Luke100000/minecraft-comes-alive/assets/61039687/38f46f77-0c00-477a-975e-7c93a75ef465">

**Comment by Luke100000** [comment]
What do you think "incomplete command" could stand for?

**Comment by ZewenSenpai** [comment]
> What do you think "incomplete command" could stand for?

than your command is broken, because if you look at the grey text, i typed out the whole command including "enable" 

also my config was on true and there were still no tts

**Comment by Luke100000** [comment]
>  i typed out the whole command

No you did not, thats the issue. Hit space to continue, as with EVERY command. Get more familiar with commands please.
