### ISSUE TITLE
[Bug] Crash or Compatibility - Corail Tombstone (Ankh of Pray), MCA Reborn, ETF, EMF

### ISSUE THREAD

**Issue by lupiiiin** [Luke100000/minecraft-comes-alive#937]
There is a serious problem that causes a crash when using the revive dead zombie mechanic with the “Ankh of Pray” added by Corail Tombstone, and provided you have the MCA Reborn mod installed. And the ETF and EMF mods.

Basically, the error occurs when Corail Tombstone, MCA Reborn, [ETF] Entity Texture Features and [EMF] Entity Model Features are together.

If only Corail Tombstone and MCA Reborn are present the error does NOT occur.
If only Corail Tombstone, ETF and EMF are present the error does NOT occur.
If Corail, ETF, EMF and MCA Reborn are present the error DOES occur.

I have also informed the creator of [ETF] Entity Texture Features and [EMF] Entity Model Features.

I attach a video demonstrating it and the crash.

Version 1.20.1, latest version of all mods.

https://pastebin.com/NV949Ewg

https://youtu.be/dwkFb7GXaFE

**Comment by Luke100000** [comment]
Merged with #920
