### ISSUE TITLE
1.20.6 Support

### ISSUE THREAD

**Issue by r333i** [Luke100000/minecraft-comes-alive#941]
Hello there,
is there a port to 1.20.6 planned? or even 1.21 when it releases?
I'm desperate to update my Minecraft World ^^"

**Comment by Luke100000** [comment]
Nope ^^ Please stay at 1.20.1, you won't miss anything and help me maintain my sanity.

There will be a 1.21 once there is a stable version.

**Comment by r333i** [comment]
Thank you for the reply! I will wait patiently for 1.21 then :o
