### ISSUE TITLE
Request to port the mod's version 7.5.18 to game version 1.16.5

### ISSUE THREAD

**Issue by Cartel47** [Luke100000/minecraft-comes-alive#946]
Version 7.5.18 of this mod has not been updated to version 1.16.5 of the game.
Because version 7.3.23 of this mod has many bugs
I'll list those vulnerabilities
1.Babies will get stuck in the wall and suffocate to death
2.The cemetery is never confirmed in the blueprint
3.You can always choose to "have children"
4.The text on all tombstones cannot be rendered
The first of these is the most severe
I'm very hopeful that the latest version of the mod will be ported to version 1.16.5 of the game, which is important to me
Thank you all

**Comment by Luke100000** [comment]
1.16.5, 1.18.2 and 1.19.2 will not receive updates. I can't keep up with maintaining one MCA, yet alone 4.
