### ISSUE TITLE
Not compatible with Productive bee's mod PLZ FIX

### ISSUE THREAD

**Issue by Faithish2002** [Luke100000/minecraft-comes-alive#947]
**Describe the bug**
Not compatible with productive bee's mod. Creates a bug that causes issues with productive bees not showing up in JEI

**To Reproduce**
1. Have the following mods in a modpack; MCA, JEI, and productive bees
2. go into the inventory and look at the rightmost JEI panel and search Bee's
3. You should see 3D versions of each type of bee and be able to press R while hovering on it to get all the info for each one including the nest they use, breeding, etc.
4. The bug removes the 3D models so all that shows up is the spawn eggs and item with the mods and JEI doesn't work.

**Version**
MCA Version - 1.20.1, Minecraft version 1.20.1 , Modloader - Curseforge

**Latest.log**
[latest.log](https://github.com/user-attachments/files/15506781/latest.log)

**Comment by BunnyStardust** [comment]
Hello! Will the fix for this be released anytime soon? Thank you!
