### ISSUE TITLE
Saying I don't have architectury.

### ISSUE THREAD

**Issue by tegsbanana** [Luke100000/minecraft-comes-alive#948]
Whenever I try and load minecraft, it tells me that mca requires architectury and it isn't installed, but I most definitely have it installed/

I have MCA 7.5.18, and architectury 12.1.3. I have forge 1.20.6.

![Screenshot (1173)](https://github.com/Luke100000/minecraft-comes-alive/assets/172084784/6c7f2723-bb34-4567-86a9-c57d69b5f1aa)

**Comment by Luke100000** [comment]
There is no MCA for 1.20.6 :)
