### ISSUE TITLE
Opinions on Homosexuality and Bisexuality

### ISSUE THREAD

**Issue by Kangmaegi** [Luke100000/minecraft-comes-alive#951]
When playing games, it's **annoying** when I can't develop a relationship with an NPC of the same gender if they don't have homosexuality/bisexuality traits.
And even if those traits are present, it's even more annoying if homosexual players can only be with homosexual NPCs and bisexual players can only be with bisexual NPCs!
Is there a reason everything has to be so strict?

A homosexual character should be able to develop a relationship with a bisexual character, and a bisexual character should be able to develop a relationship with a heterosexual character of a different gender.
Also, instead of dividing homosexuality/bisexuality into traits, it should be the default that NPCs don't care about the player's gender.
As mentioned earlier, these features are extremely annoying and unnecessary.
If you're going to include traits related to sexuality, it would be better to create separate traits for homophobia or heterosexuality.

**Comment by xanat0s** [comment]
I would hope the devs have far more meaningful and engaging features to be working than making political statements about sexuality on your behalf.

**Comment by Kangmaegi** [comment]
> I would hope the devs have far more meaningful and engaging features to be working than making political statements about sexuality on your behalf.

Well, I'm not interested in making political statements. and I'm neither homosexual nor bisexual. If it were a game where romance isn't the main focus, I would just ignore it. But in a game where romance is the main mode, it's just annoying to be hindered in pursuing relationships.

**Comment by Luke100000** [comment]
`enableGenderCheckForPlayers` in the config
