### ISSUE TITLE
Problem with "addCharacter"

### ISSUE THREAD

**Issue by KcalbVessalius** [Luke100000/minecraft-comes-alive#954]
I'm trying to add my own character from InworldAI and I can't make it work, I read the tutorial and I'm struggling in the section "Now, in Minecraft, type /mca inworldAI addCharacter "VillagerName" "workspaces/default-abc123/characters/character_name", everthing else works just fine, ChatAI, TTS. I think my API Key is working because I can see it in the config file, but I'll put what I think is what I have to put just to be sure 
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/48925478/2cc9a254-ba1c-4d51-9224-f896ee8cf7ae)

Anyway, I can't add my character, tbh I have no idea what "character_endpoint" means, reading the tutorial I think it's 

![image](https://github.com/Luke100000/minecraft-comes-alive/assets/48925478/823e84de-db2e-4f96-9801-7de6dd4413f6)

but it's doesn't work 
![image](https://github.com/Luke100000/minecraft-comes-alive/assets/48925478/c82399f7-dcaf-4044-9531-0fc9aa187896)

I tried switching the / to _ but it didn't work either, tried to put just the character name and didn't work too.

I tried to change the privacity to public but didn't work, btw the privacity is "Unlisted" in case it's change something idk.

![image](https://github.com/Luke100000/minecraft-comes-alive/assets/48925478/9818c002-c181-4094-b08c-20807c1b550c)

My config in case it helps, I tried everything so far but I get no response in game, tried to find someone with the same problem in this github but found nothing, idk what I'm doing wrong

**Comment by Luke100000** [comment]
Use quotes to escape the url

**Comment by Luke100000** [comment]
@CSCMe can we support "rest of line" args somehow?

**Comment by CSCMe** [comment]
Sorry, haven't looked at GitHub for a while.

From the (limited) research I've done I suppose we could try to change the command argument type from "string" to "greedyString", which *should* work as an rest of line reader and doesn't seem to require quotes.

I'll test this later and report on it.
Should I submit a PR in case this works?

If it doesn't I'd personally say it's probably not worth it to create a custom argumentType for this case, since we could potentially mitigate the issue by adding an emphasis on adding the quotes in the wiki.

In addition to this, Inworld is currently planning on restricting access to application-only and it's unknown if there will even be free interactions afaik, so this issue might become less prevalent as well

**Comment by Luke100000** [comment]
Ohh yea if its only that change I can do that, thanks!

And yes I just saw, right now it seems pretty much impossible for the average person to get a token/licence. I am hoping that they at least add paid self-serve again.

**Comment by CSCMe** [comment]
Yup, using greedyStrings works. We can also use them for the api key so users don't have to quote that either

**Comment by KcalbVessalius** [comment]
> Use quotes to escape the url

It did worked, but... I'm receiving "AI broke" in Minecraft chat now.

[21:25:25] [ForkJoinPool.commonPool-worker-1/ERROR]: InworldAI: Sending {"name":"workspaces/default-qe2vheqedtgnjltn7zic4w/characters/monika","user":{"endUserId":"28732aa2-072e-11eb-ab26-b42e996a7d7a","givenName":"KcalbV2","gender":"male"}} to https://api.inworld.ai/v1/workspaces/default-qe2vheqedtgnjltn7zic4w/characters/monika:openSession
[21:25:25] [ForkJoinPool.commonPool-worker-1/ERROR]: InworldAI: Received No response
[21:25:25] [ForkJoinPool.commonPool-worker-1/ERROR]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.inworld.ai/v1/workspaces/default-qe2vheqedtgnjltn7zic4w/characters/monika:openSession
[21:25:25] [ForkJoinPool.commonPool-worker-1/ERROR]: Failed to open Inworld session. Consult logs

The error in the log, also the full log if needed to

[latest.log](https://github.com/user-attachments/files/16355772/latest.log)

**Comment by Luke100000** [comment]
> > Use quotes to escape the url
> 
> It did worked, but... I'm receiving "AI broke" in Minecraft chat now.
> 
> [21:25:25] [ForkJoinPool.commonPool-worker-1/ERROR]: InworldAI: Sending {"name":"workspaces/default-qe2vheqedtgnjltn7zic4w/characters/monika","user":{"endUserId":"28732aa2-072e-11eb-ab26-b42e996a7d7a","givenName":"KcalbV2","gender":"male"}} to https://api.inworld.ai/v1/workspaces/default-qe2vheqedtgnjltn7zic4w/characters/monika:openSession [21:25:25] [ForkJoinPool.commonPool-worker-1/ERROR]: InworldAI: Received No response [21:25:25] [ForkJoinPool.commonPool-worker-1/ERROR]: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.inworld.ai/v1/workspaces/default-qe2vheqedtgnjltn7zic4w/characters/monika:openSession [21:25:25] [ForkJoinPool.commonPool-worker-1/ERROR]: Failed to open Inworld session. Consult logs
> 
> The error in the log, also the full log if needed to
> 
> [latest.log](https://github.com/user-attachments/files/16355772/latest.log)

~~As just discussed in this thread, Inworld at the moment of writing is no more.~~ only affects new users

**Comment by CSCMe** [comment]
I've tested it on my world and the service still seems to be running so I guess it'll stay that way until the 9th of September, but you might run into issues after that.

Until then,
@KcalbVessalius  from your attached image I think you copied the key directly, not the base64 version. 
Make sure you copied your api key with the marked button (see attached imaged) and used the command like this
![marked button image](https://github.com/user-attachments/assets/f77af08d-c242-4116-aa37-6f43fb07614f)
/mca inworldAI keys "YOURKEYHERE"
Make sure to have the quotes around the key :)

**Comment by KcalbVessalius** [comment]
That was it XD. Everything is working now, thank you so much. I'll enjoy while I can.
