### ISSUE TITLE
Suggestion compatibility mod with woodworks

### ISSUE THREAD

**Issue by key9585** [Luke100000/minecraft-comes-alive#962]
I added the woodworks mod to give more visuals to the items in the game but with the woodworks mod the mca does not detect the items when creating structures for the villagers.

I wish it could be possible to add a compatibility that is for the mod objects to be added to the structure, since the woodwork mod changes also the objects made of wood so the MCA does not recognize the items anymore.

**Comment by Luke100000** [comment]
Aside from [chests](https://github.com/team-abnormals/woodworks/blob/1.19.x/src/generated/resources/data/forge/tags/blocks/chests/wooden.json) what unsupported items did you encounter?

**Comment by key9585** [comment]
Only that

**Comment by Luke100000** [comment]
Merged with #401
