### ISSUE TITLE
Cannot Turn off AI

### ISSUE THREAD

**Issue by Vex-alhiaDerolo** [Luke100000/minecraft-comes-alive#966]
My friend and I are playing on a server. I turned on the AI out of curosity now it is blowing up our server with messages from our villagers and it is making it hard for us to enjoy the game. Is there anyway we can turn it off? We have tried manually turning it off in chat and in the config files. It will not work. Any further help would be appreciated.

**Comment by Luke100000** [comment]
> We have tried manually turning it off in chat
Right now there is no way to do that, forgot about that.

> and in the config files
Server sided? Did you restart?

Why do you keep talking to villagers? If you dont mention their names they wont talk.

If you closed the issue on purpose, please also leave the fix for other people :)
