### ISSUE TITLE
Server crashed unexpectedly

### ISSUE THREAD

**Issue by Sevelar** [Luke100000/minecraft-comes-alive#968]
**Version**
MCA Version: 7.5.18, Minecraft version: 1.20.1, Modloader: Fabric v0.15.11

**Description**
We are playing on relatively large modpack, but crash.log pointed out at MCA Reborn, exactly these methods:
```
	at fabric.net.mca.server.world.data.Nationality.getRegionId(Nationality.java:67)
	at fabric.net.mca.server.SpawnQueue.shouldGetConverted(SpawnQueue.java:145)
	at fabric.net.mca.server.SpawnQueue.addVillager(SpawnQueue.java:160)
```
The server crashed with exception: `java.util.concurrent.CompletionException: net.minecraft.class_148: Accessing LegacyRandomSource from multiple threads`. It happened suddenly, so I cannot really provide the steps to reproduce this issue.

I'm including the crash log for full info:
[crash-2024-07-29_12.17.54-server.txt](https://github.com/user-attachments/files/16413635/crash-2024-07-29_12.17.54-server.txt)

**Comment by Luke100000** [comment]
I assume a performance mod is stumbling across some apparantly unsafe code from MCA. It should be fixable from our side.

**Comment by Sevelar** [comment]
Great to hear that! Expecting more news from your side then.
