### ISSUE TITLE
Game crashes when opening destiny screen

### ISSUE THREAD

**Issue by MrEdixon123** [Luke100000/minecraft-comes-alive#969]
Game crashes when submiting your appearence and opening destiny screen.

Versions:
fabric 0.16.0, minecraft 1.20.1, mca-reborn 7.5.18

[crash-2024-07-29_16.19.57-client.txt](https://github.com/user-attachments/files/16414782/crash-2024-07-29_16.19.57-client.txt)

**Comment by Luke100000** [comment]
Did you modify `destinySpawnLocations`? Do you have the full log as well?

**Comment by MrEdixon123** [comment]
Yes, i did. I forgot to deleate coma after the last spawn location. Sorry it was my fault
