### ISSUE TITLE
Support Yes Steve Model

### ISSUE THREAD

**Issue by Pevernow** [Luke100000/minecraft-comes-alive#973]
The Yes Steve Model mod is a Minecraft Forge and Fabric mod that modifies the vanilla player model,
 using Minecraft Bedrock Edition models and animation files. 
![image](https://github.com/user-attachments/assets/a412efb6-0582-4e0a-a125-0ca9c8085a00)
This allows players to customize player models and animations as they wish.

I think this can bring a richer experience to this mod.

Can you add it to the Todo list?

**Comment by Luke100000** [comment]
What is the issue exactly? Why can't you just install the mod?
