### ISSUE TITLE
Cant use Local models?

### ISSUE THREAD

**Issue by CartoonVanat** [Luke100000/minecraft-comes-alive#974]
I tried to run a local model and try it on a new version of the mod because I noticed in the documentation that they added the ability to add a custom endpoint. I started the server using LM Studio, after which I entered all the necessary data (model, endpoint, token or key) into the command in Minecraft, and as a result, after interacting with the residents, the game wrote that the AI ​​was broken. And when I looked at the logs, all that was there was: “[ERROR] Unexpected endpoint or method. (POST /v1). Returning 200 anyway.” I assume that this is a bug, but I hope that you just didn’t add it to the game (Ability to use local models)
I admit that perhaps due to my inexperience I did not understand correctly how to do this and did not do it, however for this I apologize in advance.

**Comment by Luke100000** [comment]
My first guess is that you did not use the chat endpoint POST /v1/chat/completions

**Comment by CartoonVanat** [comment]
I understand now, now everything works. Sorry for this post, i hope it help someone.
