### ISSUE TITLE
Library is Failed to fetch list

### ISSUE THREAD

**Issue by xhuasui** [Luke100000/minecraft-comes-alive#980]
**Describe the bug**
My 1.20.1 version of Minecraft cannot use the library function. I have tried all mod versions related to the 1.20.1 game version, but it is still the same
**To Reproduce**
1. Go to Library
**Screenshots**
![image](https://github.com/user-attachments/assets/426485f3-4cf2-4209-b7bc-66751104ed43)

**Version**
MCA Version, Minecraft version, Modloader
Respectively：7.5.19+1.20.1,1.20.1,forge  47.3.0
**Latest.log**
Append the log, just drag and drop the file here.
You will find the file in the (launcher and profile specific) minecraft save directory, in logs, called `latest.log`. On Windows by default `%appdata%/.minecraft/logs/latest.log`.
[latest.log](https://github.com/user-attachments/files/16643007/latest.log)

**Comment by xhuasui** [comment]
(。・ω・。)

**Comment by Luke100000** [comment]
Do you have VPNs, IPv6 only, custom DNS or anything out of the ordinary? Based on logs, it seems other mods also struggle to get connections to e.g. GitHub.
