### ISSUE TITLE
Can I upload a my original character/worldview charater's skin with Creative Common-BY-NC-SA?

### ISSUE THREAD

**Issue by SakuraRK** [Luke100000/minecraft-comes-alive#986]

**Comment by Luke100000** [comment]
upload where?

**Comment by SakuraRK** [comment]
> upload where?

It's that place where you can upload your own skins like hatsune miku or etc.
Is that your own website or third-party?

**Comment by Luke100000** [comment]
Own service, and sure, if you have the rights, you can upload it. You grant me informal permissions to distribute this skin among users and in the future the permission to download skins for personal use. (People would like to be able to export skins, so basically clothing, skin, hair merged in one)

**Comment by SakuraRK** [comment]
> Own service, and sure, if you have the rights, you can upload it. You grant me informal permissions to distribute this skin among users and in the future the permission to download skins for personal use. (People would like to be able to export skins, so basically clothing, skin, hair merged in one)

Thanks!
