### ISSUE TITLE
Villager disappeared

### ISSUE THREAD

**Issue by CDAGaming** [Luke100000/minecraft-comes-alive#99]
As occured twice in my server, a villager has somehow died without any death event occuring, with the entity ID displaying in the building and village residents with the blueprint, but not actually being present.

**Comment by Luke100000** [comment]
`getResidents()` returns loaded villagers, so it might have been unloaded too.

It's proven however by several reports that the villager is indeed gone. From the entire world. No death message, no crash, nothing.

Any hints are welcome.

**Comment by WildBamaBoy** [comment]
Was there improvement after this fix? This was something I had issues with as well in the past, and the cause was indeed related to unsafe teleportation.

**Comment by CDAGaming** [comment]
@WildBamaBoy The cause in my server was resolved, as the WanderOrTeleport task was exchanged for a non-teleporting alternative, followed by a pr from me adding a safety measure to dictate safe/unsafe conditions incase the task gets added back.

It is currently unknown if any remaining causes remain, but reports of this have decreased since the initial fix.

**Comment by JahxSenpoopie** [comment]
Thought the reports might still be using an older mca, so who knows

**Comment by Kaiwawa** [comment]
It occurred to me, have a way to bring them back, like a command or something?

I think this occurred after I go to Tropicraft Dimension and came back.
I using the last version on 1.16.5.

**Comment by CDAGaming** [comment]
Closed as resolved in 7.2.0

Villagers that disappeared from teleporting could be located via a /tp query (/tp @e[name=NAME_HERE,limit=1), though if it doesn't work, that would likely mean the entity is dead/discarded, and thus unrecoverable

**Comment by CDAGaming** [comment]
Since 1.16.5 is also receiving the updates from 7.2 and 7.3 shortly, this issue can likely be locked and put away, since it'll officially no longer be relevant to current iterations of MCA 👍
