### ISSUE TITLE
Villagers Keep Turning Into Guards/Archers

### ISSUE THREAD

**Issue by Skylexia7** [Luke100000/minecraft-comes-alive#991]
It doesn't matter if they have a job or not, they're rapidly abandoning their jobs to be guards/archers. Every time I fix one villager, I turn around and there's SEVERAL more that have switched over!! It's making my town unplayable :(

I'm playing on Fabric, minecraft version 1.20.1, and mod version 7.5.19

**Comment by Luke100000** [comment]
1/6 will turn to guards, check the config if you dont want that
