### ISSUE TITLE
Mi skin no carga o no funciona

### ISSUE THREAD

**Issue by DarkXx33** [Luke100000/minecraft-comes-alive#999]
**Describe the bug**
He hosteado un server y he metdo unos mods, todo parece funcionar quitando que no me deja elegir en el menu el tipo de skin y luego despues de personalizar mi skin con e editor de mca y aparecer en el mundo se me carga otra la cual es siempre la misma y no es la que yo elegi

**Version**
MCA Version 7.5.19, Minecraft version 1.20.1, Modloader forge 

[latest.log](https://github.com/user-attachments/files/17216823/latest.log)
[latest.log](https://github.com/user-attachments/files/17216828/latest.log)

**Comment by Luke100000** [comment]
epicfight is not compatible and will disable the skin selection
